### ISSUE TITLE
ACM Portal websearch bug

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10107]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to search on the web: ACM Portal
2. Enter the test string "dd"
3. See the error message below

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/27cc707c-dd91-416b-b413-d3425a61618d)

### Appendix

...
<details>

<summary>Log File</summary>

Not updating theme because it hasn't changed
Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Aan het openen: 'F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Boek.bib'
Aan het openen: 'F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Paper\Dinosaurus Paper.bib'
Index path for F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Paper\Dinosaurus Paper.bib is C:\Users\gebruiker\AppData\Local\org.jabref\JabRef\lucene94
Index path for F:\DATA (op externe HDD)\DINOSAURUS BOEK\Dinosaurus Boek.bib is C:\Users\gebruiker\AppData\Local\org.jabref\JabRef\lucene94
Error importing
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.parseBibEntry(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.getBibEntriesFromDoiList(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.ACMPortalParser.parseEntries(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Import canceled

</details>

**Comment by dino-girl** [comment]
This error seems to appear only with certain search strings like "dd". Other search strings don't generate this error

**Comment by Siedlerchr** [comment]
The author parsing fails because the author only has a family name, not a given name 
 {"family":"Ngo-Thi-Thu-Trang"}


https://github.com/JabRef/jabref/blob/5e4cb4e8afb0dcb33629cfc2034f96b7d4ead053/src/main/java/org/jabref/logic/importer/fileformat/ACMPortalParser.java#L157
 

```
ERROR: Error importing: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.jabref/org.jabref.logic.importer.fileformat.ACMPortalParser.parseBibEntry(ACMPortalParser.java:157)
	at org.jabref/org.jabref.logic.importer.fileformat.ACMPortalParser.getBibEntriesFromDoiList(ACMPortalParser.java:102)
	at org.jabref/org.jabref.logic.importer.fileformat.ACMPortalParser.parseEntries(ACMPortalParser.java:53)
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.getBibEntries(SearchBasedParserFetcher.java:59)
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(SearchBasedParserFetcher.java:54)
	at org.jabref/org.jabref.logic.importer.SearchBasedFetcher.performSearch(SearchBasedFetcher.java:51)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$2(WebSearchPaneViewModel.java:144)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:60)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:161)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
