### ISSUE TITLE
Cannot open file links after updating Adobe Reader

### ISSUE THREAD

**Issue by Bananach** [JabRef/jabref#1031]
* JabRef version (available in the About box): 3.3dev
* Operating system and version: Windows 7
After updating to Adobe Acrobat Reader DC I cannot open linked PDFs anymore.

The console says:
```
13:28:42.977 [JabRef CachedThreadPool] WARN  net.sf.jabref.external.ExternalFileMenuItem - Unable to open link
java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openFileWithApplicationOnWindows(JabRefDesktop.java:179) ~[JabRef-3.3dev--snapshot--2016-03-03--master--49898f1.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFilePlatformIndependent(JabRefDesktop.java:255) ~[JabRef-3.3dev--snapshot--2016-03-03--master--49898f1.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFileAnyFormat(JabRefDesktop.java:229) ~[JabRef-3.3dev--snapshot--2016-03-03--master--49898f1.jar:?]
	at net.sf.jabref.external.ExternalFileMenuItem.openLink(ExternalFileMenuItem.java:104) [JabRef-3.3dev--snapshot--2016-03-03--master--49898f1.jar:?]
	at net.sf.jabref.gui.maintable.MainTableSelectionListener$1.run(MainTableSelectionListener.java:319) [JabRef-3.3dev--snapshot--2016-03-03--master--49898f1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_74]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_74]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:1.8.0_74]
	... 12 more
```

**Comment by stefan-kolb** [comment]
Could you please update to the latest dev version? This should be fixed at the current master branch.

**Comment by Bananach** [comment]
Didn't help: 

```
14:11:29.004 [JabRef CachedThreadPool] WARN  net.sf.jabref.external.ExternalFileMenuItem - Unable to open link
java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_74]
	at net.sf.jabref.gui.desktop.os.Windows.openFileWithApplication(Windows.java:29) ~[JabRef-3.3dev--snapshot--2016-03-23--master--9be805e.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFilePlatformIndependent(JabRefDesktop.java:161) ~[JabRef-3.3dev--snapshot--2016-03-23--master--9be805e.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFileAnyFormat(JabRefDesktop.java:147) ~[JabRef-3.3dev--snapshot--2016-03-23--master--9be805e.jar:?]
	at net.sf.jabref.external.ExternalFileMenuItem.openLink(ExternalFileMenuItem.java:104) ~[JabRef-3.3dev--snapshot--2016-03-23--master--9be805e.jar:?]
	at net.sf.jabref.gui.maintable.MainTableSelectionListener.lambda$mouseClicked$3(MainTableSelectionListener.java:316) ~[JabRef-3.3dev--snapshot--2016-03-23--master--9be805e.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_74]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_74]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:1.8.0_74]
	... 12 more
```

**Comment by stefan-kolb** [comment]
Ok, thanks will investigate! This did not happen with former versions of Acrobat?!

**Comment by Bananach** [comment]
Yes.

**Comment by Bananach** [comment]
Btw: My Adobe Reader is at `C:\Program Files (x86)\Adobe\Acrobat Reader DC`

I have really no clue, but looking at the error message, it looks like the path is cut in the middle

**Comment by stefan-kolb** [comment]
Can you check the settings in `Options-manage external file types` What path is set for pdf? Is it the correct path?

**Comment by stefan-kolb** [comment]
There should be a path to an executable file. 
Btw: If you want to use the standard viewer of Windows you can just remove this application value.

**Comment by stefan-kolb** [comment]
I pushed a potential fix to master. Please try the latest version form http://builds.jabref.org in a few minutes.

**Comment by oscargus** [comment]
There are some issues with the Optionals I introduced the other day. Not sure if it it related, but I'll push a fix quite soon...

**Comment by oscargus** [comment]
I noticed that you took another approach to fix the same issues, so no push on my behalf.

**Comment by Bananach** [comment]
@stefan-kolb fixing it in Options-manage external file types worked. I have no idea why that entry was set to non-default. I also don't know how I oversaw that option when I looked for a fix myself

**Comment by stefan-kolb** [comment]
It is ok if it is non null. In that case you can specify the viewer you want to use by yourself. Otherwise it will use the default viewer of the operating system. So it should work as long as a correct path is set there!

**Comment by Bananach** [comment]
yes, it was indeed set to the old path, not to the correct new path. what I meant is I am surprised it was set to anything, as opposed to left at default (as are all the other file types). but it doesn't matter, everything good now. thanks
