### ISSUE TITLE
Uncaught exception when adding group from cited references

### ISSUE THREAD

**Issue by immoschott** [JabRef/jabref#10350]
### JabRef version

5.10 (latest release)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Click "add group"
2. Under "Collect by" choose "Cited entries"
3. Select the aux file from an existing, successfully complied tex file with .bib references.

### Appendix

![Screenshot 2023-09-08 at 14 52 40](https://github.com/JabRef/jabref/assets/20950586/e17555f8-e496-4b64-8528-d50b025e3187)

<details>
<summary>Detail information:</summary>

```
Opening: '/Users/username/Library/CloudStorage/Dropbox/library.bib'
Uncaught exception occurred in Thread[#50,JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "org.jabref.model.util.FileUpdateMonitor.addListenerForFile(java.nio.file.Path, org.jabref.model.util.FileUpdateListener)" because "fileMonitor" is null
	at org.jabref@5.10.60000/org.jabref.model.groups.TexGroup.create(TexGroup.java:51)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupDialogViewModel.resultConverter(GroupDialogViewModel.java:358)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.Dialog.setResultAndClose(Dialog.java:1052)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.DialogPane.lambda$createButton$3(DialogPane.java:795)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Node.fireEvent(Node.java:8944)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.Button.fire(Button.java:203)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene$MouseHandler.process(Scene.java:3980)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2704)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:168)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:648)
	at org.jabref.merged.module@5.10.60000/javafx.stage.Stage.showAndWait(Stage.java:469)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.Dialog.showAndWait(Dialog.java:345)
	at org.jabref@5.10.60000/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(JabRefDialogService.java:268)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupTreeViewModel.lambda$addNewSubgroup$7(GroupTreeViewModel.java:161)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupTreeViewModel.addNewSubgroup(GroupTreeViewModel.java:160)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupTreeViewModel.addNewGroupToRoot(GroupTreeViewModel.java:124)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupTreeView.addNewGroup(GroupTreeView.java:516)
	at org.jabref@5.10.60000/org.jabref.gui.groups.GroupTreeView.lambda$createNodes$0(GroupTreeView.java:158)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Node.fireEvent(Node.java:8944)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.Button.fire(Button.java:203)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene$MouseHandler.process(Scene.java:3980)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at org.jabref.merged.module@5.10.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2704)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at org.jabref.merged.module@5.10.60000/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the bug report! I could reproduce this and already created a fix. 
You can get the latest dev version here https://builds.jabref.org/main/ 
Remember to make a backup of your library.

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/1)
