### ISSUE TITLE
unknown exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10373]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.11--2023-09-06--afb1a25 Linux 6.4.14-200.fc38.x86_64 amd64  Java 21-internal  JavaFX 20+19

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

it appears when switching between two libraries, but not always.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.11.81/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref@5.11.81/org.jabref.gui.LibraryTab.lambda$createMainTable$9(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref@5.11.81/org.jabref.gui.JabRefFrame.lambda$init$18(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.scene.control.behavior.TabPaneBehavior.selectTab(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.81/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at org.jabref.merged.module@5.11.81/javafx.collections.transformation.SortedList.get(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.11.81/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.11.81/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(Unknown Source)
	... 106 more

```

</details>

**Comment by Siedlerchr** [comment]
Do you have the entry editor open when switching? if yes, any specific tab?

**Comment by ilippert** [comment]
I don't think I have an entry editor open for this error to occur.

**Comment by ilippert** [comment]
though with the editor, bibtex code, opened, I regularly get



...
<details>

<summary>Log File</summary>

```
java.lang.IndexOutOfBoundsException: [ fromIndex: 1, toIndex: 2, size: 1 ]
	at org.jabref.merged.module@5.11.86/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeListener$Change.getAddedSubList(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.callObservers(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at java.base/java.util.AbstractList.add(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.scene.control.SelectedCellsMap.add(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.11.86/org.jabref.gui.StateManager.clearSearchQuery(Unknown Source)
	at org.jabref@5.11.86/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.11.86/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.11.86/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.11.86/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.86/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by Siedlerchr** [comment]
The second one seems to be related to searching, for the first one I maybe have an idea for a fix. 

This refers to search:
	at org.jabref@5.11.86/org.jabref.gui.StateManager.clearSearchQuery(Unknown Source)
	at org.jabref@5.11.86/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)

**Comment by Siedlerchr** [comment]
Can you test around with this version? https://builds.jabref.org/pull/10389/merge

**Comment by koppor** [comment]
I assume, it did not happen with version 5.9 - or did it?

**Comment by koppor** [comment]
No need to check, v5.9 doesn't work either.

**Comment by ThiloteE** [comment]
so, does the newest development version work or not?

**Comment by koppor** [comment]
I think, this is a duplicate of https://github.com/JabRef/jabref/issues/8719.

**Comment by paddomanno** [comment]
I also got an exception when searching. The same exception came up twice. Searched for a term that came up with 1 result. No entry editor open, but I have the groups tab open. This happened a couple of times before on the same version, but now if I try to reproduce it, I don't get the exception anymore, no matter the search term or if I get results. But I hope the info helps.

JabRef 5.10--2023-09-01--779e555
Windows 11 10.0 amd64 
Java 21-internal 
JavaFX 20+19

[jabref-log.txt](https://github.com/JabRef/jabref/files/13190148/jabref-log.txt)

**Comment by jenilpatel264** [comment]
The stack trace suggests that the application is trying to access a selected row in the table that no longer exists, most likely due to:
switching between libraries rapidly, or modifying the dataset while the GUI still references the old selection state.
This typically happens when the selection index or view state is not properly reset or synchronised after the library switch.

After updating, 
This is a bug in JabRef’s selection management when using JavaFX TableView in combination with filtered/sorted lists. You should report (or update your report) with the following note:

"Switching between two libraries while entries are selected or a search is active causes a NoSuchElementException due to an IndexOutOfBoundsException in SortedList.get() via MainTable.getSelectedEntries()."

Try This in the main config

Java (Java 21)

JavaFX version (20+19)

JabRef build (5.11--2023-09-06--afb1a25)

**Comment by koppor** [comment]
@jenilpatel264 Why are you posting AI generated responses? Do you really want to learn something or just get a check mark? If the former, please take this learning opportunity serious. If the latter, please move to another project. We want to spend our short time of life with people being respectful to us, we also try to be respecful.

**Comment by ThiloteE** [comment]
Does this still reproduce in 6.0alpha3? There were a few fixes since 2023. See https://github.com/JabRef/jabref/pull/14128

**Comment by ilippert** [comment]
I have not seen this issue for a long while, so closing this one.
