### ISSUE TITLE
another unknown exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10379]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.11--2023-09-12--a1e2283 Linux 6.4.14-200.fc38.x86_64 amd64  Java 21-internal  JavaFX 20+19

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I merely switch between two libraries (in each I am looking at a group).

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IndexOutOfBoundsException: [ fromIndex: 1, toIndex: 2, size: 1 ]
	at org.jabref.merged.module@5.11.138/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeListener$Change.getAddedSubList(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.callObservers(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at java.base/java.util.AbstractList.add(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.scene.control.SelectedCellsMap.add(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ReadOnlyListPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ReadOnlyListWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ListPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ListPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref@5.11.138/org.jabref.gui.StateManager.setActiveDatabase(Unknown Source)
	at org.jabref@5.11.138/org.jabref.gui.JabRefFrame.lambda$init$16(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.scene.control.behavior.TabPaneBehavior.selectTab(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.11.138/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.138/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Reproducible now:
note, that thilo's exception is more related to #10379 
with thilo's libray and instructions I could reproduce it e.g. copy field author bibtex in the entry editor to another entry while having a sort order set

**Comment by ThiloteE** [comment]
Hey Ilippert, can you still reproduce this issue in 6.0alpha3? There were a few fixes since 2023. Just recently, I tried to reproduce all those index out of bounds issues and many seem to be ok now (unreproducible). See https://github.com/JabRef/jabref/pull/14128
Trying to find out which ones are gone and which ones persist.

**Comment by ilippert** [comment]
I have not seen this issue for a long while, so closing this one.
