### ISSUE TITLE
JabRef 5.10 breaks CLI export

### ISSUE THREAD

**Issue by kingaa** [JabRef/jabref#10380]
### JabRef version

5.10 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04.3 LTS, shell is GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Calling `jabref -n -i <bibfile>,bibtex -o <htmlfile>,tablerefsabsbib` on the command line hangs indefinitely under linux.
By contrast, under version 5.9, it works perfectly.

The following is a transcript using JabRef 5.11 as downloaded from https://builds.jabref.org/main/JabRef-5.11-portable_linux.tar.gz on 2023-09-14, 14:00UTC.  The behavior is the same as under JabRef 5.10.

```
kingaa@saure:~/logos/biblios$ jabref5.11 -n -i biblios.bib,bibtex -o biblios.html,tablerefsabsbib
Messages are not initialized before accessing key: Display help on command line options
2023-09-14 10:08:28 [main] org.jabref.logic.protectedterms.ProtectedTermsLoader.update()
WARN: New protected terms resource '/protectedterms/computer_science.terms' is available and enabled by default.
2023-09-14 10:08:28 [main] org.jabref.preferences.JabRefPreferences.getFetcherKeysFromKeyring()
WARN: JabRef could not open the key store
Importing: biblios.bib
2023-09-14 10:08:30 [main] org.jabref.logic.cleanup.FieldFormatterCleanups.getFormatterFromString()
INFO: Formatter identity not found.
Exporting: biblios.html
2023-09-14 10:08:30 [main] org.jabref.cli.Launcher.main()
ERROR: Unexpected exception: java.lang.NullPointerException: Cannot invoke "org.jabref.gui.maintable.ColumnPreferences.getColumnSortOrder()" because "this.mainTableColumnPreferences" is null
        at org.jabref@5.11.142/org.jabref.preferences.JabRefPreferences.getSelfContainedTableSaveOrder(Unknown Source)
        at org.jabref@5.11.142/org.jabref.preferences.JabRefPreferences.getSelfContainedExportConfiguration(Unknown Source)
        at org.jabref@5.11.142/org.jabref.preferences.JabRefPreferences.getCustomExportFormats(Unknown Source)
        at org.jabref@5.11.142/org.jabref.preferences.JabRefPreferences.getExportPreferences(Unknown Source)
        at org.jabref@5.11.142/org.jabref.logic.exporter.ExporterFactory.create(Unknown Source)
        at org.jabref@5.11.142/org.jabref.cli.ArgumentProcessor.exportFile(Unknown Source)
        at org.jabref@5.11.142/org.jabref.cli.ArgumentProcessor.processArguments(Unknown Source)
        at org.jabref@5.11.142/org.jabref.cli.ArgumentProcessor.<init>(Unknown Source)
        at org.jabref@5.11.142/org.jabref.cli.Launcher.main(Unknown Source)
```
The call does not return (i.e., it hangs).

Here is the behavior under JabRef 5.9:
```
jabref5.9 -n -i biblios.bib,bibtex -o biblios.html,tablerefsabsbib
Importing: biblios.bib
Exporting: biblios.html
```
The resulting HTML file is as expected.

In case it is important, the `biblios.bib` BibTeX file here has been opened and saved in JabRef 5.10.

**Comment by Siedlerchr** [comment]
Refs https://github.com/JabRef/jabref/pull/10294

**Comment by koppor** [comment]
A fix is available at https://builds.jabref.org/pull/10383/merge/. Please try out.

JabRef should not hang forever after the export. Here, it hang about 10 seconds, which is OKish for me. To shorten that time even more, a major refactoring of JabRef would be necessary.

**Comment by kingaa** [comment]
Thanks very much for the fast response!  With the fixed version, I see
```
kingaa@saure:~/logos/biblios$ time jabref5.11 -n -i biblios.bib,bibtex -o biblios.html,tablerefsabsbib
Messages are not initialized before accessing key: Display help on command line options
2023-09-15 08:59:11 [main] org.jabref.logic.protectedterms.ProtectedTermsLoader.update()
WARN: New protected terms resource '/protectedterms/computer_science.terms' is available and enabled by default.
2023-09-15 08:59:11 [main] org.jabref.preferences.JabRefPreferences.getFetcherKeysFromKeyring()
WARN: JabRef could not open the key store
Importing biblios.bib
2023-09-15 08:59:13 [main] org.jabref.logic.cleanup.FieldFormatterCleanups.getFormatterFromString()
INFO: Formatter identity not found.
Exporting biblios.html

real    1m7.698s
user    0m18.249s
sys     0m0.724s
```
So, yes, it completes, and the output looks good, though it takes 67 sec as compared to 8 sec for JabRef 5.9.

Just out of curiosity, I wonder what changes from 5.9 to this development version do you think might be responsible for such a slowdown?

**Comment by koppor** [comment]
Maybe, it's because the new JDK behaves differently. Would need to compile a test version using the "old" JDK19 or JDK20. However, this cannot be simply done with the current version as we rely on JDK21's features.

**Comment by koppor** [comment]
@kingaa I tried another "workaround" with current JDK. The build should be available in 30 Minutes. You can see it as soon as new comment is added below https://github.com/JabRef/jabref/pull/10383#issuecomment-1721396759. Maybe you can try, too then?

**Comment by kingaa** [comment]
Yep, that did the trick.  Timing is now comparable with that of 5.9.
