### ISSUE TITLE
Adding bibliography entries will trigger uncaughted exception occurred in Thread

### ISSUE THREAD

**Issue by eustomaqua** [JabRef/jabref#10420]
### JabRef version

5.10 (latest release)

### Operating system

macOS

### Details on version and operating system

macOS 13.4

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a bibliography library
2. Add one reference entry, e.g., an article
3. Save the library
4. Click another entry (anyone)

The error occurs between steps 3 and 4, and I will not be able to edit other entries, and all other entries that I click will not change to the thing it should be, in other words, they will be the same entry exactly that I just added, I suspect that jumping to another entry is not working

Here is the error that I encountered
![1695743706509](https://github.com/JabRef/jabref/assets/21055888/ef71bf91-89dd-4a00-9e3c-046511c2f05a)

### Appendix

![1695743706509](https://github.com/JabRef/jabref/assets/21055888/b784273f-341c-4948-b438-29136382614c)

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
@eustomaqua  This likely the same issue as #10403 
How did you add the new entry exactly ? Did you open the Entry Editor -> Bibtex Source and added it there?
PS: You can paste bibtex directly on the table, a new entry will then be directly created

**Comment by eustomaqua** [comment]
Just want to give an update, the error disappears, I don't know why. I did nothing except for those aforementioned actions

**Comment by HoussemNasri** [comment]
Hi @eustomaqua, please share the full exception stack trace.

**Comment by Siedlerchr** [comment]
Refs https://github.com/JabRef/jabref/pull/10399 
We tried to analyze the issue

**Comment by eustomaqua** [comment]
@HoussemNasri Sorry the error didn't appear in the past four days. I will update the detailed error information when it happens again

**Comment by eustomaqua** [comment]
Hi it happens again, 
![1697863999186](https://github.com/JabRef/jabref/assets/21055888/a0af8af0-c08b-4f41-a586-09ab8ed5dcf7)

and the details are
```log
java.lang.IllegalArgumentException
	at org.jabref.merged.module@5.11.241/javafx.scene.control.IndexRange.<init>(IndexRange.java:53)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea.getParagraphSelection(GenericStyledArea.java:1142)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea.lambda$createCell$64(GenericStyledArea.java:1960)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.Val$2.computeValue(Val.java:705)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ValBase.getValue(ValBase.java:17)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ValBase.newObserver(ValBase.java:40)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ValBase.newObserver(ValBase.java:8)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.addObserver(ObservableBase.java:110)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.Val.addInvalidationObserver(Val.java:52)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.Val.addListener(Val.java:80)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.ParagraphText.lambda$new$1(ParagraphText.java:110)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.MapListenerHelper$SingleChange.fireValueChangedEvent(MapListenerHelper.java:161)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:70)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea.lambda$createCell$65(GenericStyledArea.java:1968)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.jabref.merged.module@5.11.241/org.reactfx.EventStreams$27.tryEmit(EventStreams.java:599)
	at org.jabref.merged.module@5.11.241/org.reactfx.EventStreams$27.lambda$observeInputs$2(EventStreams.java:594)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.jabref.merged.module@5.11.241/org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.jabref.merged.module@5.11.241/org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.SimpleVar.setValue(SimpleVar.java:59)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.ParagraphBox.setIndex(ParagraphBox.java:86)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea$3.updateIndex(GenericStyledArea.java:1985)
	at org.jabref.merged.module@5.11.241/org.fxmisc.flowless.CellWrapper.updateIndex(CellWrapper.java:129)
	at org.jabref.merged.module@5.11.241/org.fxmisc.flowless.CellWrapper.updateIndex(CellWrapper.java:129)
	at org.jabref.merged.module@5.11.241/org.fxmisc.flowless.CellListManager.presentCellsChanged(CellListManager.java:152)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.collection.MemoizationListImpl$MemoizedView.publishNotifications(MemoizationList.java:58)
	at org.jabref.merged.module@5.11.241/org.reactfx.collection.MemoizationListImpl$MemoizedView.access$300(MemoizationList.java:30)
	at org.jabref.merged.module@5.11.241/org.reactfx.collection.MemoizationListImpl.sourceChanged(MemoizationList.java:89)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.collection.MappedList.sourceChanged(MappedList.java:41)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
	at org.jabref.merged.module@5.11.241/org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.jabref.merged.module@5.11.241/org.reactfx.MultiGuard.close(Guard.java:83)
	at org.jabref.merged.module@5.11.241/org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
	at org.jabref.merged.module@5.11.241/org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.jabref.merged.module@5.11.241/org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.jabref.merged.module@5.11.241/org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.jabref.merged.module@5.11.241/org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.jabref.merged.module@5.11.241/org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
	at org.jabref.merged.module@5.11.241/org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.jabref.merged.module@5.11.241/org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateMulti(GenericEditableStyledDocumentBase.java:218)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.updateSingle(GenericEditableStyledDocumentBase.java:210)
	at org.jabref.merged.module@5.11.241/org.reactfx.util.Tuple3.exec(Tuple3.java:43)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.replace(GenericEditableStyledDocumentBase.java:145)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.model.SimpleEditableStyledDocument.replace(SimpleEditableStyledDocument.java:10)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea.replace(GenericStyledArea.java:1547)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1533)
	at org.jabref.merged.module@5.11.241/org.fxmisc.richtext.EditActions.clear(EditActions.java:155)
	at org.jabref@5.11.241/org.jabref.gui.entryeditor.SourceTab.lambda$updateCodeArea$6(SourceTab.java:236)
	at org.jabref@5.11.241/org.jabref.gui.util.DefaultTaskExecutor.runAndWaitInJavaFXThread(DefaultTaskExecutor.java:80)
	at org.jabref@5.11.241/org.jabref.gui.entryeditor.SourceTab.updateCodeArea(SourceTab.java:231)
	at org.jabref@5.11.241/org.jabref.gui.entryeditor.SourceTab.lambda$bindToEntry$8(SourceTab.java:260)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:318)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:70)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:173)
	at org.jabref@5.11.241/org.jabref.model.entry.BibEntry.setField(BibEntry.java:613)
	at org.jabref@5.11.241/org.jabref.model.entry.BibEntry.setField(BibEntry.java:631)
	at org.jabref@5.11.241/org.jabref.gui.entryeditor.SourceTab.storeSource(SourceTab.java:322)
	at org.jabref@5.11.241/org.jabref.gui.entryeditor.SourceTab.lambda$setupSourceEditor$5(SourceTab.java:218)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
	at org.jabref.merged.module@5.11.241/javafx.scene.Node$FocusPropertyBase.notifyListeners(Node.java:8156)
	at org.jabref.merged.module@5.11.241/javafx.scene.Node$17.notifyListeners(Node.java:8228)
	at org.jabref.merged.module@5.11.241/javafx.scene.Node.notifyFocusListeners(Node.java:8177)
	at org.jabref.merged.module@5.11.241/javafx.scene.Scene.setWindowFocused(Scene.java:2120)
	at org.jabref.merged.module@5.11.241/javafx.scene.Scene.lambda$new$5(Scene.java:2107)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at org.jabref.merged.module@5.11.241/javafx.stage.Window.setFocused(Window.java:702)
	at org.jabref.merged.module@5.11.241/javafx.stage.Window$1.setFocused(Window.java:160)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:65)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1247)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.Window.notifyFocus(Window.java:1226)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.mac.MacWindow._setVisible(Native Method)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.Window.setVisible(Window.java:630)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.WindowStage.lambda$setVisible$2(WindowStage.java:513)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.QuantumToolkit.runWithRenderLock(QuantumToolkit.java:442)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:509)
	at org.jabref.merged.module@5.11.241/javafx.stage.Window$12.invalidated(Window.java:1186)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at org.jabref.merged.module@5.11.241/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at org.jabref.merged.module@5.11.241/javafx.stage.Window.setShowing(Window.java:1239)
	at org.jabref.merged.module@5.11.241/javafx.stage.Window.show(Window.java:1254)
	at org.jabref.merged.module@5.11.241/javafx.stage.Stage.show(Stage.java:277)
	at org.jabref.merged.module@5.11.241/javafx.stage.Stage.showAndWait(Stage.java:467)
	at org.jabref.merged.module@5.11.241/javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at org.jabref.merged.module@5.11.241/javafx.scene.control.Dialog.showAndWait(Dialog.java:345)
	at org.jabref@5.11.241/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(JabRefDialogService.java:268)
	at org.jabref@5.11.241/org.jabref.gui.importer.NewEntryAction.execute(NewEntryAction.java:63)
	at org.jabref@5.11.241/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.jabref.merged.module@5.11.241/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.jabref.merged.module@5.11.241/org.controlsfx.control.action.Action.handle(Action.java:64)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.11.241/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.11.241/javafx.scene.Node.fireEvent(Node.java:8944)
	at org.jabref.merged.module@5.11.241/javafx.scene.control.Button.fire(Button.java:203)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at org.jabref.merged.module@5.11.241/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.11.241/javafx.scene.Scene$MouseHandler.process(Scene.java:3980)
	at org.jabref.merged.module@5.11.241/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at org.jabref.merged.module@5.11.241/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2704)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at org.jabref.merged.module@5.11.241/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at org.jabref.merged.module@5.11.241/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

```

thank you for taking care of this issue

**Comment by eustomaqua** [comment]
@HoussemNasri Hi just so you know, the full description about this error has been reported. Thanks for taking a look at it and trying to solve this problem
