### ISSUE TITLE
Could not save library

### ISSUE THREAD

**Issue by dkczk** [JabRef/jabref#10452]
### JabRef version

5.10 (latest release)

### Operating system

macOS

### Details on version and operating system

macOS 12.6

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I add some articles to my new library
2. CMD + S to save the library
3. The following error is returned:
```
org.jabref.logic.exporter.SaveException: Problems saving: java.io.IOException: Operation not supported
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:266)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:215)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveAs(SaveDatabaseAction.java:131)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:186)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:75)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveAction.execute(SaveAction.java:41)
	at org.jabref@5.10.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.jabref.merged.module@5.10.60000/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.jabref.merged.module@5.10.60000/org.controlsfx.control.action.Action.handle(Action.java:64)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:150)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at org.jabref.merged.module@5.10.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.10.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.10.60000/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)
Caused by: java.io.IOException: Operation not supported
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
	at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
	at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileOutputStream.<init>(AtomicFileOutputStream.java:109)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileOutputStream.<init>(AtomicFileOutputStream.java:83)
	at org.jabref@5.10.60000/org.jabref.logic.exporter.AtomicFileWriter.<init>(AtomicFileWriter.java:29)
	at org.jabref@5.10.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:243)
	... 28 more


```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Are you saving your library by chance in a sync folder like Google Drive or on a smb network share?

**Comment by dkczk** [comment]
Yes, I want to save the file to a network drive as my whole thesis is saved there.

**Comment by Siedlerchr** [comment]
@dkczk  I've implemented a workaround. Can you test if this version works for you as well? https://builds.jabref.org/pull/10454/merge 

(Tested it with macOS and a windows network share over smb)
