### ISSUE TITLE
No able to open a file once the folder value is invalid

### ISSUE THREAD

**Issue by Nosdok** [JabRef/jabref#10548]
### JabRef version

5.11 (latest release)

### Operating system

macOS

### Details on version and operating system

14.0 Sonoma

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This problem is old and already solved (https://github.com/JabRef/jabref/issues/2522) but on a failed mounted directory (with ssh) in the lastest JabRef version the problem exists (at least in MacOs).

1. The .bib file was in a mounted directory that failed to connect due to a timeout.
2. The mac system let the folder 'hanging' and not accessible anymore. 
3. At this point, I started JabRef, click in "open a library"
4. But I don't get the 'open file' window, instead I get the following exception and I'm no longer able to open any file: "Uncaught exception occured in Thread[#39,JavaFX Application Thread,5,main]"

Find attached details of the error.

The partial solution is to force the unmounting (of the directory). Only then JabRef works properly and let me open the 'open file' window. 

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:239)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:191)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1719)
	at org.jabref.merged.module@5.11.60000/javafx.stage.FileChooser.showDialog(FileChooser.java:419)
	at org.jabref.merged.module@5.11.60000/javafx.stage.FileChooser.showOpenMultipleDialog(FileChooser.java:376)
	at org.jabref@5.11.60000/org.jabref.gui.JabRefDialogService.showFileOpenDialogAndGetMultipleFiles(JabRefDialogService.java:398)
	at org.jabref@5.11.60000/org.jabref.gui.importer.actions.OpenDatabaseAction.execute(OpenDatabaseAction.java:109)
	at org.jabref@5.11.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.jabref.merged.module@5.11.60000/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.jabref.merged.module@5.11.60000/org.controlsfx.control.action.Action.handle(Action.java:64)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at org.jabref.merged.module@5.11.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.11.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:150)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at org.jabref.merged.module@5.11.60000/javafx.event.Event.fireEvent(Event.java:198)
	at org.jabref.merged.module@5.11.60000/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at org.jabref.merged.module@5.11.60000/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the report. There needs to be a check the file/folder is still existing.
As a workaround you can start JabRef from command line and reset your preferences. 

https://docs.jabref.org/advanced/commandline#reset-preferences-d-key

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/blob/a0e2564806050247bce6056a6c108b87bab315b3/src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java#L113-L123

**Comment by devanshim2207** [comment]
Hi @Siedlerchr ..I would like to work on this issue.

**Comment by koppor** [comment]
@devanshim2207 We did not see any activity the last 8 weeks, therefore I unassigned you.

**Comment by Boston54** [comment]
@Siedlerchr I would like to have a go at this issue if it's available.

**Comment by mag-sun** [comment]
Hi, I am a student at the Australian National University. For one of our assignments, we are tasked with working in a group to contribute to an open-source project - and I would like to be assigned to this issue. While working, our group will cross-review our code and help each other out to have the most efficient progress. Thanks so much!

**Comment by ThiloteE** [comment]
I assigned @Boston54.
@mag-sun at JabRef we have a first come first serve policy. This is to avoid double work, prevent arguments between students, to prevent disappointment when only one of competing pull-requests gets merged and finally to prevent issues with grading. In principle all issues can be worked on and no restrictions apply, but we try to lookout for students especially. Please choose another good first issue that is "free to take" from https://github.com/orgs/JabRef/projects/5. If you feel confident, you also can choose from https://github.com/orgs/JabRef/projects/3, but those are slightly more difficult and advanced.
