### ISSUE TITLE
NPE in getSortedEntries when exporting to external DB

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1055]
Jabref 3.3 dev, master, commit: ed989b069b768390240fd4a2946b9f4b13142cdc
Reproducable
Steps to reproduce:

1. Open Export to External SQL Database
2. Choose Mysql (doesn't matter)
3. Fill in the conn details
4 . Select Target DB/Create new one
5. Enter name 
6. Click OK

NPE is shown:
```
18:53:07.518 [Spin-0] INFO  net.sf.jabref.gui.BasePanel - Could not export to SQL database
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_74]
	at net.sf.jabref.exporter.BibDatabaseWriter.getSortedEntries(BibDatabaseWriter.java:85) ~[bin/:?]
	at net.sf.jabref.sql.exporter.DBExporter.performExport(DBExporter.java:86) ~[bin/:?]
	at net.sf.jabref.sql.exporter.DBExporter.exportDatabaseToDBMS(DBExporter.java:430) ~[bin/:?]
	at net.sf.jabref.gui.BasePanel$1.run(BasePanel.java:544) [bin/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
```

**Comment by Siedlerchr** [comment]
I am looking into that, seems like I found the problem

**Comment by tobiasdiez** [comment]
Yes, someone still passes `null` to the entries argument, which was the old version to indicate that all entries should be sorted.

**Comment by Siedlerchr** [comment]
@tobiasdiez  Yep. there is missing a getSelectedEntries() as Parameter.

**Comment by oscargus** [comment]
Hmm, I thought that I (i.e. Eclipse) had found all performExport calls, but obviously not...
