### ISSUE TITLE
unhandled exception when running cleanup

### ISSUE THREAD

**Issue by MarDiehl** [JabRef/jabref#10692]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Arch Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Attach a pdf file to this entry
2. Select only this entry
3. Click on Quality/Cleanup entries

Cleanup (which involves at least moving the attached file) works, but an unhandled exception occurs.

Note: running the portable linux binary does not work (Jabref does not even start), building an Arch package from source (current status of main branch) works but the GUI is broken and I cannot trigger cleanup. ALT+F8 also does not work, I assume GNOME captures it.

### Appendix

Message given when the exception occurs.
<details>

<summary>Log File</summary>

```
java.util.ConcurrentModificationException
	at java.base/java.util.AbstractList$Itr.checkForComodification(AbstractList.java:401)
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:370)
	at org.jabref@5.11/org.jabref.gui.cleanup.CleanupAction.cleanup(CleanupAction.java:135)
	at org.jabref@5.11/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(CleanupAction.java:90)
	at org.jabref@5.11/org.jabref.gui.util.BackgroundTask$2.call(BackgroundTask.java:69)
	at org.jabref@5.11/org.jabref.gui.util.BackgroundTask$2.call(BackgroundTask.java:66)
	at org.jabref@5.11/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:161)
	at javafx.graphics@20.0.2/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

**Comment by Siedlerchr** [comment]
Hi,

can you please try re-downloading the latest version and try again? Yesterday we fixed the issue with the startup, so the portable should work again

**Comment by MarDiehl** [comment]
I can't reproduce it for JabRef-5.12-portable_linux.tar.gz from 2023-12-06 22:32
