### ISSUE TITLE
unknown exception ""org.apache.lucene.index.IndexWriter."

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10781]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.13--2024-01-09--01c3e15 Linux 6.6.11-200.fc39.x86_64 amd64  Java 21.0.1  JavaFX 20+19

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Opening database with 9.8k entries results in this error message. no idea what is going on.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.getReader(boolean, boolean)" because "<parameter1>" is null
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.DirectoryReader.open(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.DirectoryReader.open(Unknown Source)
	at org.jabref@5.13.48/org.jabref.logic.pdf.search.PdfIndexer.initializeIndexWriterAndReader(Unknown Source)
	at org.jabref@5.13.48/org.jabref.logic.pdf.search.PdfIndexer.getIndexWriter(Unknown Source)
	at org.jabref@5.13.48/org.jabref.logic.pdf.search.PdfIndexer.getListOfFilePaths(Unknown Source)
	at org.jabref@5.13.48/org.jabref.logic.pdf.search.IndexingTaskManager.updateIndex(Unknown Source)
	at org.jabref@5.13.48/org.jabref.gui.LibraryTab.onDatabaseLoadingSucceed(Unknown Source)
	at org.jabref@5.13.48/org.jabref.gui.util.DefaultTaskExecutor.lambda$getJavaFXTask$4(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/javafx.concurrent.Task.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.48/javafx.concurrent.Task.setState(Unknown Source)
	at org.jabref.merged.module@5.13.48/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.13.48/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.48/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>
###

**Comment by Siedlerchr** [comment]
Does this still occur with the latest dev version?
