### ISSUE TITLE
Portable Linux release 5.12 can not launch

### ISSUE THREAD

**Issue by drcxd** [JabRef/jabref#10873]
### JabRef version

5.12 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

6.5.13-7-MANJARO

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download the portable Linux release from https://github.com/JabRef/jabref/releases/download/v5.12/JabRef-5.12-portable_linux.tar.gz
2. Extract and execute JabRef
3. Get the following error:
```
./JabRef
Messages are not initialized before accessing key: Display help on command line options
2024-02-10 23:11:39 [JavaFX-Launcher] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

2024-02-10 23:11:39 [main] org.jabref.cli.Launcher.main()
ERROR: Unexpected exception: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.Application.run(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

### Appendix

I have tried to build from source but encountered the same issue: https://github.com/JabRef/jabref/issues/10626
From there I found the portable Linux release but it does not work.

**Comment by drcxd** [comment]
I later found that I can not launch any GUI application. It looks like there is something wrong in my OS. After I reboot my PC, everything works fine.
