### ISSUE TITLE
 Document Viewer: java.lang.RuntimeException: ToggleButton.selected: A bound value cannot be set

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10935]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Have a pdf file linked to an entry
2. Click entry
3. Go to View -> Open Document Viewer
4. Optional: Maximize the window
5. Click on "locked"

```
java.lang.RuntimeException: ToggleButton.selected : A bound value cannot be set.
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:141)
	at javafx.controls@21.0.2/javafx.scene.control.ToggleButton.setSelected(ToggleButton.java:151)
	at javafx.controls@21.0.2/javafx.scene.control.ToggleButton.fire(ToggleButton.java:262)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

![documentViewerlocked](https://github.com/JabRef/jabref/assets/320228/0e909a41-5fe0-4c47-aae2-1017701bc82a)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Anirudhxx** [comment]
Hi, can take up this issue?

**Comment by Anirudhxx** [comment]
Steps to reproduce the behaviour

    Have a pdf file linked to an entry
    Click entry
    Hi I'm new to Jabref and I'm facing issues reproducing this error , can you please give me bit more detailed explanation what is an entry and what kind of pdf file  i should  use to reproduce this error?

**Comment by koppor** [comment]
An entry is an entry in a `.bib` file. Example bib file: https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/Chocolate.bib

Drag and drop a PDF into a line in the main table. Attach the PDF. Then, you can open the PDF in JabRef.

**Comment by koppor** [comment]
- [ ] There should also be a tooltip showing what "Locked" means

**Comment by Anirudhxx** [comment]
> An entry is an entry in a `.bib` file. Example bib file: https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/Chocolate.bib
> 
> Drag and drop a PDF into a line in the main table. Attach the PDF. Then, you can open the PDF in JabRef.

Is there any tutorial available which guides how to create a .bib file or use an existing file in our local system?

**Comment by ThiloteE** [comment]
@Anirudhxx If you open JabRef, an empty library will be created. If you add entries to that library, it will automatically be saved as `.bib` file.
See also
- https://docs.jabref.org/advanced/fields
- https://tex.stackexchange.com/questions/231729/how-do-i-create-a-bib-file-for-bibtex
- https://docs.jabref.org/cite/bibtex-and-biblatex
- https://latex-tutorial.com/tutorials/bibtex/

**Comment by koppor** [comment]
> Is there any tutorial available which guides how to create a .bib file or use an existing file in our local system?

I don't know your previous experiences. Did you use an application working with files? Like Microsoft Word or Notepad++?

Maybe, the wording "library" is confusing for you? A library is a `.bib` file.

![image](https://github.com/JabRef/jabref/assets/1366654/4f5f5802-a21f-47e5-aa92-1f55c01338ae)

If you had installed JabRef and checked out JabRef, you could navigate to the JabRef folder, go to src/test/resources/testbib sub directory and double click on `Chocolate.bib`. Tests on Windows only.

**Comment by Anirudhxx** [comment]
> documentViewerView.setLiveMode(false);
i think here we're trying to directly set a bound value of togglebutton `modeLive ` is causing the issue. But when i tried fixing it 
` boolean currentLiveModeValue = viewModel.liveModeProperty().get();
    // Toggle the value
     boolean newLiveModeValue = !currentLiveModeValue;
    // Update the view model with the toggled value
    viewModel.setLiveMode(newLiveModeValue);`
it's still showing the same error, do you have any suggestions?

**Comment by Siedlerchr** [comment]
The error message is clear. You cannot set a value that is set using Binding. Maybe you should read about javafx. bindings first https://www.informit.com/articles/article.aspx?p=2251210&seqNum=4
https://edencoding.com/javafx-properties-and-binding-a-complete-guide/

**Comment by SimoneSantin** [comment]
Hello, I'm testing the software trying to understand the reason for the bug, but I'm struggling to fully comprehend the function of the 'live' and 'locked' buttons. What would be their purpose? Additionally, I've noticed that when I press the 'live' button, it then moves to 'locked' (thus allowing me to enter 'locked' mode and avoiding the bug). However, I would like to understand if this is an additional issue to be fixed or if it's intended behavior. Thank you for your responses, and I apologize for any potentially silly questions as I'm new to this software.

**Comment by koppor** [comment]
@SimoneSantin Do you know about Ctrl+Shift+F in IntelliJ? I searched for "Locked".

![image](https://github.com/JabRef/jabref/assets/1366654/b2dbba97-cca1-423c-9864-bf5843a964b9)

I found something interesting in `DocumentViewer.fxml`:

```xml
<Tooltip text="%Show this document until unlocked."/>
```

The other one is

```xml
<Tooltip text="%Show the document of the currently selected entry."/>
```

The intention is to be mutually exclusive:

Either the document viewer updates the document on change of a BibEntry (`modeLive`) or it keeps the current document (`modeLocked`). Therefore, there is a bi-directional binding of modeLock and modeLive.

HTH!

**Comment by koppor** [comment]
@SimoneSantin I saw that we both overlooked that the issue was already assigned. Thus, a fix was meanwhile implemented and merged into main. Please choose another issue.
