### ISSUE TITLE
"Open File" doesn't lead anywhere

### ISSUE THREAD

**Issue by siainbuletin** [JabRef/jabref#10959]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 v23H2 (OS Build 22631.3235)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open my BibLaTeX file exported from Zotero with the file directory set on the Zotero/storage folder.
2. Click on an article that has an associated PDF (the correct path is associated in the BibLaTex entry, as seen below):

![image](https://github.com/JabRef/jabref/assets/97026492/1f1c559b-02ac-42e4-8ac9-2a1d855b39f3)

3. Pressing F4 or going to the context menu simply directs me to my regular C:/Users/<User>/Documents directory.

### Appendix

...
<details>

<summary>Log File</summary>

```
2024-03-02 17:15:58 [JavaFX-Launcher] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2024-03-02 17:15:59 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
2024-03-02 17:15:59 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2024-03-02 17:15:59 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2024-03-02 17:15:59 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2024-03-02 17:15:59 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2024-03-02 17:15:59 [JavaFX Application Thread] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Resource "" not found.
2024-03-02 17:16:01 [JavaFX Application Thread] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Resource "" not found.
2024-03-02 17:16:11 [pool-1-thread-1] org.jabref.gui.JabRefDialogService.notify()
INFO: Opening: 'A:\bib\My Library.bib'
2024-03-02 17:16:13 [JavaFX Application Thread] org.jabref.gui.FallbackExceptionHandler.uncaughtException()
ERROR: Uncaught exception occurred in Thread[#60,JavaFX Application Thread,5,main]: java.nio.file.InvalidPathException: Trailing char < > at index 16:  Analitica primă 
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.importer.util.FileFieldParser.convert(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.updateIndex(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.gui.LibraryTab.onDatabaseLoadingSucceed(Unknown Source)
	at org.jabref@5.12.60000/org.jabref.gui.util.DefaultTaskExecutor.lambda$getJavaFXTask$4(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.concurrent.Task.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.concurrent.Task.setState(Unknown Source)
	at org.jabref.merged.module@5.12.60000/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.12.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by HoussemNasri** [comment]
Try to add a colon `:` just before the file path, like this `file = {:A:\Zotero\storage...`

**Comment by HoussemNasri** [comment]
It turns out JabRef has a cleanup action for this case. After selecting all entries, go to the menu bar and select `Quality > Cleanup entries`. Select `Upgrade external PDF/PS links to use the 'File' field`, then click OK.

**Comment by Siedlerchr** [comment]
Can you please verify that with the newest development version as well?
Refs https://github.com/JabRef/jabref/pull/9129
The FieldFieldParser needs to probably be adjusted (see the tests as well)=

**Comment by siainbuletin** [comment]
@HoussemNasri Just performed the cleanup on this one file, ended up with this string:

![image](https://github.com/JabRef/jabref/assets/97026492/30014d4c-63ef-4843-a457-0515f5188ccd)

Please note that I have next to no knowledge of anything related to programming, so I might've done something else along the way. I'm currently trying to migrate from Zotero as it's gotten incredibly sluggish with processing my files and not even my 32gb ram, i9-12th generation pc can run it smoothly. For context, I have a ridiculous bib database (>8k entries)

@Siedlerchr Currently backing up again and installing the latest branch to see what happens.

**Comment by ThiloteE** [comment]
Is there a better solution than a cleanup action? Something more automatic?

**Comment by Siedlerchr** [comment]
For solving the issue:
0. Prepare a bib entry with such a file link 
1. Add a new test case for https://github.com/JabRef/jabref/blob/71a0b62591e2c3a5d981b2cb6c9f8df7010b8e09/src/test/java/org/jabref/logic/importer/util/FileFieldParserTest.java#L40
2.  Adjust the logic of the FileFieldParser

**Comment by HoussemNasri** [comment]
> Just performed the cleanup on this one file, ended up with this string:

Yeah, I just performed that on a Windows machine and got the same result. It seems JabRef is not dealing well with backslashes in the file path. It worked when I used double backslashes instead of one.

> Can you please verify that with the newest development version as well?

I reproduced it on the development version too.

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/10871.

@siainbuletin How did you get the content in the `file` field? Did you add the path manually?

**Comment by siainbuletin** [comment]
@koppor No, the initial path which wouldn't open is just what is set up by the Better BibLaTeX export function in Zotero. The second is what I got when I ran `Cleanup entries`, as @HoussemNasri  told me to. I didn't tinker with anything manually.

**Comment by HoussemNasri** [comment]
Makes sense, I just tried the default Zotero export function and it has the same file field format as jabref which is `description:path:filetype`. If the description and filetype are not specified it should be `:path:`

**Comment by koppor** [comment]
JabRef has some auto detection magic if the first colon is ommitted and just a path contained. There should be test cades around...

**Comment by siainbuletin** [comment]
Any news on this? Possible workarounds?

**Comment by Siedlerchr** [comment]
@siainbuletin 
I'm taking a look at it. A simple workaround is to add a colon before the file path in the file field

e.g. `:A:\Zotero..\.pdf` that works

**Comment by Siedlerchr** [comment]
@siainbuletin You could try this version now, it should be able to parse the file paths now https://builds.jabref.org/pull/11038/merge
