### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JoshuaBoschner** [JabRef/jabref#11086]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

### Appendix

Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
No open database detected
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Resource "" not found.
Opening: 'E:\Masterarbeit\00_Dokumente\03_Diplomthesis\01_Masterarbeit Boschner\literature.bib'
Resource "" not found.
Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@4f4f0cf1, org.jabref.gui.maintable.MainTableColumnModel@ba6049f2, org.jabref.gui.maintable.MainTableColumnModel@7120c2ae, org.jabref.gui.maintable.MainTableColumnModel@4bb472e0, org.jabref.gui.maintable.MainTableColumnModel@87d1ffbc, org.jabref.gui.maintable.MainTableColumnModel@31e60f81, org.jabref.gui.maintable.MainTableColumnModel@aaea1368, org.jabref.gui.maintable.MainTableColumnModel@a48e794d, org.jabref.gui.maintable.MainTableColumnModel@95d5d47, org.jabref.gui.maintable.MainTableColumnModel@2fc415af, org.jabref.gui.maintable.MainTableColumnModel@d1896e4b]
Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@4f4f0cf1, org.jabref.gui.maintable.MainTableColumnModel@ba6049f2, org.jabref.gui.maintable.MainTableColumnModel@7120c2ae, org.jabref.gui.maintable.MainTableColumnModel@4bb472e0, org.jabref.gui.maintable.MainTableColumnModel@87d1ffbc, org.jabref.gui.maintable.MainTableColumnModel@31e60f81, org.jabref.gui.maintable.MainTableColumnModel@aaea1368, org.jabref.gui.maintable.MainTableColumnModel@a48e794d, org.jabref.gui.maintable.MainTableColumnModel@95d5d47, org.jabref.gui.maintable.MainTableColumnModel@d1896e4b]
Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@4f4f0cf1, org.jabref.gui.maintable.MainTableColumnModel@ba6049f2, org.jabref.gui.maintable.MainTableColumnModel@7120c2ae, org.jabref.gui.maintable.MainTableColumnModel@4bb472e0, org.jabref.gui.maintable.MainTableColumnModel@87d1ffbc, org.jabref.gui.maintable.MainTableColumnModel@31e60f81, org.jabref.gui.maintable.MainTableColumnModel@aaea1368, org.jabref.gui.maintable.MainTableColumnModel@a48e794d, org.jabref.gui.maintable.MainTableColumnModel@95d5d47]
Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [3, -2147483646) out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Issue on GitHub successfully reported.

**Comment by Siedlerchr** [comment]
Thanks for the report. Very odd. Can you please test the latest dev version?
https://builds.jabref.org/main/

**Comment by JoshuaBoschner** [comment]
Thank for the reply. Its not working for me in the latest dev version.

<details>
<summary>Detail information:</summary>

```
Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [2, -2147483647) out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [2, -2147483647) out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [2, -2147483647) out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[#42,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [2, -2147483647) out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.304/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Log copied to clipboard.
```

</details>

**Comment by Siedlerchr** [comment]
Can you please add some more info on your OS and the steps you do/did?

Can you reset your preferences? Either in  preferences dialog or via Cli

https://docs.jabref.org/advanced/commandline


JoshuaBoschner ***@***.***> schrieb am So., 24. März 2024,
16:39:

**Comment by Siedlerchr** [comment]
Could be related to https://bugs.openjdk.org/browse/JDK-8293795

**Comment by JoshuaBoschner** [comment]
OS: Microsoft Windows 11 Pro

This error even occurs with an empty library. 
It occurs when adding an empty entry in the library or searching in the search toolbar.

As is figured out right now, starting the application as administrator solved the problem ...

**Comment by Siedlerchr** [comment]
@JoshuaBoschner  Can you please try the version from here  https://builds.jabref.org/jdk-ea/ if this works?

**Comment by koppor** [comment]
Issue tracked at https://github.com/JabRef/jabref/issues/11151.
