### ISSUE TITLE
exceptions when opening and closing a library

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#11142]
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

After opening a new or existing library, this exception occurs:
![1](https://github.com/JabRef/jabref/assets/42808557/6bf480a8-4a0e-40f2-b6ff-325de449b8bb)

After closing a library, this exception occurs:
![2](https://github.com/JabRef/jabref/assets/42808557/0d73b67e-b0bf-4b3b-a076-c5de8d54969c)

After closing the dialog window, JabRef works fine.

**Comment by AdamWysokinski** [comment]
Sure.

Upon opening:
```
Could not initialize the IndexWriter
org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/home/eb/.local/share/jabref/lucene/99/24684ab8--library.bib/_2s.cfs") [slice=_2s.fnm])): 1 (needs to be between 0 and 0)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.codecs.CodecUtil.checkHeader(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.codecs.CodecUtil.checkIndexHeader(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.codecs.lucene94.Lucene94FieldInfosFormat.read(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.IndexWriter.readFieldInfos(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.IndexWriter.getFieldNumberMap(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.IndexWriter.<init>(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.initializeIndexWriterAndReader(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.getIndexWriter(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.getListOfFilePaths(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.IndexingTaskManager.updateIndex(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.gui.LibraryTab.onDatabaseLoadingSucceed(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.gui.util.DefaultTaskExecutor.lambda$getJavaFXTask$4(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task.setState(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (7fc82d33). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/home/eb/.local/share/jabref/lucene/99/24684ab8--library.bib/_2s.cfs") [slice=_2s.fnm]))
		at org.apache.lucene.core@9.9.1/org.apache.lucene.codecs.CodecUtil.checkFooter(Unknown Source)
		... 29 more

Uncaught exception occurred in Thread[#81,JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.getReader(boolean, boolean)" because "<parameter1>" is null
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.DirectoryReader.open(Unknown Source)
	at org.apache.lucene.core@9.9.1/org.apache.lucene.index.DirectoryReader.open(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.initializeIndexWriterAndReader(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.getIndexWriter(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.getListOfFilePaths(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.IndexingTaskManager.updateIndex(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.gui.LibraryTab.onDatabaseLoadingSucceed(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.gui.util.DefaultTaskExecutor.lambda$getJavaFXTask$4(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task.setState(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Upon closing:
```
Uncaught exception occurred in Thread[#81,JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.close()" because "this.indexWriter" is null
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexer.close(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.logic.pdf.search.PdfIndexerManager.shutdownIndexer(Unknown Source)
	at org.jabref@5.13.30081/org.jabref.gui.LibraryTab.onClosed(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.scene.control.behavior.TabPaneBehavior.closeTab(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$3.handle(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$3.handle(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.30081/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Siedlerchr** [comment]
Wait a moment! Seems like you have an older version of JabRef 5.13. The latest version  must be this one
JabRef 5.13--2024-04-01--6bdcf63

**Comment by AdamWysokinski** [comment]
You're right, my mistake, sorry!

**Comment by Siedlerchr** [comment]
Another hint: Release versions usually have 5.x.60000 as version number
