### ISSUE TITLE
Total Breakdown

### ISSUE THREAD

**Issue by Energie-Fan** [JabRef/jabref#11188]
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04.4 LTS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. obening Jabref
2. clicking somewere

### Appendix

Not updating theme because it hasn't changed
Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
JabRef could not open the key store
No open database detected
Öffne: .....
No Unicode mapping for CID+71 (71) in font AAAABM+ArialMT
No Unicode mapping for CID+83 (83) in font AAAABM+ArialMT
No Unicode mapping for CID+69 (69) in font AAAABM+ArialMT
No Unicode mapping for CID+100 (100) in font AAAABM+ArialMT
No Unicode mapping for CID+117 (117) in font AAAABM+ArialMT
No Unicode mapping for CID+99 (99) in font AAAABM+ArialMT
No Unicode mapping for CID+97 (97) in font AAAABM+ArialMT
No Unicode mapping for CID+116 (116) in font AAAABM+ArialMT
No Unicode mapping for CID+105 (105) in font AAAABM+ArialMT
No Unicode mapping for CID+111 (111) in font AAAABM+ArialMT
No Unicode mapping for CID+110 (110) in font AAAABM+ArialMT
No Unicode mapping for CID+108 (108) in font AAAABM+ArialMT
No Unicode mapping for CID+86 (86) in font AAAABM+ArialMT
No Unicode mapping for CID+101 (101) in font AAAABM+ArialMT
No Unicode mapping for CID+114 (114) in font AAAABM+ArialMT
No Unicode mapping for CID+115 (115) in font AAAABM+ArialMT
No Unicode mapping for CID+50 (50) in font AAAABM+ArialMT
No Unicode mapping for CID+54 (54) in font AAAABM+ArialMT
No Unicode mapping for CID+57 (57) in font AAAABM+ArialMT
No Unicode mapping for CID+52 (52) in font AAAABM+ArialMT
No Unicode mapping for CID+49 (49) in font AAAABM+ArialMT
No Unicode mapping for CID+53 (53) in font AAAABM+ArialMT
No Unicode mapping for CID+55 (55) in font AAAABM+ArialMT
No Unicode mapping for CID+51 (51) in font AAAABM+ArialMT
No Unicode mapping for CID+44 (44) in font AAAABM+ArialMT
No Unicode mapping for CID+48 (48) in font AAAABM+ArialMT
No Unicode mapping for CID+56 (56) in font AAAABM+ArialMT
No Unicode mapping for CID+71 (71) in font AAAABU+ArialMT
No Unicode mapping for CID+83 (83) in font AAAABU+ArialMT
No Unicode mapping for CID+69 (69) in font AAAABU+ArialMT
No Unicode mapping for CID+100 (100) in font AAAABU+ArialMT
No Unicode mapping for CID+117 (117) in font AAAABU+ArialMT
No Unicode mapping for CID+99 (99) in font AAAABU+ArialMT
No Unicode mapping for CID+97 (97) in font AAAABU+ArialMT
No Unicode mapping for CID+116 (116) in font AAAABU+ArialMT
No Unicode mapping for CID+105 (105) in font AAAABU+ArialMT
No Unicode mapping for CID+111 (111) in font AAAABU+ArialMT
No Unicode mapping for CID+110 (110) in font AAAABU+ArialMT
No Unicode mapping for CID+108 (108) in font AAAABU+ArialMT
No Unicode mapping for CID+86 (86) in font AAAABU+ArialMT
No Unicode mapping for CID+101 (101) in font AAAABU+ArialMT
No Unicode mapping for CID+114 (114) in font AAAABU+ArialMT
No Unicode mapping for CID+115 (115) in font AAAABU+ArialMT
No Unicode mapping for CID+50 (50) in font AAAABU+ArialMT
No Unicode mapping for CID+54 (54) in font AAAABU+ArialMT
No Unicode mapping for CID+49 (49) in font AAAABU+ArialMT
No Unicode mapping for CID+44 (44) in font AAAABU+ArialMT
No Unicode mapping for CID+48 (48) in font AAAABU+ArialMT
No Unicode mapping for CID+56 (56) in font AAAABU+ArialMT
No Unicode mapping for CID+52 (52) in font AAAABU+ArialMT
No Unicode mapping for CID+53 (53) in font AAAABU+ArialMT
No Unicode mapping for CID+55 (55) in font AAAABU+ArialMT
No Unicode mapping for CID+51 (51) in font AAAABU+ArialMT
No Unicode mapping for CID+57 (57) in font AAAABU+ArialMT
No Unicode mapping for CID+71 (71) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+114 (114) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+117 (117) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+110 (110) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+100 (100) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+105 (105) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+115 (115) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+95 (95) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+66 (66) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+97 (97) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+101 (101) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+109 (109) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+49 (49) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+58 (58) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+53 (53) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+48 (48) in font AAAABV+Arial-BoldMT
No Unicode mapping for CID+71 (71) in font AAAACK+ArialMT
No Unicode mapping for CID+83 (83) in font AAAACK+ArialMT
No Unicode mapping for CID+69 (69) in font AAAACK+ArialMT
No Unicode mapping for CID+100 (100) in font AAAACK+ArialMT
No Unicode mapping for CID+117 (117) in font AAAACK+ArialMT
No Unicode mapping for CID+99 (99) in font AAAACK+ArialMT
No Unicode mapping for CID+97 (97) in font AAAACK+ArialMT
No Unicode mapping for CID+116 (116) in font AAAACK+ArialMT
No Unicode mapping for CID+105 (105) in font AAAACK+ArialMT
No Unicode mapping for CID+111 (111) in font AAAACK+ArialMT
No Unicode mapping for CID+110 (110) in font AAAACK+ArialMT
No Unicode mapping for CID+108 (108) in font AAAACK+ArialMT
No Unicode mapping for CID+86 (86) in font AAAACK+ArialMT
No Unicode mapping for CID+101 (101) in font AAAACK+ArialMT
No Unicode mapping for CID+114 (114) in font AAAACK+ArialMT
No Unicode mapping for CID+115 (115) in font AAAACK+ArialMT
No Unicode mapping for CID+71 (71) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+83 (83) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+69 (69) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+100 (100) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+117 (117) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+99 (99) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+97 (97) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+116 (116) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+105 (105) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+111 (111) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+110 (110) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+108 (108) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+86 (86) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+101 (101) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+114 (114) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+115 (115) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+57 (57) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+48 (48) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+49 (49) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+44 (44) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+52 (52) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+53 (53) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+55 (55) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+54 (54) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+50 (50) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+56 (56) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+51 (51) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+177 (177) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+43 (43) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+82 (82) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+72 (72) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+58 (58) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+32 (32) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+109 (109) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+66 (66) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+111 (111) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+100 (100) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+101 (101) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+110 (110) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+97 (97) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+117 (117) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+102 (102) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+98 (98) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+58 (58) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+120 (120) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+66 (66) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+104 (104) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+122 (122) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+112 (112) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+85 (85) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+107 (107) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+40 (40) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+68 (68) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+228 (228) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+103 (103) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+41 (41) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+90 (90) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+98 (98) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+68 (68) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+99 (99) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+104 (104) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+102 (102) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+75 (75) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+65 (65) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+87 (87) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+67 (67) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+84 (84) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+79 (79) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+70 (70) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+87 (87) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+74 (74) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+45 (45) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+73 (73) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+118 (118) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+252 (252) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+246 (246) in font AAAACQ+Generic1-Regular
No Unicode mapping for CID+85 (85) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+45 (45) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+87 (87) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+101 (101) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+114 (114) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+116 (116) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+32 (32) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+98 (98) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+105 (105) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+115 (115) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+48 (48) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+44 (44) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+55 (55) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+54 (54) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+47 (47) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+109 (109) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+178 (178) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+75 (75) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+83 (83) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+99 (99) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+104 (104) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+108 (108) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+110 (110) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+97 (97) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+120 (120) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+46 (46) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+52 (52) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+70 (70) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+252 (252) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+103 (103) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+246 (246) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+223 (223) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+49 (49) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+53 (53) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+50 (50) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+118 (118) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+117 (117) in font AAAACS+Generic2-Regular
No Unicode mapping for CID+75 (75) in font AAAACR+Generic0-Regular
No Unicode mapping for CID+114 (114) in font AAAACR+Generic0-Regular
Try to fix different descendant font types for font VNKJYR+ArialMT
Uncaught exception occurred in Thread[#53,JavaFX Application Thread,5,main]
java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.jabref.merged.module) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.jabref.merged.module
	at org.jabref.merged.module@5.14.42/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.<init>(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.autoComplete(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.fieldeditors.PersonsEditor.<init>(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.fieldeditors.FieldEditors.getForField(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.FieldsEditorTab.createLabelAndEditor(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.FieldsEditorTab.lambda$setupPanel$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.EntryEditor.lambda$new$0(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@22/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.findNearestAvailableTab(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$0(Unknown Source)
	at javafx.base@22/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.EntryEditor.recalculateVisibleTabs(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.entryeditor.EntryEditor.setEntry(Unknown Source)
	at org.jabref@5.14.42/org.jabref.gui.LibraryTab.lambda$createMainTable$11(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at javafx.controls@22/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Problem erfolgreich auf GitHub gemeldet.
Problem erfolgreich auf GitHub gemeldet.

**Comment by Siedlerchr** [comment]
Can you please test with the latest development version? https://builds.jabref.org/main/

**Comment by koppor** [comment]
@Energie-Fan if the main build does not work, please try the jdk-ea build (sister directory in builds.jabref.org)

**Comment by koppor** [comment]
I saw it today, too:

![image](https://github.com/JabRef/jabref/assets/1366654/0834ec40-cd5b-4d8c-ada9-2ea629104198)

```
java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.jabref.merged.module) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.jabref.merged.module
	at org.jabref.merged.module@5.14.41/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(Unknown Source)
```

**Comment by Siedlerchr** [comment]
For author editor field?

**Comment by koppor** [comment]
Does not happen in `main`, but at that build.

Happens when trying to create a new entry. Entry editor not shown at all.

One cannot open the entry editor at existing fields.

Does not occur at "citation key". Seems really to be the case at author.

I uninstalled `JabRef 5.14--2024-04-10--aa0fa84` and installed `JabRef 5.14--2024-04-12--0d1b5e8` (from https://builds.jabref.org/jdk-ea/). Still occurs.
