### ISSUE TITLE
InaccessibleObjectException

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#11198]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.14--2024-04-12--0d1b5e8 Linux 6.8.4-200.fc39.x86_64 amd64  Java 21.0.2  JavaFX 22+30

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. this happened in the settings, when going though its options

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to module org.jabref.merged.module
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.jabref.merged.module@5.14.47/impl.org.controlsfx.ImplUtils.getChildrenReflectively(Unknown Source)
	at org.jabref.merged.module@5.14.47/impl.org.controlsfx.ImplUtils.getChildren(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.decoration.GraphicDecoration.applyDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.47/impl.org.controlsfx.skin.DecorationPane.showDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.47/impl.org.controlsfx.skin.DecorationPane.addAllDecorationsOnNode(Unknown Source)
	at org.jabref.merged.module@5.14.47/impl.org.controlsfx.skin.DecorationPane.updateDecorationsOnNode(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.decoration.Decorator.lambda$updateDecorationsOnNode$0(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.decoration.Decorator.lambda$getDecorationPane$1(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.decoration.Decorator$1.invalidated(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Parent.scenesChanged(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Parent.scenesChanged(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Parent.scenesChanged(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Parent.scenesChanged(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics@22/javafx.scene.Parent$2.onChanged(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.controls@22/javafx.scene.control.skin.ScrollPaneSkin.lambda$new$0(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.ListenerHelper$4.changed(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@22/javafx.scene.control.ScrollPane.setContent(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.preferences.PreferencesDialogView.lambda$initialize$4(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@22/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MultipleSelectionModelBase.lambda$new$0(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22/javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	at javafx.controls@22/javafx.scene.control.SelectionModel.setSelectedIndex(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MultipleSelectionModelBase.select(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MultipleSelectionModelBase.clearAndSelect(Unknown Source)
	at javafx.controls@22/javafx.scene.control.ListView$ListViewBitSetSelectionModel.clearAndSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.CellBehaviorBase.simpleSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.CellBehaviorBase.doSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls@22/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@22/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.preferences.ShowPreferencesAction.execute(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.action.Action.handle(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
@koppor  seems like we need to add all exports from run to the mainArgs here as well

**Comment by Siedlerchr** [comment]
refs https://github.com/JabRef/jabref/pull/11195

**Comment by koppor** [comment]
@Siedlerchr note this exception is about `opens`. I will have a look later

- java.lang.reflect.InaccessibleObjectException: 
- Unable to make protected `javafx.collections.ObservableList javafx.scene.Parent.getChildren()` accessible: 
- module `javafx.graphics` does not "`opens javafx.scene`" to module `org.jabref.merged.module`

**Comment by Siedlerchr** [comment]
That are exactly these we have in the run block

**Comment by koppor** [comment]
> That are exactly these we have in the run block. I am just curious why this was working fine before and got picked up

I think, this is because https://github.com/JabRef/jabref/pull/11170 in this case. I am not sure about the other issue though.

Added all fixes to the PR, I'll test soon.
