### ISSUE TITLE
Uncaught exception occurred in Thread[#39,JavaFX Application Thread,5,main] -> different # -> new bug report!?

### ISSUE THREAD

**Issue by frohowi** [JabRef/jabref#11194]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.13--2024-04-01--6bdcf63 Windows 10 10.0 amd64  Java 21.0.2  JavaFX 22+30

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef
2. Start typing in search field or try copy/paste in group (field Suchausdruck for type "Freier Suchausdruck") or try do copy/paste manually the "about" information
3. error occurs/message is shown

### Appendix

I tried to install the latest development build (.msi) but being in the role of "normal"  uster Jabref did not start with this latest development build.

Starting the latest development build (JabRef 5.14--2024-04-12--0d1b5e8
Windows 10 10.0 amd64 
Java 21.0.2 
JavaFX 22+30) as administrator was successfull (and the bug was not present)

With version 5.13: 
- Resetting preferences was not successfull and bug was still persistent
- Reinstalling version 5.12 was not successfull and bus was still persistent (however I'm not 100% sure having had installed 5.12 before installing 5.13)
- Starting 5.13 as administrator was successfull and the bug was not present

Sorry, I was not sure if my bug is identical to  [#11188](https://github.com/JabRef/jabref/issues/11188)  so I started a  new one.

<details>

<summary>Log File</summary>

```
Uncaught exception occurred in Thread[#39,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [33, -2147483616) out of bounds for length 81
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.13.60000/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.13.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.13.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by frohowi** [comment]
Using the the latest development release (JabRef 5.14--2024-04-12--0d1b5e8
Windows 10 10.0 amd64 
Java 21.0.2 
JavaFX 22+30) as administrator (not importing my saved preferences) now also leads to following error message when clicking in my opened library (single click) on an entry:

Uncaught exception occurred in Thread[#39,JavaFX Application Thread,5,main]
java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.jabref.merged.module) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.jabref.merged.module
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.autoComplete(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.fieldeditors.PersonsEditor.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.fieldeditors.FieldEditors.getForField(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.createLabelAndEditor(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.lambda$setupPanel$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.EntryEditor.setEntry(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.LibraryTab.lambda$createMainTable$11(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base@22/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base@22/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at javafx.controls@22/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at javafx.controls@22/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by frohowi** [comment]
Deinstallation of JabRef via Windows Preferences followed by installation of JabRef version **5.11** did not resolve the bug. 

Upgrading from 5.11 to 5.13 did not change this fact either.

Information on Windows version:
Edition	Windows 10 Enterprise
Version	22H2
Installiert am	‎01.‎02.‎2021
Betriebssystembuild	19045.4291
Leistung	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by koppor** [comment]
@frohowi This is the same issue as https://github.com/JabRef/jabref/issues/11188. Closing this as duplicate, because the other issue number is lower.

**Comment by koppor** [comment]
@frohowi Please try out https://builds.jabref.org/pull/11195/merge?

**Comment by frohowi** [comment]
> @frohowi Please try out https://builds.jabref.org/pull/11195/merge?

I just installed the msi package in the "folder" indicated. 

JabRef 5.14-PullRequest11195.53--2024-04-15--0421bc4
Windows 10 10.0 amd64 
Java 21.0.2 
JavaFX 22+30

After installation, Jabref did not start in normal mode but only when starting as administrator.

Same bug as before: When clicking or double clicking on an entry of my library, I got the error message (but not each time...):

Uncaught exception occurred in Thread[#39,JavaFX Application Thread,5,main]
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to module org.jabref.merged.module
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.jabref.merged.module@5.14.30053/impl.org.controlsfx.ImplUtils.getChildrenReflectively(Unknown Source)
	at org.jabref.merged.module@5.14.30053/impl.org.controlsfx.ImplUtils.getChildren(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.control.decoration.GraphicDecoration.applyDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.30053/impl.org.controlsfx.skin.DecorationPane.showDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.30053/impl.org.controlsfx.skin.DecorationPane.addAllDecorationsOnNode(Unknown Source)
	at org.jabref.merged.module@5.14.30053/impl.org.controlsfx.skin.DecorationPane.updateDecorationsOnNode(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.control.decoration.Decorator.lambda$updateDecorationsOnNode$0(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.control.decoration.Decorator.getDecorationPane(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.control.decoration.Decorator.updateDecorationsOnNode(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.control.decoration.Decorator.addDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.validation.decoration.AbstractValidationDecoration.decorate(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.validation.decoration.AbstractValidationDecoration.lambda$applyValidationDecoration$0(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.jabref.merged.module@5.14.30053/org.controlsfx.validation.decoration.AbstractValidationDecoration.applyValidationDecoration(Unknown Source)
	at org.jabref.merged.module@5.14.30053/de.saxsys.mvvmfx.utils.validation.visualization.ControlsFxVisualizer.applyVisualization(Unknown Source)
	at org.jabref.merged.module@5.14.30053/de.saxsys.mvvmfx.utils.validation.visualization.ValidationVisualizerBase.lambda$initVisualization$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by frohowi** [comment]
... but writing in search field didn't produce an error :)
