### ISSUE TITLE
controlsfx textfiled AutoCompleteBinding issue?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#11197]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.14--2024-04-12--0d1b5e8 Linux 6.8.4-200.fc39.x86_64 amd64  Java 21.0.2  JavaFX 22+30

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open library
2. doubleclick on entry, to see entry details
3. click on any tab, like `Required fields`

the error below occurs - *sometimes*. My `abstract` field works, however.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.jabref.merged.module) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.jabref.merged.module
	at org.jabref.merged.module@5.14.47/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.autoComplete(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.autoComplete(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.fieldeditors.SimpleEditor.<init>(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.fieldeditors.FieldEditors.getForField(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.createLabelAndEditor(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.lambda$setupPanel$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref@5.14.47/org.jabref.gui.entryeditor.EntryEditor.lambda$new$0(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.controls@22/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at javafx.controls@22/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at javafx.controls@22/com.sun.javafx.scene.control.behavior.TabPaneBehavior.selectTab(Unknown Source)
	at javafx.controls@22/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at javafx.controls@22/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


```

</details>

**Comment by ilippert** [comment]
oh, I guess this is the same as https://github.com/JabRef/jabref/issues/11188 and therefore I close this issue
