### ISSUE TITLE
While testing performance I'm getting this exception

### ISSUE THREAD

**Issue by SunilMulgi** [JabRef/jabref#11193]
java.net.MalformedURLException: unknown protocol: https://
	at java.base/java.net.URL.<init>(URL.java:452)
	at java.base/java.net.URL.<init>(URL.java:338)
	at java.base/java.net.URL.<init>(URL.java:361)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.getUrl(HTTPSamplerBase.java:1133)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1311)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1300)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by koppor** [comment]
I don't see any JabRef methods in the stack trace. What are the steps you are doing to get that exception? Start with the IDE you are using!
