### ISSUE TITLE
Drag and Drop of a file under macOS 14.4.1 gives an exception: Flush is forbidden from target 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11214]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

JabRef 5.14-PullRequest11195.69--2024-04-15--26b72db Mac OS X 14.4.1 aarch64  Java 21.0.2  JavaFX 22+30

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef
2. Drag a PDF file onto the main table
3. Get the exception 

Note: Dropping onto the entry editor works 

### Appendix

```
java.lang.UnsupportedOperationException: Flush is forbidden from target!
	at javafx.graphics@22/com.sun.glass.ui.View$2.flush(View.java:1017)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:275)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1326)
	at javafx.graphics@22/javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3169)
	at javafx.graphics@22/javafx.scene.Scene$DnDGesture.process(Scene.java:3238)
	at javafx.graphics@22/javafx.scene.Scene$MouseHandler.process(Scene.java:4001)
	at javafx.graphics@22/javafx.scene.Scene.processMouseEvent(Scene.java:1891)
	at javafx.graphics@22/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2709)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at javafx.graphics@22/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@22/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@22/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@22/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

```

**Comment by koppor** [comment]
This is a challenge for the [javafxreproducer](https://github.com/Siedlerchr/javafxreproducer), isn't it?

**Comment by Siedlerchr** [comment]
Maybe related https://github.com/openjdk/jfx/pull/1371
