### ISSUE TITLE
Preferences do not open if no files are open

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1130]
JabRef version 3.3dev--snapshot--2016-04-06--master--6488cf7 on Windows 10

Steps to reproduce:

1. Close all opened files
2. Open Preferences

Result:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.sf.jabref.gui.labelpattern.LabelPatternPanel.buildGUI(LabelPatternPanel.java:107)
	at net.sf.jabref.gui.labelpattern.LabelPatternPanel.<init>(LabelPatternPanel.java:55)
	at net.sf.jabref.gui.preftabs.LabelPatternPrefTab.<init>(LabelPatternPrefTab.java:58)
	at net.sf.jabref.gui.preftabs.PreferencesDialog.<init>(PreferencesDialog.java:97)
```

**Comment by stefan-kolb** [comment]
```
        for (EntryType type : EntryTypes.getAllValues(panel.getBibDatabaseContext().getMode())) {
            textFields.put(type.getName().toLowerCase(), addEntryType(pan, type, y));
            y++;
        }
```
