### ISSUE TITLE
403 for "lookup fulltext"

### ISSUE THREAD

**Issue by jiucenglou** [JabRef/jabref#11357]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open `https://pubs.acs.org/doi/10.1021/ja010365z` in browser
2. click jabref browser extension to import
3. the error occurs 
    ```
    Error message: org.jabref.logic.importer.FetcherClientException: Encountered HTTP Status code 403 
    URL: https://pubs.acs.org/doi/pdf/10.1021/ja010365z 
    Please check the URL and try again.
    ```
4. pdf can be viewed or downloaded in browser

### Appendix

...
<details>

<summary>Log File</summary>

```
2024-06-07 11:45:50 [JabRef - Remote Listener Server on port 6050] org.jabref.gui.remote.CLIMessageHandler.handleCommandLineArguments()
INFO: Processing message [-importToOpen, C:\Users\HiWin10\AppData\Local\Temp\tmp244C.tmp]
2024-06-07 11:45:55 [JavaFX Application Thread] org.jabref.gui.fieldeditors.LinkedFileViewModel.download()
INFO: Downloading file from 
2024-06-07 11:45:55 [JavaFX Application Thread] org.jabref.gui.linkedfile.DownloadLinkedFileAction.execute()
INFO: Downloading file from https://pubs.acs.org/doi/pdf/10.1021/ja010365z
2024-06-07 11:45:55 [JavaFX Application Thread] org.jabref.gui.linkedfile.DownloadLinkedFileAction.onFailure()
ERROR: Error downloading from URL: URLDownload{source=https://pubs.acs.org/doi/pdf/10.1021/ja010365z}: java.io.IOException: org.jabref.logic.importer.FetcherClientException: Encountered HTTP Status code 403
	at org.jabref@5.13.60000/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	at org.jabref@5.13.60000/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	at org.jabref@5.13.60000/org.jabref.gui.linkedfile.DownloadLinkedFileAction$FileDownloadTask.call(Unknown Source)
	at org.jabref@5.13.60000/org.jabref.gui.linkedfile.DownloadLinkedFileAction$FileDownloadTask.call(Unknown Source)
	at org.jabref@5.13.60000/org.jabref.gui.util.BackgroundTask$3.call(Unknown Source)
	at org.jabref@5.13.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.13.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jabref.logic.importer.FetcherClientException: Encountered HTTP Status code 403
	... 13 more
```

</details>

**Comment by RishabhRawat9** [comment]
I tried to reproduce it but it works as expected the import succeeds in jabref, so i don't think this issue is there anymore.

**Comment by koppor** [comment]
The issue is a bit differnet today:

1.

<img width="1162" height="517" alt="Image" src="https://github.com/user-attachments/assets/0df9d415-ec47-4b14-bb03-0f50dc4ac430" />

2. "Files and links"

3. "+ File"

4. Click "Lookup"

<img width="460" height="274" alt="Image" src="https://github.com/user-attachments/assets/693640af-ffc4-441e-9514-3ced0187ae45" />

5. see

<img width="1431" height="637" alt="Image" src="https://github.com/user-attachments/assets/2d693da5-a137-45a8-8c84-d4d627076f16" />

and

<img width="1209" height="236" alt="Image" src="https://github.com/user-attachments/assets/89757414-cd62-4108-9698-c9eab8e8de07" />

---

Action point: Fix Download

1. AI Service should not ingest online links
2. Download should work
3. Download should THEN Trigger AI (maybe already done by observable)

**Comment by RishabhRawat9** [comment]
Hey @koppor, I traced the 403 during full-text lookup.

The error shown in JabRef is `Access denied. You do not have permission to access this resource`, and the response body contains:

```TEXT
Access denied. You do not have permission to access this resource. Please contact the administrator for assistance or try a different action.

URL: https://pubs.acs.org/doi/suppl/10.1021/acs.inorgchem.2c02170/suppl_file/ic2c02170_si_001.pdf
HTTP 403 Forbidden
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="content-security-policy" content="default-src &#39;none&#39;; script-src &#39;nonce-5ZsvUR9qFJy2wYXYw7p05q&#39; &#39;unsafe-eval&#39; https://challenges.cloudflare.com; script-src-attr &#39;none&#39;; style-src &#39;unsafe-inline&#39;; img-src &#39;self&#39; https://challenges.cloudflare.com; connect-src &#39;self&#39; https://challenges.cloudflare.com; frame-src &#39;self&#39; https://challenges.cloudflare.com blob:; child-src &#39;self&#39; https://challenges.cloudflare.com blob:; worker-src blob:; form-action http: https:; base-uri &#39;self&#39;"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple... (truncated)
```

I also reproduced the same 403 using `curl`. The response contains `cf-mitigated: challenge` and requires JavaScript/cookies, while the URL opens normally in a browser.

The same issue also occurs with another ACS resource (maybe it's for all of the acs resources):
`https://pubs.acs.org/doi/10.1021/acs.inorgchem.2c02170`

Is there an intended fallback for publisher URLs protected by such browser challenges, or should these downloads be treated as unsupported?

Also, regarding embeddings, should AI ingestion simply be skipped when the download fails, since ingestion is intended to operate on a successfully downloaded file?
