### ISSUE TITLE
Exception when importing arXiv entries (commons logging module error)

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#11401]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Push "Add specific entry" button.
2. Select "arXiv" and enter arXiv ID and press Ok
3. An exception is thrown, see below
4. But the entry is at least created, however, hard to tell whether everything is done correctly.

### Appendix

<details>

<summary>Log File</summary>

```
java.lang.IllegalAccessError: class org.apache.http.conn.ssl.AbstractVerifier (in module org.jabref.merged.module) cannot access class org.apache.commons.logging.LogFactory (in module org.apache.commons.logging) because module org.jabref.merged.module does not read module org.apache.commons.logging
	at org.jabref.merged.module@5.14.191/org.apache.http.conn.ssl.AbstractVerifier.<init>(Unknown Source)
	at org.jabref.merged.module@5.14.191/org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(Unknown Source)
	at org.jabref.merged.module@5.14.191/org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(Unknown Source)
	at org.jabref.merged.module@5.14.191/org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.SecurityConfig.createDefaultRegistry(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.SecurityConfig.buildSocketFactory(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.SecurityConfig.createManager(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.ApacheClient.<init>(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.ApacheClient$Builder.lambda$apply$2(Unknown Source)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.ApacheClient$Builder.apply(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.apache.ApacheClient$Builder.apply(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.Config.buildClient(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.Config.getClient(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.BaseRequest.request(Unknown Source)
	at org.jabref.merged.module@5.14.191/kong.unirest.BaseRequest.asString(Unknown Source)
	at org.jabref@5.14.191/org.jabref.logic.net.URLDownload.canBeReached(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.linkedfile.DownloadLinkedFileAction.checkSSLHandshake(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.linkedfile.DownloadLinkedFileAction.execute(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.fieldeditors.LinkedFileViewModel.download(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.externalfiles.ImportHandler.lambda$downloadLinkedFiles$0(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.externalfiles.ImportHandler.downloadLinkedFiles(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.externalfiles.ImportHandler.importEntryWithDuplicateCheck(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.externalfiles.ImportHandler.importEntryWithDuplicateCheck(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.entrytype.EntryTypeViewModel.lambda$runFetcherWorker$4(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@22.0.1/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.importer.NewEntryAction.execute(Unknown Source)
	at org.jabref@5.14.191/org.jabref.gui.actions.JabRefAction.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.14.191/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.14.191/org.controlsfx.control.action.Action.handle(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@22.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@22.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by ytzemih** [comment]
There was another bug with importing DOI entries, but that seems to have gone with today's nightly build.

**Comment by Siedlerchr** [comment]
I can reproduce the issue
