### ISSUE TITLE
java.util.ConcurrentModificationException in saveActions

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11416]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Tumbleweed with KDE Plasma 6.0.5

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select some entries that have an attachment
2. Run Cleanup Entries with the options shown in the screenshot
3. ConcurrentModificationException occurs but cleanup succeeds

JabRef 5.14-PullRequest11403.199--2024-06-21--ef06b19
Linux 6.9.3-1-default amd64 
Java 21.0.2 
JavaFX 22.0.1+7

![image](https://github.com/JabRef/jabref/assets/23321102/65e3b0b2-5a8c-4b5a-9c79-85ed4f976130)

### Appendix

...
<details>

<summary>Log File</summary>

```
java.util.ConcurrentModificationException
	at java.base/java.util.AbstractList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at org.jabref@5.14.30199/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@5.14.30199/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@5.14.30199/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.14.30199/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.14.30199/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the report 
Unfortunately, no screenshost is present, can you pleae re-add it?

**Comment by ryan-carpenter** [comment]
> Thanks for the report Unfortunately, no screenshot is present, can you please re-add it?

Added to the report.

**Comment by Siedlerchr** [comment]
This shoudl now be be fixed by https://github.com/JabRef/jabref/pull/12809
