### ISSUE TITLE
Unable to make protected javafx.scene.control.skin.TableHeaderRow

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11426]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Tumbleweed with KDE Plasma 6.0.5

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Check integrity of some entries
2. Error occurs and the Check integrity window pops up.
3. Dismiss the error (times three)
4. Continue working

JabRef 5.14-PullRequest11414.206--2024-06-22--a41867e
Linux 6.9.3-1-default amd64 
Java 21.0.2 
JavaFX 22.0.1+7

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.scene.control.skin.TableHeaderRow javafx.scene.control.skin.TableViewSkinBase.getTableHeaderRow() accessible: module javafx.controls does not "opens javafx.scene.control.skin" to module org.jabref.merged.module
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.jabref.merged.module@5.14.30206/impl.org.controlsfx.ReflectionUtils.getTableHeaderRowFrom(Unknown Source)
	at org.jabref.merged.module@5.14.30206/org.controlsfx.control.table.FilterPanel.checkChangeContextMenu(Unknown Source)
	at org.jabref.merged.module@5.14.30206/org.controlsfx.control.table.FilterPanel.lambda$new$0(Unknown Source)
	at javafx.base@22.0.1/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22.0.1/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.graphics@22.0.1/javafx.css.StyleableObjectProperty.set(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at javafx.controls@22.0.1/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics@22.0.1/javafx.scene.Node.applyCss(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.HeavyweightDialog.positionStage(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.HeavyweightDialog$1.centerOnScreen(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@22.0.1/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.14.30206/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(Unknown Source)
	at org.jabref@5.14.30206/org.jabref.gui.integrity.IntegrityCheckAction.lambda$execute$1(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@22.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@22.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
needs to be added afterwards here and also in the mac yaml pipelines
 https://github.com/JabRef/jabref/blob/f24a57838b8c8aa29bbdc95baa61e34ca4fd2c5f/build.gradle#L83
