### ISSUE TITLE
JabRef (Portable/tar.gz) not opening in sway/swaywm/wayland; Debian 12

### ISSUE THREAD

**Issue by alaminkouser** [JabRef/jabref#11489]
### JabRef version

5.15 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download the tar.gz file/Linux Portable
2. Extract with tar xf <downloaded_file>
3. run "./bin/JabRef"
4. OR run "./lib/runtime/bin/JabRef"
5. JabRef not opening

### Appendix

...
<details>

<summary>Log File: 5.15 stable</summary>

```
aak@debian:~/Downloads/JabRef$ ./bin/JabRef
Messages are not initialized before accessing key: Display help on command line options
2024-07-13 14:39:47 [main] org.jabref.Launcher.main()
ERROR: Unexpected exception: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.Application.run(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
^Caak@debian:~/Downloads/JabRef$ ./lib/runtime/bin/JabRef
Messages are not initialized before accessing key: Display help on command line options
2024-07-13 14:40:20 [main] org.jabref.Launcher.main()
ERROR: Unexpected exception: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.Application.run(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
^C
```

</details>

...
<details>

<summary>Log File: 5.16 dev; 2024-07-11</summary>

```
aak@debian:~/Downloads/JabRef$ ./bin/JabRef
Messages are not initialized before accessing key: Display help on command line options
2024-07-13 15:03:27 [main] org.jabref.Launcher.main()
ERROR: Unexpected exception: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.Application.run(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
^Caak@debian:~/Downloads/JabRef$ ./lib/runtime/bin/JabRef
Messages are not initialized before accessing key: Display help on command line options
2024-07-13 15:03:38 [main] org.jabref.Launcher.main()
ERROR: Unexpected exception: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.glass.ui.Application.run(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@22.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
^C
```

</details>

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/11464, where we also had a missing `DISPLAY` variable.

Google found https://www.jr-it-services.de/how-to-set-environment-variables-for-x11-programs-running-under-sudo-to-use-wayland-or-xwayland/

To support us fixing the issue, could you work on a `Vagrantfile` similar to the one we made for Ubuntu? -- https://github.com/JabRef/jabref/tree/main/scripts/vms/ubuntu. Background is written down here: https://github.com/JabRef/jabref/tree/main/scripts/vms#virtual-machines-for-testing-jabref

**Comment by koppor** [comment]
Maybe simply

    declare -X DISPLAY=:0

helps, but IDK.

**Comment by alaminkouser** [comment]
It was working when I was in gnome. Let me do some research first.

And it seems I need to have a windows computer to work on `Vagrantfile` file. I will setup a windows computer.

**Comment by koppor** [comment]
> It was working when I was in gnome. Let me do some research first.

As far as I understood, sway is Wayland, and Gnome still has some X11.

> And it seems I need to have a windows computer to work on `Vagrantfile` file. I will setup a windows computer next month.

Where do you get this information from?

I went to https://www.vagrantup.com/, then clicked on Download. Then I **scrolled down**. This is the important step. Do not miss that on that page!

They do offer Linux. Several editions. I tried to mark it in the screenshot. Maybe, it helps, to find it!

![image](https://github.com/user-attachments/assets/0f9da77e-fb56-428e-8bb4-7d19ff962cba)

**Comment by jonassmedegaard** [comment]
make sure to have xwayland installed.

**Comment by koppor** [comment]
@jonassmedegaard Which version did you check? According to https://openjfx.io/highlights/23/, JavaFX has build-in support for wayland? Maybe, it's "just" version 5.15. which does not run? Thus, there could be an FAQ entry added to https://github.com/JabRef/user-documentation/blob/main/en/faq/linux.md. The other possibility is that more people of the community support development. Be it working on issues listed at https://github.com/JabRef/jabref/milestones - or be it contributing in other ways - listed at <https://contribute.jabref.org>.

**Comment by koppor** [comment]
> And it seems I need to have a windows computer to work on `Vagrantfile` file. I will setup a windows computer next month.

@alaminkouser How did this work out? It's now about 16 months later. 😅

**Comment by jonassmedegaard** [comment]
I would love to be wrong, but I found this very issue because I ununstalled xwayland from my system yesterday, only to learn this morning that JabRef failed to load, with a stack track indicating that xwayland was missing. Reinstalling xwayland, loging out and then in again made JabRef work again - and double-checking now, indeed it loads xwayland.

This is the version I am using:
JabRef 6.0-alpha.3--2025-10-30--11a232b
Linux 6.17.11+deb14-amd64 amd64 
Java 24.0.2 
JavaFX 25+29

Perhaps JabRef, or JavaFX more generally, rely on some evironment variables set or unset in order to use Wayland natively?

**Comment by jonassmedegaard** [comment]
Seemingly, what is supported since JavaFX 23 is not *native* Wayland but Wayland via XWayland: https://bugs.openjdk.org/browse/JDK-8326710

**Comment by alaminkouser** [comment]
@koppor Thanks for checking in! Sorry, I actually ended up switching back to GNOME not long after, so I didn’t get around to trying it in the end. Appreciate the follow-up though!

**Comment by koppor** [comment]
Action point: Add Q&A to https://github.com/JabRef/user-documentation/blob/main/en/faq/linux.md

**Comment by Phaneendra2005** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by viictor1** [comment]
Hi! I would like to work on this issue. Can you assign it to me please? :)

**Comment by koppor** [comment]
A  FAQ entry is in place.
