### ISSUE TITLE
Search for unlinked local files throws exception 

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#11540]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Debian Testing

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. Press Shift-F7 or go to Lookup -> Search for unlinked local files
 

### Appendix

...
<details>

<summary>Log File</summary>

java.lang.IllegalStateException: Cannot load org.jabref.gui.externalfiles.unlinkedfilesdialog
	at afterburner.fx/com.airhacks.afterburner.views.ViewLoader.load(Unknown Source)
	at org.jabref@5.16.36/org.jabref.gui.externalfiles.UnlinkedFilesDialogView.<init>(Unknown Source)
	at org.jabref@5.16.36/org.jabref.gui.externalfiles.FindUnlinkedFilesAction.execute(Unknown Source)
	at org.jabref@5.16.36/org.jabref.gui.actions.JabRefAction.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.16.36/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.16.36/org.controlsfx.control.action.Action.handle(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23-ea/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls@23-ea/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls@23-ea/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at javafx.controls@23-ea/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23-ea/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23-ea/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23-ea/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@23-ea/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@23-ea/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@23-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@23-ea/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@23-ea/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/org.jabref/org/jabref/gui/externalfiles/UnlinkedFilesDialog.fxml

</details>

**Comment by Siedlerchr** [comment]
Confirmed:

```
Caused by: javafx.fxml.LoadException: 
/Users/christophs/workspace/jabref/build/resources/main/org/jabref/gui/externalfiles/unlinkedfilesdialog.fxml

	at javafx.fxml@22.0.2/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2727)
	at javafx.fxml@22.0.2/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2697)
	at javafx.fxml@22.0.2/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2568)
	at javafx.fxml@22.0.2/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2536)
	at afterburner.fx/com.airhacks.afterburner.views.ViewLoader.load(ViewLoader.java:172)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at javafx.base@22.0.2/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at javafx.fxml@22.0.2/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@22.0.2/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2693)
	... 28 more
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at org.jabref@100.0.0/org.jabref.gui.externalfiles.UnlinkedFilesDialogView.loadSavedConfiguration(UnlinkedFilesDialogView.java:239)
	at org.jabref@100.0.0/org.jabref.gui.externalfiles.UnlinkedFilesDialogView.initDirectorySelection(UnlinkedFilesDialogView.java:177)
	at org.jabref@100.0.0/org.jabref.gui.externalfiles.UnlinkedFilesDialogView.initialize(UnlinkedFilesDialogView.java:145)
	... 34 more
````

**Comment by Siedlerchr** [comment]
Seems to be an issue related to https://github.com/JabRef/jabref/pull/11493

**Comment by AdamWysokinski** [comment]
Works fine in the latest 5.16 build, thank you!
