### ISSUE TITLE
Cannot invoke "javafx.beans.InvalidationListener.invalidated(javafx.beans.Observable)" because "<local1>[<local5>]" is null

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11628]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Tumbleweed with KDE Plasma 6.0.5

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Unknown: possibly renaming or moving groups

JabRef 5.16--2024-08-13--1374813
Linux 6.9.9-1-default amd64 
Java 21.0.2 
JavaFX 22.0.2+4

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.NullPointerException: Cannot invoke "javafx.beans.InvalidationListener.invalidated(javafx.beans.Observable)" because "<local1>[<local5>]" is null
	at javafx.base@22.0.2/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.2/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@22.0.2/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base@22.0.2/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.maintable.BibEntryTableViewModel.updateMatchCategory(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.maintable.MainTableDataModel.updateEntryGroupMatch(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.maintable.MainTableDataModel.lambda$updateGroupMatches$16(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.maintable.MainTableDataModel.lambda$updateGroupMatches$17(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@5.16.226/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.2/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by ryan-carpenter** [comment]
Edits: updated description with additional context.

**Comment by koppor** [comment]
DevCall: 

- This seems to have been introduced in the floating mode
- Related: https://github.com/JabRef/jabref/issues/10731 - same strack trace in JavaFX

**Comment by calixtus** [comment]
Could not reproduce on windows 10 using `.gradlew run`

**Comment by koppor** [comment]
@ryan-carpenter Could you recheck with the latest build, please?

**Comment by koppor** [comment]
Closing this issue due to inactivity :zzz: 

Please reopen the issue with additional information if the problem persists.
