### ISSUE TITLE
Cannot invoke "javafx.geometry.Point2D.distance(double, double)" because "this.dragStartLocation" is null

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11869]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Tumbleweed with KDE Plasma 6.0.5

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Copy a DOI from a PDF, where the copied string includes a line break and some extraneous characters to the left of the DOI
2. Click "Import by ID" and paste the DOI + extraneous text into the input field.
3. Attempt to select and delete the extraneous characters => _Exception_
5. Repeat steps to check for reproducibility => _No exception_.
6. Repeat steps again, this time clicking and selecting multiple times/location within the "Import by ID" input field => _Exception_
7. Try a few more times testing different locations in the input and with different inputs. I got the exception a few times consecutively, then no exception with just the DOI as input but also no exception when I returned to the previous input. In other words, it isn't clear that the error is related to the input.
8. Attempt to reproduce by dragging selected text within the "Import by ID" field => _No exception_

Form of the input data.
```
Journal 2005;19(2):e123–4. https://doi.org/10.1234/ABC.
0000000000000123
```

The line break is <control> `0xa`

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.NullPointerException: Cannot invoke "javafx.geometry.Point2D.distance(double, double)" because "this.dragStartLocation" is null
	at org.jabref.merged.module@6.0.6325/impl.org.controlsfx.skin.PopOverSkin.lambda$new$7(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@23/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@23/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@23/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@23/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@23/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@23/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by ryan-carpenter** [comment]
An unresolved example of the same exception: https://github.com/mkpaz/atlantafx/issues/66

**Comment by Siedlerchr** [comment]
@xDido  This issue needs refinement and verification first. And it's likely to be caused by external isssues.
If you want to take another issue look through the good first issues https://github.com/orgs/JabRef/projects/5

**Comment by ryan-carpenter** [comment]
> And it's likely to be caused by external isssues.

Note: This was in a Kwin Wayland session, if it matters.

**Comment by Siedlerchr** [comment]
@ryan-carpenter  can you please test if this sitll occurs with the latest dev version that uses javafx25?

**Comment by ryan-carpenter** [comment]
> [@ryan-carpenter](https://github.com/ryan-carpenter) can you please test if this sitll occurs with the latest dev version that uses javafx25?

It does not appear to occur any more. When I pasted the example input into the box, the line break was removed and I was able to click to the left of the DOI and delete the extra text.
