### ISSUE TITLE
Support GPT4All Server API

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#11870]
### Describtion of solution:

I want to use JabRef's AI feature locally. There are multiple applications out there that provide a server API. They very often offer an API that resembles OpenAI API.

GPT4All is such an application. Others are Llama.cpp, Ollama, LMStudio, Jan, KobolCPP. I am sure, there are more, but those are the most well known ones.

The grand advantage of those applications is that they offer more samplers, GPU acceleration, hardware support and support for models that have not been added to JabRef.

### Problem

It kinda works with GPT4All already, but something is wrong. I believe the embeddings are not sent together with the prompt and responses look like they are cutoff in the middle.

GPT4All:
![image](https://github.com/user-attachments/assets/91f62af1-f445-4457-a1ff-24aa5ae15556)

JabRef:
![image](https://github.com/user-attachments/assets/28b67a88-eb19-4a3c-a3e5-25c6a0cecb01)

### Additional context

- GPT4All documentation for [local API server](https://github.com/nomic-ai/gpt4all/wiki/Local-API-Server)
- The phi-3.1-mini-128k-instruct model can be downloaded here: https://huggingface.co/GPT4All-Community/Phi-3.1-mini-128k-instruct-GGUF/tree/main. Just move the model file into the [model directory](https://github.com/nomic-ai/gpt4all/wiki/Frequently-Asked-Questions#where-are-the-default-directories-for-models-and-settings) of GPT4All and then configure it in the model settings as shown in my screenshots down below.
- Documentation about how to configure other custom models: https://github.com/nomic-ai/gpt4all/wiki/Configuring-Custom-Models.

JabRef preferences:
![image](https://github.com/user-attachments/assets/f1ded2a8-c34a-4d69-871c-73d635afae93)

GPT4All preferences:
![image](https://github.com/user-attachments/assets/a0f6cf24-53d7-43a0-b685-72c600d7ccac)

GPT4All model settings 1:
![image](https://github.com/user-attachments/assets/d6f4b388-2585-41a5-9494-967e0dc53ba8)

GPT4All model settings 2:
![image](https://github.com/user-attachments/assets/1be2da21-88e4-4c78-b5cc-2b18654ae638)

**Comment by ThiloteE** [comment]
I also often get those errors/warnings in the commandline, when I try to send messages when connected to GPT4All server API. Not sure, if related.

```
2024-10-01 13:13:53 [pool-2-thread-4] org.jabref.logic.ai.chatting.AiChatLogic.execute()
INFO: Sending message to AI provider (https://api.openai.com/v1) for answering in entry CooperEtAl200708cah: What are the authors of the paper?
2024-10-01 13:13:53 [JavaFX Application Thread] org.jabref.gui.ai.components.aichat.AiChatComponent.lambda$onSendMessage$11()
ERROR: Got an error while sending a message to AI: io.github.stefanbratanov.jvm.openai.OpenAIException: 400 - message: Invalid 'messages[2].role': did not expect 'user' here, type: invalid_request_error, param: null, code: null
        at jvm.openai@0.11.0/io.github.stefanbratanov.jvm.openai.OpenAIClient.lambda$validateHttpResponse$6(OpenAIClient.java:129)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
        at jvm.openai@0.11.0/io.github.stefanbratanov.jvm.openai.OpenAIClient.validateHttpResponse(OpenAIClient.java:127)
        at jvm.openai@0.11.0/io.github.stefanbratanov.jvm.openai.OpenAIClient.sendHttpRequest(OpenAIClient.java:85)
        at jvm.openai@0.11.0/io.github.stefanbratanov.jvm.openai.OpenAIClient.sendHttpRequest(OpenAIClient.java:78)
        at jvm.openai@0.11.0/io.github.stefanbratanov.jvm.openai.ChatClient.createChatCompletion(ChatClient.java:37)
        at org.jabref@100.0.0/org.jabref.logic.ai.chatting.model.JvmOpenAiChatLanguageModel.generate(JvmOpenAiChatLanguageModel.java:65)
        at org.jabref@100.0.0/org.jabref.logic.ai.chatting.model.JabRefChatLanguageModel.generate(JabRefChatLanguageModel.java:142)
        at langchain4j@0.34.0/dev.langchain4j.chain.ConversationalRetrievalChain.execute(ConversationalRetrievalChain.java:85)
        at langchain4j@0.34.0/dev.langchain4j.chain.ConversationalRetrievalChain.execute(ConversationalRetrievalChain.java:32)
        at org.jabref@100.0.0/org.jabref.logic.ai.chatting.AiChatLogic.execute(AiChatLogic.java:168)
        at org.jabref@100.0.0/org.jabref.gui.ai.components.aichat.AiChatComponent.lambda$onSendMessage$9(AiChatComponent.java:204)
        at org.jabref@100.0.0/org.jabref.logic.util.BackgroundTask$1.call(BackgroundTask.java:73)
        at org.jabref@100.0.0/org.jabref.gui.util.UiTaskExecutor$1.call(UiTaskExecutor.java:191)
        at javafx.graphics@23/javafx.concurrent.Task$TaskCallable.call(Task.java:1401)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ThiloteE** [comment]
I think there is also an issue when switching models.
![image](https://github.com/user-attachments/assets/099fe0fd-5eb7-4f87-9c7e-df06ae1c131d)
Even after clearing the chat history, it is not possible to get around this erorr message, unless switching to a different entry in JabRef. Then I can chat again.

**Comment by ThiloteE** [comment]
@InAnYan

**Comment by InAnYan** [comment]
Such an interesting issue and such an interesting behaviour...

IMHO it's very wrong that there is no OpenAI API compatible mode in gpt4all. (Standardization made people's life much easier).

However, I will look into this issue in more detail, because Gpt4All is a popular app and this is also important

**Comment by FeiLi-lab** [comment]
![Image](https://github.com/user-attachments/assets/57052343-1001-4cbf-b1bd-8c19edf9fd83)

This is so weird. I tried it last night and encountered the problem mentioned above, that is, the returned content would be truncated. But I tried it again this afternoon and found that it could be returned normally without truncating the content.

**Comment by FeiLi-lab** [comment]
Ok... I reproduced it. I will try to fix it.

**Comment by ThiloteE** [comment]
I will try to have a look at this on the weekend.

**Comment by ThiloteE** [comment]
Maybe could have been https://github.com/ggerganov/llama.cpp/pull/9867 too. The fix needs some time to reach GPT4All.

**Comment by NoahXu718** [comment]
I am also working on this issue. I think the problem that responses look like cutoff in the middle may come from the request.

I ran the following two commands on my computer, one with max_token set and one without, and the result shows that the answer without max_token set was cutoff.

> curl -X POST http://localhost:4891/v1/chat/completions -H "Content-Type: application/json" -d "{\"model\": \"Phi-3.1-mini-128k-instruct-Q4_0-precise-output-tensor\", \"messages\": [{\"role\": \"user\", \"content\": \"could you please introduce more about your self?\"}], \"max_tokens\": 2048, \"temperature\": 0.7}"

![Image](https://github.com/user-attachments/assets/71a8ccaf-00a4-425b-964d-a623db6ffb07)

> curl -X POST http://localhost:4891/v1/chat/completions -H "Content-Type: application/json" -d "{\"model\": \"Phi-3.1-mini-128k-instruct-Q4_0-precise-output-tensor\", \"messages\": [{\"role\": \"user\", \"content\": \"could you please introduce more about your self?\"}], \"temperature\": 0.7}"

![Image](https://github.com/user-attachments/assets/31c9875e-a4ed-4585-a32d-4040c338267e)

I set the max_token in the code, now the response looks complete.
preference:
![Image](https://github.com/user-attachments/assets/6fb587dc-61da-4590-a94b-22cb4fda4dcc)

JabRef:
![Image](https://github.com/user-attachments/assets/972a64bf-b52f-4e83-aa60-e8393ce81f11)
 
@ThiloteE I will refine the code later if you can review it.

**Comment by ThiloteE** [comment]
Oh, nice! Good to know. Yes, a pull-request would be nice, otherwise nobody can review.
Do you think this is something we would need to add to the preferences?
