### ISSUE TITLE
Bibtex can not save file when Tex Studio is open on Windows 11

### ISSUE THREAD

**Issue by austindowney** [JabRef/jabref#11916]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.15--2024-07-10--1eb3493; Windows 11 10.0 amd64;  Java 21.0.2;  JavaFX 22.0.1+7

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

If Texstudio is open, Jabref can not save the file. 
 
Sometimes if I compile the document and try to save the .bib file during the compile it will save. 

The issue is the same as reported here https://tex.stackexchange.com/questions/727245/jabref-cannot-save-file-while-texstudio-is-running
 
The issue has to do with Windows holding access to the file. See the errors below. 

org.jabref.logic.exporter.SaveException: Problems saving: java.nio.file.FileSystemException: C:\Users\adowney2\Downloads\Curriculum_vitae\publications.bib.tmp -> C:\Users\user2\Downloads\Curriculum_vitae\publications.bib: The process cannot access the file because it is being used by another process
	at org.jabref@5.15.60000/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
My first thought would be to check, if Tex Studio is triggering Windows to lock the file (which would be an external issue and better be reported to Tex Studio), but according to the tex.stackexchange post, it is apparently possible to edit the file with Visual Studio Code, so it could be an JabRef issue. Best to test what Visual Studio Code does exactly. "Editing" does not mean "saving". According to your report, JabRef also can "edit" those files, but cannot "save".

**Comment by austindowney** [comment]
> My first thought would be to check, if Tex Studio is triggering Windows to lock the file (which would be an external issue and better be reported to Tex Studio), but according to the tex.stackexchange post, it is apparently possible to edit the file with Visual Studio Code, so it could be an JabRef issue. Best to test what Visual Studio Code does exactly. "Editing" does not mean "saving". According to your report, JabRef also can "edit" those files, but cannot "save".

If I run the .tex file in Texstudio, I can not save changes to the .bib made in jabref until I close out of the .tex studio. I can open the .bib file in notepad ++ make edits, and save it, all while jabref cannot save it. 

All of that is to say that Texstudio could be locking the file, but Notepad ++ can save it. So I don't know if this is an issue to report to Texstudio or Jabref.

**Comment by dayusun** [comment]
I have the same issue.
The version information:
JabRef 5.15--2024-07-10--1eb3493
Windows 11 10.0 amd64 
Java 21.0.2 
JavaFX 22.0.1+7

**Comment by joelreis** [comment]
Same problem over here, with:
JabRef 5.15--2024-07-10--1eb3493
Windows 10 10.0 amd64 
Java 21.0.2 
JavaFX 22.0.1+7

**Comment by vdaghan** [comment]
I did encounter this bug with TexStudio v4.8.6 and JabRef v5.15 on Windows. The root cause and workaround are hinted at in [this StackExchange post](https://tex.stackexchange.com/a/727330/390421), but not clearly enough for my overworked brain — took me a second read to get it.

Posting here to confirm the issue and repeat the workaround. When the ```.bib``` file is located in a different folder than your main ```.tex``` file which TexStudio operates on, there seems to be no issue. Just place your bibliography in a different folder:

Problematic layout:
```<work_folder>/main.tex```
```<work_folder>/refs.bib```

Workaround:
```<work_folder>/main.tex```
```<work_folder>/refs/refs.bib```

**Comment by ybchen11** [comment]
I also encountered the same issue with JabRef v5.15, V4.8.6, win 11.

I have tried an easy way to address this problem: you can create a new folder in your current latex folder, name it for example "Ref", and put your .bib file into this "Ref" folder. This operation is to ensure that your .tex file and .bib file do not appear in the same folder at the same time. 

For example, when you calling this .bib file (here I name it 'my_ref.bib') in the .tex file when editing via the TesStudio, you can use 
' \bibliography{Ref/my_ref} '  rather than  ' \bibliography{my_ref} '.

I have tried and this way worked. Hope this could help.

**Comment by Siedlerchr** [comment]
Key issues: JabRef writes to a new temp file, then atomically replaces the original file. And under Windows, locks are behaving differently from under Unix/POSIX.  And the TexStudio FileWatcher keeps the file locked so JabRef cannot replace it 
https://github.com/texstudio-org/texstudio/issues/4258#issuecomment-4722205379

I think we can add an FAQ Entry for this using the workaround @ybchen11  posted

**Comment by subhramit** [comment]
Pasting an RCA summary done using Claude Opus 5 on both repositories.

# Root cause: JabRef cannot save `.bib` while TeXstudio is open (Windows)
 
**Refs:** [JabRef#11916](https://github.com/JabRef/jabref/issues/11916) · [texstudio#4258](https://github.com/texstudio-org/texstudio/issues/4258)
 
**Symptom**
 
```
org.jabref.logic.exporter.SaveException: Problems saving:
java.nio.file.FileSystemException: D:\Ref.bib.tmp -> D:\Ref.bib:
The process cannot access the file because it is being used by another process.
```
 
**One-line summary.** JabRef saves by rename-replace, which requires `DELETE` access to the target; Qt (and therefore TeXstudio) opens every file without `FILE_SHARE_DELETE`. Neither program is wrong on its own — the failure only exists in the pairing. It is a millisecond-scale race, not a persistent lock.
 
---
 
## 1. The JabRef half: the save is a rename, not a write
 
`AtomicFileOutputStream.close()` writes `refs.bib.tmp`, copies the original to `refs.bib.sav`, then commits with:
 
```java
// logic/exporter/AtomicFileOutputStream.java
Files.move(temporaryFile, targetFile,
           StandardCopyOption.ATOMIC_MOVE,
           StandardCopyOption.REPLACE_EXISTING);
```
 
On Windows the JDK maps `ATOMIC_MOVE + REPLACE_EXISTING` to exactly one call:
 
```java
// jdk/src/java.base/windows/classes/sun/nio/fs/WindowsFileCopy.java:318-328
if (atomicMove) {
    try {
        MoveFileEx(sourcePath, targetPath, MOVEFILE_REPLACE_EXISTING);
    } catch (WindowsException x) { ... x.rethrowAsIOException(source, target); }
}
```
 
`MOVEFILE_REPLACE_EXISTING` deletes the target as part of the rename, so the kernel must open `refs.bib` with `DELETE` access. If any other process holds a handle opened without `FILE_SHARE_DELETE`, this returns `ERROR_SHARING_VIOLATION` (32) — whose message string is verbatim the one users report. The `source -> target` formatting in the exception comes from `rethrowAsIOException(source, target)`, confirming this is the failing call.
 
## 2. The TeXstudio half: Qt never grants delete-sharing
 
```cpp
// qtbase/src/corelib/io/qfsfileengine_win.cpp:74
DWORD shareMode = FILE_SHARE_READ | FILE_SHARE_WRITE;
```
 
Unconditional, and not configurable through any Qt API. For the lifetime of **any** `QFile` TeXstudio opens on the `.bib`, that file cannot be renamed over or deleted by another process.
 
TeXstudio opens the `.bib` in at least three places, all short-lived:
 
| Site | Trigger |
|---|---|
| `BibTeXFileInfo::load()` — `src/bibtexparser.cpp` | `LatexDocuments::updateBibFiles()`, guarded by `loadIfModified()` (mtime check) |
| `bibtexReader::searchSection()` — `src/bibtexreader.cpp` | citation tooltips / preview |
| `QEditor::fileChanged` → reload — `src/qcodeedit/lib/qeditor.cpp:1246` | watcher fires and the `.bib` is open in a tab |
 
## 3. Why it presents as an intermittent "lock"
 
There is no long-lived handle. This accounts for every confusing observation in the threads:
 
| Observation | Explanation |
|---|---|
| Resource Monitor shows **no file handle**, only two directory handles | The file handle exists for milliseconds; only the watcher's directory handles persist |
| Reproduces on *alternating* Ctrl+S | Self-feeding loop: a successful save changes mtime → that is exactly the trigger for `loadIfModified()` and for the watcher-driven reload → TeXstudio opens the file → the *next* save collides |
| Not reproducible on some machines | Race window; depends on machine speed, AV, file size |
| Disabling "Monitor files for external changes" does not help | It only sets `mIgnoreExternalChanges`, checked *inside* `QEditor::fileChanged` (`qeditor.cpp:1248`). It never calls `removeWatch`, and it does not touch the `updateBibFiles()` reparse path at all |
| Notepad++ can save the same file at the same time | In-place write — see §4 |
 
**On the two directory handles.** Qt's Windows watcher calls `FindFirstChangeNotification` on the *parent directory* when you watch a file:
 
```cpp
// qfilesystemwatcher_win.cpp:351
const QString absolutePath = isDir ? fileInfo.absoluteFilePath() : fileInfo.absolutePath();
```
 
These handles are real and also lack delete-sharing, but they only protect the *directory* from being renamed or deleted — they do not block a `MoveFileEx` of a file inside it. So the watcher is the **trigger** (it drives the reload that opens the file), not the holder.
 
**On the subfolder workaround.** Moving `refs.bib` into `refs/` does not stop TeXstudio parsing it. It takes the file out of the directory whose change-notification stream TeXstudio reacts to most (the one churning with `.aux`/`.log`/`.pdf` during builds), which narrows the race window rather than closing it. This is the least well-established part of the analysis and should be treated as a mitigation, not a fix.
 
## 4. Why VS Code and Notepad++ are unaffected — for two independent reasons
 
**As the writer.** VS Code takes the temp-and-rename path only when `opts.atomic.postfix` is set, which ordinary text saves do not set:
 
```ts
// vscode/src/vs/platform/files/node/diskFileSystemProvider.ts:245
if (opts?.atomic !== false && opts?.atomic?.postfix && await this.canWriteFileAtomic(resource)) {
    return this.doWriteFileAtomic(...);   // temp + rename
} else {
    return this.doWriteFile(...);         // open + write in place
}
```
 
An in-place truncating write needs only `GENERIC_WRITE` on the target, which Qt's `FILE_SHARE_WRITE` explicitly permits. Notepad++ behaves the same way. Neither ever requests `DELETE`, so neither can hit the sharing violation.
 
**As the holder.** libuv opens every file with all three share flags, so VS Code can never block anyone else's atomic replace either:
 
```c
/* libuv/src/win/fs.c:512 */
share = FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE;
```
 
**The collision requires both halves** — a writer that renames *and* a concurrent reader that withholds delete-sharing. Of the four programs involved, JabRef + TeXstudio is the only pairing that has both.
 
## 5. Proposed remedies
 
Qt exposes no way for TeXstudio to pass a share mode short of dropping to raw `CreateFileW`, so the practical fix is on the JabRef side.
 
**Primary — bounded retry around the commit.** Retry the `Files.move` a handful of times over roughly 300–500 ms with backoff on `FileSystemException` / `AccessDeniedException`. TeXstudio's handles live for milliseconds, so this clears effectively all of these. It also fixes the same class of failure caused by Windows Defender and the search indexer, which today gets misattributed to TeXstudio.
 
**Fallback — in-place rewrite if retries exhaust.** Reopen the target with `WRITE` + `TRUNCATE_EXISTING` and write the buffer directly instead of renaming. `.sav` already exists at that point, so the crash-durability loss is bounded, and an in-place write succeeds against a Qt handle for the reason in §4.
 
**Incidental finding.** `AtomicFileOutputStream` deliberately uses `new FileOutputStream(tmp)` rather than `Files.newOutputStream` so it can call `getChannel().tryLock()`. Legacy `java.io` on Windows opens with `FILE_SHARE_READ | FILE_SHARE_WRITE` only:
 
```c
/* jdk/src/java.base/windows/native/libjava/io_util_md.c:221 */
const DWORD sharing = FILE_SHARE_READ | FILE_SHARE_WRITE;
```
 
whereas NIO defaults `shareDelete = true` (`WindowsChannelFactory.java:82`). That handle is closed before the move, so it is not the cause here — but it does mean JabRef is the same kind of bad neighbour as Qt during its own write window, and any other `java.io`-based read of a `.bib` in the codebase will block other tools' atomic saves.
 
**TeXstudio side, optional.** Reading `.bib` files through a native `CreateFileW` that includes `FILE_SHARE_DELETE` would remove the hazard at the source and benefit every rename-replace tool, not just JabRef.
 
## 6. User-facing workaround (for a FAQ entry)
 
Keep the `.bib` outside the directory containing the `.tex` files:
 
```
work/main.tex
work/refs/refs.bib      →  \bibliography{refs/refs}
```
 Verified in https://github.com/JabRef/jabref/issues/11916#issuecomment-2832922211
This narrows the race window substantially, but it is timing-dependent and not a guarantee.

**Comment by subhramit** [comment]
@koppor I am taking this up.
