### ISSUE TITLE
Editor Formatter

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#1193]
I'm on JabRef 3.2 on windowsXP. 

\begin{editor} \format[HTMLChars,AuthorFirstFirst]{\editor} (Ed.) \end{editor}
(as written as exemple at page http://help.jabref.org/en/CustomExports/)

I get this error : avr. 13, 2016 11:38:12 AM net.sf.jabref.exporter.ExportFormat performExport
AVERTISSEMENT: []
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.sf.jabref.gui.search.MatchesHighlighter.highlightWordsWithHTML(MatchesHighlighter.java:26)
	at net.sf.jabref.exporter.layout.LayoutEntry.doLayout(LayoutEntry.java:252)
	at net.sf.jabref.exporter.layout.Layout.doLayout(Layout.java:128)
	at net.sf.jabref.exporter.layout.Layout.doLayout(Layout.java:115)
	at net.sf.jabref.exporter.ExportFormat.performExport(ExportFormat.java:269)
	at net.sf.jabref.exporter.ExportFormats$1ExportAction$1.run(ExportFormats.java:230)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

I try the same InBook entry in two differents database : one is exporting fine and not in the other one. What could be the difference?

**Comment by tobiasdiez** [comment]
Could you please try out the latest development build available at http://builds.jabref.org/master/. It should work in this version.

**Comment by melTr** [comment]
Ah, effectively, it's working!
