### ISSUE TITLE
Can't use "Cleanup Entries" on more than one entry

### ISSUE THREAD

**Issue by Luram123** [JabRef/jabref#11966]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 11 23H2

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Hello there :)

1. Select entries in your library (5 are enough).
2. Run the "Cleanup Entries" feature.
3. In my case I wanted to get rid of the field Urldate, which means that I take away every tick on the checkboxes and only enable field formatters.
4. I add: "Field name: Urldate" and "Formatter name: Clear"
5. I hit enter.

A window ("Exception details") should show up and say: "Unhandles exception occured."
When looking at the details a bunch of java related stuff comes up, but I can't read computer language very well. But every line of this text ends with the words "Unknown Source" within brackets.

When looking at the entries selected only one was cleaned up.
After installing the latest development version I was able to clean up two entries but the process still breaks in the same way.

What can I do to fix this? Or is it an issue that has to be fixed by the developers and I have to wait?

Thanks in advance
Luram

PS.:
My Jabref Version
JabRef 6.0--2024-10-14--e0cd309
Windows 11 10.0 amd64 
Java 21.0.2 
JavaFX 23+29

**Comment by MadDingzhen** [comment]
Hi, I'm working in a course team and required to work on a good first issue. Can I work on this?

**Comment by Siedlerchr** [comment]
Can you please paste the whole stack trace of the exception?
That helps us to identify the real problems

**Comment by Siedlerchr** [comment]
```
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = pool-2-thread-5
	at javafx.graphics@23/com.sun.glass.ui.Application.checkEventThread(Application.java:445)
	at javafx.graphics@23/com.sun.glass.ui.MenuItem.setEnabled(MenuItem.java:108)
	at javafx.graphics@23/com.sun.javafx.tk.quantum.GlassSystemMenu.lambda$insertMenuItem$8(GlassSystemMenu.java:260)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:376)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:239)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:239)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:239)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.binding.BooleanBinding.invalidate(BooleanBinding.java:180)
	at javafx.base@23/com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
	at javafx.base@23/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:239)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.binding.BooleanBinding.invalidate(BooleanBinding.java:180)
	at javafx.base@23/javafx.beans.binding.Bindings$ShortCircuitAndInvalidator.invalidated(Bindings.java:4669)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:376)
	at javafx.base@23/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base@23/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.base@23/javafx.beans.property.BooleanProperty.setValue(BooleanProperty.java:79)
	at org.jabref@100.0.0/org.jabref.gui.undo.CountingUndoManager.updateUndoableStatus(CountingUndoManager.java:70)
	at org.jabref@100.0.0/org.jabref.gui.undo.CountingUndoManager.addEdit(CountingUndoManager.java:29)
	at org.jabref@100.0.0/org.jabref.gui.cleanup.CleanupAction.cleanup(CleanupAction.java:147)
	at org.jabref@100.0.0/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(CleanupAction.java:93)
	at org.jabref@100.0.0/org.jabref.logic.util.BackgroundTask$2.call(BackgroundTask.java:82)
	at org.jabref@100.0.0/org.jabref.logic.util.BackgroundTask$2.call(BackgroundTask.java:79)
	at org.jabref@100.0.0/org.jabref.gui.util.UiTaskExecutor$1.call(UiTaskExecutor.java:191)
	at javafx.graphics@23/javafx.concurrent.Task$TaskCallable.call(Task.java:1401)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by Luram123** [comment]
This is the exception stacktrace that i got:

`java.util.ConcurrentModificationException
	at java.base/java.util.AbstractList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at org.jabref@6.0.6393/org.jabref.gui.cleanup.CleanupAction.cleanup(Unknown Source)
	at org.jabref@6.0.6393/org.jabref.gui.cleanup.CleanupAction.lambda$execute$1(Unknown Source)
	at org.jabref@6.0.6393/org.jabref.logic.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@6.0.6393/org.jabref.logic.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@6.0.6393/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@23/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Siedlerchr** [comment]
Okay that's a different error. This is then a simliar/the same issue as https://github.com/JabRef/jabref/issues/11416

**Comment by Siedlerchr** [comment]
This should now  be fixed by  https://github.com/JabRef/jabref/pull/12809

**Comment by Siedlerchr** [comment]
@Luram123  This issue is now fixed in the latest development version
