### ISSUE TITLE
PostgreSQL unique constraint violation when editing an entry

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#12167]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint Debian 12

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open bib file and the entry editor
2. Change some field (it happened to me when editing the "Publisher" field, but could be other fields as well)
3. At some point you should observe an exception (see below) in the command line
4. Doesn't seem to have relevant effects ...

### Appendix

...
<details>

<summary>Log File</summary>

```
2024-11-09 10:22:37 [pool-2-thread-1] org.jabref.logic.search.indexing.BibFieldsIndexer.insertField()
ERROR: Could not add an entry to the index.: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO bib_fields."yks1w6neg84c" ("entryid", "field_name", "field_value_literal", "field_value_transformed")
VALUES (('00229933'), ('publisher'), ('Springer'), ('Springer'))
 was aborted: ERROR: duplicate key value violates unique constraint "yks1w6neg84c_pkey"
  Detail: Key (entryid, field_name)=(00229933, publisher) already exists.  Call getNextException to see other errors in the batch.
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.BatchResultHandler.handleCompletion(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.core.v3.QueryExecutorImpl.execute(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgStatement.internalExecuteBatch(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgStatement.executeBatch(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgPreparedStatement.executeBatch(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.indexing.BibFieldsIndexer.insertField(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.indexing.BibFieldsIndexer.updateEntry(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.IndexManager$8.call(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@23.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "yks1w6neg84c_pkey"
  Detail: Key (entryid, field_name)=(00229933, publisher) already exists.
	at org.jabref.merged.module@6.0.6556/org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.core.v3.QueryExecutorImpl.processResults(Unknown Source)
	... 15 more
```

</details>

**Comment by ytzemih** [comment]
Btw, the same seems to be true for the "Comments" field. 

Also, quite consistently, the postgres server in the background takes 100% CPU for a while, but it stops at some point.

**Comment by ytzemih** [comment]
Closing the corresponding file stops the postgres daemon from hazarding but throws (obviously) an exception

```
2024-11-09 10:38:14 [pool-2-thread-2] org.jabref.logic.search.indexing.BibFieldsIndexer.removeField()
ERROR: Error deleting field from entry in index: org.postgresql.util.PSQLException: This connection has been closed.
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgConnection.checkClosed(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgConnection.createStatement(Unknown Source)
	at org.jabref.merged.module@6.0.6556/org.postgresql.jdbc.PgConnection.createStatement(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.indexing.BibFieldsIndexer.removeField(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.indexing.BibFieldsIndexer.updateEntry(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.IndexManager$8.call(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@23.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ytzemih** [comment]
@Siedlerchr Thanks for confirming. Also, in the meanwhile, I am wondering whether this issue is a side effect of https://github.com/JabRef/jabref/issues/12190?

**Comment by Siedlerchr** [comment]
From this discussion it seems that this happens when the sequence is out of sync https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint

**Comment by ytzemih** [comment]
Ok, this issue seems to be fixed for me with the @LoayGhreeb 's PR.
