### ISSUE TITLE
IllegalArgumentException: URI is not absolute

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#12186]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-05--4705977 Linux 6.1.0-26-amd64 amd64  Java 21.0.5  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I've just been using global search. 

Unfortunately, I can't quite reproduce this issue, although I've had this exception a few times already. It appears to be related to when I use search, the entry list when a group is selected. Also, it seems to happen after JR has been running for a while.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.of(Unknown Source)
	at java.base/java.net.URI.toURL(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.convert(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$1.computeValue(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.optional.PreboundOptionalBinding$3.computeValue(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.checkState(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.Control.computePrefHeight(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.prefHeight(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.layout.Region.prefHeight(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.resizeCell(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at javafx.graphics@23.0.1/javafx.stage.Stage.showAndWait(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.JabRefDialogService.showConfirmationDialogAndWait(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$8(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.ToggleButton.setSelected(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$14(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.SetListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.SetListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.ObservableSetWrapper.callObservers(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.collections.ObservableSetWrapper.remove(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.logic.search.SearchPreferences.setSearchFlag(Unknown Source)
	at org.jabref@6.0.6556/org.jabref.gui.search.GlobalSearchBar.lambda$initSearchModifierButtons$9(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@23.0.1/javafx.scene.control.ToggleButton.fire(Unknown Source)
	at javafx.controls@23.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@23.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@23.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@23.0.1/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@23.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by Siedlerchr** [comment]
It seems to be related to a value in the file field somewhere that cannot be parsed to an URL

**Comment by ytzemih** [comment]
That makes sense, though, I haven't seen these exceptions before. Perhaps, the URI parser is now less relaxed? Ok, I'll try to check the file fields and see whether I can find something odd.

**Comment by koppor** [comment]
After https://github.com/JabRef/jabref/pull/12156/ is merged, we can work on this.

**Comment by yash-agrawal03** [comment]
@koppor by when is the pr #12156 expected to close? I have to wait for that PR to get closed right?

**Comment by koppor** [comment]
@yash-agrawal03 I worked on it, it is merged now.

**Comment by yash-agrawal03** [comment]
Thank-You koppor, I will start working on this issue.

**Comment by yash-agrawal03** [comment]
/assign-me

Please give me another chance to complete this request

**Comment by yshukla01** [comment]
Hi, I am Yash , a student at King's College London working with @LinusDietz. Could I work on this task?

**Comment by sfahaddev** [comment]
Hello, @koppor  I am Fahad can you assign me this task, please?

**Comment by subhramit** [comment]
Should we keep this issue open? Or a refined one is needed (ref. https://github.com/JabRef/jabref/pull/13337#pullrequestreview-2938191896)? @koppor

**Comment by calixtus** [comment]
Reopened, the referring pr was just making the error message more clear but maybe did not fix the issue itself. Further testing and investigation required

**Comment by koppor** [comment]
We need to link the issue having `www.example.org` as URL. I think they are the same cause

**Comment by Siedlerchr** [comment]
@jetbbrains-junie Solve this issuse by

**Comment by Siedlerchr** [comment]
@jetbrains-junie Solve this issue and use the reproducer for tests

**Comment by ghost** [comment]
Hey, it’s Junie by JetBrains! I started [processing](https://github.com/JabRef/jabref/actions/runs/16631469984) your request 🚀

**Comment by Siedlerchr** [comment]
@jetbrains-junie Try again

**Comment by Siedlerchr** [comment]
@jetbrains-junie try again

**Comment by ghost** [comment]
### ✅ Generation Status

* Code generation was **successful**

Message:

> A fix was implemented for the `IllegalArgumentException: URI is not absolute` error in JabRef by modifying the `URLUtil.create` method to add "http://" to URLs starting with "www." All tests passed successfully after these changes, and the fix was documented in the CHANGELOG.md.



---


### 📌 Issues Detected During Processing

- Some issues occurred that may have limited the context available during generation.
- These **did not prevent** the operation, but fixing them could improve the results.

Message:

> ❌ **I tried to build the project before getting started, but it didn’t work.**
> 
> There might be issues with the environment or the code itself. Please check [build log](https://github.com/JabRef/jabref/actions/runs/16806636676/junie/3711314334) for more details.
> 
> 
> 
> 




More information:
* 🔗 [GitHub Action](https://github.com/JabRef/jabref/actions/runs/16806636676)
* 💬 [Report the issue on our Discord and help us improve](https://jb.gg/junie/github)
