### ISSUE TITLE
Postgres daemon uses 100% of CPU for several minutes despite indexing deactivated

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#12190]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-13--5f1dd59 Linux 6.1.0-26-amd64 amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I can't exactly replicate this issue, it occurs a few times a day. The following steps might increase the likelihood to stimulate the issue:
1. I've generally deactivated "fulltext search" or background features in the preference pane.
2. Use (global) search and leave search term in the search field (might be an optional step).
3. Add a new entry to a large DB OR edit the comments field and other field of an existing entry.
4. Save file.

I'm using `top` to see that there is a postgre instance spun off and to check its CPU load. This issue has not occurred under JR5.x.

### Appendix

<details>

<summary>Log File</summary>

```
78754 xxx     25   5  235792  56520  50536 R  99.7   0.4   7:35.39 postgres
```

</details>

**Comment by ytzemih** [comment]
When killing the postgre instance (needed, otherwise my laptop will die), I'm getting about 10-15 of such exceptions thrown:
```
2024-11-14 13:47:06 [pool-2-thread-2] org.jabref.logic.search.retrieval.BibFieldsSearcher.search()
ERROR: Error during bib fields search execution: org.postgresql.util.PSQLException: This connection has been closed.
	at org.jabref.merged.module@6.0.6575/org.postgresql.jdbc.PgConnection.checkClosed(Unknown Source)
	at org.jabref.merged.module@6.0.6575/org.postgresql.jdbc.PgConnection.prepareStatement(Unknown Source)
	at org.jabref.merged.module@6.0.6575/org.postgresql.jdbc.PgConnection.prepareStatement(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.logic.search.retrieval.BibFieldsSearcher.search(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.logic.search.retrieval.BibFieldsSearcher.isMatched(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.logic.search.IndexManager.isEntryMatched(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.gui.groups.GroupNodeViewModel$SearchIndexListener.lambda$listen$1(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.logic.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.logic.util.BackgroundTask$2.call(Unknown Source)
	at org.jabref@6.0.6575/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@23.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
I don't know why such a comprehensive search is triggered when just editing some entry fields... I've not been using search, but I realise that my global search is non-empty. Apparently, it seems to be the search update is again triggered to often. I realise that there is a related issue with JR5, right?

**Comment by ytzemih** [comment]
Perhaps it helps to distinguish two search triggers, 

1. one when a user requests a search (that should be immediate) 
2. one when some update is made in the DB (that should be delayed to a bunch of updates)

**Comment by koppor** [comment]
> Before my CPU kept spinning, which suggests to me a classical DB deadlock situation (spinlocks) created by several (5?) java postgre calls not being synchronized (that is, not being properly monitored). It seems reasonable to start having a look there.

Can you help us with that? Our contributor developing that feature disappeared.

**Comment by ytzemih** [comment]
@koppor Sorry to hear that and thanks for asking. 

First of all, can you or anybody else confirm that there is a bug?

I'm not familiar with the JR code base, nor it's architecture, which means, it'd take me a while to isolate the problem and make informed decisions. From February onward, however, I'd have time to take have a look into this issue if this helps you?

**Comment by koppor** [comment]
> First of all, can you or anybody else confirm that there is a bug?

TBH, if it appears at one user, it is most likely that it will appear at other users, too.

We will do an alpha-release these days - and hope for feedback at https://discourse.jabref.org/c/beta-testing/11.

> I'm not familiar with the JR code base, nor it's architecture, which means, it'd take me a while to isolate the problem and make informed decisions. From February onward, however, I'd have time to take have a look into this issue if this helps you?

Sure! We are all volunteers and busy with other things. (I personally need to get my funding ordered for 2025 and beyond). Thus, any help is very much welcome. Looking forward!

**Comment by ytzemih** [comment]
Alright, good to know. I'll see whether I can spot the issue in the then alpha-release and, if possible, can propose a fix in February.

In the meanwhile, all the best for your funding acquisition!

**Comment by LoayGhreeb** [comment]
Hello @ytzemih,

First of all, disabling the "fulltext search" will not affect this issue. Fulltext search does not use PostgreSQL; we use Lucene for the fulltext search of linked files. PostgreSQL is used for searching bib fields and search groups.

Killing the PostgreSQL server process will certainly cause a lot of exceptions, as jabref expects the server to be running.

I cannot reproduce the issue on my machine. The initial indexing of a large library with 6.5K entries took about 8% of CPU usage, while updating or inserting entries did not exceed 0.3% CPU usage.

Do you have any search groups in your library? This might be the cause of the issue. After every update to the index, for each character you type in the field, a search query is performed for every search group you have.

**Comment by ytzemih** [comment]
@LoayGhreeb Thanks for clarifying the use of PostgreSQL. 

I'm indeed using search groups, a handful of them the files affected.

In the meanwhile, I've observed that the issue occurs when I work on bib entries, in particular, editing comments and other fields, which involves a lot of typing. And, certainly, I'd expect any hooks for search routines NOT to be spawned upon every other key stroke. Rather, I'd expect (in a way like pawn detection algorithms with touch pads) to only react after a typing activity, say one second after the last key stroke. Because otherwise, it is unsure whether the synchronisation is fast enough for preventing too many PostgreSQL instances to be spawned, right? I don't know the implementation but long story short: 

I can confirm your conjecture about the cause.

**Comment by ytzemih** [comment]
The question then is, whether an update of all search groups is necessary if no or at most one group is selected? Is an update of the search perhaps done too often?

Whatever it is, there seems to be some interaction between search, global search, and search groups that can cause performance issues and might need some rethinking.

**Comment by ytzemih** [comment]
This issue is still occurring for me after the fix of #12373. It, however, seems to be performance issue. I didn't have this before with JR 5.x, but used similarly large bib files as well as search groups. JR is spinning up my CPU after each couple of changes, which is not so nice when working with my laptop without power connection.

If PostgreSQL has already been used in JR 5 for searching bib fields and search groups, then there is some change in JR 6 that seems to cause this issue. If PostgreSQL has been newly introduced in JR6, that implementation might need a look at.

**Comment by ytzemih** [comment]
After a few weeks of using JR6, I think, this issue could be a severe showstopper for anyone using a combination of medium to large bib-files and search groups. I just wanted to add some information for the protocol:

Closing the just changed file (because the postgresql daemon is killing my laptop) , I get (unsurprisingly) the following three kinds of exceptions (1000s of them actually but with the same ID):
1. 2025-01-25 14:09:11 [pool-2-thread-4] org.jabref.logic.search.retrieval.BibFieldsSearcher.search()

> ERROR: Error during bib fields search execution: org.postgresql.util.PSQLException: ERROR: relation "bib_fields.i1otlkgvdvhl" does not exist
>   Position: 44
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.core.v3.QueryExecutorImpl.processResults(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.core.v3.QueryExecutorImpl.execute(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgStatement.executeInternal(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgStatement.execute(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgPreparedStatement.executeQuery(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.retrieval.BibFieldsSearcher.search(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.IndexManager.lambda$search$5(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)

2. 2025-01-25 14:09:11 [pool-2-thread-3] org.jabref.logic.search.indexing.BibFieldsIndexer.removeField()

> ERROR: Error deleting field from entry in index: org.postgresql.util.PSQLException: This connection has been closed.
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.checkClosed(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.createStatement(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.createStatement(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.indexing.BibFieldsIndexer.removeField(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.indexing.BibFieldsIndexer.updateEntry(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.IndexManager$8.call(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
> 	at javafx.graphics@23.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)

3. 2025-01-25 14:09:11 [pool-2-thread-3] org.jabref.logic.search.indexing.BibFieldsIndexer.insertField()

> ERROR: Could not add an entry to the index.: org.postgresql.util.PSQLException: This connection has been closed.
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.checkClosed(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.prepareStatement(Unknown Source)
> 	at org.jabref.merged.module@6.0.15043/org.postgresql.jdbc.PgConnection.prepareStatement(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.indexing.BibFieldsIndexer.insertField(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.indexing.BibFieldsIndexer.updateEntry(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.logic.search.IndexManager$8.call(Unknown Source)
> 	at org.jabref@6.0.15043/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
> 	at javafx.graphics@23.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 

Perhaps, this helps us to hunt down the location of the cause

**Comment by koppor** [comment]
> JR is spawing a postgresql instance upon my changes to update the index.

This should not happen. One Postres instance per JabRef instance - not more fine grained.

@ytzemih Which GNU/Linux do you run? I learned that there are differences between different distributions. E.g., NixOS behaves very different than CachyOS with Gnome than Debian/stable 😅.

**Comment by HoussemNasri** [comment]
> In the meanwhile, I've observed that the issue occurs when I work on bib entries, in particular, editing comments and other fields, which involves a lot of typing. And, certainly, I'd expect any hooks for search routines NOT to be spawned upon every other key stroke. Rather, I'd expect (in a way like pawn detection algorithms with touch pads) to only react after a typing activity, say one second after the last key stroke.

@ytzemih We can definitely implement request throttling to reduce load on the database but we are not certain about the problem, it could be a deadlock, or a race condition that lead to an infinite loop or something else. Introducing throttling is not without cost and it could result in even more bugs as it adds more complexity to the current design. We need more data to make the correct decision. Since you are the only one who can reproduce this, we need your help.

We created a build with JMX enabled which should allow you to attach to JabRef process using [VisualVM](https://visualvm.github.io/download.html) and collect diagnosis about what's happening: https://github.com/JabRef/jabref/pull/13896.

Please install that version, try to reproduce the problem and then use VisualVM to collect Thread dumps (multiple if possible) and heap dumps and screenshots of hotspots from sampling CPU usage.

<img width="1792" height="1120" alt="Image" src="https://github.com/user-attachments/assets/7844da95-8a50-4587-8794-6b41d7e11b13" />

<img width="1792" height="1120" alt="Image" src="https://github.com/user-attachments/assets/39023c85-3d52-4d54-b88d-cb44036782a5" />

**Comment by HoussemNasri** [comment]
Also, it would be great if you run JabRef from the command line and pass the `--debug` option and send us the logs.

**Comment by ytzemih** [comment]
Dear @HoussemNasri , thanks a lot for your response on that and the debugging guidance, much appreciated. Unfortunately, I've had to backport to JR5 sometime in spring, as JR6 basically rendered unusable on my specific machine. Haven't been using JR6 since thin. JR5 is doing just fine for me and backported all the search expressions and stuff. Been diving into a new job recently, so I'll need to see whether I have the time on one of the coming weekends to have a look. Independent of that, I'd not pay too much attention to this as it seems, I'm the only one experiencing that problem so far, right? So, it might not be critical. Cheers, M

**Comment by subhramit** [comment]
> JR6 basically rendered unusable on my specific machine

By rendered unusable, do you mean due to this issue or were there other things you recall?

**Comment by ytzemih** [comment]
@subhramit and others: Sorry for my late answer (lots to do): No other issues. I just think, my combination of using bib files with 1000+ entries, "search groups", "search field", and updating the comments field in the entry editor lies on the "critical path" of JR (that is, on a scenario that occurs extremely often). So, if that scenario doesn't work, I basically can't use JR6. 

I guess, more generally, the problem of JR6 in comparison with JR5 seems to be that computation heavy procedures (e.g. indexing/Postgre) are triggered (e.g. by me using the entry editor) more often. And, in my case, leading to limited usability.

Btw: I'm still running on LMDE (Linux Mint Debian Edition) 6.

**Comment by koppor** [comment]
TL;DR: We need to reproduce with following parameters

> I just think, my combination of using bib files with 1000+ entries, "search groups", "search field", and updating the comments field in the entry editor

It is NOT about a small library with 10 entries, it is about a library with 10k entries. A real-life library.

**Comment by koppor** [comment]
A start to reproduce publicly can be to work on https://github.com/JabRef/jabref/blob/main/scripts/bib-file-generator.py to produce some other large library.

We can also use existing libraries privately sent to us.

Currently, this issue does not have any hint on any try to reproduce the issue.

**Comment by LoayTarek5** [comment]
I would love to work on this issue, can anyone assign it to me?
because I have "Assignment Limit Reached",
i have already made PRs to the other issues, and I am waiting to be merged

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@LoayTarek5 I would like to be respective of your time. I am reading up on https://github.com/JabRef/jabref/issues/12708, but forgot to assign myself (🤦 ).

There is a risk the time you spend of this issue will be wasted depending on which direction https://github.com/JabRef/jabref/issues/12708 goes. If you are interested in it on your own volition, and are ok with your time potentially being wasted, let me know and I'll try to speed up reviewing one or two of your open PRs.

**Comment by LoayTarek5** [comment]
@k3KAW8Pnf7mkmdSMPHz27 I am actually interested in submitting a proposal for this [project](https://jabref.github.io/GSoC/posts/postgres/), so I am trying to address the issues related to it.
i would appreciate guidance or suggestions on issues I could work on , it will help

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@LoayTarek5 I didn't realize this was part of GSoC. Feel free to go ahead with the GSoC proposal and you can of course take advantage of the information in https://github.com/JabRef/jabref/issues/12708. I am not up to date with the GSoC rules, but as long as you stay within them and JabRef's community/contribution/AI rules you should be good to go.

**Comment by koppor** [comment]
> @LoayTarek5 I didn't realize this was part of GSoC.

Link: https://jabref.github.io/GSoC/posts/own-project/

And maybe https://jabref.github.io/GSoC/posts/postgres/

**Comment by LoayTarek5** [comment]
> > [@LoayTarek5](https://github.com/LoayTarek5) I didn't realize this was part of GSoC.
> 
> Link: https://jabref.github.io/GSoC/posts/own-project/
> 
> And maybe https://jabref.github.io/GSoC/posts/postgres/

I am a bit lost now😅, is it wise to go with this issue now or not?
to be honset according to @k3KAW8Pnf7mkmdSMPHz27, what he said is that it might risk the time you spend of this issue will be wasted depending on which direction the main issue goes
so any suggestions for any valid issues related to that project ?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I had Claude Code analyse the codebase around this issue. @LoayGhreeb's hypothesis about search groups and @ytzemih's observation about per-keystroke triggering are both confirmed by the code.

> [!NOTE]
> The analysis below was generated by Claude Code and reviewed by @k3KAW8Pnf7mkmdSMPHz27.

## Root cause

There is no debouncing in the indexing pipeline. On every keystroke in the entry editor:

1. `BibEntry.setField()` posts a `FieldChangedEvent`
2. `LibraryTab.IndexUpdateListener` calls `IndexManager.updateEntry()` — no filtering or throttling
3. `BibFieldsIndexer.updateEntry()` executes SQL DELETE + INSERT against Postgres
4. An `IndexAddedOrUpdatedEvent` is posted, causing **every** active `SearchGroup` to re-query via `GroupNodeViewModel.SearchIndexListener`

With N search groups, each keystroke triggers 1 index update + N search queries. This confirms @koppor's clarification — there is one Postgres instance, but the issue is the volume of queries, not the number of instances.

PR #12373 fixed the concurrency bug (unique constraint violation from racing threads) by adding synchronization, but as @ytzemih noted, the CPU issue persists because the underlying throughput problem — too many operations per keystroke — was not addressed.

@ytzemih's suggestion of reacting "one second after the last key stroke" is exactly the right approach. The codebase already has `DelayTaskThrottler` and `CoarseChangeFilter` used elsewhere (e.g., autosave, backup), but neither is wired into the indexing path.

## Possible solutions

As @HoussemNasri noted, throttling adds complexity — but these are relatively contained changes since the utilities already exist:

1. **Debounce `IndexManager.updateEntry()`** using the existing `DelayTaskThrottler` (200–300 ms delay after last keystroke)
2. **Batch `IndexAddedOrUpdatedEvent` notifications** so search groups coalesce multiple updates before re-querying
3. **Check `CoarseChangeFilter.isFilteredOut()`** in `IndexUpdateListener` before forwarding to the index manager

The fix is backend-agnostic — the same debouncing gap would exist with any search backend (see #12708 for the broader architecture discussion).

This issue is currently unassigned and open for contributors. @LoayTarek5 if you're no longer hitting the assignment limit, you're good to go on this one.

**Comment by koppor** [comment]
Note that we have a throttling at the events. I think, if one searches the code for "thrott", one finds it.

**Comment by subhramit** [comment]
@LoayTarek5 Note that the first step you should follow when working on this is to replicate the 100% usage, and not start working on the fix right away.
Once you are able to come up with a library with a [sufficient number of groups](https://github.com/JabRef/jabref/issues/12190#issuecomment-2580315024) that is able to trigger it, you can try the proposed solutions and see what helps it.

**Comment by LoayTarek5** [comment]
> [@LoayTarek5](https://github.com/LoayTarek5) Note that the first step you should follow when working on this is to replicate the 100% usage, and not start working on the fix right away. Once you are able to come up with a library with a [sufficient number of groups](https://github.com/JabRef/jabref/issues/12190#issuecomment-2580315024) that is able to trigger it, you can try the proposed solutions and see what helps it.

Yeah, of course, you are right.

**Comment by Siedlerchr** [comment]
In the JabRef repo under scripts you can find some scripts to generate a large library with many groups as well https://github.com/JabRef/jabref/blob/main/scripts/bib-file-generator.py

**Comment by ytzemih** [comment]
Again using JR6 for a good week now. It seems that this issue has gone now. There are a couple of 10 postgres instances (given they are installed by JR), but none of them is consuming CPU while JabRef is running in the background.

<img width="582" height="323" alt="Image" src="https://github.com/user-attachments/assets/fdbf4ccf-1517-4176-87e3-a471f05dd690" />

<img width="685" height="146" alt="Image" src="https://github.com/user-attachments/assets/dbd74afa-a459-40a1-823c-bb0d46fcd248" />

**Comment by subhramit** [comment]
@LoayTarek5 🎉

**Comment by LoayTarek5** [comment]
I am really happy that this got resolved.
