### ISSUE TITLE
bug with entry from plain text

### ISSUE THREAD

**Issue by luca-ferrigno** [JabRef/jabref#12211]
JabRef 5.15--2024-07-10--1eb3493
Windows 11 10.0 amd64 
Java 21.0.2

Steps to reproduce:

1. click on "new entry from plain text"
2. insert citation
3. "0 entries were parsed from your query."

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Opening: 'C:\Users\lucaf\Scuola\Università\Articoli\biblio.bib'
Resource "" not found.
Resource "" not found.
Java vector incubator module is not readable. For optimal vector performance, pass '--add-modules jdk.incubator.vector' to enable Vector API.
Problem parsing XMP schema. Continuing with other schemas.
java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.readXmp(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfXmpImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfMergeMetadataImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.externalfiles.ExternalFilesContentImporter.importPDFContent(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.externalfiles.ImportHandler$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.externalfiles.ImportHandler$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.manageArray(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.createProperty(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parse(Unknown Source)
	... 16 more

Deleted 1 entry(ies)
Importing file (Aspects of Mathematics 6) Prof. Dr. Gerd Faltings, Prof. Dr. Gisbert W_stholz (auth.) - Rational Points_ Seminar Bonn_Wuppertal 1983_84-Vieweg+Teubner Verlag (1992).pdf as unknown format
Problem parsing XMP schema. Continuing with other schemas.
java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.readXmp(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfXmpImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfMergeMetadataImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$0(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.manageArray(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.createProperty(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parse(Unknown Source)
	... 19 more

Problem parsing XMP schema. Continuing with other schemas.
java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.readXmp(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.hasMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfXmpImporter.isRecognizedFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.manageArray(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.createProperty(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parse(Unknown Source)
	... 19 more

Supplied encoding could not be determined
java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.implReadLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.getSuppliedEncoding(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.getEncodingResult(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$0(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Problem parsing XMP schema. Continuing with other schemas.
java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.readXmp(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfXmpImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfMergeMetadataImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$0(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.manageArray(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.createProperty(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parse(Unknown Source)
	... 19 more

Problem parsing XMP schema. Continuing with other schemas.
java.io.IOException: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.parseXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.getXmpMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilReader.readXmp(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.xmp.XmpUtilShared.hasMetadata(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.PdfXmpImporter.isRecognizedFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xmpbox.xml.XmpParsingException: Invalid array type, expecting Seq and found Bag [prefix=dc; name=creator]
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.manageArray(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.createProperty(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseChildrenAsProperties(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parseDescriptionRoot(Unknown Source)
	at org.jabref.merged.module@5.15.60000/org.apache.xmpbox.xml.DomXmpParser.parse(Unknown Source)
	... 19 more

Supplied encoding could not be determined
java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.implReadLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.getSuppliedEncoding(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.getEncodingResult(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.lambda$importUnknownFormat$0(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.doImport(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.importer.ImportCommand.lambda$importSingleFile$1(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.15.60000/org.jabref.gui.util.UiTaskExecutor$1.call(Unknown Source)
	at javafx.graphics@22.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Import canceled
Your text is being parsed...
0 entries were parsed from your query.
Your text is being parsed...
0 entries were parsed from your query.
Deleted 1 entry(ies)
Your text is being parsed...
0 entries were parsed from your query.
External changes are resolved successfully
Library saved
Your text is being parsed...
0 entries were parsed from your query.
Library saved
Your text is being parsed...
0 entries were parsed from your query.
Library saved
Your text is being parsed...
0 entries were parsed from your query.
Library saved
Your text is being parsed...
0 entries were parsed from your query.
Library saved
Issue on GitHub successfully reported.
```

</details>

**Comment by koppor** [comment]
@luca-ferrigno Could you paste the reference here? I assume, you have activated Grobid - and our Grobid server is probably down.

I tried with 

    O. Kopp, A. Armbruster, und O. Zimmermann, "Markdown Architectural Decision Records: Format and Tool Support", in 10th ZEUS Workshop, 2018.

![Image](https://github.com/user-attachments/assets/cdb7030f-9b85-4286-9b71-238ce2941df5)

Result

```bibtex
@Book{Kopp2018,
  author    = {Kopp, A. and und, O. },
  publisher = { "Markdown Architectural Decision Records: Format and Tool Support"},
  title     = {Zimmermann},
  year      = {2018},
  comment   = {O. [author_tag]Armbruster, [author_tag]Zimmermann, "Markdown Architectural Decision Records: Format and Tool Support", in[pages_tag]th ZEUS Workshop, [year_tag].},
  pages     = { 10},
}
```

(Wrong entry type etc)

---

With LLM:

![Image](https://github.com/user-attachments/assets/ae377f80-ce3e-4157-a0f0-3d6bf3a971e1)

```bibtex
@InProceedings{Kopp2018b,
  author    = {O. Kopp and A. Armbruster and O. Zimmermann},
  booktitle = {10th ZEUS Workshop},
  title     = {Markdown Architectural Decision Records: Format and Tool Support},
  year      = {2018},
}
```

**Comment by koppor** [comment]
Did not hear any update. Maybe it is related to https://github.com/jabref/jabref/issues/10082

**Comment by ThiloteE** [comment]
I wrote new documentation for "entry from plain text". See https://docs.jabref.org/collect/newentryfromplaintext. I recommend trying the 6.0alpha release. Grobid is currently down, but LLM works.

**Comment by luca-ferrigno** [comment]
I cannot select the parser, as there is no selection menu. I'm currently using version 5.15 on Windows.

**Comment by ThiloteE** [comment]
Yes, it is a new feature only available in JabRef 6.0alpha.

**Comment by ThiloteE** [comment]
You can download the alpha version from here: https://builds.jabref.org/tags/v6.0-alpha/

**Comment by luca-ferrigno** [comment]
Thank you!

**Comment by koppor** [comment]
Releases are best downloaded from the releases page. --> https://github.com/JabRef/jabref/releases
