### ISSUE TITLE
App doesn't open the library anymore, shows spinning wheel

### ISSUE THREAD

**Issue by genseirin** [JabRef/jabref#12326]
JabRef 5.15--2024-07-10--1eb3493
Mac OS X 14.7.2 aarch64 
Java 21.0.2

Steps to reproduce:

1. Start the app
2. Watch the wheel spinning

The app has always loaded the database before. Reopening the app always leads to the same result.
I have to force-quit the app afterwards, the dock icon doesn't quit per command.

Pasted logs:

```
New protected terms resource '/protectedterms/computer_science.terms' is available and enabled by default.
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Öffne: '/Users/myname/Library/CloudStorage/Tresorit-FooBar/Literatur/Bücher.bib'
Resource "" not found.
Resource "" not found.
Problem erfolgreich auf GitHub gemeldet.
```

Some more info about the file mentioned in the logs:
`-rw-------@ 1 myname  staff  212778 Nov 23 22:13 /Users/myname/Library/CloudStorage/Tresorit-FooBar/Literatur/Bücher.bib`

**Comment by Siedlerchr** [comment]
Hm, seems Ike something is wrong in your library which prevents JabRef from opening your library 
You can try to start JabRef via command line  using the `--blank` https://docs.jabref.org/advanced/commandline#no-files-at-startup-b  

and additionally also try debug to see if the log shows some more output

Did you install the arm version of JabRef for mac?

**Comment by genseirin** [comment]
I don't remember, which version it was, so I installed now arm.

With `--blank` the app starts fine, `--debug` doesn't create a new log file (I have there logs from old versions), but I see additional output in the terminal:

```
Messages are not initialized before accessing key: Display help on command line options
2024-12-22 23:47:47 [main] org.jabref.logic.remote.client.RemoteClient.ping()
DEBUG: Could not ping server at port 6050: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at org.jabref@5.15.60000/org.jabref.logic.remote.client.RemoteClient.openNewConnection(RemoteClient.java:69)
	at org.jabref@5.15.60000/org.jabref.logic.remote.client.RemoteClient.ping(RemoteClient.java:31)
	at org.jabref@5.15.60000/org.jabref.Launcher.handleMultipleAppInstances(Launcher.java:173)
	at org.jabref@5.15.60000/org.jabref.Launcher.main(Launcher.java:68)
2024-12-22 23:47:47 [main] org.jabref.Launcher.handleMultipleAppInstances()
DEBUG: Could not ping JabRef instance.
2024-12-22 23:47:47 [main] org.jabref.migrations.PreferencesMigrations.upgradePrefsToOrgJabRef()
DEBUG: New prefs node already exists with content - skipping migration
2024-12-22 23:47:48 [main] org.jabref.logic.protectedterms.ProtectedTermsLoader.update()
WARN: New protected terms resource '/protectedterms/computer_science.terms' is available and enabled by default.
2024-12-22 23:47:48 [main] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
DEBUG: Trust store path: /Users/myname/Library/Application Support/jabref/ssl/truststore.jks
2024-12-22 23:47:48 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.baseCssLiveUpdate()
DEBUG: Updating base CSS for main window scene
2024-12-22 23:47:48 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2024-12-22 23:47:48 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2024-12-22 23:47:48 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.additionalCssLiveUpdate()
DEBUG: Updating additional CSS for main window scene and 0 web engines
2024-12-22 23:47:54 [JavaFX Application Thread] org.jabref.gui.journals.AbbreviateAction.<init>()
DEBUG: Unknown action: UNABBREVIATE
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: aboutdialog.fxml not found, attempting with camel case
2024-12-22 23:47:54 [JavaFX Application Thread] org.jabref.gui.util.JabRefResourceLocator.getResourceBundle()
DEBUG: Requested bundle for 'org.jabref.gui.help.aboutdialog'.
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class org.jabref.gui.help.AboutDialogView and instance org.jabref.gui.help.AboutDialogView@2b0610bc
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class org.jabref.gui.ClipBoardManager and instance org.jabref.gui.ClipBoardManager@36ba2c1a
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class java.lang.Object and instance org.jabref.gui.ClipBoardManager@36ba2c1a
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class org.jabref.gui.util.BaseDialog and instance org.jabref.gui.help.AboutDialogView@2b0610bc
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.control.Dialog and instance org.jabref.gui.help.AboutDialogView@2b0610bc
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class java.lang.Object and instance org.jabref.gui.help.AboutDialogView@2b0610bc
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: aboutdialog.bss not found, attempting with camel case
2024-12-22 23:47:54 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: aboutdialog.css not found, attempting with camel case
2024-12-22 23:47:54 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
2024-12-22 23:47:54 [JavaFX Application Thread] org.jabref.gui.JabRefGUI.openWindow()
DEBUG: Initializing frame
2024-12-22 23:47:54 [JavaFX Application Thread] org.jabref.gui.JabRefGUI.debugLogWindowState()
DEBUG: SCREEN DATA:mainStage.WINDOW_MAXIMISED: true
mainStage.POS_X: 0.0
mainStage.POS_Y: 25.0
mainStage.SIZE_X: 1440.0
mainStages.SIZE_Y: 875.0

2024-12-22 23:47:54 [JavaFX Application Thread] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Resource "" not found.
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.logic.util.WebViewStore.lambda$addWebViewLater$0()
DEBUG: Cached Web views: 1
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.logic.util.WebViewStore.lambda$addWebViewLater$0()
DEBUG: Cached Web views: 2
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.logic.util.WebViewStore.lambda$addWebViewLater$0()
DEBUG: Cached Web views: 3
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.logic.util.WebViewStore.lambda$addWebViewLater$0()
DEBUG: Cached Web views: 4
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.gui.search.GlobalSearchBar.updateSearchQuery()
DEBUG: Flags: [KEEP_SEARCH_STRING]
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.gui.search.GlobalSearchBar.updateSearchQuery()
DEBUG: Updated search query: 
2024-12-22 23:47:55 [JavaFX Application Thread] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
WARN: Resource "" not found.
2024-12-22 23:47:55 [JavaFX Application Thread] org.jabref.gui.frame.JabRefFrameViewModel.handleUiCommands()
DEBUG: Handling UI commands [BlankWorkspace[]]
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: entryeditor.fxml not found, attempting with camel case
2024-12-22 23:48:03 [JavaFX Application Thread] org.jabref.gui.util.JabRefResourceLocator.getResourceBundle()
DEBUG: Requested bundle for 'org.jabref.gui.entryeditor.entryeditor'.
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class org.jabref.gui.entryeditor.EntryEditor and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.layout.BorderPane and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.layout.Pane and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.layout.Region and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.Parent and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class javafx.scene.Node and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.injection.Injector.injectMembers()
DEBUG: Injecting members for class class java.lang.Object and instance EntryEditor@2b3980ff
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: entryeditor.bss not found, attempting with camel case
2024-12-22 23:48:03 [JavaFX Application Thread] com.airhacks.afterburner.views.ViewLoader.getResourceCamelOrLowerCase()
DEBUG: File: entryeditor.css not found, attempting with camel case
2024-12-22 23:48:03 [pool-2-thread-1] org.jabref.gui.JabRefDialogService.notify()
INFO: Öffne: '/Users/myname/Library/CloudStorage/Tresorit-FooBar/Literatur/Bücher.bib'
2024-12-22 23:48:04 [JavaFX Application Thread] org.jabref.gui.maintable.PersistenceVisualStateTable.updateColumns()
DEBUG: Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@7151ce59, org.jabref.gui.maintable.MainTableColumnModel@be752888, org.jabref.gui.maintable.MainTableColumnModel@f8ac92c8, org.jabref.gui.maintable.MainTableColumnModel@f24c2621, org.jabref.gui.maintable.MainTableColumnModel@9c6035e6, org.jabref.gui.maintable.MainTableColumnModel@156439cd, org.jabref.gui.maintable.MainTableColumnModel@f089fb2, org.jabref.gui.maintable.MainTableColumnModel@18b83c30, org.jabref.gui.maintable.MainTableColumnModel@97ad9c59, org.jabref.gui.maintable.MainTableColumnModel@7623f12b, org.jabref.gui.maintable.MainTableColumnModel@17e949c7]
2024-12-22 23:48:04 [JavaFX Application Thread] org.jabref.gui.maintable.PersistenceVisualStateTable.updateColumns()
DEBUG: Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@7151ce59, org.jabref.gui.maintable.MainTableColumnModel@be752888, org.jabref.gui.maintable.MainTableColumnModel@f8ac92c8, org.jabref.gui.maintable.MainTableColumnModel@f24c2621, org.jabref.gui.maintable.MainTableColumnModel@9c6035e6, org.jabref.gui.maintable.MainTableColumnModel@156439cd, org.jabref.gui.maintable.MainTableColumnModel@f089fb2, org.jabref.gui.maintable.MainTableColumnModel@18b83c30, org.jabref.gui.maintable.MainTableColumnModel@97ad9c59, org.jabref.gui.maintable.MainTableColumnModel@7623f12b, org.jabref.gui.maintable.MainTableColumnModel@17e949c7]
2024-12-22 23:48:04 [JavaFX Application Thread] org.jabref.gui.maintable.PersistenceVisualStateTable.updateColumns()
DEBUG: Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@7151ce59, org.jabref.gui.maintable.MainTableColumnModel@be752888, org.jabref.gui.maintable.MainTableColumnModel@f8ac92c8, org.jabref.gui.maintable.MainTableColumnModel@f24c2621, org.jabref.gui.maintable.MainTableColumnModel@9c6035e6, org.jabref.gui.maintable.MainTableColumnModel@156439cd, org.jabref.gui.maintable.MainTableColumnModel@f089fb2, org.jabref.gui.maintable.MainTableColumnModel@18b83c30, org.jabref.gui.maintable.MainTableColumnModel@97ad9c59, org.jabref.gui.maintable.MainTableColumnModel@7623f12b, org.jabref.gui.maintable.MainTableColumnModel@17e949c7]
2024-12-22 23:48:04 [JavaFX Application Thread] org.jabref.gui.maintable.PersistenceVisualStateTable.updateColumns()
DEBUG: Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@7151ce59, org.jabref.gui.maintable.MainTableColumnModel@be752888, org.jabref.gui.maintable.MainTableColumnModel@f8ac92c8, org.jabref.gui.maintable.MainTableColumnModel@f24c2621, org.jabref.gui.maintable.MainTableColumnModel@9c6035e6, org.jabref.gui.maintable.MainTableColumnModel@156439cd, org.jabref.gui.maintable.MainTableColumnModel@f089fb2, org.jabref.gui.maintable.MainTableColumnModel@18b83c30, org.jabref.gui.maintable.MainTableColumnModel@97ad9c59, org.jabref.gui.maintable.MainTableColumnModel@7623f12b, org.jabref.gui.maintable.MainTableColumnModel@17e949c7]
2024-12-22 23:48:04 [JavaFX Application Thread] org.jabref.gui.maintable.PersistenceVisualStateTable.updateColumns()
DEBUG: Updating columns to [org.jabref.gui.maintable.MainTableColumnModel@7151ce59, org.jabref.gui.maintable.MainTableColumnModel@be752888, org.jabref.gui.maintable.MainTableColumnModel@f8ac92c8, org.jabref.gui.maintable.MainTableColumnModel@f24c2621, org.jabref.gui.maintable.MainTableColumnModel@9c6035e6, org.jabref.gui.maintable.MainTableColumnModel@156439cd, org.jabref.gui.maintable.MainTableColumnModel@f089fb2, org.jabref.gui.maintable.MainTableColumnModel@18b83c30, org.jabref.gui.maintable.MainTableColumnModel@97ad9c59, org.jabref.gui.maintable.MainTableColumnModel@7623f12b, org.jabref.gui.maintable.MainTableColumnModel@17e949c7]

```

**Comment by Siedlerchr** [comment]
As I suspected, the log doesn't hint on an error. Can you open the problematic library now?

**Comment by genseirin** [comment]
> As I suspected, the log doesn't hint on an error. Can you open the problematic library now?

No, unfortunately it shows the same behavior. The log stems from the attempt to open the library.

**Comment by Siedlerchr** [comment]
Very odd. Would it be possible to send us your bib file? We handle it privately (you can send it to web@jabref.org)

**Comment by genseirin** [comment]
So I tried to compress the file for sending it, which also froze. That gave me the idea to look into file system issues. It turned out that apparently the file was locked, probably by a virtual disk app. Disabling it resolved the issue.

Thanks for the support!

For UX it could be useful to add a timeout when opening files so that it fails gracefully.

**Comment by Siedlerchr** [comment]
Glad to hear it worked. Happy Holidays!  We will think about your suggestion or other possibiilies to check that.
