### ISSUE TITLE
Exception on Get BibTeX data from DOI

### ISSUE THREAD

**Issue by paulsputer** [JabRef/jabref#1239]
Using JabRef version 3.3 on Windows 7 I seem to be getting exceptions when requesting BibTex data from DOI after dragging and dropping certain papers which auto populated the DOI.  

If I restart JabRef and request BibTex data from DOI again it works fine, and then fails a few papers later.

Log
```
5:52:07.499 [AWT-EventQueue-0] INFO  net.sf.jabref.importer.fetcher.CrossRef - DOI 10.1109/im.2001.924423 for Efficient Variants of the ICP Algorithm found.
```

Exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.sf.jabref.logic.util.DOI.<init>(DOI.java:63)
	at net.sf.jabref.importer.fetcher.DOItoBibTeXFetcher.getEntryFromDOI(DOItoBibTeXFetcher.java:86)
	at net.sf.jabref.gui.mergeentries.MergeEntryDOIDialog.<init>(MergeEntryDOIDialog.java:72)
	at net.sf.jabref.gui.entryeditor.FieldExtraComponents.lambda$getDoiExtraComponent$4(FieldExtraComponents.java:193)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)

```

Any ideas?

**Comment by stefan-kolb** [comment]
See #1234?

**Comment by paulsputer** [comment]
Thanks, I did a search for "exception" so didn't see that one.  Clicking the DOI text field works for me too as a workaround.

**Comment by stefan-kolb** [comment]
What do oyu mean by dragging and dropping a paper? Can you give me the steps and artifacts to reproduce this? It would be probably handy if you can give me a link to a PDF that auto populates the doi field.

**Comment by stefan-kolb** [comment]
Also, can you try a build from here so we can see if this fixes your issue as well? http://builds.jabref.org/fix-1234/

**Comment by paulsputer** [comment]
> What do you mean by dragging and dropping a paper? 

As in click on a PDF file and drag it into the JabRef window to import it.

When I get a moment I'll try running it with debugger attached and see what's happening

**Comment by stefan-kolb** [comment]
Have you tried the new build? I think this should solve your issue.

**Comment by paulsputer** [comment]
Thanks @stefan-kolb, just tested and yes http://builds.jabref.org/fix-1234/ does solve the issue

**Comment by stefan-kolb** [comment]
Good to hear :+1: Thanks for your report!
