### ISSUE TITLE
View -> Sort Tab gives NPE

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1295]
Version: ced4a0aefba4890848e9f96b4be084fdb654ec9a (master) on Win 7 x64 with Java 8

Steps to reproduce:

1. Open two bib dbs
2. Click View -> Sort Tab
3. Look at error Console

Reproducible 

````
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.sf.jabref.gui.JabRefFrame.updateEnabledState(JabRefFrame.java:1604)
	at net.sf.jabref.gui.JabRefFrame.lambda$2(JabRefFrame.java:1563)
	at javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
	at javax.swing.JTabbedPane.removeAll(Unknown Source)
	at net.sf.jabref.gui.actions.SortTabsAction.actionPerformed(SortTabsAction.java:53)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
...
````

**Comment by stefan-kolb** [comment]
@Siedlerchr You might want to test the build inside the PR :smile:

**Comment by Siedlerchr** [comment]
@stefan-kolb  Will try it the next days. Discovered this bug by chance. I never really used that feature.
