### ISSUE TITLE
Null exception when trying to import from external database with no *.bib open

### ISSUE THREAD

**Issue by fishforbreakfast** [JabRef/jabref#1476]
JabRef version 3.4 on x86_64 Linux

Steps to reproduce:
Start JabRef.
1. Close all opened or previously opened databases.
2. From the file menu choose "import from external database"
3. Connect to a database server.
4. Choose a database to import from.
JabRef throws an exception.  Here is the log:

20:40:18.796 [Spin-0] ERROR net.sf.jabref.sql.importer.DbImportAction - Error importing from database
java.lang.NullPointerException
	at net.sf.jabref.sql.importer.DbImportAction.performImport(DbImportAction.java:161) [JabRef-3.4.jar:?]
	at net.sf.jabref.sql.importer.DbImportAction.run(DbImportAction.java:125) [JabRef-3.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at spin.Invocation.evaluate(Invocation.java:175) [JabRef-3.4.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) [JabRef-3.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
_______________________________________________________________________________
If another database is open previous to trying to import, everything works as it is supposed to.  I've only tested this against a PostgreSQL server.

Cheers,

Fred

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
I can reproduce the behavior and we will work on a fix for this issue. Stay tuned.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `fix-1476`. Please try the latest build from http://builds.jabref.org/fix-1476.

**Comment by fishforbreakfast** [comment]
The fix works for this issue.  Thank you again.  I will test it for a while further to see if there is anything related that crops up.

Regards,

Fred
