### ISSUE TITLE
Cannot searching from google scholar

### ISSUE THREAD

**Issue by AriaAsuka** [JabRef/jabref#1538]
JabRef version  3.4 on  Arch Linux 4.5.4 

Steps to reproduce:

1. I get nothing through searching feature from google scholar, there is "status: searching" displaying on status bar all the time. But I can achieve expected results with JabRef 3.4 on Windows 7.

**Comment by matthiasgeiger** [comment]
Thanks for your Report! 

Can you please check whether there are some errors in the error Console ("Help" -> "Show error console").

**Comment by AriaAsuka** [comment]
The log below
18:24:49.994 [AWT-EventQueue-0] WARN  net.sf.jabref.JabRefGUI - There seem to be problems with OpenJDK and the default GTK Look&Feel. Using Metal L&F instead. Change to another L&F with caution.
18:25:04.911 [JabRef CachedThreadPool] WARN  net.sf.jabref.logic.net.URLDownload - Could not copy input
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_92]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:1.8.0_92]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_92]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:157) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:152) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.runConfig(GoogleScholarFetcher.java:176) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.processQueryGetPreview(GoogleScholarFetcher.java:96) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GeneralFetcher.lambda$actionPerformed$4(GeneralFetcher.java:231) ~[JabRef-3.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
18:25:04.913 [JabRef CachedThreadPool] WARN  net.sf.jabref.importer.fetcher.GoogleScholarFetcher - Error fetching from Google Scholar
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789) ~[?:1.8.0_92]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_92]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:1.8.0_92]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_92]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:157) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:152) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.runConfig(GoogleScholarFetcher.java:176) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.processQueryGetPreview(GoogleScholarFetcher.java:96) ~[JabRef-3.4.jar:?]
	at net.sf.jabref.importer.fetcher.GeneralFetcher.lambda$actionPerformed$4(GeneralFetcher.java:231) ~[JabRef-3.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]


There is nothing in exceptions and outpus

**Comment by Siedlerchr** [comment]
Thanks for the detailed error message.
A SocketException indicates  that the Remote host (Google) unexpectedly closed the connection.
Is this reproducible, e.g. does it happen every time?
Do you use a Proxy?

**Comment by AriaAsuka** [comment]
It happen every time and I use shadowsocks.


On 7/4/2016 20:55, Christoph wrote:
>
> Thanks for the detailed error message.
> A SocketException indicates that the Remote host (Google) unexpectedly 
> closed the connection.
> Is this reproducible, e.g. does it happen every time?
> Do you use a Proxy?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/JabRef/jabref/issues/1538#issuecomment-230284257>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AImuyaOEWkOEG_zXypAhun6dOIq5vCyxks5qSQLWgaJpZM4JDrb1>.
>

-- 
*/Cordially,/
/Alice Aria/
* From: butterflyonleft@gmail.com <mailto:butterflyonleft@gmail.com>

**Comment by AriaAsuka** [comment]
The terminal shows

kbibtex(2262) OnlineSearchAbstract::hanleErrors: Search using "Google 
Scholar" failed (error code 202 ( "Error downloading 
http://scholar.google.com/ - server replied: Forbidden" ), HTTP code 403 
: "Forbidden")


On 7/4/2016 20:55, Christoph wrote:
>
> Thanks for the detailed error message.
> A SocketException indicates that the Remote host (Google) unexpectedly 
> closed the connection.
> Is this reproducible, e.g. does it happen every time?
> Do you use a Proxy?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/JabRef/jabref/issues/1538#issuecomment-230284257>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AImuyaOEWkOEG_zXypAhun6dOIq5vCyxks5qSQLWgaJpZM4JDrb1>.
>

-- 
*/Cordially,/
/Alice Aria/
* From: butterflyonleft@gmail.com <mailto:butterflyonleft@gmail.com>

**Comment by Siedlerchr** [comment]
@AriaAsuka  There we see the reason HTTP code 403 -Forbidden. So this is not a Problem of JabRef.
Seems like Google Scholar has blocked your  Proxy-IP.
A quick Google Search turned up with this, maybe that helps you: 
https://github.com/sjtug/kxsw/wiki/Google-Scholar

The only improvement we can do in JabRef is do display a more clear Error message
Refs #1542
