### ISSUE TITLE
NPE when starting JabRef

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1551]
JabRef-3.5dev--snapshot--2016-07-06--master--d5b42a0

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at net.sf.jabref.gui.groups.GroupSelector.setGroups(GroupSelector.java:725)
        at net.sf.jabref.gui.groups.GroupSelector.<init>(GroupSelector.java:356)
        at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:693)
        at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:600)
        at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:528)
        at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:114)
        at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:70)
        at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:108)
```

No UI is opened, but the JAR is still active.

JabRef should stop when startup doesn't work

Steps to reproduce:

1. Close all opened tabs in JabRef
2. Update to latest master branch
3. `gradlew run`

**Comment by koppor** [comment]
@oscargus It seems that this might be caused by your code cleanups (#1546), isn't it?

**Comment by koppor** [comment]
I solved this by a quick fix. I don't get, why the refactoring causes NPEs during runtime. @tobiasdiez Could you comment?

**Comment by oscargus** [comment]
Interesting!

**Comment by tobiasdiez** [comment]
Proper fix in https://github.com/JabRef/jabref/pull/1552. To be honest, I'm not sure why the previous code does not result in an NPE.
