### ISSUE TITLE
Google Scholar web search -- Cannot download entry

### ISSUE THREAD

**Issue by davydden** [JabRef/jabref#1674]
JabRef version 3.5 on Mac OS X 10.11.6, Java  1.8.0_20.

Steps to reproduce:

1. choose Google Scholar for Web search, enter `Truesdell rational continuum mechanics`
2. Choose the first book from the list `A first course in rational continuum mechanics`, click ok.
3. Empty list with nothing to choose but with an error log

```
14:39:51.339 [JabRef CachedThreadPool] WARN  net.sf.jabref.importer.fetcher.GoogleScholarFetcher - Cannot download entry from Google scholar
java.net.UnknownHostException: scholar.google.comhttp
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_101]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_101]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_101]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_101]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[?:1.8.0_101]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:140) ~[JabRef-3.5.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:157) ~[JabRef-3.5.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:152) ~[JabRef-3.5.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.downloadEntry(GoogleScholarFetcher.java:266) ~[JabRef-3.5.jar:?]
	at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.getEntries(GoogleScholarFetcher.java:136) ~[JabRef-3.5.jar:?]
	at net.sf.jabref.importer.fetcher.GeneralFetcher.lambda$null$2(GeneralFetcher.java:245) ~[JabRef-3.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by matthiasgeiger** [comment]
Google has changed its underlying source code and thus JabRef 3.5 fails to download the right data.

The issues has already been reported (https://github.com/JabRef/jabref/issues/1639) and is fixed in the recent development builds. 

Thus, if you rely on the Google Scholar fetcher please use a dev build from here: http://builds.jabref.org/master/

**Comment by davydden** [comment]
@matthiasgeiger thanks for the prompt reply. Should have searched issues list better.
