### ISSUE TITLE
jabref 2.10 fails to start on Ubuntu 15.10

### ISSUE THREAD

**Issue by severin-lemaignan** [JabRef/jabref#168]
Using ``jabref 2.10`` as packaged on Ubuntu 15.10, jabref fails to start most of the time: it displays the splashscreen, and stalls. Nothing special is displayed in the console either (except for ``Found 2 plugins:...``).

Running on gnome-shell 3.16.
```
$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK 64-Bit Server VM (build 25.66-b01, mixed mode)
```
Sometimes (roughly one out of 10 trials), jabref does start, but display a ``NullPointerException`` on the console (may or may not be related):
```
$ jabref
log4j:WARN No appenders could be found for logger (org.java.plugin.ObjectFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Found 2 plugin(s):
- net.sf.jabref.export.misq (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)
- net.sf.jabref.core (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.core/plugin.xml)

java.lang.NullPointerException
at com.sun.java.swing.plaf.gtk.GTKEngine.native_get_gtk_setting(Native Method)
at com.sun.java.swing.plaf.gtk.GTKEngine.getSetting(GTKEngine.java:622)
at com.sun.java.swing.plaf.gtk.GTKLookAndFeel.getGTKStyleFactory(GTKLookAndFeel.java:1581)
at com.sun.java.swing.plaf.gtk.GTKLookAndFeel.loadStyles(GTKLookAndFeel.java:1567)
at com.sun.java.swing.plaf.gtk.GTKLookAndFeel.initialize(GTKLookAndFeel.java:1452)
at javax.swing.UIManager.setLookAndFeel(UIManager.java:538)
at javax.swing.UIManager.setLookAndFeel(UIManager.java:583)
at net.sf.jabref.JabRef.setLookAndFeel(JabRef.java:669)
at net.sf.jabref.JabRef.openWindow(JabRef.java:726)
at net.sf.jabref.JabRef.<init>(JabRef.java:201)
at net.sf.jabref.JabRef.main(JabRef.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.sf.jabref.JabRefMain.main(Unknown Source)
Opening: /home/skadge/publications/hri2016-attention/sigproc.bib
Could not get key binding for "Open folder"
page tab list
```

**Comment by koppor** [comment]
Please try to start the latest beta version. The `jar` is provided at https://sourceforge.net/projects/jabref/files/jabref/2.11%20beta%204/.

If that works, I would suggest to use that and to wait for a new Debian package. You can also file a bug at [launchpad](https://launchpad.net/ubuntu/+source/jabref/+bugs) as we do not support Ubuntu directly, but rely on the [Debian package maintainers](https://packages.debian.org/en/sid/jabref) (with whom we are in close contact).

**Comment by koppor** [comment]
No answer, therefore closing this issue. Feel free to reopen if desired.

**Comment by severin-lemaignan** [comment]
@koppor sorry for not getting back! The beta version works well in my experience. If I can reproduce the issue on a different machine with Ubuntu 15.10, I'll open a ticket on Launchpad.

Cheers!

**Comment by mastrogeppetto** [comment]
Same problem, just upgraded to 15.10:

    $ jabref
    log4j:WARN No appenders could be found for logger (org.java.plugin.ObjectFactory).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    Found 2 plugin(s):
      - net.sf.jabref.core (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.core/plugin.xml)
      - net.sf.jabref.export.misq (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)
    
    The program 'java' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadMatch (invalid parameter attributes)'.
      (Details: serial 278 error_code 8 request_code 42 minor_code 0)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the --sync command line
       option to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)

Downloaded and tried last available but:

    $ java -jar JabRef-3.0.jar 
    Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jabref/JabRefMain : Unsupported major.minor version 52.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
    $ java -showversion
    java version "1.7.0_91"
    OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.15.10.1)
    OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
    ....

The "unsupported major.minor..." might indicate a discrepancy in the java versions used for compiling and executing.

Thank you

**Comment by koppor** [comment]
JabRef 3.0 requires Java 8. Please update your Java to version 8 and try again. Think, following link is good: http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/#

**Comment by mastrogeppetto** [comment]
Sorry, I do not think I'll try that right now: I prefer to keep my box in sync with Ubuntu, and right now the recommended version of the jre is 7.0. I'll stick to that, and wait for next upgrade. After all, it looks like jabref works ok, when it starts :-).

Thank you!

**Comment by moorepants** [comment]
Did a launchpad ticket get opened for this? I can't run the apt-get install jabref on Ubuntu 15.10 either.

**Comment by koppor** [comment]
The solution currently is to use Ubuntu's snaps. They should be supported on Ubuntu 15.10: https://snapcraft.io/docs/core/install.

    sudo apt-get install snapd
    sudo snap install jabref --beta

More information is currently given at https://github.com/JabRef/jabref/issues/3121.
