### ISSUE TITLE
NullPointerException while installing Jabref v3_2 on Mac OS X EI Capitan 10.11.6

### ISSUE THREAD

**Issue by purvakulkarni7** [JabRef/jabref#1692]
While installing Jabref v3_2 on my Mac OS X EI Capitan 10.11.6, I get a NullPointerException with the following error log. 

```
Exception:

java.lang.NullPointerException
	at com.install4j.runtime.beans.actions.desktop.AddToDockAction.install(AddToDockAction.java:41)
	at com.install4j.runtime.installer.InstallerContextImpl$2.fetchValue(InstallerContextImpl.java:170)
	at com.install4j.runtime.installer.InstallerContextImpl$2.fetchValue(InstallerContextImpl.java:167)
	at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(FetchObjectAction.java:14)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionDirect(HelperCommunication.java:266)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(HelperCommunication.java:241)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionChecked(HelperCommunication.java:179)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.fetchObjectChecked(HelperCommunication.java:162)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionIntStatic(InstallerContextImpl.java:167)
	at com.install4j.runtime.installer.InstallerContextImpl.performActionInt(InstallerContextImpl.java:155)
	at com.install4j.runtime.installer.ContextImpl.performAction(ContextImpl.java:1058)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Controller.java:318)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Controller.java:170)
	at com.install4j.runtime.installer.controller.Controller.start(Controller.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:41)
	at com.install4j.runtime.installer.Installer.main(Installer.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:65)

System properties:

java.runtime.name=Java(TM) SE Runtime Environment
exe4j.moduleName=/Volumes/JabRef 1/JabRef Installer.app
sun.boot.library.path=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib
java.vm.version=25.91-b14
user.country.format=DE
i4j.jreBundle=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin
gopherProxySet=false
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
install4j.exeDir=/Volumes/JabRef 1/
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/Volumes/JabRef 1/JabRef Installer.app/Contents/Resources/app
java.runtime.version=1.8.0_91-b14
i4j.ownBundlePath=/Volumes/JabRef 1/JabRef Installer.app
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.endorsed.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/endorsed
os.arch=x86_64
java.io.tmpdir=/var/folders/hv/ydgb_6jn62l3xqqmbv8s19pr0000gp/T/
line.separator=

java.vm.specification.vendor=Oracle Corporation
os.name=Mac OS X
proxySet=false
sun.java2d.noddraw=true
sun.jnu.encoding=UTF-8
java.library.path=/Users/localadm/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
sun.awt.enableExtraMouseButtons=true
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=10.11.6
user.home=/Users/localadm
user.timezone=Europe/Berlin
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=/Volumes/JabRef 1/JabRef Installer.app/Contents/Resources/app/.install4j/i4jruntime.jar:/Volumes/JabRef 1/JabRef Installer.app/Contents/Resources/app/user.jar
user.name=localadm
java.vm.specification.version=1.8
sun.java.command=com.install4j.runtime.launcher.MacLauncher
java.home=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.lwawt.macosx.LWCToolkit
java.vm.info=mixed mode
java.version=1.8.0_91
java.ext.dirs=/Users/localadm/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
sun.boot.class.path=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/resources.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/rt.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/sunrsasign.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jsse.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jce.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/charsets.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jfr.jar:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/classes
install4j.appDir=/Volumes/JabRef 1/JabRef Installer.app/Contents/Resources/app/
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.font.fontmanager=sun.font.CFontManager
sun.io.unicode.encoding=UnicodeBig
sun.cpu.endian=little
install4j.systemLanguage=en
sun.cpu.isalist=
```

The installation still completes. When I open my database and try to fetch a new entry using Google Scholar, I can see the entry in the preview window, but when the go to the next window which generates the key, the window is blank. Here is a screenshot.

<img width="1680" alt="screen shot 2016-08-08 at 10 13 09" src="https://cloud.githubusercontent.com/assets/4562171/17473476/f73563ca-5d50-11e6-8d67-2de8cbf2bf76.png">

**Comment by mlep** [comment]
- Installation problems on Mac OSX should be solved in version 3.5 of JabRef. See http://www.jabref.org/blog/
- About Google Scholar, there is an issue with version 3.5 (and perhaps earlier versions). See: https://github.com/JabRef/jabref/issues/1639. This bug should be fixed in the development version, which you can find here: http://builds.jabref.org/master/
