### ISSUE TITLE
JabRef 2.11 beta4 starting problem in Windows XP or no more support for XP ?

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#194]
I tried to run JabRef 2.11 beta4 in my virtual Windows XP (clean install).
I found that the beta 4 cannot start, but 2.10 stable can.
here you have the message : 
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.11b4.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up func
tion 'GetCurrentProcessExplicitAppUserModelID': The specified procedure could no
t be found.
        at com.sun.jna.Function.<init>(Function.java:208)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
        at com.sun.jna.Native.register(Native.java:1509)
        at com.sun.jna.Native.register(Native.java:1396)
        at com.sun.jna.Native.register(Native.java:1156)
        at net.sf.jabref.JabRef.<clinit>(Unknown Source)
        at net.sf.jabref.JabRefMain.main(Unknown Source)
C:\Program Files\JabRef>
</pre>

the same message for 2.10 under command line:
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.10.jar
Found 2 plugin(s):
  - net.sf.jabref.core (jar:file:/C:/Program%20Files/JabRef/JabRef-2.10.jar!/plu
gins/net.sf.jabref.core/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/C:/Program%20Files/JabRef/JabRef-2.10.j
ar!/plugins/net.sf.jabref.export.misq/plugin.xml)
Opening: C:\Documents and Settings\PC\my.bib
</pre>
Is there something wrong, or just there is no more compability for XP ?
Thank you all.

<b>same error in 2.11 beta 3</b>
<pre>
C:\Program Files\JabRef>java -jar JabRef-2.11b3.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up func
tion 'GetCurrentProcessExplicitAppUserModelID': The specified procedure could no
t be found.
        at com.sun.jna.Function.<init>(Function.java:208)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
        at com.sun.jna.Native.register(Native.java:1509)
        at com.sun.jna.Native.register(Native.java:1396)
        at com.sun.jna.Native.register(Native.java:1156)
        at net.sf.jabref.JabRef.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.sf.jabref.JabRefMain.main(Unknown Source)
</pre>

**Comment by mlep** [comment]
I get the same error message under my xp virtual machine with version 2.11b4.
And launching with
java -jar JabRef-2.11b4.jar --prdef all -n
do not change the error message.

I can try on a real xp machine if necessary.

> java -version
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b20)
Java HotSpot(TM) Client VM (build 23.0-b21, mixed mode, sharing)

**Comment by stefan-kolb** [comment]
There is a native Windows function called via JNA to set the application user model id so that pinning JabRef to the Win7/8 taskbar works. This function is not available under Windows XP.
