### ISSUE TITLE
Regression: New entry in Biblatex mode freezes

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2001]
JabRef 3.7dev--snapshot--2016-09-16--master--fcec333
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. File > New Biblatex database
2. Bibtex > New entry > Article
3. Freeze

**Comment by koppor** [comment]
This calls for an integration test. Refs #1700. I tried with b1ec0e3c2cc24072cd0d0fbe6d233dbf8011c12d and English UI and I can confirm this issue.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at net.sf.jabref.gui.EntryTypeDialog.stopFetching(EntryTypeDialog.java:262)
        at net.sf.jabref.gui.EntryTypeDialog.actionPerformed(EntryTypeDialog.java:272)
```

I think, it works in JabRef 3.6, thus we do not need a CHANGELOG entry for it.
