### ISSUE TITLE
Can't fetch DOI information

### ISSUE THREAD

**Issue by devster31** [JabRef/jabref#2052]
JabRef version 3.6

Steps to reproduce:

1. Choose DOI to Bibtex in the web search interface
2. Insert the DOI
3. Press Fetch

I'm using JabRef from a closed network with a firewall, but I can easily access dx.doi.org from a web browser and I have no problems with many other sites, however JabRef can't fetch the informations automatically. I'm launching JabRef JAR file using `java.exe` on a Windows machine. I tried both the 32-bit and 64-bit versions of Java.

```
10:39:58.027 [JabRef CachedThreadPool] WARN  net.sf.jabref.logic.net.URLDownload - Could not copy input
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_101]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_101]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:110) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:123) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DOItoBibTeX.getEntryFromDOI(DOItoBibTeX.java:53) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.DOItoBibTeXFetcher.processQuery(DOItoBibTeXFetcher.java:27) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:223) ~[JabRef_3.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
10:39:58.038 [JabRef CachedThreadPool] WARN  net.sf.jabref.logic.importer.fetcher.DOItoBibTeX - Communication problems
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_101]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_101]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:110) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:123) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DOItoBibTeX.getEntryFromDOI(DOItoBibTeX.java:53) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.DOItoBibTeXFetcher.processQuery(DOItoBibTeXFetcher.java:27) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:223) ~[JabRef_3.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
10:39:58.041 [JabRef CachedThreadPool] WARN  net.sf.jabref.logic.importer.fetcher.DOItoBibTeX - Communication problems
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_101]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_101]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_101]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_101]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:110) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:123) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DOItoBibTeX.getEntryFromDOI(DOItoBibTeX.java:53) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.DOItoBibTeXFetcher.processQuery(DOItoBibTeXFetcher.java:27) ~[JabRef_3.6.jar:?]
	at net.sf.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:223) ~[JabRef_3.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by koppor** [comment]
Could you try to set proxy preferences?

![grabbed_20160924-155228](https://cloud.githubusercontent.com/assets/1366654/18808907/44992104-826f-11e6-94a8-f161edb75981.png)

Maybe, also `java -Dhttp.proxyHost="hostname" -Dhttp.proxyPort="portnumber -jar JabRef.jar` could help.

**Comment by AEgit** [comment]
Just to make sure: Does this problem occur with any DOI or just with some? Because some DOIs also don't work for me (usually if the article has just been published the same day). Could you post any of the DOIs that don't work for you just to see, whether it is a general problem or not?

**Comment by devster31** [comment]
I will try to set proxy preferences if I can find them, but it doesn't seem to use them for the browser.
I did try a wide variety of DOIs, some were extremely recent, but still resolved from dx.doi.org and they all resolve from my home.
```
10.1126/science.353.6306.1354
10.1586/14760584.6.5.723
```
It's probably some connection configuration that I can't find that's preventing JabRef or Java itself from connecting to the resolvers.
I'll try with `--debug` and `--nogui --fetch:DOItoBibTeX:10.1586/14760584.6.5.723` and see if it changes anything.

**Comment by AEgit** [comment]
I've just tried both DOIs that you provided and I can resolve them from within Jabref, so yea, it has to be a problem with your connection.

**Comment by lenhard** [comment]
Any updates here @devster31 ? I seems like we can close this issue, because it is a connection problem on your side.

**Comment by devster31** [comment]
It was, thanks for the support.
