### ISSUE TITLE
Encoding problem in XMPUtilTest from gradle commandline in windows

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2143]
There seems to be some problem with the XMPUtil test which is related to encoding.
Running it from gradle commandline (bash) on Windows 7, it fails on the abstract.

It came recently, after  #2062, 
@mairdl  Could you take a look?
There must be somewhere a problem with DefaultCharset (windows native  vs UTF8 charset.

` comparing abstract expected:<Optional[The success of the Linux operating system has demonstrated the viability of an alternative form of software development ?`

` but was:<Optional[The success of the Linux operating                                                                                                                                                                                                system has demonstrated the viability of an alternative form of software develo                                                                                                                                                                                               pment � open source software � `

```
at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at net.sf.jabref.logic.xmp.XMPUtilTest.assertEqualsBibtexEntry(XMPUtilTe                                                                                                                                                                                               st.java:774)
        at net.sf.jabref.logic.xmp.XMPUtilTest.testCommandLineSeveral(XMPUtilTes                                                                                                                                                                                               t.java:1297)

```

**Comment by grimes2** [comment]
I can confirm. Here the original excerpt:
![failed](https://cloud.githubusercontent.com/assets/15456836/19220745/b9fc878a-8e34-11e6-8570-7f1189200dc4.png)

Th other test, that fail locally:
net.sf.jabref.logic.importer.fetcher.MathSciNetTest > searchByQueryFindsEntry FAILED
net.sf.jabref.logic.importer.fetcher.zbMATHTest > searchByQueryFindsEntry FAILED

**Comment by mairdl** [comment]
I will have a look into this matter.

**Comment by mairdl** [comment]
I am on Windows 8 and it's failing as well. On Ubuntu 15.10 tests work fine. So I can confirm it is Windows related.
This PR seems to be related: https://github.com/JabRef/jabref/pull/1597

**Comment by Siedlerchr** [comment]
Kinda. But the real reason is probably that there is somewhere a
Charset.DefaultCharset in the test/code vs a StandardCharsets.UTF-8
In #1844 I fixed it for the file-importer tests

2016-10-11 17:39 GMT+02:00 Daniel Mair <notifications@github.com>:

**Comment by Siedlerchr** [comment]
Note to me: copac importer also fails

**Comment by Siedlerchr** [comment]
Fixed by @koppor  in https://github.com/JabRef/jabref/commit/f664f4edfc4808729a4861530b43ce1979c6e51c
