### ISSUE TITLE
IndexOutOfBounds when dragging pdf to place after entry

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2171]
Reproducible in current master: https://github.com/JabRef/jabref/commit/3f61baeb4c22a2b3950d6a6bd5a684edd877ebd7
Steps to reproduce: 
1. Have a Database with 1 entry.
2. Move file to position after entry (see Screenshot)
3. Exception occurs.

As far as I can tell this is just a dev bug

![jabrefdraganddrop](https://cloud.githubusercontent.com/assets/320228/19420072/2edf0c08-93e4-11e6-93f0-b8f23b454b1a.png)

```
exception in thread "JabRef CachedThreadPool" java.lang.IndexOutOfBoundsException: Cannot get at -1 on list of size 1
    at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105)
    at net.sf.jabref.gui.maintable.MainTable.getEntryAt(MainTable.java:355)
    at net.sf.jabref.gui.externalfiles.DroppedFileHandler.linkPdfToEntry(DroppedFileHandler.java:173)
    at net.sf.jabref.pdfimport.PdfImporter.importPdfFilesInternal(PdfImporter.java:160)
    at net.sf.jabref.pdfimport.PdfImporter.importPdfFiles(PdfImporter.java:114)
    at net.sf.jabref.gui.groups.EntryTableTransferHandler.lambda$0(EntryTableTransferHandler.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

**Comment by koppor** [comment]
There must be something else happening. I stripped down complex.bib to one entry and it works. Also restart of JabRef does not help to reproduce the issue.

windows 10 10.0 amd64 
Java 1.8.0_102

**Comment by Siedlerchr** [comment]
I run it directly from Eclipse and I can reproduce it with different bib files and different pdf files.
You have to move the pdf to the whitespace after the entry.

**Comment by stefan-kolb** [comment]
@Siedlerchr Works for me with Jabref 3.7 and creates a new entry. Can you please check if this is still valid?

**Comment by Siedlerchr** [comment]
Seems to be fixed. Can no longer reproduce this in the current dev.
