### ISSUE TITLE
Clear Bibtexkey NullPointerException

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2177]
JabRef 3.7dev--snapshot--2016-10-18--master--8f7ae51
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. Entry editor > clear field bibtexkey
2. Save database
3. NullPointerException

```
[AWT-EventQueue-0] ERROR net.sf.jabref.gui.BasePanel - runCommand error: field value must not be null
java.lang.NullPointerException: field value must not be null
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_101]
	at net.sf.jabref.model.entry.BibEntry.setField(BibEntry.java:416) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.model.entry.BibEntry.setField(BibEntry.java:457) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.model.entry.BibEntry.setCiteKey(BibEntry.java:200) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.gui.entryeditor.EntryEditor$StoreFieldAction.actionPerformed(EntryEditor.java:1126) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.gui.entryeditor.EntryEditor.storeCurrentEdit(EntryEditor.java:704) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.gui.BasePanel.storeCurrentEdit(BasePanel.java:1780) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at net.sf.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:121) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at spin.Invocation.evaluate(Invocation.java:175) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) ~[JabRef-3.7dev--snapshot--2016-10-18--master--8f7ae51.jar:?]
```

> FindBugs reports: EntryEditor.java:1108 Nullcheck of newValue at line 1110 of value previously dereferenced in net.sf.jabref.gui.entryeditor.EntryEditor$StoreFieldAction.actionPerformed(ActionEvent) [Scary(9), High confidence]

**Comment by shitikanth** [comment]
Another related bug, which is more visible to the end user.

Steps to reproduce:
1. Open database
2. Edit some field for an entry
3. Open another entry and clear its bibtexkey
4. Save database
5. Quit JabRef (by pressing Ctrl-q or from the menu) and select discard changes when prompted


![JabRef waiting for save operation to finish](https://cloud.githubusercontent.com/assets/544054/19501176/61b5de02-9571-11e6-8adf-14efd6a59ae3.png)
