### ISSUE TITLE
Groups interface does not appear at startup

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2201]
JabRef current master.
1. Open JabRef
2. Open a database with groups
3. Toggle groups interface to have it shown
4. Close JabRef
5. Open JabRef

Groups interface is not shown, but an exception is printed to the console:

```
11:59:03.633 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: groups
java.lang.ClassNotFoundException: groups
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
    at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:169) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:215) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:126) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:98) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.openoffice.OpenOfficeSidePanel.<init>(OpenOfficeSidePanel.java:23) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.openoffice.OpenOfficePanel.<init>(OpenOfficePanel.java:136) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:721) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:614) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:546) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:103) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:66) ~[JabRef-dev-fat.jar:?]
    at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:136) ~[JabRef-dev-fat.jar:?]
    at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_101]
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_101]
    at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_101]
    at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_101]
    at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_101]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_101]
    at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_101]
    at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by matthiasgeiger** [comment]
Using IntelliJ to run master toggling works (but the toggled pane is not shown on next startup, which is a known issue - however, there is no exception for me).

Are you using a jar version or are you running from the source?

**Comment by Siedlerchr** [comment]
I get similar exceptions for the (whole?) sidepane when starting inside Eclipse

**Comment by Siedlerchr** [comment]
I just installed the latest master version from yesterday (2016-10-27) and on startup I got the following error in log:

```
21:46:56.162 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: Web search
java.lang.ClassNotFoundException: Web search
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_112]
	at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:169) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:215) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:126) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:98) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficeSidePanel.<init>(OpenOfficeSidePanel.java:23) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficePanel.<init>(OpenOfficePanel.java:136) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:720) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:613) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:545) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:103) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:66) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:123) ~[JabRef-3.7dev--snapshot--2016-10-27--master--58997cb.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_112]

```

**Comment by AEgit** [comment]
This might be a replicate of this issue (?):
https://github.com/JabRef/jabref/issues/1825

**Comment by stefan-kolb** [comment]
For me it looks like there is just no preference for any of the toggle views (web search, groups,...)

**Comment by jp5400** [comment]
The new JabRef version 3.8.1 can handle the medline web-page connection but need to be started with root privileges otherwise it gives ERROR SidePaneManager . This is not dependent on Java (Oracle vs openJDK) and I believe it might be related to secure internet connections with web databases
