### ISSUE TITLE
Astrophysics Data System Fetcher broken

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#2218]
It seems that our implementation of the Astrophysics Data System Fetcher is broken.

We are getting a 503 Service Unavailable error, although the service is well up and running. I can reproduce the error locally and also travis gets it, which breakes the master build. The URLs mentioned in the tests can be accessed when copying them into the browser and visiting the entry manually. Maybe this is some bot-detection defense on their side.

I turned of the failing tests in master with 573328c7bd12c93dd37109852e3ac3732f1d7598, so that we have a working master again. The commit can be reverted once we have a working fetcher again.

Here comes an excerpt of the travis build
```
net.sf.jabref.logic.importer.fetcher.AstrophysicsDataSystemTest > testPerformSearchByXiongSunEntry FAILED

    net.sf.jabref.logic.importer.FetcherException: An I/O exception occurred

        at net.sf.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:85)

        at net.sf.jabref.logic.importer.fetcher.AstrophysicsDataSystemTest.testPerformSearchByXiongSunEntry(AstrophysicsDataSystemTest.java:187)

        Caused by:

        java.io.IOException: Server returned HTTP response code: 503 for URL: http://adsabs.harvard.edu/doi/10.1109/TGRS.2006.890567?data_type=BIBTEXPLUS

            at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)

            at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)

            at java.net.URL.openStream(URL.java:1045)

            at net.sf.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:63)

            ... 1 more
```

**Comment by matthiasgeiger** [comment]
Potential quickfix: User Agent?

**Comment by lenhard** [comment]
Maybe. You can go ahead and try!

**Comment by matthiasgeiger** [comment]
Not from my smartphone :wink:
