### ISSUE TITLE
Exception on log output after startup

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#2252]
JabRef version JabRef 3.7-dev--snapshot--2016-11-08--master--fffad83
windows 10 10.0 amd64 
Java 1.8.0_112

Steps to reproduce:

1. start jabref
2. look at error console

```
13:41:44.199 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: C:\paper\references\references.bib
13:41:46.331 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.openoffice.StyleLoader - Cannot find external style file C:\projects\jabref\build\resources\main\resource\openoffice\default_authoryear.jstyle
java.io.FileNotFoundException: C:\projects\jabref\build\resources\main\resource\openoffice\default_authoryear.jstyle (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_112]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_112]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_112]
	at net.sf.jabref.logic.openoffice.OOBibStyle.reload(OOBibStyle.java:246) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.logic.openoffice.OOBibStyle.<init>(OOBibStyle.java:147) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.logic.openoffice.StyleLoader.loadExternalStyles(StyleLoader.java:87) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.logic.openoffice.StyleLoader.<init>(StyleLoader.java:44) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficePanel.<init>(OpenOfficePanel.java:133) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:712) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:605) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:537) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:103) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:66) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:123) ~[JabRef-3.7-dev--snapshot--2016-11-08--master--fffad83.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_112]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_112]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_112]
```

**Comment by grimes2** [comment]
I've encountered the same problem. The path points to the local clone. The problem was solved on my system, by running `gradlew check` locally. But I think, this exception should be caught nevertheless.

**Comment by matthiasgeiger** [comment]
Huh? 

Have you manually set a reference to this style file which now no longer exists?

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.

**Comment by simonharrer** [comment]
I did not execute it through gradle, but simply used the installer with the current master build at builds.jabref.org (the version is very recent, as I updated only a few hours ago. 

I cannot remember setting up a jstyle file anywhere... as I do not use the open office plugin at all..

**Comment by simonharrer** [comment]
Maybe this is just specific to my environment then. Hence, I close it and let you have more time for the important things. :)

**Comment by Siedlerchr** [comment]
Maybe some preferences thing? I have a similiar issue with another style I
once used for testing. I am sure this is somewhere an old preference record
beeing stored somewhere

2016-11-08 15:03 GMT+01:00 Simon Harrer <notifications@github.com>:

**Comment by grimes2** [comment]
The variable in Show preferences is set in my system to `c:\\Users\\me\\jabref\\build\\resources\\main\\resource\\openoffice\\default-authoryear.jstyle`
It is not set by me. I don't know the default path. This path point to my local jabref clone. I assume, that the path variable changed, while working with and compiling my local installation.
