### ISSUE TITLE
File linking with shared databases

### ISSUE THREAD

**Issue by har-wradim** [JabRef/jabref#2255]
JabRef 3.7-dev--snapshot--2016-11-04--master--949ca17
linux 3.13.0-100-generic i386 
Java 1.8.0_91

There are two problems with linking files to entries when working with shared databases (tested only on Postgres). Linking files copied manually to the target folder with the "Get fulltext" button doesn't function, neither does adding files with the "+" button.

Steps to reproduce:

1. Create a (local postgres) database
2. Populate it with JabRef
3. Add a dummy entry with a bibtexkey Test2016
4a. Copy a dummy file, say Test2016.pdf, to the file directory
5a. Click "Get fulltext". The dialogue with the progress bar appears and stays forever, no files get linked
4b. Click "+" next to "File"
5b. Choose the the same file. In the dialogues: "Open", "OK". The dialogues disappear, no files appear on list.

Remote-link based "Get fulltext" and "Download from URL" function smoothly. No problems appear when working with a bib database, although a seemingly harmless java.lang.StringIndexOutOfBoundsException pops up.

Exception appearing on 5a:

	Exception in thread "JabRef CachedThreadPool" java.lang.NullPointerException
		at java.io.File.<init>(File.java:277)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
		at net.sf.jabref.gui.externalfiles.AutoSetLinks$1.run(AutoSetLinks.java:101)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

Exception appearing on 5b:

	Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
		at java.io.File.<init>(File.java:277)
		at net.sf.jabref.gui.filelist.FileListEntryEditor.storeSettings(FileListEntryEditor.java:305)
		at net.sf.jabref.gui.filelist.FileListEntryEditor.lambda$new$0(FileListEntryEditor.java:108)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
		at java.awt.Component.processMouseEvent(Component.java:6535)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
		at java.awt.Component.processEvent(Component.java:6300)
		at java.awt.Container.processEvent(Container.java:2236)
		at java.awt.Component.dispatchEventImpl(Component.java:4891)
		at java.awt.Container.dispatchEventImpl(Container.java:2294)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
		at java.awt.Container.dispatchEventImpl(Container.java:2280)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
		at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
		at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
		at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
		at java.awt.Dialog.show(Dialog.java:1084)
		at java.awt.Component.show(Component.java:1673)
		at java.awt.Component.setVisible(Component.java:1625)
		at java.awt.Window.setVisible(Window.java:1014)
		at java.awt.Dialog.setVisible(Dialog.java:1005)
		at net.sf.jabref.gui.filelist.FileListEntryEditor.setVisible(FileListEntryEditor.java:271)
		at net.sf.jabref.gui.fieldeditors.FileListEditor.editListEntry(FileListEditor.java:410)
		at net.sf.jabref.gui.fieldeditors.FileListEditor.addEntry(FileListEditor.java:350)
		at net.sf.jabref.gui.fieldeditors.FileListEditor.addEntry(FileListEditor.java:362)
		at net.sf.jabref.gui.fieldeditors.FileListEditor.lambda$new$0(FileListEditor.java:106)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
		at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
		at java.awt.Component.processMouseEvent(Component.java:6535)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
		at java.awt.Component.processEvent(Component.java:6300)
		at java.awt.Container.processEvent(Container.java:2236)
		at java.awt.Component.dispatchEventImpl(Component.java:4891)
		at java.awt.Container.dispatchEventImpl(Container.java:2294)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
		at java.awt.Container.dispatchEventImpl(Container.java:2280)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by har-wradim** [comment]
In addition: it is impossible to change the type of an already linked file when editing in the "General" tab. The dialogue appears, but no changes are saved. Nevertheless, manually changing correcting the source in the "BibTeX source" works (it is also the only workaround for the two other bugs described above). Again, no problems of this kind appear to bib-based databases.

**Comment by har-wradim** [comment]
Correction: "get fulltext" does not work even if DOI and/or URL are provided as it gets stuck on "automatically setting file links". I believe this was OK one or two releases ago.

**Comment by har-wradim** [comment]
Fixed in 3.8
