### ISSUE TITLE
Cannot complete save of database with empty key(s)

### ISSUE THREAD

**Issue by kingwarrick** [JabRef/jabref#2285]
JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c
windows 10 10.0 amd64 
Java 1.8.0_102 

Steps to reproduce:

1. Open existing or create new database
2. Create or import entry without a key
3. Save or Save as

File is created, but JabRef freezes and will not close without being forced through Task Manager
See the following link, though it is for a 3.7 dev build:
http://discourse.jabref.org/t/jabref-cannot-complete-save-of-database-error-in-log/294

```
11:29:39.290 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.BasePanel - runCommand error: null
java.lang.UnsupportedOperationException: null
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source) ~[?:1.8.0_102]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:1.8.0_102]
	at java.nio.file.Files.getPosixFilePermissions(Unknown Source) ~[?:1.8.0_102]
	at net.sf.jabref.logic.exporter.FileSaveSession.commit(FileSaveSession.java:93) ~[JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c.jar:?]
	at net.sf.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:256) ~[JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c.jar:?]
	at net.sf.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:146) ~[JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at spin.Invocation.evaluate(Invocation.java:175) ~[JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) ~[JabRef-3.8-dev--snapshot--2016-11-18--master--4932a8c.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_102]
```

**Comment by Siedlerchr** [comment]
Thanks for your report, this might be a follow up error from  https://github.com/JabRef/jabref/pull/2281 
I will check it

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
