### ISSUE TITLE
ClassCastException for Ctrl-A when "General" tab is open

### ISSUE THREAD

**Issue by Nnidyu** [JabRef/jabref#2444]
JabRef version 3.8.1 on Fedora 25

Steps to reproduce:
1. Open the "General" tab in the edit entry view.
2. Press ctrl-a.
3. Nothing happens.
4. `ClassCastException` is visible in the console.

I am not sure what should happen in this case (with other tabs it selects the first entry), however current behavior is confusing and probably not correct.

```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
```

Exception thrown:
```
11:46:44.109 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ClassCastException: net.sf.jabref.gui.fieldeditors.EntryLinkListEditor cannot be cast to javax.swing.text.JTextComponent
	at net.sf.jabref.gui.autocompleter.AutoCompleteListener.keyTyped(AutoCompleteListener.java:271) ~[JabRef-3.8.1.jar:?]
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:240) ~[?:1.8.0_111]
	at java.awt.Component.processKeyEvent(Component.java:6488) ~[?:1.8.0_111]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832) ~[?:1.8.0_111]
	at java.awt.Component.processEvent(Component.java:6310) ~[?:1.8.0_111]
	at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_111]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) ~[?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) ~[?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) ~[?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) ~[?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_111]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_111]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_111]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_111]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_111]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at spin.off.AWTReflectDispatcherFactory$AWTReflectDispatcher.start(AWTReflectDispatcherFactory.java:76) [JabRef-3.8.1.jar:?]
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:114) [JabRef-3.8.1.jar:?]
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85) [JabRef-3.8.1.jar:?]
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102) [JabRef-3.8.1.jar:?]
	at com.sun.proxy.$Proxy33.run(Unknown Source) [?:?]
	at net.sf.jabref.gui.BasePanel.runCommand(BasePanel.java:1002) [JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.entryeditor.EntryEditor$SaveDatabaseAction.actionPerformed(EntryEditor.java:1379) [JabRef-3.8.1.jar:?]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) [?:1.8.0_111]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) [?:1.8.0_111]
	at javax.swing.JTable.processKeyBinding(JTable.java:5259) [?:1.8.0_111]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929) [?:1.8.0_111]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) [?:1.8.0_111]
	at java.awt.Component.processEvent(Component.java:6310) [?:1.8.0_111]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) [?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) [?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) [?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) [?:1.8.0_111]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) [?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_111]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_111]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_111]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_111]

```

**Comment by lenhard** [comment]
Thanks for the report! I pushed a quick fix that avoids the ClassCastException and a new version should be available at http://builds.jabref.org/master/ in a few minutes.

As for the behavior, this has been also mentioned here: https://github.com/JabRef/jabref/issues/2322

However, I can no longer reproduce the behavior you describe. Depending on the Emacs preferences, the cursor either jumps to the start of the text or marks it all (as desired) when a text field is selected, or in case of the General tab when no text field is selected it does nothing (as desired). 

Could you please try the new version in a few minutes and play around with the Emacs settings (Options -> Preferences -> Entry Editor -> Use Emacs key bindings) and report if the problem persists?

**Comment by Nnidyu** [comment]
Thanks, the exception is gone.

As for the expected behavior - Emacs options work ok, however I do not use them. Default behavior is also working correctly - when I have the editor closed, all of the entries are selected, and when it is open and in focus - the text in the first field is selected.

The unexpected behavior that lead me to discovering this exception was that when the editor is open and then you click on the entry list (so there is no focus on the editor), and press Ctrl-a, then the **first** entry is selected along the current one - but only if you are on the "Required fields" or "BibLaTex source" tab. On other tabs there is no possibility to "defocus" editor so Ctrl-a always selects the first field.

Now I also noticed that I cannot select multiple entries when I have the editor open on tabs other than "Required fields" or "BibLaTex source", so that is probably related.

**Comment by Siedlerchr** [comment]
You can close the editor always with the escape  key in when open

Am 02.01.2017 2:39 nachm. schrieb "Łukasz Faber" <notifications@github.com>:

Thanks, the exception is gone.

As for the expected behavior - Emacs options work ok, however I do not use
them. Default behavior is also working correctly - when I have the editor
closed, all of the entries are selected, and when it is open and in focus -
the text in the first field is selected.

The unexpected behavior that lead me to discovering this exception was that
when the editor is open and then you click on the entry list (so there is
no focus on the editor), and press Ctrl-a, then the *first* entry is
selected along the current one - but only if you are on the "Required
fields" or "BibLaTex source" tab. On other tabs there is no possibility to
"defocus" editor so Ctrl-a always selects the first field.

Now I also noticed that I cannot select multiple entries when I have the
editor open on tabs other than "Required fields" or "BibLaTex source", so
that is probably related.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2444#issuecomment-269973703>, or mute
the thread

**Comment by lenhard** [comment]
@Nnidyu Ah, thanks! The selection of an entry in the table was the missing ingredient! To sum up:
 1. Open entry editor on a tab other than required or source
 2. Select an entry in the main table 
 3. Press CTRL-A

In this case nothing happens, and I think the UI should behave identically for all tabs (i.e. either move to the first entry, or select all entries, or do nothing at all).

**Comment by stefan-kolb** [comment]
Can this be closed?!

**Comment by Nnidyu** [comment]
@stefan-kolb if this is a question for me, then yes, my original issue is resolved.
