### ISSUE TITLE
No Shutdown possible after external modification of file

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2449]
JabRef version at least 3.8 and `master`

Steps to reproduce:

1. Open a file
2. modify it externally
3. Accept changes
4. Try to close JabRef

```20:06:39.628 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is net.sf.jabref.logic.autosaveandbackup.BackupManager@5147902d registered?
	at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:111) ~[guava-20.0.jar:?]
	at com.google.common.eventbus.EventBus.unregister(EventBus.java:201) ~[guava-20.0.jar:?]
	at net.sf.jabref.model.metadata.MetaData.unregisterListener(MetaData.java:257) ~[main/:?]
	at net.sf.jabref.logic.autosaveandbackup.BackupManager.shutdown(BackupManager.java:149) ~[main/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_60]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_60]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[?:1.8.0_60]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_60]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_60]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_60]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_60]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_60]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_60]
	at net.sf.jabref.logic.autosaveandbackup.BackupManager.shutdown(BackupManager.java:85) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame.quit(JabRefFrame.java:859) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame$CloseAction.actionPerformed(JabRefFrame.java:1778) ~[main/:?]
	at net.sf.jabref.gui.JabRefFrame$2.windowClosing(JabRefFrame.java:604) ~[main/:?]
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349) ~[?:1.8.0_60]`

....

```

**Comment by rfgiusti** [comment]
Additional info: this only happens if you review the changes (regardless whether you mark them as accepted or not). If you cancel the review, nothing happens.

This bug can be work-arounded by closing the database before attempting to close JabRef (still raises an exception).

**Comment by matthiasgeiger** [comment]
also covered in #2486

as @lenhard is working on a fix I'll close this as a duplicate

**Comment by lenhard** [comment]
Blind me! Sorry for not discovering that this issue already exists!
