### ISSUE TITLE
ERROR SidePaneManager

### ISSUE THREAD

**Issue by jp5400** [JabRef/jabref#2478]
The new JabRef version 3.8.1 which can handle the secure Medline web-page connection requires root privileges otherwise it gives error. I use Mint 17 with Java-Oracle-8 or openJDK-8.

**Comment by matthiasgeiger** [comment]
Can you please post the error message shown in the error console here?

Thanks!

**Comment by jp5400** [comment]
21:48:57.232 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: Web search
java.lang.ClassNotFoundException: Web search
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficeSidePanel.<init>(OpenOfficeSidePanel.java:23) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficePanel.<init>(OpenOfficePanel.java:134) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:716) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:609) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:542) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-3.8.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
21:48:57.236 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: search
java.lang.ClassNotFoundException: search
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficeSidePanel.<init>(OpenOfficeSidePanel.java:23) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.openoffice.OpenOfficePanel.<init>(OpenOfficePanel.java:134) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initSidePane(JabRefFrame.java:716) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:609) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:542) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-3.8.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
21:48:57.317 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: Web search
java.lang.ClassNotFoundException: Web search
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.fillMenu(JabRefFrame.java:1220) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initLayout(JabRefFrame.java:890) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:611) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:542) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-3.8.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
21:48:57.318 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.SidePaneManager - Following side pane could not be found: search
java.lang.ClassNotFoundException: search
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at net.sf.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.fillMenu(JabRefFrame.java:1220) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.initLayout(JabRefFrame.java:890) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.init(JabRefFrame.java:611) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:542) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.openWindow(JabRefGUI.java:100) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[JabRef-3.8.1.jar:?]
	at net.sf.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-3.8.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]

**Comment by tobiasdiez** [comment]
This error message should just be an internal problem and (hopefully) does not have any negative consequences on any functionality.

**Comment by jp5400** [comment]
Thank you,
I confirm that so far besides showing the ERROR message it is working correctly. I noticed that when running as root JabRef could not connect to LibreOffice. 
jp

**Comment by Siedlerchr** [comment]
We still don't know why these Side Pane Manager errors happen (because they
happen to me on Windows, too)
Mabye it is some thing with storing the position of the windows and loading
them at startup.
However, as tobias already wrote, it does not have any negative impact


2017-01-22 22:26 GMT+01:00 jp5400 <notifications@github.com>:

**Comment by jp5400** [comment]
Thank you all,
jp

**Comment by tobiasdiez** [comment]
I think we should let this open because this error message is indeed irritating.

**Comment by jp5400** [comment]
Thank you for comments,
I would like to price the authors for 2 major point: using java (which means "zero installation"), frequent updating. My competency level do not allow me to solve this problem now. Strange that root level does not show ERROR and strange that libreoffice connection does not work (path problems?).
JP

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
