### ISSUE TITLE
Cannot edit dynamic group with regular expression activated

### ISSUE THREAD

**Issue by theagoliveira** [JabRef/jabref#2481]
**Description**: groups which have both options "_Dynamically group entries by searching a field for a keyword_" and "_regular expression_" checked cannot be edited after creation (edit screen doesn't appear).

**JabRef version 3.8.1 on Ubuntu 14.04**

**Steps to reproduce**:

1. Create new BibTeX/BibLaTeX database
2. Create a group
3. Check "_Dynamically group entries by searching a field for a keyword_" and "_regular expression_" and fill _Name_ and _Keyword_
4. Double click the group name or select "_Edit group_" in the context menu

**Bibliography file**:
```
% Encoding: UTF-8

@Comment{jabref-meta: databaseType:bibtex;}

@Comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:test1\;0\;;
1 ExplicitGroup:test2\;1\;;
1 ExplicitGroup:test3\;2\;;
1 KeywordGroup:test4\;0\;keywords\;test\;0\;0\;;
1 KeywordGroup:test5\;0\;keywords\;test\;0\;1\;;
1 KeywordGroup:test6\;1\;keywords\;test\;0\;0\;;
1 KeywordGroup:test7\;1\;keywords\;test\;0\;1\;;
1 KeywordGroup:test8\;2\;keywords\;test\;0\;0\;;
1 KeywordGroup:test9\;2\;keywords\;test\;0\;1\;;
1 SearchGroup:test10\;0\;test\;0\;0\;;
1 SearchGroup:test11\;0\;test\;0\;1\;;
1 SearchGroup:test12\;1\;test\;0\;0\;;
1 SearchGroup:test13\;1\;test\;0\;1\;;
1 SearchGroup:test14\;2\;test\;0\;0\;;
1 SearchGroup:test15\;2\;test\;0\;1\;;
}
```
_test5_, _test7_, and _test9_ cannot be edited.

**Console Log**:
```
18:01:48.822 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ClassCastException: net.sf.jabref.model.groups.RegexKeywordGroup cannot be cast to net.sf.jabref.model.groups.WordKeywordGroup
    at net.sf.jabref.gui.groups.GroupDialog.<init>(GroupDialog.java:317) ~[JabRef_3.8.1.jar:?]
    at net.sf.jabref.gui.groups.GroupSelector$EditGroupAction.actionPerformed(GroupSelector.java:790) ~[JabRef_3.8.1.jar:?]
    at net.sf.jabref.gui.groups.GroupSelector$3.mouseClicked(GroupSelector.java:413) ~[JabRef_3.8.1.jar:?]
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270) ~[?:1.8.0_66-internal]
    at java.awt.Component.processMouseEvent(Component.java:6538) ~[?:1.8.0_66-internal]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_66-internal]
    at java.awt.Component.processEvent(Component.java:6300) ~[?:1.8.0_66-internal]
    at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_66-internal]
    at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[?:1.8.0_66-internal]
    at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_66-internal]
    at java.awt.Component.dispatchEvent(Component.java:4713) ~[?:1.8.0_66-internal]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_66-internal]
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534) ~[?:1.8.0_66-internal]
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_66-internal]
    at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_66-internal]
    at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[?:1.8.0_66-internal]
    at java.awt.Component.dispatchEvent(Component.java:4713) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_66-internal]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66-internal]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_66-internal]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_66-internal]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66-internal]
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_66-internal]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_66-internal]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_66-internal]
```

**Comment by tobiasdiez** [comment]
Thanks for your very detailed and clear report. 
This should be fixed now in the latest development version. Could you please check the build from http://builds.jabref.org/master/ and report back if it still not working. Thanks!

**Comment by theagoliveira** [comment]
I tried to run `java -jar JabRef-3.8.2-dev--snapshot--2017-01-26--master--ed89bdae2.jar` and got `Error: Invalid or corrupt jarfile`

**Comment by tobiasdiez** [comment]
We had some problems with our build server. Should work now.
