### ISSUE TITLE
Import RIS from Elsevier does not get journal name

### ISSUE THREAD

**Issue by tagMacher** [JabRef/jabref#2506]
JabRef version 3.8.2 on Ubuntu 16.04

This problem is also observed for versions 3.7, 3.8, and 3.8.1.

Steps to reproduce:

1. Export RIS for any journal article from ScienceDirect.com. Save file on local hard-disk.
2. Drag-drop RIS file onto JabRef window. This opens up the import dialog, Click ok after ensuring 'keep' checkbox for the article entry is selected.
3. Check the created entry for journal name - it is seen to be blank.

The RIS file created by ScienceDirect has a JO entry for journal name - this used to be correctly downloaded earlier. The last correctly working version is 3.6. Sample RIS file from ScienceDirect is enclosed (as ZIP archive) - RIS file can be seen in any text editor. Log pasted below.

[sciencea49f51c3.ris.zip](https://github.com/JabRef/jabref/files/743866/sciencea49f51c3.ris.zip)

```
10:18:35.724 [JabRef CachedThreadPool] ERROR net.sf.jabref.logic.xmp.XMPUtil - XMP reading failed
java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1519) ~[JabRef-3.8.2.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parseHeader(PDFParser.java:372) ~[JabRef-3.8.2.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:186) ~[JabRef-3.8.2.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1235) ~[JabRef-3.8.2.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1202) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.loadWithAutomaticDecryption(XMPUtil.java:127) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.readXMP(XMPUtil.java:160) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1110) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1090) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fileformat.PdfXmpImporter.isRecognizedFormat(PdfXmpImporter.java:71) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:191) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.importer.ImportMenuItem$MyWorker.run(ImportMenuItem.java:115) ~[JabRef-3.8.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at spin.Invocation.evaluate(Invocation.java:175) ~[JabRef-3.8.2.jar:?]
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:120) ~[JabRef-3.8.2.jar:?]
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85) ~[JabRef-3.8.2.jar:?]
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102) ~[JabRef-3.8.2.jar:?]
	at com.sun.proxy.$Proxy32.run(Unknown Source) ~[?:?]
	at net.sf.jabref.gui.importer.ImportMenuItem.automatedImport(ImportMenuItem.java:74) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.groups.EntryTableTransferHandler.loadOrImportFiles(EntryTableTransferHandler.java:372) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.groups.EntryTableTransferHandler.lambda$handleDraggedFiles$0(EntryTableTransferHandler.java:315) ~[JabRef-3.8.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by koppor** [comment]
@tschechlovdev Could you have a look? - Refs https://github.com/JabRef/jabref/pull/2028
Maybe also @obraliar  - Refs https://github.com/JabRef/jabref/pull/817

**Comment by tschechlovdev** [comment]
I can confirm this issue. I'll handle this.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by tagMacher** [comment]
Works fine. Looking forward to release version of 4.0! Thanks.
