### ISSUE TITLE
File link: if wrong link (manual input), exception raised, and Browse and Open do not work anymore

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2511]
JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar 
Linux Mint LMDE Betsy
Oracle Java 8

Steps to reproduce:

1. Open an entry without a file link
2. In the entry editor, go to the tab General and click on ````+```` (field ````file````)
3. In the file browsing window, enter a name that does not exist in the proposed directory, such as ````dummy.pdf````
4. Click on ````Browse```` or ````Open````
==> Browse and Open buttons do not work, and an Error is displayed in console. 

```
16:56:16.598 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.FileDialog - java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Folder parameter must be a valid folder
16:56:16.600 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.sf.jabref.gui.filelist.FileListEntryEditor.lambda$new$4(FileListEntryEditor.java:351) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_66]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_66]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_66]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_66]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_66]
	at java.awt.Component.processMouseEvent(Component.java:6535) ~[?:1.8.0_66]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_66]
	at java.awt.Component.processEvent(Component.java:6300) ~[?:1.8.0_66]
	at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) ~[?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[?:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[?:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) ~[?:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_66]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) ~[?:1.8.0_66]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) ~[?:1.8.0_66]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) ~[?:1.8.0_66]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) ~[?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) ~[?:1.8.0_66]
	at java.awt.Dialog.show(Dialog.java:1084) ~[?:1.8.0_66]
	at java.awt.Component.show(Component.java:1673) ~[?:1.8.0_66]
	at java.awt.Component.setVisible(Component.java:1625) ~[?:1.8.0_66]
	at java.awt.Window.setVisible(Window.java:1014) ~[?:1.8.0_66]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:1.8.0_66]
	at net.sf.jabref.gui.filelist.FileListEntryEditor.setVisible(FileListEntryEditor.java:272) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at net.sf.jabref.gui.fieldeditors.FileListEditor.editListEntry(FileListEditor.java:407) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at net.sf.jabref.gui.fieldeditors.FileListEditor.addEntry(FileListEditor.java:347) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at net.sf.jabref.gui.fieldeditors.FileListEditor.addEntry(FileListEditor.java:359) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at net.sf.jabref.gui.fieldeditors.FileListEditor.lambda$new$0(FileListEditor.java:103) ~[JabRef-4.0.0-dev--snapshot--2017-02-01--master--5793cea45.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_66]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_66]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_66]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) [?:1.8.0_66]
	at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_66]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_66]
	at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_66]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_66]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_66]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_66]

```

**Comment by Siedlerchr** [comment]
I encountered a similar problem yesterday with the File Dialogs, but it only didn't work when I started it in Eclipse. That is probably a problem with the Swing dialogs on top of the javafx stuff.  

A quick googling turned up this, seems like they had the same problem. Maybe this helps:
https://github.com/MovingBlocks/TerasologyLauncher/pull/249/files
@tobiasdiez

**Comment by Siedlerchr** [comment]
Please try again with the latest master version, I can no longer reproduce this issue

**Comment by mlep** [comment]
Seems solved to me too!
