### ISSUE TITLE
Cannot import from Medline

### ISSUE THREAD

**Issue by boxconnect** [JabRef/jabref#2565]
JabRef version 3.3 (via homebrew)

I wanted to import an article from Medline via their ID (ie 11456302)
The error `Leerstellen erforderlich zwischen publicId und systemId.` (spaces required between publicid and systemid) keeps coming up. Java 8.

```
org.xml.sax.SAXParseException: Leerstellen erforderlich zwischen publicId und systemId.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanExternalID(XMLScanner.java:1072) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.scanDoctypeDecl(XMLDocumentScannerImpl.java:642) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:924) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_121]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327) ~[?:1.8.0_121]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195) ~[?:1.8.0_121]
	at net.sf.jabref.importer.fileformat.MedlineImporter.importEntries(MedlineImporter.java:122) ~[JabRef-3.3.jar:?]
	at net.sf.jabref.importer.fileformat.MedlineImporter.fetchMedline(MedlineImporter.java:93) ~[JabRef-3.3.jar:?]
	at net.sf.jabref.importer.fetcher.MedlineFetcher.processQuery(MedlineFetcher.java:153) ~[JabRef-3.3.jar:?]
	at net.sf.jabref.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:245) ~[JabRef-3.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by boxconnect** [comment]
Updated to 3.8.2 and it works flawlessly.
