### ISSUE TITLE
FXDialogService does not work inside Swing

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2566]
Inside a Swing Action:    
```
 DialogService service = new FXDialogService();
            service.showConfirmationDialogAndWait("test", "test2");
```

When I copy the method `runInJavaFXThread` from the FileDialog class and wrap the showing inside the 
`runInJavaFXThread(() ->      service.showConfirmationDialogAndWait("test", "test2"))); `
it works

results in  

```
12:15:06.236 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]
	at javafx.stage.Stage.<init>(Stage.java:241) ~[jfxrt.jar:?]
	at javafx.stage.Stage.<init>(Stage.java:227) ~[jfxrt.jar:?]
	at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52) ~[jfxrt.jar:?]
	at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52) ~[jfxrt.jar:?]
	at javafx.scene.control.Dialog.<init>(Dialog.java:263) ~[jfxrt.jar:?]
	at javafx.scene.control.Alert.<init>(Alert.java:245) ~[jfxrt.jar:?]
	at javafx.scene.control.Alert.<init>(Alert.java:223) ~[jfxrt.jar:?]
	at org.jabref.gui.FXDialog.<init>(FXDialog.java:85) ~[bin/:?]
	at org.jabref.gui.FXDialog.<init>(FXDialog.java:75) ~[bin/:?]
	at org.jabref.gui.FXDialogService.createDialog(FXDialogService.java:30) ~[bin/:?]
	at org.jabref.gui.FXDialogService.showConfirmationDialogAndWait(FXDialogService.java:69) ~[bin/:?]
	at org.jabref.gui.externalfiles.RenameFileAction.actionPerformed(RenameFileAction.java:90) ~[bin/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[?:1.8.0_121]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) ~[?:1.8.0_121]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) ~[?:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[?:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
```

**Comment by tobiasdiez** [comment]
This is expected behavior. Every JavaFX component that you invoke from Swing has to be run on the JavaFX thread.

**Comment by Siedlerchr** [comment]
Yeah. I know that, but I thought the FXDialogService already takes care of that, because it is stated in the javadoc comment: 
 * This class provides methods to create default JavaFX dialogs which will also work on top of Swing

Well, it would be nice then to let the DialogService automatically take care of this like in the FileDialog.

**Comment by stefan-kolb** [comment]
@Siedlerchr @tobiasdiez Is this really an issue or more a clarification thread?

**Comment by Siedlerchr** [comment]
As this class/methods are useful to be used inside/on top of/instead of normal swing dialogs , I think we should add a way to run all methods in the javafx thread as done with the FileDialog class already:
There is a helper method. But I had problems getting it to work in this class as I tried it.

**Comment by tobiasdiez** [comment]
I don't see where the problem is in using code like `Platform.invoke ( new FXDialogService().show.... )`. This should work. I don't want to modify the FXDialogService class to always use `Platform.invoke` internally. What we could do is to create a SwingDialogService class that acts as a proxy to FXDialogService. But I'm not sure if this is worth the effort.

By the way "also work on top of Swing" means that the dialogs generated by this class are also in front of Swing dialogs.

**Comment by Siedlerchr** [comment]
After discussion I created a helper method `runInJavaFXThread` in `DefaultTaskExecutor` in the gui.util packace
