### ISSUE TITLE
PDF importation freezes when filename contains a curly bracket

### ISSUE THREAD

**Issue by programagor** [JabRef/jabref#2577]
When I try to import PDFs via the Quality -> Find unlinked files, the process freezes when a PDF containing a curly bracket ( "{" or "}" ) in its filename is encountered.

JabRef version 4.0.0-dev (snapshot 2017-02-18) on Win 10 (1607)

Steps to reproduce:

1. Open Quality -> Find unlinked files
2. Select a folder containing at least one PDF with a curly bracket in its name
3. Scan directory
4. Make sure the offending file is selected
5. Apply

After the last step, the process goes through all valid files (showing "Importing into database... M of N"), but freezes the whole JabRef once it gets to the offending file.

**Comment by lenhard** [comment]
Probably related to #2439. It seems like our pdf-handling code has problems with curly braces.

**Comment by bernhard-kleine** [comment]
Not confirmed! I am working with 3.8.2 and snapshots JabRef 4.0.0-dev--snapshot--2017-02-24--master--83219486e
and others before I didnot have issues with braces.

**Comment by Siedlerchr** [comment]
I could reproduce the bug:
```
21:52:04.655 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.IndexOutOfBoundsException: Cannot get at -1 on list of size 2
	at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105) ~[glazedlists_java15-1.9.1.jar:1.9.1]
	at org.jabref.gui.maintable.MainTable.getEntryAt(MainTable.java:347) ~[bin/:?]
	at org.jabref.gui.externalfiles.DroppedFileHandler.linkPdfToEntry(DroppedFileHandler.java:172) ~[bin/:?]
	at org.jabref.pdfimport.PdfImporter.importPdfFilesInternal(PdfImporter.java:159) ~[bin/:?]
	at org.jabref.pdfimport.PdfImporter.importPdfFiles(PdfImporter.java:113) ~[bin/:?]
	at org.jabref.gui.importer.EntryFromPDFCreator.createBibtexEntry(EntryFromPDFCreator.java:64) ~[bin/:?]
	at org.jabref.gui.importer.EntryFromFileCreator.createEntry(EntryFromFileCreator.java:90) ~[bin/:?]
	at org.jabref.gui.importer.EntryFromFileCreatorManager.addEntriesFromFiles(EntryFromFileCreatorManager.java:131) ~[bin/:?]
	at org.jabref.gui.FindUnlinkedFilesDialog.lambda$2(FindUnlinkedFilesDialog.java:526) ~[bin/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

**Comment by Siedlerchr** [comment]
@programagor The issue is not related to the filename, but happens when you select a pdf and don't create an entry from it (just select nothing), then it throws an exception which breaks JabRef
