### ISSUE TITLE
IndexOutOfBoundsException in MainTable  switching to group with fewer entries

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2655]
Have some groups
Have some entries

Assign same entries to several groups 
e.g. Group 2 contains 4 entries
Group 1 only contains 1 of the entries 
Group 3 contains zero entries 

Steps to reproduce:
1. Select  (last) entry in Group 2 
2. Switch to Group 3 with zero entries

I have provided my test sample bib file:
[test_groupsException.bib.txt](https://github.com/JabRef/jabref/files/849071/test_groupsException.bib.txt)

Exception occurs:
```
22:25:34.355 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IndexOutOfBoundsException: Cannot get at 1 on list of size 0
	at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105) ~[glazedlists_java15-1.9.1.jar:1.9.1]
	at org.jabref.gui.maintable.MainTable.getEntryAt(MainTable.java:344) ~[bin/:?]
	at org.jabref.gui.maintable.MainTable.getCellStatus(MainTable.java:477) ~[bin/:?]
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:288) ~[bin/:?]
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2113) ~[?:1.8.0_121]
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016) ~[?:1.8.0_121]
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812) ~[?:1.8.0_121]
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[?:1.8.0_121]
	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[?:1.8.0_121]
	at javax.swing.JComponent.paint(JComponent.java:1056) ~[?:1.8.0_121]
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[?:1.8.0_121]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) ~[?:1.8.0_121]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) ~[?:1.8.0_121]
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[?:1.8.0_121]
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[?:1.8.0_121]
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[?:1.8.0_121]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[?:1.8.0_121]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) ~[?:1.8.0_121]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) ~[?:1.8.0_121]
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) ~[?:1.8.0_121]
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[?:1.8.0_121]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) ~[?:1.8.0_121]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]

```

**Comment by tobiasdiez** [comment]
I can't reproduce this bug anymore with the most recent development version.
