### ISSUE TITLE
Error console does not update on new events

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2667]
The dialog is not modal, but does not update itself when new events arrive, i.e., needs to be closed and opened again to see new events.

**Comment by stefan-kolb** [comment]
Hm, maybe I'm not getting this right. Some events are actually updated on the fly. Which kinds of events should be logged in our console right now?

**Comment by stefan-kolb** [comment]
It looks like sometimes it is updating and sometimes not...

**Comment by stefan-kolb** [comment]
probably caused by this one?:
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.getAvailableCell(VirtualFlow.java:2037) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1245) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1194) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:231) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.ListViewSkin.updateRowCount(ListViewSkin.java:247) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualContainerBase.lambda$new$62(VirtualContainerBase.java:54) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.control.ControlUtils.lambda$scrollToIndex$607(ControlUtils.java:46) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.Utils.executeOnceWhenPropertyIsNonNull(Utils.java:778) ~[jfxrt.jar:?]
	at javafx.scene.control.ControlUtils.scrollToIndex(ControlUtils.java:45) ~[jfxrt.jar:?]
	at javafx.scene.control.ListView.scrollTo(ListView.java:898) ~[jfxrt.jar:?]
	at org.jabref.gui.errorconsole.ErrorConsoleController.lambda$initialize$0(ErrorConsoleController.java:52) ~[main/:?]
	at com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(ListExpressionHelper.java:593) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(ListExpressionHelper.java:571) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:109) ~[jfxrt.jar:?]
	at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:200) ~[jfxrt.jar:?]
	at javafx.beans.property.ReadOnlyListWrapper.fireValueChangedEvent(ReadOnlyListWrapper.java:115) ~[jfxrt.jar:?]
	at javafx.beans.property.ListPropertyBase.lambda$new$29(ListPropertyBase.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) ~[jfxrt.jar:?]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) ~[jfxrt.jar:?]
	at org.jabref.gui.MappedList.sourceChanged(MappedList.java:49) ~[main/:?]
	at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106) ~[jfxrt.jar:?]
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) ~[jfxrt.jar:?]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) ~[jfxrt.jar:?]
	at javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$52(FXCollections.java:929) ~[jfxrt.jar:?]
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88) [jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164) [jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) [jfxrt.jar:?]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) [jfxrt.jar:?]
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482) [jfxrt.jar:?]
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541) [jfxrt.jar:?]
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205) [jfxrt.jar:?]
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155) [jfxrt.jar:?]
	at java.util.AbstractList.add(AbstractList.java:108) [?:1.8.0_121]
	at org.jabref.logic.logging.LogMessages.add(LogMessages.java:34) [main/:?]
	at org.jabref.logic.logging.GuiAppender.append(GuiAppender.java:44) [main/:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) [log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1971) [log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1829) [log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.jcl.Log4jLog.error(Log4jLog.java:116) [log4j-jcl-2.8.1.jar:2.8.1]
	at org.jabref.gui.BasePanel.runCommand(BasePanel.java:998) [main/:?]
	at org.jabref.gui.JabRefFrame$GeneralAction.actionPerformed(JabRefFrame.java:1999) [main/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [?:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356) [?:1.8.0_121]
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802) [?:1.8.0_121]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) [?:1.8.0_121]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) [?:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699) [?:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) [?:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) [?:1.8.0_121]
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677) [?:1.8.0_121]
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307) [?:1.8.0_121]
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293) [?:1.8.0_121]
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974) [?:1.8.0_121]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966) [?:1.8.0_121]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) [?:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6310) [?:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_121]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) [?:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) [?:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) [?:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) [?:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) [?:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) [?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
```

**Comment by tobiasdiez** [comment]
https://github.com/JabRef/jabref/commit/9b28d3662c142684baaad49d13a315e65e57de09 should have fixed the exception. Can you please test if the error console is updated properly now. Thanks.

**Comment by stefan-kolb** [comment]
Looks like it works 👍

**Comment by lynyus** [comment]
Hi @tobiasdiez, commit https://github.com/JabRef/jabref/commit/9b28d3662c142684baaad49d13a315e65e57de09 made the entire GUI unusable for me. Any click in the entry editor or the menu items froze the program and it had to be killed (not only terminated via the window manager).

I'm using Manjaro Linux with cinnamon and 
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
java-openjfx 8.u121-1
```

So I have reverted it. Has anybody an idea or can confirm the behavior?

**Comment by matthiasgeiger** [comment]
Another related problem: 
If an instance of a `JabRefException` is caught, the error console tries to call `getLocalizedMessage()` - this might result in a warning - which is also shown in the console. 
This is basically no problem, but when I start scrolling in the FX error console the method seems to get recalled, and recalled, and recalled... which creates even more warnings...

**Comment by matthiasgeiger** [comment]
Regarding the actual problem... 

Instead of @tobiasdiez proposal:

```
    public static void runInJavaFXThread(Runnable runnable) {
        runInJavaFXThread(() -> {
            runnable.run();
            return null;
        });
    }
```
A simple 
```
    public static void runInJavaFXThread(Runnable runnable) {
        Platform.runLater(runnable);
    }
```
should be sufficient, or do I miss something?!
