### ISSUE TITLE
Changing fieldname in source tab throws Exception

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2713]
bib entry:

```
@InProceedings{DBLP:conf/zeus/KoppLUW11,
  author    = {Oliver Kopp and Frank Leymann and Tobias Unger and Sebastian Wagner},
  title     = {Towards The Essential Flow Model},
  booktitle = {3rd Central-European Workshop on Services and their Composition, Services und ihre Komposition, {ZEUS} 2011, Karlsruhe, Germany, February 21-22, 2011. Proceedings},
  year      = {2011},
  editor    = {Daniel Eichhorn and Agnes Koschmider and Huayu Zhang},
  volume    = {705},
  series    = {{CEUR} Workshop Proceedings},
  pages     = {26--33},
  publisher = {CEUR-WS.org},
  bibsource = {dblp computer science bibliography, http://dblp.org},
  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/zeus/KoppLUW11},
  timestamp = {Mon, 30 May 2016 16:43:12 +0200},
  url       = {http://ceur-ws.org/Vol-705/paper4.pdf},
}
```

If I change `pages` to `_pages`, that field is **mostly** completely removed.

```
Unable to parse stored date for field 'timestamp' with current settings. Clear button in calender popup will not work.

runCommand error: null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at org.jabref.gui.entryeditor.EntryEditor.storeSource(EntryEditor.java:862)
	at org.jabref.gui.entryeditor.EntryEditor.access$3300(EntryEditor.java:128)
	at org.jabref.gui.entryeditor.EntryEditor$StoreFieldAction.actionPerformed(EntryEditor.java:1366)
	at org.jabref.gui.entryeditor.EntryEditor.storeCurrentEdit(EntryEditor.java:796)
	at org.jabref.gui.BasePanel.storeCurrentEdit(BasePanel.java:1611)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:130)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)
```

When testing it with a "minimal" example, JabRef saves the file without issues:

```
@InProceedings{DBLP:conf/zeus/KoppLUW11,
  title     = {Towards The Essential Flow Model},
  timestamp = {Mon, 30 May 2016 16:43:12 +0200},
  url       = {http://ceur-ws.org/Vol-705/paper4.pdf},
}
```

**Comment by matthiasgeiger** [comment]
This is not caused by the timestamp as the same `ConcurrentModificationException` also occurs if no timestamp is present.

The exception is thrown if a fieldname is changed in the source tab.

**Comment by stefan-kolb** [comment]
How should we reproduce this? For me changing field names work as expected.

**Comment by matthiasgeiger** [comment]
Hmmmm... I can reproduce it... but only if the entry is just pasted using CTRL-V

So the steps to reproduce are:
1. copy a bibtex string representation to the clipboard
2. paste it directly in the JabRef main table
3. modify the field name in the source tab of the entry editor
4. switch tab

**Comment by lenhard** [comment]
I've just tested this on recent master with the description from @matthiasgeiger It seems to work now, no fields are deleted.

Just to be on the safe side: @koppor Can you test this and close it if it works?

**Comment by koppor** [comment]
Yes, works.
