### ISSUE TITLE
Groups issues on JabRef 4 OSX

### ISSUE THREAD

**Issue by juanmduran** [JabRef/jabref#2722]
Hi, I'm having issues with adding, deleting, etc groups JabRef 4 on OSX. Basically, it stops working.

I've also experience problems with groups on earlier versions (3.8.2), such as references are not added to a group, or JabRef mess them up in different groups. 

Anyone knows about these issues? I really need my groups, its a great feature.

Thanks!

**Comment by tobiasdiez** [comment]
So it just stops working without error message? Do you see some errors reported in the `Help -> Event log`?

@chochreiner can you reproduce these errors on OSX?

**Comment by boceckts** [comment]
I can confirm this very strange behaviour. After clicking on the "+" sign in the groups tab JabRef freezes without an exception. After I waited more than ten minutes it still didn't respond and only showed the spinning wheel for my mouse pointer.

When executing the jar in a terminal I could see the following log statements.

![screen shot 2017-04-08 at 14 23 09](https://cloud.githubusercontent.com/assets/15340757/24828943/8cae4d0a-1c68-11e7-8d66-65ce6909744e.png)

Other JavaFX dialogs can be used normally. Also there was no message/exception in the event log present when I opened the dialog before clicking the "+" in the groups tab.

**Comment by tobiasdiez** [comment]
That is indeed very strange. @boceckts may I ask you to investigate this problem further as I have no Mac to debug it myself? Does JabRef still frezzes with other group related changes (e.g. delete of a group?). Is the dropdown menu the reason? The group edit dialog?

**Comment by boceckts** [comment]
I will have a look into it.

**Comment by juanmduran** [comment]
Thanks guys, I really appreciate the quick response. 

Ok, so I can't see anything on the log file. Jabref freezes, I kill it, and then the log is empty (other than showing which .bib file I recently open). 

I've tried to run it on a terminal. Here's the output

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
OSX 10.12.4


2017-04-08 16:50:29,944 JavaFX Application Thread ERROR Appenders contains an invalid element or attribute "ApplicationInsightsAppender"
2017-04-08 16:50:29,953 JavaFX Application Thread ERROR Unable to locate appender "applicationInsightsAppender" for logger config "root"
16:50:31.277 [AWT-EventQueue-0] WARN  org.jabref.logic.remote.server.RemoteListenerServerLifecycle - Port is blocked
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[?:1.8.0_60]
	at java.net.ServerSocket.bind(ServerSocket.java:375) ~[?:1.8.0_60]
	at java.net.ServerSocket.<init>(ServerSocket.java:237) ~[?:1.8.0_60]
	at org.jabref.logic.remote.server.RemoteListenerServer.<init>(RemoteListenerServer.java:26) ~[JabRef-4.0.0-dev--snapshot--2017-04-08--master--65dccbf8a.jar:?]
	at org.jabref.logic.remote.server.RemoteListenerServerThread.<init>(RemoteListenerServerThread.java:18) ~[JabRef-4.0.0-dev--snapshot--2017-04-08--master--65dccbf8a.jar:?]
	at org.jabref.logic.remote.server.RemoteListenerServerLifecycle.open(RemoteListenerServerLifecycle.java:43) ~[JabRef-4.0.0-dev--snapshot--2017-04-08--master--65dccbf8a.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:110) ~[JabRef-4.0.0-dev--snapshot--2017-04-08--master--65dccbf8a.jar:?]
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:53) ~[JabRef-4.0.0-dev--snapshot--2017-04-08--master--65dccbf8a.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_60]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_60]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_60]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_60]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_60]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_60]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_60]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_60]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_60]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_60]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_60]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_60]
16:50:31.286 [AWT-EventQueue-0] INFO  org.jabref.JabRefMain - Arguments passed on to running JabRef instance. Shutting down.

**Comment by juanmduran** [comment]
Hi again, dunno if this is useful, but I've been playing around with older versions and this is what I found out:

3.7, 3.8 and up: static groups can be created but references dragged and drop (or "Add to group") work ONLY in the following case: first, save one reference, immediately after save a second reference. Only the first reference is saved in the selected group. It does NOT work by dragging (or saving) one reference at the time (and then clicking on the group), or dragging (or saving) two or more references. I've also noticed that some of the references disappear after adding new ones.

Thanks

**Comment by boceckts** [comment]
Thank you for your great support in this issue @juanmduran. From the console log I can see that you had another instance of JabRef running, which is why it "won't start". Other than that there is unfortunately no log statement regarding the groups issue.

I have looked into the code and it seems that the old Swing Dialog is still used to create/edit the groups however the displayed TreeView component is now in JavaFX. This means we have to be very careful to execute the Swing stuff in the EDT and to execute the JavaFX stuff on the JavaFX Application Thread.

Wrapping the call inside of all the methods which are called on the Java FX Application Thread and want to open a Swing dialog, makes the group actions work again.

@tobiasdiez 
However it still behaved strange. Adding and removing group/subgroup seemed to work as expected, but editing a group still showed me the old name in the tree view, adding and removing selected entries also didn't update the view...

The strange thing is that it works on Windows(?) but not on Mac OS X?...So much for the Platform independency 😁

**Comment by tobiasdiez** [comment]
Mhh strange. There appears to be some issues on MacOS when JavaXF and Swing need to communicate. But good that you could isolate the underlying issue and fix it. I think the update problems are still inconvenient but not as worse as a not responding JabRef. Can you please open a PR with the fix so that it can be included in the beta release at the weekend. Thanks.

**Comment by boceckts** [comment]
I just found out that the method `removeSubgroups` isn't even getting called, seems like a copy paste error when assigning the actions to the menu items. I will create a pull request later and have a look if the rest of the groups actions are working as expected or if I can fix it.

**Comment by juanmduran** [comment]
@boceckts, sorry you're right. Here's my output running the .jar

The last two lines show up when I click "+"

Thanks again to all of you.

dyn-mit-239:Downloads Juan$ java -jar JabRef-4.0.0-dev--snapshot--2017-04-11--master--d206fb8b1.jar 
2017-04-11 16:13:19,375 JavaFX Application Thread ERROR Appenders contains an invalid element or attribute "ApplicationInsightsAppender"
2017-04-11 16:13:19,385 JavaFX Application Thread ERROR Unable to locate appender "applicationInsightsAppender" for logger config "root"
AI: INFO 11-04-2017 16:13, 17: Configuration file has been successfully found as resource
AI: INFO 11-04-2017 16:13, 17: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 11-04-2017 16:13, 17: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: TRACE 11-04-2017 16:13, 17: Using Http Client version 4.3+
AI: INFO 11-04-2017 16:13, 17: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: INFO 11-04-2017 16:13, 17: Configuration file has been successfully found as resource
AI: INFO 11-04-2017 16:13, 17: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 11-04-2017 16:13, 17: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: INFO 11-04-2017 16:13, 17: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 11-04-2017 16:13, 17: InProcessTelemetryChannel sending telemetry
AI: ERROR 11-04-2017 16:13, 31: Failed to send, Bad request  : {"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Unknown domain type 'Microsoft.ApplicationInsights.SessionStateData'"}]}
16:13:25.800 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Users/Juan/Dropbox/00_PAPERS/BibTex/biblioZotero.bib
File: grouptree.fxml not found, attempting with camel case
Apr 11, 2017 4:13:27 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
File: grouptree.css not found, attempting with camel case
AI: TRACE 11-04-2017 16:13, 17: InProcessTelemetryChannel sending telemetry
AI: TRACE 11-04-2017 16:13, 12: InProcessTelemetryChannel sending telemetry

**Comment by boceckts** [comment]
No worries and thank you for your great collaboration.
The changes I made in #2727 should do the trick.

**Comment by juanmduran** [comment]
Works perfect. Thank you guys!

**Comment by juanmduran** [comment]
Hi guys, sorry to be a pain again, but is it possible that fixing groups messed up the web search? I keep getting an error message. Here's the terminal output.

Thanks

dyn-mit-239:Downloads Juan$ java -jar JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar 
2017-04-13 10:45:52,661 JavaFX Application Thread ERROR Appenders contains an invalid element or attribute "ApplicationInsightsAppender"
2017-04-13 10:45:52,671 JavaFX Application Thread ERROR Unable to locate appender "applicationInsightsAppender" for logger config "root"
AI: INFO 13-04-2017 10:45, 17: Configuration file has been successfully found as resource
AI: INFO 13-04-2017 10:45, 17: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 13-04-2017 10:45, 17: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: TRACE 13-04-2017 10:45, 17: Using Http Client version 4.3+
AI: INFO 13-04-2017 10:45, 17: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: INFO 13-04-2017 10:45, 17: Configuration file has been successfully found as resource
AI: INFO 13-04-2017 10:45, 17: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 13-04-2017 10:45, 17: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: INFO 13-04-2017 10:45, 17: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 13-04-2017 10:45, 17: InProcessTelemetryChannel sending telemetry
10:45:55.839 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Users/Juan/Dropbox/00_PAPERS/BibTex/biblioZotero.bib
AI: ERROR 13-04-2017 10:45, 31: Failed to send, Bad request  : {"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Unknown domain type 'Microsoft.ApplicationInsights.SessionStateData'"}]}
File: grouptree.fxml not found, attempting with camel case
Apr 13, 2017 10:46:01 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
File: grouptree.css not found, attempting with camel case
AI: TRACE 13-04-2017 10:46, 17: InProcessTelemetryChannel sending telemetry
AI: TRACE 13-04-2017 10:46, 17: InProcessTelemetryChannel sending telemetry
AI: TRACE 13-04-2017 10:46, 17: InProcessTelemetryChannel sending telemetry
10:46:17.379 [JabRef CachedThreadPool] ERROR org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher - Error while fetching from Google Scholar
org.jabref.logic.importer.FetcherException: Fetching from Google Scholar failed.
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:134) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:217) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dmoore&hl=en&q=EgSNOgXvGNb1vMcFIhkA8aeDS2RqpbB4esuBKXpPAdWw-HxYkMQhMgNyY24
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_60]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_60]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:152) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:166) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:142) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:118) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	... 5 more
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dmoore&hl=en&q=EgSNOgXvGNb1vMcFIhkA8aeDS2RqpbB4esuBKXpPAdWw-HxYkMQhMgNyY24
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_60]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_60]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[?:1.8.0_60]
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:294) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:152) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:166) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:142) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:118) ~[JabRef-4.0.0-dev--snapshot--2017-04-12--master--6a5eb6ff3.jar:?]
	... 5 more

**Comment by Siedlerchr** [comment]
@juanmduran  I can not confirm the first issue of your list. When I create groups and save the db, the groups are definitively there.

**Comment by juanmduran** [comment]
@Siedlerchr I should've probably mentioned that I'm running it on OSX Sierra 10.12.4.

Triple check and the problem is still there. I've tried with Static groups, dynamic groups, and Automatically created groups. Same result: when I quit, the groups in the group interface are not there anymore (thou, again, the entry "group" in a given reference remains correct).

**Comment by tobiasdiez** [comment]
Your second problem is a known issue. You can switch to a second db and then back to your first and the subgroups are refreshed (as a workaround).

I've never seen that groups are not saved correctly. Can you please give a step by step procedure how this issue can be reproduced (maybe in a new github issue).

**Comment by mvt91** [comment]
Hello,
Lat be I'm late and the problem is solved and closed but...
With the last development release(s),  I've the same problem.
After a "double clic" on e line to show the details of the bibref reference I chooses, JabRef (JabRef-4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07.jar) freezes.
Linux Mint Cinnamon 18.1, last update with
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

" AI: INFO 19-06-2017 16:34, 19: Configuration file has been successfully found as resource
16:34:22.884 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/tidy/Documents/Biblio/Cur_BibFiles/170619PmId.bib
File: grouptree.fxml not found, attempting with camel case
Jun 19, 2017 4:34:24 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
File: grouptree.css not found, attempting with camel case
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
Jun 19, 2017 4:34:57 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
"

Thanks.
Best regards

**Comment by Siedlerchr** [comment]
Could you please exactly describe the freezing? There is a slight delay for showing the entry editor when you do a double click on the entry. Does the entry editor show up?

**Comment by mvt91** [comment]
Hi Siedlerchr ,
I launch JabRef and load a .bib file (about 1400 - 1500 refs).
When I select (just a clic) a line, I can see the content at the bottom of the window. If I "double clic" on the line to show all the properties (tabbed display format at the bottom of the windows, include the bibtex "raw text", JabRef freezes. The sole solution is to kill the process. If needed, I can try to do the same command on some previous release (last 3 or 4 dev snapshot - 11, 14, 15 and 18 june - and a 3.8.2 release).
I just tried with the same last snapshot release under windows 8.1. The program works well. May be  this an issue with openJDK under Mint 8.1 (or Ubuntu like linuxes)
Best regards

**Comment by Siedlerchr** [comment]
Okay, that narrows it down a bit. Could you please try to install the
Oracle hee?
For ubuntu there is an external repo
http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html?m=1

Am 19.06.2017 6:38 nachm. schrieb "mvt91" <notifications@github.com>:

**Comment by mvt91** [comment]
I tried the last release (snapshot) under windows 8.1 (with Oracle Java). It works well.
I'll try Oracle under Mint in a few days. I hope the next WE.
Thanks

**Comment by mvt91** [comment]
Hi Siedlerchr ,,

Sorry for the delay.
Under Linux Mint Cinnamon 18.1, I removed OpenJDK :+1:
sudo apt-get update && sudo apt-get remove openjdk*
sudo apt-get autoremove && sudo apt-get clean

I download the last JDK release from Oracle website :+1: 
jdk-8u131-linux-x64.tar.gz

I did these commands :+1: 
sudo mkdir -p -v /opt/java/64

Into ~/Download dir :
tar -zxvf jdk-8u131-linux-x64.tar.gz
sudo mv  -v jdk-8u131-linux-x64* /opt/java/64

sudo update-alternatives --install "/usr/bin/java" "java" "/opt/java/64/jdk1.8.0_131/jre/bin/java" 1
sudo update-alternatives --set java /opt/java/64/jdk1.8.0_131/jre/bin/java

~/java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Running JabRef last snapshot (17-06-26) :
java -jar JabRef-4.0.0-dev--snapshot--2017-06-26--master--c3f60f813.jar 
AI: INFO 27-06-2017 11:33, 19: Configuration file has been successfully found as resource
11:33:49.603 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/tidy/Documents/Biblio/Cur_BibFiles/170619PmId.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case

Opening the last opened file (by default)
Double clic on the first entry
Jabref freezes...

May I try something else ?

Note : the external repository for java was mentioned to be use with older releases of Ubuntu (eg. <13.x, release not maintained)

Thanks
