### ISSUE TITLE
Illegal file annotation type

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#2777]
JabRef 4.0.0-beta
Windows 10 10.0 amd64 
Java 1.8.0_131

There happened to strange behavior when click on some group.

![image](https://cloud.githubusercontent.com/assets/13306020/25273728/b121e15e-26bf-11e7-87b2-231650d0bb98.png)

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Opening: D:\git\JabRefBibs\MyFullResearch.bib
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: No enum constant org.jabref.model.pdf.FileAnnotationType.INK
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at org.jabref.logic.pdf.FileAnnotationCache.getFromCache(FileAnnotationCache.java:43)
	at org.jabref.gui.entryeditor.FileAnnotationTab.addAnnotations(FileAnnotationTab.java:110)
	at org.jabref.gui.entryeditor.FileAnnotationTab.initializeTab(FileAnnotationTab.java:89)
	at org.jabref.gui.entryeditor.EntryEditor$TabListener.lambda$stateChanged$0(EntryEditor.java:1163)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant org.jabref.model.pdf.FileAnnotationType.INK
	at java.lang.Enum.valueOf(Unknown Source)
	at org.jabref.model.pdf.FileAnnotationType.valueOf(FileAnnotationType.java:4)
	at org.jabref.model.pdf.FileAnnotation.<init>(FileAnnotation.java:54)
	at org.jabref.logic.pdf.PdfAnnotationImporter.importAnnotations(PdfAnnotationImporter.java:61)
	at org.jabref.logic.pdf.EntryAnnotationImporter.lambda$importAnnotationsFromFiles$2(EntryAnnotationImporter.java:60)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.logic.pdf.EntryAnnotationImporter.importAnnotationsFromFiles(EntryAnnotationImporter.java:60)
	at org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:30)
	at org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:27)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 22 more

Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: No enum constant org.jabref.model.pdf.FileAnnotationType.INK
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at org.jabref.logic.pdf.FileAnnotationCache.getFromCache(FileAnnotationCache.java:43)
	at org.jabref.gui.entryeditor.FileAnnotationTab.addAnnotations(FileAnnotationTab.java:110)
	at org.jabref.gui.entryeditor.FileAnnotationTab.initializeTab(FileAnnotationTab.java:89)
	at org.jabref.gui.entryeditor.EntryEditor$TabListener.lambda$stateChanged$0(EntryEditor.java:1163)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No enum constant org.jabref.model.pdf.FileAnnotationType.INK
	at java.lang.Enum.valueOf(Unknown Source)
	at org.jabref.model.pdf.FileAnnotationType.valueOf(FileAnnotationType.java:4)
	at org.jabref.model.pdf.FileAnnotation.<init>(FileAnnotation.java:54)
	at org.jabref.logic.pdf.PdfAnnotationImporter.importAnnotations(PdfAnnotationImporter.java:61)
	at org.jabref.logic.pdf.EntryAnnotationImporter.lambda$importAnnotationsFromFiles$2(EntryAnnotationImporter.java:60)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.logic.pdf.EntryAnnotationImporter.importAnnotationsFromFiles(EntryAnnotationImporter.java:60)
	at org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:30)
	at org.jabref.logic.pdf.FileAnnotationCache$1.load(FileAnnotationCache.java:27)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 22 more

```

</details>

**Comment by tobiasdiez** [comment]
The exception is a result of an unknown file annotation type (INK). No idea what happened to the text in your main table through.

**Comment by Siedlerchr** [comment]
Maybe @lynyus  can help answering the question on the unknown enum

**Comment by lynyus** [comment]
Yep, that's a bug I will have to take care of. Currently an unknown Annotation type throws such an error. I will change the behavior to ignore the annotation entirely and write a log message instead of throwing an exception.
Also I will add "Ink" to to list of supported annotations.

**Comment by psychelzh** [comment]
@tobiasdiez @Siedlerchr What can I do to do you a favor?

**Comment by psychelzh** [comment]
@lynyus Thank you so much! 💯

**Comment by koppor** [comment]
You can help us by picking something from
http://help.jabref.org/en/FAQcontributing

Am 21.04.2017 15:02 schrieb "张亮" <notifications@github.com>:
