### ISSUE TITLE
DOI search for in incollection article failed

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2815]
Jabref 3.8.2.

Steps to reproduce:

1. Open new entry...
2. Select DOI...
3. type 10.1002/cphy.c110009

results in an error: Error whil fetching from DOI / Invalid URL

This was however copied from
[http://onlinelibrary.wiley.com/doi/10.1002/cphy.c110009/abstract](http://onlinelibrary.wiley.com/doi/10.1002/cphy.c110009/abstract)

```
18:14:43.948 [SwingWorker-pool-5-thread-6] WARN  net.sf.jabref.JabRefException - No localized message exception message defined. Falling back to getMessage().
net.sf.jabref.logic.importer.FetcherException: Invalid URL
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:293) [JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:276) [JabRef-3.8.2.jar:?]
	at javax.swing.SwingWorker$1.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at javax.swing.SwingWorker.run(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://data.crossref.org/10.1002%2Fcphy.c110009
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_131]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:153) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55) ~[JabRef-3.8.2.jar:?]
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://data.crossref.org/10.1002%2Fcphy.c110009
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_131]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_131]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:126) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:153) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55) ~[JabRef-3.8.2.jar:?]
	... 8 more

```

**Comment by Siedlerchr** [comment]
Hi,
this is a temporary problem of the CrossRef.org service, the api is quite unstable in the last days. We will see if we find a solution.
I just checked the 4.0.0 current and I get a connectione error/http 500:

`Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://data.crossref.org/10.1002%2Fcphy.c110009`

**Comment by bernhard-kleine** [comment]
On 3. Mai 2017 18:42:00 MESZ, Christoph <notifications@github.com> wrote:
|Hi,
|this is a temporary problem of the CrossRef.org service, the api is
|quite unstable in the last days. We will see if we find a solution.
|I just checked the 4.0.0 current and I get a connectione error/http
|500:
|
|`Caused by: java.io.IOException: Server returned HTTP response code:
|500 for URL: http://data.crossref.org/10.1002%2Fcphy.c110009`
|
|
|
|-- 
|You are receiving this because you authored the thread.
|Reply to this email directly or view it on GitHub:
|https://github.com/JabRef/jabref/issues/2815#issuecomment-298967241

Ok
-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by tobiasdiez** [comment]
I reported the problem to CrossRef https://github.com/CrossRef/rest-api-doc/issues/201. Hopefully they fix it at their end.
