### ISSUE TITLE
Using right-click->attch file does not open the file dialog in the selected directory

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2825]
JabRef 4.0.0-dev--snapshot--2017-05-06--master--98e2e4379
Windows 7 6.1 amd64 
Java 1.8.0_131

Steps to reproduce:

1. right-click any entry
2. choose attach-file
3. a file dialog which displays a window with files in the selected directory, does not open

The error in previous snapshot version that clicking the + in edit window -> General does not open the window is gone. One can use the dialog there to link files, once again.

```
Put the excerpt of the log file here
```

**Comment by Siedlerchr** [comment]
Can reproduce this.
```
java.lang.NullPointerException: null
	at org.jabref.gui.filelist.FileListEntryEditor.lambda$0(FileListEntryEditor.java:105) ~[bin/:?]
	at org.jabref.gui.filelist.FileListEntryEditor$3.lambda$0(FileListEntryEditor.java:247) ~[bin/:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_131]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) [?:1.8.0_131]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) [?:1.8.0_131]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) [?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) [?:1.8.0_131]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_131]
	at java.awt.Component.show(Component.java:1671) [?:1.8.0_131]
	at java.awt.Component.setVisible(Component.java:1623) [?:1.8.0_131]
	at java.awt.Window.setVisible(Window.java:1014) [?:1.8.0_131]
	at java.awt.Dialog.setVisible(Dialog.java:1005) [?:1.8.0_131]
	at org.jabref.gui.filelist.FileListEntryEditor.setVisible(FileListEntryEditor.java:322) [bin/:?]
```

**Comment by Siedlerchr** [comment]
The underlying problem should be resolved now. Unfortunately we have not yet converted the context menus to javafx in the entry editor, so they are currently disabled.
