### ISSUE TITLE
Entry editor does not open

### ISSUE THREAD

**Issue by bvdalen** [JabRef/jabref#2829]
JabRef version:
JabRef 4.0.0-dev--snapshot--2017-05-07--master--4832e5d86
Windows 7 6.1 amd64 
Java 1.8.0_92
The problem persists when I reset all options to their default values.

**Steps to reproduce:**
1. Open the below BibLaTeX file (or, apparently, any other).
2. Double click on any of the three entries, press ENTER with one selected, or click on the "Edit entry" button.
3. Problem: the entry editor does not open (meaning that I have no way to make any changes to entries).

**Comment:**
I had this problem before in version 2.10 or so. Then it seemed to be related to the particular option settings that I used. But now the problem does not go away even when I reset all options.
N.B. This problem does not yet appear in 
JabRef 3.8.2
windows 7 6.1 amd64 
Java 1.8.0_92

**BibLaTeX file:**
% Encoding: UTF-8

@Article{Item:1,
  author    = {Rodriguez Fernandez, José María},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:2,
  author    = {José María {Rodriguez Fernandez}},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:3,
  author = {José Martinez},
  title  = {Jabref's Issues},
  date   = {2017},
}

@Comment{jabref-meta: databaseType:biblatex;}

**Comment by mlep** [comment]
Same behaviour
JabRef-4.0.0-dev--snapshot--2017-05-07--master--4832e5d86.jar
Linux LMDE
java version "1.8.0_66"

**Message in console:**

Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:156)
	at org.jabref.gui.entryeditor.EntryEditorTab.<init>(EntryEditorTab.java:82)
	at org.jabref.gui.entryeditor.EntryEditor.addRequiredTab(EntryEditor.java:394)
	at org.jabref.gui.entryeditor.EntryEditor.setupFieldPanels(EntryEditor.java:261)
	at org.jabref.gui.entryeditor.EntryEditor.<init>(EntryEditor.java:234)
	at org.jabref.gui.BasePanel.getEntryEditor(BasePanel.java:1496)
	at org.jabref.gui.maintable.MainTableSelectionListener.editSignalled(MainTableSelectionListener.java:189)
	at org.jabref.gui.maintable.MainTableSelectionListener.mouseClicked(MainTableSelectionListener.java:230)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lynyus** [comment]
I can also confirm this, although I get a slightly different stack trace:
```
19:14:12.489 [JabRef CachedThreadPool] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /tmp/biblatex.bib
19:14:26.908 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in T
hread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
        at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:164) ~[main/:?]
        at org.jabref.gui.entryeditor.EntryEditorTab.lambda$new$0(EntryEditorTab.java:88) ~[main/:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
java.lang.RuntimeException: Requested texture dimensions (2147483647x2147483647) require dimensions (0x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Requested texture dimensions (2147483647x2147483647) require dimensions (0x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Requested texture dimensions (2147483647x2147483647) require dimensions (0x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Requested texture dimensions (2147483647x2147483647) require dimensions (0x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Requested texture dimensions (2147483647x2147483647) require dimensions (0x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by truefalsename** [comment]
Hello, I am experiencing this issue on Jabref 4.3.1 on windows 10 v1809

**Comment by tobiasdiez** [comment]
@truefalsename please try the build from http://builds.jabref.org/master/.
