### ISSUE TITLE
Editing in the minimal window no longer possible 

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2847]
JabRef 4.0.0-dev--snapshot--2017-05-16--master--f81716173
Windows 7 6.1 amd64 
Java 1.8.0_131

Steps to reproduce:

1.  Select on entry and try to edit it
2.  The fields in Optional Fields are not visible since jabref squeezes all the fields on the visible display instead of allowing scrolling.
3.  When changing to the next entry jabref does not stay in the Optional Fields tab (or any other) but switches to Required fields, always.

![grafik](https://cloud.githubusercontent.com/assets/9216487/26142460/e76b00e4-3ae0-11e7-8e54-d02c350510d7.png)
```
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\testisDevelopment.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\stra8AndMeiosis.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\ovarianDevelopment.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\leptin.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\adiponectin.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\thyroidHormon.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\Cannon2004_CitiertIn.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism.bib

Could not parse date 2005(?)
Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:228)
	at org.jabref.gui.entryeditor.EntryEditorTab.lambda$new$0(EntryEditorTab.java:90)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)



Could not parse date 1927, 14 May
Could not parse date 2005(?)


DoiResolution fetcher failed: 
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:655)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:676)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:628)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:260)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:249)
	at org.jabref.logic.importer.fetcher.DoiResolution.findFullText(DoiResolution.java:53)
	at org.jabref.logic.importer.FulltextFetchers.findFullTextPDF(FulltextFetchers.java:66)
	at org.jabref.gui.fieldeditors.LinkedFilesEditorViewModel.lambda$fetchFulltext$6(LinkedFilesEditorViewModel.java:174)
	at org.jabref.gui.util.BackgroundTask.call(BackgroundTask.java:63)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:63)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


```
Edit: I deleted duplicates from the error log.

**Comment by lenhard** [comment]
Thanks for the report! I can spot three bugs here:
 1. The entry editor fields should be scrollable instead of squeezing them into the visible area
 2. JabRef should keep the selected entry editor tab instead of switching to the first one when scrolling between entries.
 3. It seems that there are uncaught exceptions when parsing dates.

All of this should be fixed before the release of 4.0.

**Comment by bernhard-kleine** [comment]
BTW My database is 900+ entries large with abstract. It never had been a problem to display the bibtexkey immediately when calling an other entry. However, as of today I had to wait for the bibtexkey quite some time, I first thought it was missing. But eventually the bibtexkey appeared. This behaviour was mostly with book entries. I had never before to wait for the bibtexkey displayed. 

With the previous snapshot (JabRef_windows-x64_4_0_0-dev--snapshot--2017-05-09--master--78185153b) book entries were blank. However, when I moved to the last version (of today) book entries were back, however, very slow.

**Comment by tobiasdiez** [comment]
At least the last mentioned update problems should be fixed in the most recent development version.

**Comment by bernhard-kleine** [comment]
Today snapshot JabRef_windows-x64_4_0_0-dev--snapshot--2017-05-18--master--018173ebd is better that it reacts faster when changing entries in the editor. However, there is still a delay which happened not before. 
While scrolling in the biblatex source tab is allowed in the Optional fields it is not. 

The following errors from the log (any error twice and more)
```

Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:219)
	at org.jabref.gui.entryeditor.EntryEditorTab.lambda$new$0(EntryEditorTab.java:81)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)


Could not parse date 2005(?)

Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IndexOutOfBoundsException: Cannot get at 1 on list of size 1
	at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105)
	at org.jabref.gui.maintable.MainTable.getEntryAt(MainTable.java:344)
	at org.jabref.gui.maintable.MainTable.getCellStatus(MainTable.java:477)
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:288)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by bernhard-kleine** [comment]
snaphot JabRef_windows-x64_4_0_0-dev--snapshot--2017-05-23--master--6db383443:
the fields are shown only for one bib-file while for the others they are not, when shown, however, with a delay, scrolling not possible in the editor window, event log not available

**Comment by bernhard-kleine** [comment]
JabRef 4.0.0-dev--snapshot--2017-05-23--master--6db383443
Windows 7 6.1 amd64 
Java 1.8.0_131

This starts uneventfull. When double clicking on an entry there is (only) this error in the eventlog:
```
Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:219)
	at org.jabref.gui.entryeditor.EntryEditorTab.lambda$new$0(EntryEditorTab.java:81)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by bernhard-kleine** [comment]
This issue is not selved with the entry editor fix: Scrolling in the editor window is not (yet) possible. The delay and the missing entries are solved. There is no longer an error in the event log.

![grafik](https://cloud.githubusercontent.com/assets/9216487/26623395/e1747c3e-45ed-11e7-8896-dabf16ec0033.png)

**Comment by bernhard-kleine** [comment]
Hi
with the latest snapshot the problem is going to be solved, but not fully achieved yet:
Now the fields Editor-Window Optional Fields are no longer shown crippled ( to small to see the text) but those fields which are not in the screen can not be reached by scrolling, which is not possible at all. The screenshots hopefully show the problem.

![grafik](https://user-images.githubusercontent.com/9216487/26935974-abb38cb2-4c6d-11e7-9a9f-f77ec73c49df.png)

This shot shows in extremis what fields are in the editor window.

The next one demonstrates that in case the editor window is small you cannot reach the missing fields by scolling since there is no possible scroll bar.

![grafik](https://user-images.githubusercontent.com/9216487/26936128-07b7cb22-4c6e-11e7-90d0-1cdf5c67193e.png)

**Comment by lenhard** [comment]
@tobiasdiez Wouldn't it be possible to use a scroll pane as the top container in the optional fields tab (and maybe the other tabs)? That should solve the remaining problem here, shouldn't it?

**Comment by tobiasdiez** [comment]
Yes, that worked. Good suggestion. So this issue should be fixed now, too.
