### ISSUE TITLE
Automatic Bug Report - 20170601210028

### ISSUE THREAD

**Issue by AlexShevtsov** [JabRef/jabref#2880]
JabRef 4.0.0-dev--snapshot--2017-06-01--master--f5386b28d
Linux 4.11.3-1-arch amd64 
Java 1.8.0_121

I have just made a fresh install of the JabRef after deleting the old version (3.8.2). 
Now, when I am trying to make a web search nothing happens, and the console displays the following error message (see below). Is there anything which needs to be installed? All dependencies, including the optional ones (gsettings-desktop-schemas) are installed. 

P.S. Before reinstall the web search was working fine.

<details>
ERROR MESSAGE:

Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jabref.gui.importer.ImportInspectionDialog.<init>(ImportInspectionDialog.java:240)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.actionPerformed(GeneralFetcher.java:210)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</details>

**Comment by koppor** [comment]
Which web search are you using with with search string?

**Comment by AlexShevtsov** [comment]
I get the same error message for all types of web search except for 'ACM Portal'. I am particularly interested in 'arXiv' one. 

Also note that this error is not specific to the new version of JabRef. Even if I reinstall the old one, which I had previously working fine, it also displays the same behavior.

**Comment by AlexShevtsov** [comment]
I don't know what happened, but I managed to get it working again. I am sorry for bothering you.

**Comment by AlexShevtsov** [comment]
I have finally figured out what happened. I am using Arch Linux (Antergos) and I had JabRef-3.8.2 previously installed from the AUR repositories: https://aur.archlinux.org/packages/jabref/

It lists **gsettings-desktop-schemas**  as an optional dependency necessary for running Web Search feature in JabRef. I had it installed and the Web Search was working fine. I would not bother with reinstalling anything if there was no issue with DOI import feature, see https://github.com/JabRef/jabref/issues/2879

So, I decided to download the latest 'jar' of the JabRef development build and give it a try. As can be seen from the issue quoted above, the DOI import problem was fixed on June 6, 2017, so it now works in the dev. build.

However, I have a problem with the Web Search now. It looks like it does not pick up **gsettings-desktop-schemas** as a dependency, which automatically disables Web Search. This means that when I hit the "Fetch" button I get an error log reported at the top of the current issue ticket.

Could anyone help me by hinting what I have to change in the build process in order for the JabRef fresh build to pick up the dependency -- **gsettings-desktop-schemas**?

Thank you!

**Comment by tobiasdiez** [comment]
The error message above was actually a small bug on our side and not related to the `gsettings-desktop-schemas`. At least this error should be fixed now. Can you please try out the latest build from http://builds.jabref.org/master/. Thanks!

**Comment by AlexShevtsov** [comment]
Thank you very much for the quick reply! The new build indeed has fixed the error. It works great now.
