### ISSUE TITLE
Keybinding Exception when doing CTRL+Z or SHIFT+ sth (but works)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2901]
Latest master

Edit entry, change author for example or in code editor:
1. Remove some value
2 . Type CTRL+Z
3. Exception occurs
4. But Undo is executed

```
14:32:44.708 [AWT-EventQueue-0] WARN  org.jabref.gui.BasePanel - Nothing to undo
javax.swing.undo.CannotUndoException: null
	at javax.swing.undo.UndoManager.undo(UndoManager.java:411) ~[?:1.8.0_131]
	at org.jabref.gui.undo.CountingUndoManager.undo(CountingUndoManager.java:30) ~[bin/:?]
	at org.jabref.gui.BasePanel$UndoAction.action(BasePanel.java:2172) [bin/:?]
	at org.jabref.gui.BasePanel.runCommand(BasePanel.java:1016) [bin/:?]
	at org.jabref.gui.entryeditor.EntryEditor$UndoAction.actionPerformed(EntryEditor.java:827) [bin/:?]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) [?:1.8.0_131]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) [?:1.8.0_131]
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307) [?:1.8.0_131]
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250) [?:1.8.0_131]
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974) [?:1.8.0_131]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966) [?:1.8.0_131]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) [?:1.8.0_131]
	at javafx.embed.swing.JFXPanel.processKeyEvent(JFXPanel.java:463) [jfxrt.jar:?]
	at java.awt.Component.processEvent(Component.java:6310) [?:1.8.0_131]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_131]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_131]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_131]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_131]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) [?:1.8.0_131]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) [?:1.8.0_131]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) [?:1.8.0_131]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) [?:1.8.0_131]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) [?:1.8.0_131]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) [?:1.8.0_131]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_131]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_131]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_131]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_131]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_131]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_131]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]

```

2nd example: 
2.  HOLD SHIFT + Type sth to get captial letters
Capital letters occur 

```
14:32:57.596 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IllegalArgumentException: Cannot parse key binding SHIFT
	at javafx.scene.input.KeyCombination.valueOf(KeyCombination.java:429) ~[jfxrt.jar:?]
	at org.jabref.gui.keyboard.KeyBindingRepository.checkKeyCombinationEquality(KeyBindingRepository.java:81) ~[bin/:?]
	at org.jabref.gui.keyboard.KeyBindingRepository.checkKeyCombinationEquality(KeyBindingRepository.java:170) ~[bin/:?]
	at org.jabref.gui.keyboard.KeyBindingRepository.mapToKeyBinding(KeyBindingRepository.java:135) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditor.lambda$2(EntryEditor.java:183) ~[bin/:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964) ~[jfxrt.jar:?]
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910) ~[jfxrt.jar:?]
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040) ~[jfxrt.jar:?]
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$300(EmbeddedScene.java:310) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$keyEvent$301(EmbeddedScene.java:296) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Siedlerchr** [comment]
The first problem occurs because the JFXPanel passed the key pressed event up to it's Swing parent which then executes the method in the entryEditor.

The second problem is a bit weird. I tried to debug through it. At some point there is suddenly a value null

**Comment by tobiasdiez** [comment]
I also don't really understand why we need a custom `checkKeyCombinationEquality` method. The `KeyCombination` class already contains a `match` method which looks like what is needed (but does not work).

**Comment by Siedlerchr** [comment]
Yes, this is really mysterious. I replaced it with caling the match method and now the exceptions are gone and the key codes seem to work. Tried several things manually.
I tried to debug through it and I don't why some of the tests fail, but I guess it has sth to do with the binding/preferences stuff (although debugging shows the correct values)
