### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by jabaa** [JabRef/jabref#3021]
JabRef version 3.8.1

Steps to reproduce:

1. Open jabref
2. click on something

When I open jabref it seems ok. But I can't use it. When I click something, nothing happens. No menu opens. The console gives me

    21:48:01.804 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: /home/xxx/xxx.bib
    21:48:07.053 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
    java.lang.ExceptionInInitializerError: null
	    at com.jgoodies.looks.common.ShadowPopup.<clinit>(ShadowPopup.java:84) ~[jgoodies-looks.jar:?]
	    at com.jgoodies.looks.Options.isPopupDropShadowActive(Options.java:639) ~[jgoodies-looks.jar:?]
	    at com.jgoodies.looks.common.ShadowPopupFactory.getPopup(ShadowPopupFactory.java:177) ~[jgoodies-looks.jar:?]
	    at javax.swing.plaf.PopupMenuUI.getPopup(PopupMenuUI.java:61) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.showPopup(JPopupMenu.java:837) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:790) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.show(JPopupMenu.java:965) ~[?:1.8.0_131]
	    at net.sf.jabref.gui.maintable.MainTableSelectionListener.processPopupTrigger(MainTableSelectionListener.java:357) ~[JabRef-3.8.1.jar:?]
	    at net.sf.jabref.gui.maintable.MainTableSelectionListener.mouseReleased(MainTableSelectionListener.java:208) ~[JabRef-3.8.1.jar:?]
	    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[?:1.8.0_131]
	    at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_131]
	    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_131]
	    at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_131]
	    at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_131]
	    at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_131]
	    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
    Caused by: java.lang.NullPointerException
	    at javax.swing.ImageIcon.<init>(ImageIcon.java:217) ~[?:1.8.0_131]
	    at com.jgoodies.looks.common.ShadowPopupBorder.<clinit>(ShadowPopupBorder.java:69) ~[jgoodies-looks.jar:?]
	    ... 41 more
    21:52:24.470 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
    java.lang.NoClassDefFoundError: Could not initialize class com.jgoodies.looks.common.ShadowPopup
	    at com.jgoodies.looks.Options.isPopupDropShadowActive(Options.java:639) ~[jgoodies-looks.jar:?]
	    at com.jgoodies.looks.common.ShadowPopupFactory.getPopup(ShadowPopupFactory.java:177) ~[jgoodies-looks.jar:?]
	    at javax.swing.plaf.PopupMenuUI.getPopup(PopupMenuUI.java:61) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.showPopup(JPopupMenu.java:837) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:790) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.show(JPopupMenu.java:965) ~[?:1.8.0_131]
	    at javax.swing.JMenu.setPopupMenuVisible(JMenu.java:345) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1478) ~[?:1.8.0_131]
	    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:222) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI.access$200(BasicMenuUI.java:49) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:461) ~[?:1.8.0_131]
	    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[?:1.8.0_131]
	    at java.awt.Component.processMouseEvent(Component.java:6530) ~[?:1.8.0_131]
	    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_131]
	    at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_131]
	    at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_131]
	    at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_131]
	    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]
    21:52:25.178 [AWT-EventQueue-0] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
    java.lang.NoClassDefFoundError: Could not initialize class com.jgoodies.looks.common.ShadowPopup
	    at com.jgoodies.looks.Options.isPopupDropShadowActive(Options.java:639) ~[jgoodies-looks.jar:?]
	    at com.jgoodies.looks.common.ShadowPopupFactory.getPopup(ShadowPopupFactory.java:177) ~[jgoodies-looks.jar:?]
	    at javax.swing.plaf.PopupMenuUI.getPopup(PopupMenuUI.java:61) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.showPopup(JPopupMenu.java:837) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:790) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.show(JPopupMenu.java:965) ~[?:1.8.0_131]
	    at javax.swing.JMenu.setPopupMenuVisible(JMenu.java:345) ~[?:1.8.0_131]
	    at javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1478) ~[?:1.8.0_131]
	    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:222) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI.access$200(BasicMenuUI.java:49) ~[?:1.8.0_131]
	    at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:461) ~[?:1.8.0_131]
	    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[?:1.8.0_131]
	    at java.awt.Component.processMouseEvent(Component.java:6530) ~[?:1.8.0_131]
	    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_131]
	    at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_131]
	    at java.awt.Container.processEvent(Container.java:2236) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522) ~[?:1.8.0_131]
	    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[?:1.8.0_131]
	    at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[?:1.8.0_131]
	    at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_131]
	    at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_131]
	    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_131]
	    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_131]
	    at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_131]
	    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_131]
	    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_131]
	    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_131]

**Comment by Siedlerchr** [comment]
Seems like you are having some problems with some old version of the jgoodies libs:
See also here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846918
You could try to install the latest version from the unstable repo:
https://packages.debian.org/sid/tex/jabref

**Comment by jabaa** [comment]
My

**Comment by koppor** [comment]
Which operating system?

**Comment by jabaa** [comment]
Xubuntu 17.04

**Comment by jabaa** [comment]
![image](https://user-images.githubusercontent.com/6706626/28402636-278d48d6-6d21-11e7-806d-57ef7665552c.png)

**Comment by koppor** [comment]
Could you try `sudo snap install jabref --edge --devmode` and see whether our recent build runs. I know that a snap build is very different from the normal Debian packaging (https://github.com/koppor/jabref/issues/135).

Refs https://github.com/JabRef/jabref/pull/2345

**Comment by jabaa** [comment]
$ jabref
    libGL error: unable to load driver: i965_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: i965
    libGL error: unable to load driver: i965_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: i965
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    X Error:  BadValue
      Request Major code 155 (GLX)
      Request Minor code 24 ()
      Value 0x0
      Error Serial #39
      Current Serial #40

**Comment by Siedlerchr** [comment]
Hi, the latest version should now work with snap
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
