### ISSUE TITLE
Creation of reference list in document LibreOffice

### ISSUE THREAD

**Issue by cedmfr** [JabRef/jabref#3153]
JabRef version 4.0-beta3 on macOS Sierra 10.12.6

The connection with LO 5.4.0.3 is not working. An error message 'no office executable found!' is appearing both auto or manual connection with corresponding path to LO.
Anyhow with JabRef 3.8.2 the connection is working. Citation can be inserted into a LO Writer document but the reference list is not inserted. How to force the reference list to display ?

**Comment by Siedlerchr** [comment]
Hi,

I can not reproduce the issue under Windows with the latest snapshot. When I insert a citation in LO (5.4.0.3) the citation gets inserted and the reference list is automatically produced.

Do you get any error messages in the log?

**Comment by Doc73** [comment]
Same error in Debian GNU/Linux 9 Stretch with
> JabRef 4.0-beta3
> Linux 4.11.0-0.bpo.1-amd64 amd64 
> Java 1.8.0_141

and with
> JabRef 4.0-dev--snapshot--2017-08-27--master--6a26798aa
> Linux 4.11.0-0.bpo.1-amd64 amd64 
> Java 1.8.0_141

LibreOffice:
> Version: 5.4.0.3
> Build ID: 1:5.4.0-1~bpo9+1

but also with previous LO versions.

Here is the terminal output:
```
19:59:43.799 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file unoil.jar inside the directory /opt/openoffice.org3
19:59:43.801 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file jurt.jar inside the directory /opt/openoffice.org3
19:59:43.803 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file juh.jar inside the directory /opt/openoffice.org3
19:59:43.806 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file ridl.jar inside the directory /opt/openoffice.org3
19:59:43.809 [AWT-EventQueue-1] WARN  org.jabref.gui.openoffice.OpenOfficePanel - Could not connect to running OpenOffice/LibreOffice
java.io.IOException: (Not all) required Open Office Jars were found inside installation path.
	at org.jabref.gui.openoffice.OpenOfficePanel.loadOpenOfficeJars(OpenOfficePanel.java:438) ~[JabRef-4.0-dev--snapshot--2017-08-27--master--6a26798aa.jar:?]
	at org.jabref.gui.openoffice.OpenOfficePanel.connect(OpenOfficePanel.java:388) ~[JabRef-4.0-dev--snapshot--2017-08-27--master--6a26798aa.jar:?]
	at org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$0(OpenOfficePanel.java:145) ~[JabRef-4.0-dev--snapshot--2017-08-27--master--6a26798aa.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_141]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_141]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_141]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_141]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_141]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) [?:1.8.0_141]
	at java.awt.Component.processMouseEvent(Component.java:6533) [?:1.8.0_141]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_141]
	at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_141]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_141]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_141]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_141]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_141]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_141]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_141]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_141]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_141]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_141]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_141]
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700) [java-atk-wrapper.jar:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_141]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_141]
```

**Comment by Doc73** [comment]
`/opt/openoffice.org3`
LibreOffice isn't in that folder!!!!

**Comment by Siedlerchr** [comment]
Seems like you have an older version of OpenOffice installed parallel with LibreOffice. You should either remove that, or if you need it for some reason you can manually choose the path:

 You can use **manual connect** (Second button from left side  in the panel) to select the right folder:
> If you connect by clicking the Connect button, JabRef will try to automatically determine these locations. If this does not work, you need to connect using the Manual connect button, which will open a window asking you for the needed locations. 

http://help.jabref.org/en/OpenOfficeIntegration

**Comment by Doc73** [comment]
@Siedlerchr 
No, no! Mine is a fresh installation with format of /, but I **never** installed OpenOffice or LibreOffice in a different way than by Debian Repositories. With JR version 3.8.2 the plugin worked perfectly. Same issue in my laptop with the same system.

In **manual connection** the paths are correct, but I still receive the same error.

![schermata del 2017-08-27 21-55-18](https://user-images.githubusercontent.com/1306260/29753473-9b809634-8b72-11e7-9c32-2031b223d41d.png)

**Comment by Doc73** [comment]
Ah, cf. #3139

**Comment by Siedlerchr** [comment]
@Doc73  Yes, I was just thinking that this might be the same problem. Could you check if the output from my comment looks similar?
https://github.com/JabRef/jabref/issues/3139#issuecomment-324634944

**Comment by Doc73** [comment]
Done in #3139
