### ISSUE TITLE
Can't remove or move online file link

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3165]
When I use ArXiv search to find and insert an entry into my bib file, an online file link is inserted in the General tab.  There's no way to delete the link, nor to move it below the file link I've created for a locally stored paper that has my annotations on it.   

When I click on the document icon for this entry in the main paper list, Jabref doesn't bring up any paper (maybe it's trying to fetch the online document?).  What I would like it to do is to open up my local annotated version.

I've attached the .bib for this entry, and also a screenshot with the problem link highlighted.

JabRef version 

JabRef 4.0-dev--snapshot--2017-08-21--master--d46fd5c84
Windows 7 6.1 amd64 
Java 1.8.0_141

![image](https://user-images.githubusercontent.com/3851891/29834280-a2c8b098-8cee-11e7-9af3-f52fb496baa4.png)

[undeletableLink.txt](https://github.com/JabRef/jabref/files/1261093/undeletableLink.txt)

**Comment by Siedlerchr** [comment]
Hi, you can normally delete the link via the del key or from the context
menu

Regarding opening, do you see anything in the log?

Am 29.08.2017 7:18 nachm. schrieb "notuntoward" <notifications@github.com>:

**Comment by notuntoward** [comment]
Not for this entry:  the delete key has no effect, and there's no "delete" entry in the right mouse button context menu (there is a"remove link" entry but it's grayed out).

Below is what I see in the log when I click the document icon:
Uncaught exception Occurred in Thread[JabRef CachedThreadPool,6,main]
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://arxiv.org/pdf/1312.6098v5
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at org.jabref.gui.desktop.JabRefDesktop.openExternalFileAnyFormat(JabRefDesktop.java:142)
	at org.jabref.gui.externalfiletype.ExternalFileMenuItem.openLink(ExternalFileMenuItem.java:84)
	at org.jabref.gui.externalfiletype.ExternalFileMenuItem.actionPerformed(ExternalFileMenuItem.java:57)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at org.jabref.gui.maintable.MainTableSelectionListener.lambda$mouseClicked$3(MainTableSelectionListener.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Siedlerchr** [comment]
I will at least enable the deletion of the online links, for the other part I will look at the fetcher

**Comment by Siedlerchr** [comment]
Online links can be deleted now and the opening of the URL is now also possibleö


Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by notuntoward** [comment]
Thanks.  I can now delete the online link, and I can open it.  

It would also be nice to get the link reordering controls back.  In JabRef 3.x, I used them every once in a while.

**Comment by Siedlerchr** [comment]
@notuntoward  I  implemented the drag and drop feature in the files list for reordering, see #3194 
Could you try out the dev build and report if it works for you, too?
 http://builds.jabref.org/dragdropfiles/

**Comment by notuntoward** [comment]
Yes, drag and drop works for me.  Thanks.
