### ISSUE TITLE
Exceptions regarding XMP

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#3226]
JabRef 4.0-beta3
Windows 10 10.0 amd64 
Java 1.8.0_131

In the event log there are two exceptions for which I have no clue where they happened and what should I do to fix them (the following are only the two exceptions, the rest of the log has been deleted):

```
XMP reading failed
java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1519)
	at org.apache.pdfbox.pdfparser.PDFParser.parseHeader(PDFParser.java:372)
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:186)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1235)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1202)
	at org.jabref.logic.xmp.XMPUtil.loadWithAutomaticDecryption(XMPUtil.java:118)
	at org.jabref.logic.xmp.XMPUtil.readXMP(XMPUtil.java:147)
	at org.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1046)
	at org.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1027)
	at org.jabref.logic.importer.fileformat.PdfXmpImporter.isRecognizedFormat(PdfXmpImporter.java:71)
	at org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:189)
	at org.jabref.gui.importer.ImportMenuItem$MyWorker.run(ImportMenuItem.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Thread.java:748)


Invalid byte 1 of 1-byte UTF-8 sequence.
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.jabref.logic.importer.fileformat.MrDLibImporter.isRecognizedFormat(MrDLibImporter.java:54)
	at org.jabref.logic.importer.fetcher.MrDLibFetcher.performSearch(MrDLibFetcher.java:58)
	at org.jabref.gui.entryeditor.RelatedArticlesTab.lambda$getPane$0(RelatedArticlesTab.java:41)
	at org.jabref.gui.util.BackgroundTask.call(BackgroundTask.java:63)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:63)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Please add to the exception message at least the key that caused the error.
Thanks!
mario

**Comment by lenhard** [comment]
The messages just say that JabRef tried to read meta information from a pdf file, but failed. That's nothing critical. You can just ignore those.

Are you trying to read XMP data from a file?

**Comment by crystalfp** [comment]
No for what I know. Simply I cannot understand where it happened and asked for something to identify where has been triggered. Anyway, I agree with you, it seems harmless. 
Thanks! 
Mario

Il 18 Settembre 2017 16:35:55 CEST, "Jörg Lenhard" <notifications@github.com> ha scritto:
>The messages just say that JabRef tried to read meta information from a
>pdf file, but failed. That's nothing critical. You can just ignore
>those.
>
>Are you trying to read XMP data from a file?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JabRef/jabref/issues/3226#issuecomment-330243244

-- 
Inviato da Galaxy Notes con K-9 Mail. Perdonate la brevità.

**Comment by koppor** [comment]
We are going to rewrite the XMP functionality. See https://github.com/JabRef/jabref/pull/1096.

**Comment by lenhard** [comment]
Ok, thanks for the feedback. In that case, I think this can be closed.
