### ISSUE TITLE
Jabref4  connection with LibreOffice

### ISSUE THREAD

**Issue by vanukkalla** [JabRef/jabref#3263]
This relates to #3139 and #3153.

I am using LO 5.4.1.2 with Jabref on Debian 9. Connecting Jabref 3.8.2 is working without problems. When I try to connect Jabref 4.0, I have the previously reported connectivity problems.

`[File:] grouptree.fxml not found, attempting with camel case
Oct 05, 2017 12:33:54 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.111
File: grouptree.css not found, attempting with camel case
12:34:42.507 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file unoil.jar inside the directory /opt/openoffice4
12:34:42.514 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file jurt.jar inside the directory /opt/openoffice4
12:34:42.515 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file juh.jar inside the directory /opt/openoffice4
12:34:42.515 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file ridl.jar inside the directory /opt/openoffice4
12:34:42.516 [AWT-EventQueue-1] WARN  org.jabref.gui.openoffice.OpenOfficePanel - Could not connect to running OpenOffice/LibreOffice
java.io.IOException: (Not all) required Open Office Jars were found inside installation path.
	at org.jabref.gui.openoffice.OpenOfficePanel.loadOpenOfficeJars(OpenOfficePanel.java:438) ~[JabRef_4.0.jar:?]
	at org.jabref.gui.openoffice.OpenOfficePanel.connect(OpenOfficePanel.java:388) ~[JabRef_4.0.jar:?]
	at org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$1(OpenOfficePanel.java:146) ~[JabRef_4.0.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_141]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_141]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_141]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_141]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_141]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) [?:1.8.0_141]
	at java.awt.Component.processMouseEvent(Component.java:6533) [?:1.8.0_141]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_141]
	at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_141]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_141]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_141]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_141]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_141]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_141]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_141]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_141]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_141]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_141]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_141]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_141]
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700) [java-atk-wrapper.jar:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_141]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_141]`

with the final message: 
Error message: (Not all) required Open Office jars were found inside the installation path.

my java version:
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
libreoffice-java-common package is installed.

Evidently Jabref is looking for those jars in /opt/openoffice4, which never existed on my computer, and keeps doing this although I selected the correct paths during manual connect. 
Resetting the preferences did not work for me, neither did importing the preferences of the 3.8.2 version into version 4.0.

In previous versions it really helped that the error message contained the information in which folders Jabref was looking for the files. 

Thank you.

**Comment by vanukkalla** [comment]
The problem persists under LO 5.4.2. No such problems under Windows in virtualbox. 
Creating a symlink does not work either.

But creating the folder /opt/openoffice4 and copying all jars there, while not very elegant, works.

**Comment by Siedlerchr** [comment]
I will take a look at that.  the path is defined in the code, but a manual lookup should work

**Comment by stefan-kolb** [comment]
JabRef will try to find the following jars inside the installation directory (any subdirectory) of LO/OO: `"unoil.jar", "jurt.jar", "juh.jar", "ridl.jar"` Where are those libs located in your installation and is maybe one of them missing?!

**Comment by Siedlerchr** [comment]
Hi, could you please try if this version works for you?
http://builds.jabref.org/linuxOO/
You probably have to reset your prefs before connecting to LO

**Comment by vanukkalla** [comment]
The jars are all there in Libreoffice5.4/program/classes. 

And the new version works like a charm! Thanks a lot!

**Comment by vanukkalla** [comment]
I do not know, whether other people have the same problem (as described above):

I am now on LO 6.0.4.2 on Debian 9, use JabRef 4.2 and openJDK. 
When trying to connect JabRef to LO, the paths to programm and jars are correct, but it then gives an error message:      not all jars found in the directory. 

In the Terminal, the information is more informative:
09:51:05.224 [AWT-EventQueue-1] ERROR org.jabref.logic.util.io.FileUtil - Error trying to locate the file ridl.jar inside the directory /opt/openoffice4

As above, the program displays the correct path but is looking in the wrong directory. 
I am using a work-around by using the /openoffice4 directory where I copied all the jar files. 
Everyting is working fine then.

**Comment by Siedlerchr** [comment]
@vanukkalla  That's very weird. The only thing I can imagine is that in your preferences somehow an old path is stored. You could try exporting the JabRef settings, modifying the following keys and reimporting the settings. I think the default values for linux should be this one: 
```
<entry key="ooPath" value="/usr/lib/libreoffice">
<entry key="ooExecutablePath" value="/usr/lib/libreoffice/program/soffice/>
<entry key="ooJarsPath" value="/usr/lib/libreoffice/program/classes"/>
```
