### ISSUE TITLE
Exception after clicking "journal PDF" in JabRef 2.10

### ISSUE THREAD

**Issue by nemobis** [JabRef/jabref#3279]
I'm using LocalCopy 2.6 with JabRef 2.10. I imported a bibtex files with some DOIs and I clicked "journal PDF" after selecting one of them. The dialog hangs forever and I see:

```
LocalCopy: updated to version 1.5
Exception in thread "Thread-6" java.lang.NoSuchMethodError: net.sf.jabref.labelPattern.LabelPatternUtil.makeLabel(Lnet/sf/jabref/labelPattern/LabelPattern;Lnet/sf/jabref/BibtexDatabase;Lnet/sf/jabref/BibtexEntry;)Lnet/sf/jabref/BibtexEntry;
        at localcopy.FNTemplate.getKey(FNTemplate.java:58)
        at localcopy.FNTemplate.getFN(FNTemplate.java:100)
        at localcopy.Download.downloadFromPage(Download.java:558)
        at localcopy.CommandDoiUrl.run(LocalCopyPane.java:139)
        at localcopy.ProgressDialog$Task.run(ProgressDialog.java:118)
```

I can't tell whether this is the same as some other reports here; the versions seem different.

**Comment by nemobis** [comment]
Sorry, wrong repo. Moved to https://github.com/lehner/LocalCopy/issues/8
