### ISSUE TITLE
Exception in opening bib file

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#3342]
At some point during the 4.1dev development this started to happen. The problem is not there with 4.0
and was not there with 4.1dev until a couple of weeks ago.

It is unusual in that the exception only occurs when giving a bib file to jabref e.g.

 java -jar /usr/share/jabref VU_bibtex_master.bib

When you just start jabref via "java -jar /usr/share/jabref" it starts and then I can open the bib file fine.
It does not depend on the name or content of the bib file. I tried java 1.8.0_151 or _152. The error is:

=======================
12:10:20.060 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: VU_bibtex_master.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
12:10:21.285 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at org.jabref.gui.util.FileUpdateMonitor.addListenerForFile(FileUpdateMonitor.java:75) ~[jabref:?]
        at org.jabref.collab.DatabaseChangeMonitor.lambda$new$0(DatabaseChangeMonitor.java:40) ~[jabref:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_162-ea]
        at org.jabref.collab.DatabaseChangeMonitor.<init>(DatabaseChangeMonitor.java:38) ~[jabref:?]
        at org.jabref.gui.BasePanel.<init>(BasePanel.java:231) ~[jabref:?]
        at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1598) ~[jabref:?]
        at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1301) ~[jabref:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:134) ~[jabref:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[jabref:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:150) ~[jabref:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_162-ea]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162-ea]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_162-ea]
^C$ export JAVA_HOME=/usr/java/jdk1.8.0;java -jar /usr/share/jabref VU_bibtex_master.bib   
12:19:40.295 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: VU_bibtex_master.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
12:19:41.395 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at org.jabref.gui.util.FileUpdateMonitor.addListenerForFile(FileUpdateMonitor.java:75) ~[jabref:?]
        at org.jabref.collab.DatabaseChangeMonitor.lambda$new$0(DatabaseChangeMonitor.java:40) ~[jabref:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_162-ea]
        at org.jabref.collab.DatabaseChangeMonitor.<init>(DatabaseChangeMonitor.java:38) ~[jabref:?]
        at org.jabref.gui.BasePanel.<init>(BasePanel.java:231) ~[jabref:?]
        at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1598) ~[jabref:?]
        at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1301) ~[jabref:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:134) ~[jabref:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[jabref:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:150) ~[jabref:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_162-ea]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162-ea]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_162-ea]

**Comment by sambo57u** [comment]
PS: Using Linux x86_64

**Comment by Siedlerchr** [comment]
Thanks for your report, I could reproduce the issue under Win and prepared a fix. Will be in the next dev version, as soon as #3343  is merged
