### ISSUE TITLE
Automatically set file links - shortcut F7 not working

### ISSUE THREAD

**Issue by tpet** [JabRef/jabref#3346]
**JabRef version**
JabRef 4.0
Linux 4.4.8-040408-generic amd64 
Java 1.8.0_151

**Steps to reproduce:**
1. Select an entry without the file link for which there is a matching file.
2. Press F7. The file link should be set automatically but is not.
3. Select the item from menu (Automatically set file links). The link is set correctly.
4. Press F4. The file just set opens correctly.

The button within the entry editor (Automatically set file links for this entry) is also not working.

Not sure whether this is related, but there is an exception in the log, enclosing below.
<details>
  ```
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: 619 not in [0, 1]
	at org.reactfx.util.Lists.checkPosition(Lists.java:110)
	at org.reactfx.util.Lists.checkPosition(Lists.java:105)
	at org.reactfx.util.FingerTree$NonEmptyFingerTree.locateProgressively(FingerTree.java:51)
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument$Pos.offsetBy(ReadOnlyStyledDocument.java:378)
	at org.fxmisc.richtext.model.ReadOnlyStyledDocument.offsetToPosition(ReadOnlyStyledDocument.java:207)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.offsetToPosition(GenericEditableStyledDocumentBase.java:119)
	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.offsetToPosition(SimpleEditableStyledDocument.java:7)
	at org.fxmisc.richtext.GenericStyledArea.lambda$new$7(GenericStyledArea.java:664)
	at org.reactfx.value.Val$2.computeValue(Val.java:705)
	at org.reactfx.value.ValBase.getValue(ValBase.java:17)
	at org.reactfx.value.ValBase.newObserver(ValBase.java:40)
	at org.reactfx.value.ValBase.newObserver(ValBase.java:8)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:110)
	at org.reactfx.value.Val.addInvalidationObserver(Val.java:52)
	at org.reactfx.value.Val.addListener(Val.java:70)
	at org.reactfx.value.Val.observeInvalidations(Val.java:432)
	at org.reactfx.value.MappedVal.connect(MappedVal.java:28)
	at org.reactfx.value.ValBase.observeInputs(ValBase.java:26)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:108)
	at org.reactfx.ObservableBase.observe(ObservableBase.java:100)
	at org.reactfx.value.Val.observeInvalidations(Val.java:61)
	at org.reactfx.value.Val$1.observeInputs(Val.java:104)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:108)
	at org.reactfx.ObservableBase.observe(ObservableBase.java:100)
	at org.reactfx.EventStream.subscribe(EventStream.java:53)
	at org.reactfx.SuspendableBase.observeInputs(SuspendableBase.java:49)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:108)
	at org.reactfx.value.Val.addInvalidationObserver(Val.java:52)
	at org.reactfx.value.Val.addListener(Val.java:70)
	at org.reactfx.value.Val$2.connect(Val.java:693)
	at org.reactfx.value.ValBase.observeInputs(ValBase.java:26)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:108)
	at org.reactfx.value.Val.addInvalidationObserver(Val.java:52)
	at org.reactfx.value.Val.addListener(Val.java:80)
	at org.reactfx.EventStreams$3.observeInputs(EventStreams.java:106)
	at org.reactfx.ObservableBase.addObserver(ObservableBase.java:108)
	at org.reactfx.ObservableBase.observe(ObservableBase.java:100)
	at org.reactfx.EventStream.subscribe(EventStream.java:53)
	at org.fxmisc.richtext.GenericStyledArea.createCell(GenericStyledArea.java:1375)
	at org.fxmisc.richtext.GenericStyledArea.lambda$new$13(GenericStyledArea.java:760)
	at org.fxmisc.flowless.CellPool.getCell(CellPool.java:20)
	at org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:75)
	at org.reactfx.collection.MappedList.get(MappedList.java:27)
	at org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99)
	at org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:64)
	at org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:129)
	at org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:95)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:183)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:111)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:49)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:67)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:165)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
  ```
</details>

**Comment by matthiasgeiger** [comment]
There are also some additional reports regarding this functionality in the discourse Forum: http://discourse.jabref.org/t/automatically-set-file-links-f7-not-working-any-more/859

**Comment by notuntoward** [comment]
I see this too: #2985

**Comment by Siedlerchr** [comment]
Hi,
could you please try the current version from here?
http://builds.jabref.org/autofilelink/
