### ISSUE TITLE
4.0 Crossref Websearch fails with "Parser error"

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3376]
JabRef version 
```
JabRef 4.0
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```

Steps to reproduce:
search for 10.1103/PhysRevLett.119.177201
![selection_369](https://user-images.githubusercontent.com/298682/32225308-f9e659ac-be44-11e7-905d-9849edc8fe66.png)

![selection_368](https://user-images.githubusercontent.com/298682/32225318-06442a94-be45-11e7-9556-d568ddf263be.png)
```

14:11:58.427 [JabRef CachedThreadPool] ERROR org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher - Error while fetching from Crossref
org.jabref.logic.importer.FetcherException: An internal parser error occurred
	at org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(SearchBasedParserFetcher.java:72) ~[JabRef-4.0.jar:?]
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37) ~[JabRef-4.0.jar:?]
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216) ~[JabRef-4.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.jabref.logic.importer.ParseException: CrossRef API JSON format has changed
	at org.jabref.logic.importer.fetcher.CrossRef.jsonItemToBibEntry(CrossRef.java:131) ~[JabRef-4.0.jar:?]
	at org.jabref.logic.importer.fetcher.CrossRef.lambda$getParser$3(CrossRef.java:88) ~[JabRef-4.0.jar:?]
	at org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(SearchBasedParserFetcher.java:60) ~[JabRef-4.0.jar:?]
	... 5 more
Caused by: org.json.JSONException: JSONObject["title"] not found.
	at org.json.JSONObject.get(JSONObject.java:471) ~[JabRef-4.0.jar:?]
	at org.json.JSONObject.getJSONArray(JSONObject.java:618) ~[JabRef-4.0.jar:?]
	at org.jabref.logic.importer.fetcher.CrossRef.jsonItemToBibEntry(CrossRef.java:113) ~[JabRef-4.0.jar:?]
	at org.jabref.logic.importer.fetcher.CrossRef.lambda$getParser$3(CrossRef.java:88) ~[JabRef-4.0.jar:?]
	at org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(SearchBasedParserFetcher.java:60) ~[JabRef-4.0.jar:?]
	... 5 more

```

**Comment by lenhard** [comment]
Well, the error message reads `CrossRef API JSON format has changed`. I wish they would do this less frequently...

**Comment by lenhard** [comment]
Appologies to CrossRef, they did not change the format. The error was actually that the search returned a few entries from CrossRef that do have titles and our code wasn't able to handle that.

I submitted a fix as pull request, it should be merged soon.
