### ISSUE TITLE
Jabref 4.0 freezes with unsaved file after DOI lookup and grouping

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3377]
```
JabRef 4.0
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```

Steps to reproduce:

1. Add new paper, select DOI, and lookup
`10.1103/PhysRevLett.119.177201`
![selection_372](https://user-images.githubusercontent.com/298682/32226786-d5f91138-be49-11e7-906e-a3de7f885bd9.png)

2. Jabref gets proper data and imports it. 
![selection_370](https://user-images.githubusercontent.com/298682/32226082-d6a4baee-be47-11e7-9c0b-feab25509284.png)

3. I drag a category 

![selection_373](https://user-images.githubusercontent.com/298682/32226848-f7d0d322-be49-11e7-8b50-2c800c3f3182.png)
over the article. Jabref freezes now. I can not even close it on the X icon and have to kill it.

I restarted and reproduced this with screenshots.
Output on stderr was

```
java -jar JabRef-4.0.jar 
14:39:08.736 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /data/literature.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
Oct 31, 2017 2:41:56 PM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method listen(org.jabref.model.database.event.EntryRemovedEvent) on subscriber org.jabref.gui.BasePanel$EntryRemovedListener@1b08b4e1 when dispatching event: org.jabref.model.database.event.EntryRemovedEvent@d569a03
java.lang.NullPointerException
	at org.jabref.gui.BasePanel$EntryRemovedListener.listen(BasePanel.java:2110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at org.jabref.model.database.BibDatabase.removeEntry(BibDatabase.java:250)
	at org.jabref.model.database.BibDatabase.removeEntry(BibDatabase.java:234)
	at org.jabref.gui.BasePanel.delete(BasePanel.java:797)
	at org.jabref.gui.BasePanel.lambda$setupActions$3(BasePanel.java:363)
	at org.jabref.gui.BasePanel.runCommand(BasePanel.java:1028)
	at org.jabref.gui.menus.RightClickMenu$GeneralAction.actionPerformed(RightClickMenu.java:312)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

4. The file was not saved. Can Jabref destroy the database by crashing with open files?
![selection_371](https://user-images.githubusercontent.com/298682/32226263-6033c07a-be48-11e7-81d7-447be5980ecd.png)

**Comment by jonasstein** [comment]
Thank you very much. 
I confirm, that it is fixed in 
```
JabRef 4.1-dev--snapshot--2017-10-31--master--42ea6bc9c
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```
sadly this major bug is now in the released 4.0 version.

**Comment by Siedlerchr** [comment]
@jonasstein  Thanks for the update. As you report a lot of bugs, which is fine, please do as a favor and test if they are already resolved in the latest dev version.  That helps us a lot to focus on the right issues.

**Comment by jonasstein** [comment]
@Siedlerchr will do so.
