### ISSUE TITLE
GOT A dragExit when dndGesture is null!

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3429]
JabRef version 4.1-dev (latest) on Arch

Steps to reproduce:

1. Click on "Get fulltext"

<details>
  <summary>Log File</summary>
  
  ```
15:05:09.807 [pool-3-thread-3] INFO  org.jabref.logic.importer.fetcher.DoiResolution - Fulltext PDF found @ https://doi.org/10.1515/9783110213881.2.920
java.lang.NullPointerException
        at javafx.embed.swing.SwingDnD$DnDTransferable.getTransferDataFlavors(SwingDnD.java:387)
        at sun.awt.dnd.SunDropTargetContextPeer.getTransferDataFlavors(SunDropTargetContextPeer.java:192)
        at sun.awt.datatransfer.TransferableProxy.getTransferDataFlavors(TransferableProxy.java:65)
        at java.awt.dnd.DropTargetContext$TransferableProxy.getTransferDataFlavors(DropTargetContext.java:344)
        at javafx.embed.swing.CachingTransferable.updateData(CachingTransferable.java:76)
        at javafx.embed.swing.SwingDragSource.updateContents(SwingDragSource.java:52)
        at javafx.embed.swing.SwingDnD$3.dragOver(SwingDnD.java:171)
        at java.awt.dnd.DropTarget.dragOver(DropTarget.java:382)
        at sun.awt.dnd.SunDropTargetContextPeer.processMotionMessage(SunDropTargetContextPeer.java:475)
        at sun.awt.X11.XDropTargetContextPeer.processMotionMessage(XDropTargetContextPeer.java:178)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchMotionEvent(SunDropTargetContextPeer.java:824)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:770)
        at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
        at java.awt.Component.dispatchEventImpl(Component.java:4744)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4599)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82  ```
</details>

**Comment by Siedlerchr** [comment]
Not reproducible under Windows 10 . Are you using GTK Look and Feel? It is known to make proble,sx

**Comment by j0hannes** [comment]
No, I use the default (Plastic)

**Comment by stefan-kolb** [comment]
Will be fixed in javafx-maintable-beta.
