### ISSUE TITLE
Google scholar search not working on High Sierra Automatic Bug Report - 20171128133811

### ISSUE THREAD

**Issue by DanteArucard** [JabRef/jabref#3462]
JabRef 4.0
Mac OS X 10.13.1 x86_64 
Java 1.8.0_151

Steps to reproduce:

1. just trying to search on google scholar
2. ...
3. ...

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Opening: /Users/dimitriognibene/Dropbox/pdf_jabref/bibliographynew.bib
Opening: /Users/dimitriognibene/Dropbox/personal/applications/CV BASE/reduced.bib
Error while fetching from Google Scholar
org.jabref.logic.importer.FetcherException: This might be caused by reaching the traffic limitation of Google Scholar (see 'Help' for details).
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:134)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3DMedial%2BOrbitofrontal%2BCortex%2BMediates%2BOutcome%2BRetrieval%2Bin%2BPartially%2BObservable%2BTask%2BSituations&hl=en&q=EgSb9UDcGLfE9dAFIhkA8aeDS4Ffj4-p87iTxXvy7BRRio7AnKPzMgFy
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:195)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:209)
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:142)
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:118)
	... 5 more
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3DMedial%2BOrbitofrontal%2BCortex%2BMediates%2BOutcome%2BRetrieval%2Bin%2BPartially%2BObservable%2BTask%2BSituations&hl=en&q=EgSb9UDcGLfE9dAFIhkA8aeDS4Ffj4-p87iTxXvy7BRRio7AnKPzMgFy
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:305)
	... 9 more

Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException
	at org.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344)
	at org.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:207)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:179)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException
	at org.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344)
	at org.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:207)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:179)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Error while fetching from Google Scholar
org.jabref.logic.importer.FetcherException: This might be caused by reaching the traffic limitation of Google Scholar (see 'Help' for details).
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:134)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dbarto%2Bintrinsic&hl=en&q=EgSb9UDcGJ3J9dAFIhkA8aeDS3xoQ-ZJxwhxuLTQWgmHlpKAJ-rxMgFy
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:195)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:209)
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:142)
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:118)
	... 5 more
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dbarto%2Bintrinsic&hl=en&q=EgSb9UDcGJ3J9dAFIhkA8aeDS3xoQ-ZJxwhxuLTQWgmHlpKAJ-rxMgFy
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:305)
	... 9 more

```

</details>

**Comment by lenhard** [comment]
Cannot reproduce on (Google Scholar search working as expected):
JabRef 4.1-dev
Windows 7 6.1 amd64 
Java 1.8.0_121

Have a look at the error message. It says: `This might be caused by reaching the traffic limitation of Google Scholar (see 'Help' for details).` Probably, Google Scholar is just blocking your IP.

For solutions, look here: https://help.jabref.org/en/GoogleScholar#traffic-limitations

**Comment by DanteArucard** [comment]
Thanks a lot,
but google scholar works perfectly in the browser.
-- 
Dimitri Ognibene, PhD
School of Computer Science and Electronic Engineering, University of Essex, UK

http://sites.google.com/site/dimitriognibenehomepage/
Skype: dimitri.ognibene

**Comment by Siedlerchr** [comment]
Both fetchers work in the latest master.
