### ISSUE TITLE
Fetching error

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#3463]
JabRef version 4 Windows7
First time I got this error. We have trouble with our university network, so it could explained. But in this case, I guess user should receive an error message (for now, it just turns endless).

```
107024 results found. Only 50 relevant results will be fetched by default.
Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException
	at org.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344)
	at org.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:207)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:179)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Thanks

**Comment by lenhard** [comment]
From the stacktrace you've posted, it looks like a bug. It shouldn't be too hard to fix. An additional null check at the respective position in code.

**Comment by curtcorum** [comment]
@melTr and @lenhard 

It may be something on the medline side! 

I am experiencing multiple versions of JabRef on multiple hosts that did work with Pubmed/Medline suddenly not working today. They were working as recently as yesterday. I went and tried a recent development snapshot to make sure.

20:00:38.641 [JabRef CachedThreadPool] ERROR net.sf.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException: null
	at net.sf.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:204) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:176) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:217) ~[JabRef-3.8.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]



20:07:59.728 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException: null
	at org.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at org.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:207) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:179) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216) ~[JabRef-4.1-dev--snapshot--2017-11-27--master--42a959d1d.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

Did something change in the medline output recently?

Is anybody else seeing this?

Curt

**Comment by curtcorum** [comment]
Possibly something has changed in the output format from medline...

"Late November 2017: PubMed's MEDLINE citations, translation tables, and the MeSH database will have been updated to reflect 2018 MeSH."

https://www.nlm.nih.gov/bsd/policy/yep_activities.html

**Comment by melTr** [comment]
Hmmm... @curtcorum You're probably right. I try on my home computer running Ubuntu 16.04 and I get the same error, so I guess it was not my network.

**Comment by Andyroo1966** [comment]
Having the same error running jabRef 4.0 on manjaro  java 1.8.0_144

721953 results found. Only 50 relevant results will be fetched by default.
Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.NullPointerException
	at org.jabref.logic.importer.fileformat.MedlineImporter.parseArticle(MedlineImporter.java:344)
	at org.jabref.logic.importer.fileformat.MedlineImporter.importDatabase(MedlineImporter.java:162)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.fetchMedline(MedlineFetcher.java:207)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:179)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lenhard** [comment]
It seems that they've made a part of the data (date created for articles) optional, but our code expected this to be there.

@melTr @Andyroo1966 @curtcorum I have pushed a fix and Medline fetch works for me again. Could you please try out the current dev version and let me know if it works for you: http://builds.jabref.org/master/

**Comment by melTr** [comment]
@lenhard Solved for me. Got other errors in journal but unrelated to this issue.

**Comment by lenhard** [comment]
Ok, thanks! Then I am closing this one.

**Comment by curtcorum** [comment]
Working, thanks!

JabRef 4.1-dev--snapshot--2017-11-29--master--42ba568ea
Linux 4.10.0-40-generic amd64 
Java 1.8.0_151

**Comment by Andyroo1966** [comment]
Working for me also.
JabRef-4.1-dev--snapshot--2017-12-03
linux 4.13.15-300.fc27.x86_64
java 1.8.0_151
