### ISSUE TITLE
Cannot start jabref.

### ISSUE THREAD

**Issue by lordloh** [JabRef/jabref#3489]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  JabRef-4.0.jar  on Windows 10

Steps to reproduce:

1. `java -jar JabRef-4.0.jar --prdef all -n`
 or
`java -jar JabRef-4.0.jar`

This results in 
```
13:47:00.433 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(TelemetryConfigurationFactory.java:65) ~[JabRef-4.0.jar:?]
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(TelemetryConfigurationFactory.java:53) ~[JabRef-4.0.jar:?]
        at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:70) ~[JabRef-4.0.jar:?]
        at org.jabref.Globals.startTelemetryClient(Globals.java:90) ~[JabRef-4.0.jar:?]
        at org.jabref.Globals.startBackgroundTasks(Globals.java:78) ~[JabRef-4.0.jar:?]
        at org.jabref.JabRefMain.start(JabRefMain.java:68) ~[JabRef-4.0.jar:?]
        at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:53) ~[JabRef-4.0.jar:?]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.EventQueue.access$500(Unknown Source) ~[?:?]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 21 more
```

also 

```
$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by lordloh** [comment]
As a work around, I have updated my windows shortcut in the start menu to start with the command -
`"C:\Program Files\Java\jre1.8.0_152\bin\java.exe" -jar "C:\Program Files\JabRef\JabRef-4.0.jar"` instead of the `jabref.exe`

**Comment by tobiasdiez** [comment]
You probably have Java9 installed and configured to be the default. As of now, JabRef is not compatible with Java9 #2594. Uninstalling Java9 or changing the default to Java8 should fix your problem.

**Comment by lordloh** [comment]
Yes. I had not used JabRef in a few weeks and had installed Java9 in that time. I have installed Java8 RE now and will probably hang around with the command line work around till JabRef updates for Java9.

Thank you!
