### ISSUE TITLE
External Group Changes result in NPE

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3526]
current master:
Open a   bib file
Modify the bib file in an external editor., add for example this group tree information:
```

@Comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:12\;0\;;
2 ExplicitGroup:1\;0\;;
2 ExplicitGroup:2\;0\;;
2 ExplicitGroup:3\;0\;;
2 ExplicitGroup:4\;0\;;
2 ExplicitGroup:5\;0\;;
2 ExplicitGroup:6\;0\;;
2 ExplicitGroup:7\;0\;;
2 ExplicitGroup:8\;0\;;
2 ExplicitGroup:9\;0\;;
2 ExplicitGroup:10\;0\;;
2 ExplicitGroup:11\;0\;;
2 ExplicitGroup:12\;0\;;
2 ExplicitGroup:13\;0\;;
2 ExplicitGroup:14\;0\;;
2 ExplicitGroup:15\;0\;;
0 ExplicitGroup:16\;0\;;
2 ExplicitGroup:17\;0\;;
}

```
Review changes lead to NPE

```
21:17:40.388 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at org.jabref.gui.collab.GroupChangeViewModel.makeChange(GroupChangeViewModel.java:50) ~[main/:?]
	at org.jabref.gui.collab.ChangeDisplayDialog.lambda$2(ChangeDisplayDialog.java:94) ~[main/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_152]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_152]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_152]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_152]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_152]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_152]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_152]
	at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_152]
	at java.awt.Container.processEvent(Container.java:2237) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_152]
	at java.awt.Container.dispatchEventImpl(Container.java:2295) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) ~[?:1.8.0_152]
	at java.awt.Container.dispatchEventImpl(Container.java:2281) ~[?:1.8.0_152]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_152]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_152]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_152]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:1.8.0_152]
	at java.awt.Dialog.show(Dialog.java:1084) ~[?:1.8.0_152]
	at java.awt.Component.show(Component.java:1671) ~[?:1.8.0_152]
	at java.awt.Component.setVisible(Component.java:1623) ~[?:1.8.0_152]
	at java.awt.Window.setVisible(Window.java:1014) ~[?:1.8.0_152]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:1.8.0_152]
	at org.jabref.gui.collab.ChangeScanner.lambda$1(ChangeScanner.java:89) ~[main/:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_152]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_152]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_152]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_152]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_152]

```

**Comment by Siedlerchr** [comment]
Deleting all group information,, for example the stuff I inserted also lead to an NPE.

```
1:29:57.446 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at org.jabref.gui.groups.UndoableModifySubtree.<init>(UndoableModifySubtree.java:28) ~[main/:?]
	at org.jabref.gui.collab.GroupChangeViewModel.makeChange(GroupChangeViewModel.java:32) ~[main/:?]
	at org.jabref.gui.collab.ChangeDisplayDialog.lambda$2(ChangeDisplayDialog.java:94) ~[main/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_152]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_152]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_152]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_152]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_152]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_152]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_152]
	at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_152]
	at java.awt.Container.processEvent(Container.java:2237) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_152]
	at java.awt.Container.dispatchEventImpl(Container.java:2295) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526) ~[?:1.8.0_152]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) ~[?:1.8.0_152]
	at java.awt.Container.dispatchEventImpl(Container.java:2281) ~[?:1.8.0_152]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_152]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_152]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_152]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_152]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_152]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_152]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:1.8.0_152]
	at java.awt.Dialog.show(Dialog.java:1084) ~[?:1.8.0_152]
	at java.awt.Component.show(Component.java:1671) ~[?:1.8.0_152]
	at java.awt.Component.setVisible(Component.java:1623) ~[?:1.8.0_152]
	at java.awt.Window.setVisible(Window.java:1014) ~[?:1.8.0_152]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:1.8.0_152]
	at org.jabref.gui.collab.ChangeScanner.lambda$1(ChangeScanner.java:89) ~[main/:?]
```
