### ISSUE TITLE
Deleting an entry causes NPE exception

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3584]
Delete an entry in the current master 64c774b 

```
SEVERE: Exception thrown by subscriber method listen(org.jabref.model.database.event.EntryRemovedEvent) on subscriber org.jabref.gui.BasePanel$EntryRemovedListener@600cdad9 when dispatching event: org.jabref.model.database.event.EntryRemovedEvent@3850ee8f
java.lang.NullPointerException
	at org.jabref.gui.BasePanel$EntryRemovedListener.listen(BasePanel.java:2092)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.model.database.BibDatabase.removeEntry(BibDatabase.java:252)
	at org.jabref.model.database.BibDatabase.removeEntry(BibDatabase.java:236)
	at org.jabref.gui.BasePanel.delete(BasePanel.java:803)
	at org.jabref.gui.BasePanel.lambda$7(BasePanel.java:369)
```

**Comment by Siedlerchr** [comment]
@tobiasdiez Seems to be a followup error from your recent changes:

       BibEntry previewEntry = selectionListener.getPreview().getEntry();
getPreview returns null
