### ISSUE TITLE
Entry preview and editor blank after 

### ISSUE THREAD

**Issue by kingwarrick** [JabRef/jabref#3608]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-01-04--master--1b06811df
Windows 10 10.0 amd64 
Java 1.8.0_151

Steps to reproduce:

1. Start JabRef
2. Open two databases
3. Select and open one entry for editing in first database
4. Click to open DOI or URL in browser
5. Select and open second entry for editing or preview in first database
6. Select and open third entry--will see a blank entry editor and preview
7. Select second database
8. Repeat #3-6 - entry editor shows fine until same routine as above (click to view URL/DOI, next entry shows, then blank for third.

Log file included, but does not seem to be repeated for each time this issue arises.

<details>
  <summary>Log File</summary>
```Opening: DOAJ-WaterGov-MLG-Indig-Eng.bib
Opening: Wiley-WaterGov-Indig-Eng.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 21) is not a valid range within [0, 21)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184)
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82)
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29)
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.lambda$addNotify$49(JFXPanel.java:799)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```
</details>
[Blank](https://user-images.githubusercontent.com/23559478/34622024-0fb5c11e-f211-11e7-82e3-4e732987f7d7.png)

**Comment by Siedlerchr** [comment]
Hi, thanks for your report. 
I just discovered and fixed a bug which could solve your issue:
Could you please try this version here and check if this works for you`?
https://builds.jabref.org/fixnpeonEntryChange/

**Comment by kingwarrick** [comment]
Hello,

Thank you for the quick work on this. I was away and did not get to try
the version on my Windows computer before the link disappeared. Is it
possible to get the link back up, or has it already been rolled into
master?

Warrick

**Comment by Siedlerchr** [comment]
Hi, it has already been merged in the master verison. So you can use that version

**Comment by kingwarrick** [comment]
The problem persists in both Windows and Mac:

JabRef 4.2-dev--snapshot--2018-01-09--master--728ddbf8f
Mac OS X 10.13.2 x86_64 
Java 1.8.0_152

JabRef 4.2-dev--snapshot--2018-01-09--master--728ddbf8f
Windows 10 10.0 amd64 
Java 1.8.0_151

I also seem to be able to trigger this behaviour another way:
1. Open first entry in entry editor
2. Cycle through Required, General, Abstract, Review, Source tabs in editor
3. Select second entry
4. Editor does not update, showing previous entry, and now exhibits blanking when clicking to different tabs.

For step 2, I tried many permutations and iterations, and found this the most reliable way to cause the issue.

**Comment by tobiasdiez** [comment]
Probably fixed with https://github.com/JabRef/jabref/pull/3591 (which is not yet completely ready to try out).

**Comment by kingwarrick** [comment]
Looks like a nice update. Please let me know when it is ready for testing and I will gladly do so.

**Comment by tobiasdiez** [comment]
@kingwarrick You can now try out the new version from https://builds.jabref.org/maintable-beta/ but please it is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
