### ISSUE TITLE
Linux rightclick on file-icon when multiple files does not work if one file ist a Text-file

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#3641]
JabRef 4.1
Linux 4.13.0-26-generic amd64 
Java 1.8.0_151

Steps to reproduce:

1. Open the bibfile below in JabRef on Linux
2. Rightklick on the file-icon
3. It should open a drop-down-menu which file to open, but it opens the first file.

[example.bib.txt](https://github.com/JabRef/jabref/files/1638862/example.bib.txt)

```bib
% Encoding: UTF-8
@Article{crick1975kinky,
  author   = {Crick, F.~H.~C and Klug, A},
  title    = {Kinky helix},
  journal  = {Nature},
  year     = {1975},
  volume   = {255},
  number   = {5509},
  pages    = {530--533},
  month    = jun,
  adsnote  = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl   = {http://adsabs.harvard.edu/abs/1975Natur.255..530C },
  doi      = {10.1038/255530a0},
  file     = {:PhDJK\\Literature\\DNA\\Weitere\\Crick_Klug_1975_Nature.pdf:PDF;:PhDJK\\Literature\\DNA\\Weitere\\Crick_Klug_1975_Nature.ocr:Text},
  groups   = {DNA},
  keywords = {rank2},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

My log details.
[JabRef.log](https://github.com/JabRef/jabref/files/1638873/JabRef.log)
```log
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jabref.gui.maintable.MainTableSelectionListener.showIconRightClickMenu(MainTableSelectionListener.java:388)
	at org.jabref.gui.maintable.MainTableSelectionListener.mouseReleased(MainTableSelectionListener.java:209)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
