### ISSUE TITLE
JabRef doesn't start if AutomaticKeywordGroup uses a semicolon as separator

### ISSUE THREAD

**Issue by elenziat** [JabRef/jabref#3646]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Windows 10
(JabRef 4.1, Windows 10 10.0 amd64, Java 1.8.0_144)

Steps to reproduce:

1. Open a bibtex-file ([test0.txt](https://github.com/JabRef/jabref/files/1643240/test0.txt)). Create Automatic keyword group. Use proposed standard values, only change "," to ";" as separator.
2. Close JabRef. The bibtex-file looks like this: [test.txt](https://github.com/JabRef/jabref/files/1643209/test.txt)
3. Start JabRef.
4. JabRef doesn't start: It appears in the task manager, using the CPU a short time and then stays at 0% CPU with a constant amount of RAM used. No window opens.

If within the test file the `\;` which stands for the separator (the second one after `keywords`, I guess) is changed to `,` or `-` JabRef opens again. If this `\;` is changed to `;` JabRef doesn't start.

Regards

**Comment by Siedlerchr** [comment]
Okay I could reproduce this: It produces an exception when parsing the line. Seems like it gets problems with the delimiter.
@tobiasdiez  What is your opinion: Should we disallow the semicolon as separator?


```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658) ~[?:1.8.0_162]
	at org.jabref.logic.importer.util.GroupsParser.automaticKeywordGroupFromString(GroupsParser.java:130) ~[main/:?]
	at org.jabref.logic.importer.util.GroupsParser.fromString(GroupsParser.java:99) ~[main/:?]
	at org.jabref.logic.importer.util.GroupsParser.importGroups(GroupsParser.java:47) ~[main/:?]
	at org.jabref.logic.importer.util.MetaDataParser.parse(MetaDataParser.java:65) ~[main/:?]
	at org.jabref.logic.importer.util.MetaDataParser.parse(MetaDataParser.java:35) ~[main/:?]
	at org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(BibtexParser.java:221) ~[main/:?]
	at org.jabref.logic.importer.fileformat.BibtexParser.parse(BibtexParser.java:154) ~[main/:?]
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:70) ~[main/:?]
	at org.jabref.logic.importer.Importer.importDatabase(Importer.java:88) ~[main/:?]
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:62) ~[main/:?]
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:72) ~[main/:?]
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:51) ~[main/:?]
	at org.jabref.JabRefGUI.openLastEditedDatabases(JabRefGUI.java:207) ~[main/:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:91) ~[main/:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:60) ~[main/:?]
	at org.jabref.JabRefMain.lambda$1(JabRefMain.java:193) ~[main/:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_162]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_162]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_162]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_162]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_162]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_162]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_162]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_162]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_162]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_162]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_162]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_162]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_162]
```

**Comment by tobiasdiez** [comment]
If somebody uses the semicolon as a keyword separator, then the automatic groups should support that as well. I think, this bug can easily be resolved by using the `StringUtil.(un)quote` commands to escape the separator.

**Comment by SachithS** [comment]
Hi,
I am a first-timer in open-source, can I look in to this or someone has already taken it? Please guide me.

**Comment by tobiasdiez** [comment]
@SachithS sure, go ahead! The relevant lines are
https://github.com/JabRef/jabref/blob/5e96d46bd24a851ad958af982f80ac383df44a3d/src/main/java/org/jabref/logic/importer/util/GroupsParser.java#L158-L159
and
https://github.com/JabRef/jabref/blob/5e96d46bd24a851ad958af982f80ac383df44a3d/src/main/java/org/jabref/logic/exporter/GroupSerializer.java#L174-L176

It probably suffices to add `quote/unquote` calls (as seen for other data). Please also add tests to https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/logic/importer/util/GroupsParserTest.java and https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/logic/exporter/GroupSerializerTest.java.

**Comment by SachithS** [comment]
@tobiasdiez, Thanks for helping-out. But it seems issue is closed. :smile: Will try to find another stater for me. Thanks again.
