### ISSUE TITLE
Edit entry panel freezes while adding a new entry

### ISSUE THREAD

**Issue by SilverSpirit** [JabRef/jabref#3660]
The most painless workaround I could find was saving, closing and reopening the library.

JabRef 4.1
Windows 10 10.0 amd64 
Java 1.8.0_161

Steps to reproduce:

1. Ctrl + n to add a new entry
2. Select "Article"

<details>
<summary>Detail information:</summary>

```
Opening: C:\Aditya\Text Detection\Literature\Keeper.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 29) is not a valid range within [0, 29)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184)
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82)
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29)
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by lenhard** [comment]
As suggested by the issue template, please try the newest dev version available here http://builds.jabref.org/master/

With this version (but on Win7) I cannot reproduce your problem, so there's a good chance this is already fixed.

**Comment by SilverSpirit** [comment]
Seems to work for now, thanks.
