### ISSUE TITLE
HTTP Response 502 from SAO/NASA Astrophysics Data System

### ISSUE THREAD

**Issue by csahlholdt** [JabRef/jabref#3750]
JabRef 4.1
Mac OS X 10.13.3 x86_64 
Java 1.8.0_152

Steps to reproduce:

1. Open JabRef and create a new BibTeX library.
2. Perform web search from "SAO/NASA Astrophysics Data System" for anything (e.g. Stancliffe as I did).

<details>
<summary>Detail information:</summary>

```
Error while fetching from SAO/NASA Astrophysics Data System
org.jabref.logic.importer.FetcherException: An I/O exception occurred
	at org.jabref.logic.importer.fetcher.AstrophysicsDataSystem.performSearch(AstrophysicsDataSystem.java:142)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://adsabs.harvard.edu/cgi-bin/nph-basic_connect?data_type=BIBTEXPLUS&start_nr=1&nr_to_return=200&qsearch=Stancliffe
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.jabref.logic.importer.fetcher.AstrophysicsDataSystem.performSearch(AstrophysicsDataSystem.java:135)
	... 5 more
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for reporting.
Works as expected. An Error 502 often indicates a temporary Error on the server side. I just tested it manually in the browser and in JabRef. Works fine.
So maybe a temporary problem
