### ISSUE TITLE
Unable to drag-and-drop an item to the group tree

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#3752]
* [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-02-20--master--ae3aed804
Windows 8.1 6.3 x86 
Java 1.8.0_161

Step to reproduce:

1. Drag an item into a group.

The item won't be added to the group. The cursor shows a "forbidden" sign.

<details>
  <summary>Log File</summary>
  
  ```
  13:27:36.563 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NoClassDefFoundError: Could not initialize class org.jabref.gui.DragAndDropDataFormats
        at org.jabref.gui.groups.GroupNodeViewModel.acceptableDrop(GroupNodeViewModel.java:251) ~[JabRef-4.2-dev--snapshot--2018-02-20--master--ae3aed804.jar:?]

        at org.jabref.gui.groups.GroupTreeController.lambda$initialize$14(GroupTreeController.java:213) ~[JabRef-4.2-dev--snapshot--2018-02-20--master--ae3aed804.jar:?]
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
        at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
        at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933) ~[jfxrt.jar:?]
        at javafx.scene.Scene$DnDGesture.processTargetEnterOver(Scene.java:3105) ~[jfxrt.jar:?]
        at javafx.scene.Scene$DnDGesture.access$6100(Scene.java:2909) ~[jfxrt.jar:?]
        at javafx.scene.Scene$DropTargetListener.dragOver(Scene.java:2830) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragOver$309(GlassSceneDnDEventHandler.java:110) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragOver(GlassSceneDnDEventHandler.java:107) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.EmbeddedSceneDT.lambda$handleDragOver$320(EmbeddedSceneDT.java:115) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.EmbeddedSceneDnD.lambda$executeOnFXThread$301(EmbeddedSceneDnD.java:113) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

  ```
</details>

**Comment by lenhard** [comment]
I just tested this on the current master (both, by building it from source and by installing the version available at builds.jabref.org) and unfortunately I cannot reproduce your problem. Dragging entries onto groups works just fine.

Also your error message is very strange. I have no clue how it's possible to not find the class `DragAndDropDataFormats` except if something went really wrong during packaging.

I guess we are going to need more information to reproduce that, e.g. every tiny step from installing JabRef to getting the error.

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
