### ISSUE TITLE
No-GUI mode (--nogui) should not try to use DISPLAY

### ISSUE THREAD

**Issue by auge** [JabRef/jabref#3754]
JabRef version 4.1 on RedHat 7 using JRE 1.8.0-162

Steps to reproduce:

1. use a headless (RH) Linux system that provides no DISPLAY
2. run only command line feature: 
3. java -jar JabRef-4.1.jar -n --help

<details>
  <summary>JabRef does not run when invoked with the --nogui option and no DISPLAY is available.</summary>
  
  ```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for the report.  Definitely a thing to consider.  From what I saw, TestFX is relying on monocle to run in headless environment 
https://github.com/TestFX/Monocle

**Comment by Siedlerchr** [comment]
Hi, I  think I actually found a way which could work:
But in my test I still got an exception from the Telemetry client, I will try around  if I can disable that in headless mode

You first need to install `openjdk8` and `openjfx`

Then you can start it from commandline using this options:
``` 
java -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -jar JabRef--master--latest.jar -n --help
```

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by auge** [comment]
Thanks, it was working as soon as I had manually downloaded openjfx-monocle to .../jre/lib/ext/ ( as indicated by https://jeromecambon.wordpress.com/2016/03/15/testing-javafx-in-headless-mode/ )
