### ISSUE TITLE
Edit window gets unusable after one or two additions

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#3777]
Just upgraded to version 4.1 and after one or two additions, the following happens:

1) I add a new entry, e.g. "article"
2) the edit pane with all the tabs does not show any fields and cannot be used
3) the tabs often only get displayed partly

After this, the edit pane is unusable and I have to re-start jabref. This makes using jabref 
essentially impossible for me. 

I do not know if there is a way to reliably reproduce this or avoid it.

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

4.1

<details>
  <summary>Log File</summary>
  
  ```
22:13:57.693 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 17) is not a valid range within [0, 17)
	at org.reactfx.util.Lists.checkRange(Lists.java:128) ~[JabRef-4.1.jar:?]
	at org.reactfx.util.Lists.checkRange(Lists.java:123) ~[JabRef-4.1.jar:?]
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85) ~[JabRef-4.1.jar:?]
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78) ~[JabRef-4.1.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257) ~[JabRef-4.1.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Scene.doLayoutPass(Scene.java:552) ~[jfxrt.jar:?]
	at javafx.scene.Scene.preferredSize(Scene.java:1646) ~[jfxrt.jar:?]
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720) ~[jfxrt.jar:?]
	at javafx.stage.Window$9.invalidated(Window.java:864) ~[jfxrt.jar:?]
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109) ~[jfxrt.jar:?]
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144) ~[jfxrt.jar:?]
	at javafx.stage.Window.setShowing(Window.java:940) ~[jfxrt.jar:?]
	at javafx.stage.Window.show(Window.java:955) ~[jfxrt.jar:?]
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58) ~[jfxrt.jar:?]
	at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

  ```
</details>

**Comment by Siedlerchr** [comment]
Known issue due to the interaction between the old and new UI technology . Should already be fixed in the latest development version.
Please always try the latest dev version before reporting an issue, because the issue might have already been resolved.
