### ISSUE TITLE
JabRef throws exception when started in another language with missing fxml localization

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3796]
Tried to test #3795 
@koppor  It might actually be useful to add the missing keys to other language files.

```

16:07:34.023 [JavaFX Application Thread] ERROR org.jabref.gui.util.ControlHelper - Problem loading fxml for control
javafx.fxml.LoadException: Resource "Close window" not found.
/E:/workspace/JabRef/jabref/bin/main/org/jabref/gui/entryeditor/EntryEditor.fxml:22

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:103) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.resolvePrefixedValue(FXMLLoader.java:424) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:363) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at org.jabref.gui.util.ControlHelper.loadFXMLForControl(ControlHelper.java:29) ~[main/:?]
	at org.jabref.gui.entryeditor.EntryEditor.<init>(EntryEditor.java:76) ~[main/:?]
```
```

**Comment by tobiasdiez** [comment]
The relevant code in the FXMLLoader is 
````java
400  } else if (aValue.startsWith(RESOURCE_KEY_PREFIX)) {
401      aValue = aValue.substring(RESOURCE_KEY_PREFIX.length());
402      if (aValue.length() == 0) {
403          throw new LoadException("Missing resource key.");
404      }
405      if (aValue.startsWith(RESOURCE_KEY_PREFIX)) {
406          // The prefix was escaped
407          warnDeprecatedEscapeSequence(RESOURCE_KEY_PREFIX);
408          return aValue;
409      } else {
410          // Resolve the resource value
411          if (resources == null) {
412              throw new LoadException("No resources specified.");
413          }
414          if (!resources.containsKey(aValue)) {
415              throw new LoadException("Resource \"" + aValue + "\" not found.");
416          }
418          return resources.getString(aValue);
419      }
420  } else if (aValue.startsWith(EXPRESSION_PREFIX)) {
````
Hence, as soon as the resource does not contain the language key, the load exception is thrown.  There are two ways to fix this:
- Add (empty) key-value pairs for every string and for every language
- Always return true here:
https://github.com/JabRef/jabref/blob/cf8e6aac8263ce30eb2b042c8aacf2d88bbac4c8/src/main/java/org/jabref/logic/l10n/Localization.java#L243-L245

**Comment by Siedlerchr** [comment]
The problem is now that the Duplication finder complains about duplicates and I think this is a problem with the merge of #3798

**Comment by koppor** [comment]
Which duplicates? Did git merge something wrong? We should remove the
untranslated keys again from the translation files or are they already
removed?

Am 09.03.2018 18:03 schrieb "Christoph" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
We should remove the English values from the tl property again. Then the test should be green again (git merge probably kept the English values I initially added to make Jabref work)
