### ISSUE TITLE
Blank "File annotations" tab

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#3809]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-05--master--aeea686e3
Windows 8.1 6.3 x86 
Java 1.8.0_161

Step to reproduce:

1. Click on the "File annotations" tab (for an entry with PDF file)

<details>
  <summary>Log File</summary>
  
  ```
  Mar 05, 2018 4:15:14 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.
16:15:14.430 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: [some_filename].bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case

----------------------------[File annotations is clicked...]----------------------------

File: fileannotationtab.fxml not found, attempting with camel case
16:15:34.915 [JavaFX Application Thread] ERROR org.jabref.gui.DefaultInjector -
Cannot instantiate dependency: interface org.jabref.model.util.FileUpdateMonitor

java.lang.InstantiationException: org.jabref.model.util.FileUpdateMonitor
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_161]
        at org.jabref.gui.DefaultInjector.createDependency(DefaultInjector.java:43) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Injector.java:114) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:147) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:132) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Injector.java:105) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Injector.java:57) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.DefaultInjector.instantiatePresenter(DefaultInjector.java:58) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.lambda$loadSynchronously$1(FXMLView.java:96) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]

        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
        at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:137) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.AbstractView.getView(AbstractView.java:28) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTab.bindToEntry(FileAnnotationTab.java:29) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.entryeditor.EntryEditorTab.lambda$notifyAboutFocus$0(EntryEditorTab.java:42) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

Caused by: java.lang.NoSuchMethodException: org.jabref.model.util.FileUpdateMonitor.<init>()
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_161]
        ... 31 more

16:15:34.946 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IllegalStateException: Cannot load org.jabref.gui.entryeditor.fileannotationtab.fileannotationtab
        at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:101) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:137) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.AbstractView.getView(AbstractView.java:28) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTab.bindToEntry(FileAnnotationTab.java:29) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.entryeditor.EntryEditorTab.lambda$notifyAboutFocus$0(EntryEditorTab.java:42) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

Caused by: javafx.fxml.LoadException: file:/[masked path]/JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar!/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTab.fxml:21

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
        at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        ... 12 more

Caused by: java.lang.NullPointerException
        at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:131) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Injector.java:114) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:147) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:132) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Injector.java:105) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Injector.java:57) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at org.jabref.gui.DefaultInjector.instantiatePresenter(DefaultInjector.java:58) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at com.airhacks.afterburner.views.FXMLView.lambda$loadSynchronously$1(FXMLView.java:96) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
        at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-05--master--aeea686e3.jar:?]
        ... 12 more
  ```
</details>

**Comment by Siedlerchr** [comment]
Should be fixed now and in the next dev version. Thanks for reporting!

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
