### ISSUE TITLE
Automatic Bug Report - 20180307164431

### ISSUE THREAD

**Issue by lucy-kim** [JabRef/jabref#3814]
JabRef 4.1
Mac OS X 10.13.3 x86_64 
Java 1.8.0_161

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
<summary>Detail information:</summary>

```
Opening: /Users/kimk13/Dropbox/Research/dissertn_bib.bib
Error while fetching from Google Scholar
org.jabref.logic.importer.FetcherException: This might be caused by reaching the traffic limitation of Google Scholar (see 'Help' for details).
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:134)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dziedan&hl=en&q=EgTYpX59GK-6gdUFIhkA8aeDS62Kfl7xzSF3gJVojvLVp_BM5NpyMgFy
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:196)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:210)
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:142)
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:118)
	... 5 more
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://ipv4.google.com/sorry/index?continue=https://scholar.google.com/scholar%3Fhl%3Den%26btnG%3DSearch%26q%3Dziedan&hl=en&q=EgTYpX59GK-6gdUFIhkA8aeDS62Kfl7xzSF3gJVojvLVp_BM5NpyMgFy
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:306)
	... 9 more

```

</details>

**Comment by Siedlerchr** [comment]
As Google Scholar works  here it is probably that you reached the server limit and are now blocked for a while from using google scholar.
