### ISSUE TITLE
Exception when trying to save linked file

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3818]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-06--master--bb471a26d
Linux 4.4.0-104-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. Create an entry with a URL leading to a PDF file, like this: https://www.gla.ac.uk/media/media_452489_en.pdf
2. Right-click the entry in the entry table.
3. Choose "Copy linked files to folder...".
4. Choose your home folder.

<details>
File: copyfilesdialog.fxml not found, attempting with camel case
10:16:05.694 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IllegalStateException: Cannot load org.jabref.gui.copyfiles.copyfilesdialog
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:101) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:125) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:137) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at org.jabref.gui.AbstractView.getView(AbstractView.java:28) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at org.jabref.gui.copyfiles.CopyFilesDialogView.show(CopyFilesDialogView.java:25) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at org.jabref.gui.copyfiles.CopyFilesAction.showDialog(CopyFilesAction.java:63) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at org.jabref.gui.copyfiles.CopyFilesAction.lambda$startServiceAndshowProgessDialog$3(CopyFilesAction.java:58) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: javafx.fxml.LoadException: 
file:/home/erelsgl/Dropbox/papers/JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar!/org/jabref/gui/copyfiles/CopyFilesDialog.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[?:1.8.0_161]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[?:1.8.0_161]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_161]
	at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:99) ~[jfxrt.jar:?]
	at javafx.beans.binding.ListExpression.addAll(ListExpression.java:266) ~[jfxrt.jar:?]
	at org.jabref.gui.copyfiles.CopyFilesDialogViewModel.<init>(CopyFilesDialogViewModel.java:14) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at org.jabref.gui.copyfiles.CopyFilesDialogController.initialize(CopyFilesDialogController.java:34) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[?:1.8.0_161]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[?:1.8.0_161]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef-4.2-dev--snapshot--2018-03-06--master--bb471a26d.jar:?]
	... 13 more

</details>

**Comment by Siedlerchr** [comment]
This error has probably todo with the File Annotation Tab. One line in the code needs to be adapted

**Comment by tobiasdiez** [comment]
Thank you for your report. This issue should be fixed now in the latest development version. Could you please check the build from http://builds.jabref.org/master/.

**Comment by erelsgl** [comment]
Now I do not see the exception anymore, but the file is not downloaded - I get an error dialog box saying "No content in table".

**Comment by Siedlerchr** [comment]
Yes, that's right. The functionality is only for copying exiting linked physical files of an entry to an external folder.
What you want to do is in the Entry  Eiditor -> general Tab -> Download from url

**Comment by tobiasdiez** [comment]
@Siedlerchr Could you please update the dialog and show are more helpful message, something like "no file to copy".
