### ISSUE TITLE
Changes to preferences are not saved

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3845]
JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. open options/preferences
2. make any change, e.g., entry table columns, or export sort order, or anything afaik
3. press OK

Nothing happens.  The preferences window stays open, and no changes are saved.

Log:

Opening: /home/dom/Dropbox/Projects/HSSA/issue 5.2 rasayana issue/07 Sehnalova/paper/sehnalova.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
	at org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
	at org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
	at org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
	at org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
	at org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
	at org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
	at org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
	at org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
	at org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
	at org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
	at org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
	at org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
	at org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
	at org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
	at org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
	at org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
	at org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
	at org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
	at org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
	at org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
	at org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Siedlerchr** [comment]
You seem to have some odd things in your Preview Preferences Tab, Could you try adding and removing some of the Preview Styles? and see if it works afterwards?

**Comment by wujastyk** [comment]
I went into Options/Entry preview and deleted the three "current preview"
selections that I have.  But then, of course, I still couldn't save the
change.  Pressing "OK" did nothing.

I'm not aware of having any odd things in the preview preferences tab.  I
have selected three standard styles from the collection on the left window,
that's all.  What are you seeing that looks odd?

Best,
Dominik



------------------------

JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64
Java 1.8.0_161

Log:
Opening: /home/dom/Dropbox/Projects/HSSA/issue 5.2 rasayana issue/07
Sehnalova/paper/sehnalova.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib


​
--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
​,​

Singhmar Chair in Classical Indian Society and Polity
​,​

Department of History and Classics <http://historyandclassics.ualberta.ca/>
​,​
University of Alberta, Canada
​.​

South Asia at the U of A:

​sas.ualberta.ca​
​​

**Comment by wujastyk** [comment]
I opened JabRef 4.0, went into Options/Preferences/Entry preview, and I was able to delete the selected styles in the right pane.  But I had to do each one separately, followed by a save.  Finally I was down to the default "Preview", and could save.

Then I reopened 
JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64 
Java 1.8.0_161

and I could now add and remove styles and save.

But with other Options/Preferences, I could still not save.  For example I can't change the Appearance.   I mean, I can change it, but I can't save the change.  Checking many other settings at random, I can't save changes to any of them.

**Comment by Siedlerchr** [comment]
Hm. The error indicates that something with storing the current cycled position of the preview (when you cycle through the entry preview layouts with F9) is wrong. 
Whenever you cycle through the entry previews, the current cycle position is stored. And there  the error was raised. 

https://github.com/JabRef/jabref/blob/ae6d01be46c96ef57e9871dfeb208ab0b7aab295/src/main/java/org/jabref/preferences/PreviewPreferences.java#L75-L82

**Comment by Siedlerchr** [comment]
Do you get now different errors in the log or still the same when you try to save prefs in 4.2?

**Comment by tobiasdiez** [comment]
In line 80, you may divide by `0` (implicitly using the reminder `%` operation) and thus the error occurs.

**Comment by wujastyk** [comment]
This is the log after opening
JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64
Java 1.8.0_161,
opening Options/Preferences and trying (and failing) to change Appearance:

Opening: /home/dom/Dropbox/Projects/HSSA/issue 5.2 rasayana issue/07
Sehnalova/paper/sehnalova.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
    at
org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
    at
org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
    at
org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
    at
org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
    at
org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
    at
org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
    at
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2237)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2295)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
    at java.awt.Container.dispatchEventImpl(Container.java:2281)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArithmeticException: / by zero
    at
org.jabref.preferences.PreviewPreferences$Builder.withPreviewCyclePosition(PreviewPreferences.java:80)
    at
org.jabref.preferences.PreviewPreferences$Builder.withPreviewCycle(PreviewPreferences.java:72)
    at
org.jabref.gui.preftabs.PreviewPrefsTab.storeSettings(PreviewPrefsTab.java:247)
    at
org.jabref.gui.preftabs.PreferencesDialog.storeAllSettings(PreferencesDialog.java:243)
    at
org.jabref.gui.preftabs.PreferencesDialog.access$000(PreferencesDialog.java:54)
    at
org.jabref.gui.preftabs.PreferencesDialog$OkAction.actionPerformed(PreferencesDialog.java:271)
    at
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2237)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2295)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
    at java.awt.Container.dispatchEventImpl(Container.java:2281)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


​
--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
​,​

Singhmar Chair in Classical Indian Society and Polity
​,​

Department of History and Classics <http://historyandclassics.ualberta.ca/>
​,​
University of Alberta, Canada
​.​

South Asia at the U of A:

​sas.ualberta.ca​
​​

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by wujastyk** [comment]
My simple tests show that changing and then saving preferences now works
fine.  Many thanks!

​​

**Comment by douglasrizzo** [comment]
Sorry if this is not the place to ask this, but are the preferences saved in a file? If so, where is it located?

**Comment by douglasrizzo** [comment]
Nevermind, I found them at `~/.java/.userPrefs/org/jabref`.

**Comment by Siedlerchr** [comment]
The storage location is the default preference storage location from Java. It differs on systems. On Unix it's stored in files, in windows in the registry
