### ISSUE TITLE
Requested texture dimensions require dimensions that exceed maximum texture size

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3846]
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.4.0-116-generic amd64 
Java 1.8.0_161

Steps to reproduce:

This exception happens apparently at random. Last time, it happened when I deleted some entries. Before that, it happened when I tried to edit an entry. It happens quite often, but I still did not find a specific set of actions that reproduces it.

<details>
java.lang.RuntimeException: Requested texture dimensions (1107x2147483647) require dimensions (1107x0) that exceed maximum texture size (16384)
	at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
	at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)

</details>

**Comment by Siedlerchr** [comment]
As I never encoutered that exception and reading around it seems like it is caused by some control which is not seized propertly. Do you use a high dpi or a monitor with a high resolution?

**Comment by erelsgl** [comment]
Here is the window showing my display settings. I have Ubuntu 16.04 if that matters.
![screenshot from 2018-03-14 11-58-44](https://user-images.githubusercontent.com/1462215/37395556-27a9b39a-277f-11e8-8b90-13ddca1246f5.png)

**Comment by stefan-kolb** [comment]
Do you experience any wrong behavior from Jabref? Or is it just that the Exception is logged but everything working "fine" for you?

**Comment by erelsgl** [comment]
Sometimes this exception does no harm, but sometimes JabRef hangs (freezes) and when I look at the console I see this exception.
Maybe the two are unrelated - I did not find out yet.

**Comment by Siedlerchr** [comment]
This is probably one of our javafx/swing issues.
. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.

**Comment by stefanSchuhbaeck** [comment]
I encountered the same (or similar?) exception  and when it happens I can not edit an item (see image). 
Here some information about the version
JabRef 4.1 / Linux 3.10.0-693.21.1.el7.x86_64 amd64 / Java 1.8.0_161 / Centos with KDE

![jabref-error](https://user-images.githubusercontent.com/11520228/38099140-265c1ecc-337a-11e8-908f-e39547a45bec.png)

**Comment by stefanSchuhbaeck** [comment]
With JabRef--master--latest.jar I still get a RuntimeException but with a different required dimension. The gui problem however (red rectangle in my previous post) did not happened again. The JabRef-4.2-dev--snapshot--2018-03-30--master--3d0853325.jar also created the exception. I didn't find a pattern to reproduce it every time. 

<details>

```
java.lang.RuntimeException: Requested texture dimensions (1908x2147483647) require dimensions (1908x0) that exceed maximum texture size (16384)
        at com.sun.prism.es2.ES2RTTexture.create(ES2RTTexture.java:220)
        at com.sun.prism.es2.ES2ResourceFactory.createRTTexture(ES2ResourceFactory.java:157)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by Siedlerchr** [comment]
Could you please test if the current development version still causes the issues?
https://builds.jabref.org/master/

**Comment by stefanSchuhbaeck** [comment]
Hi, with JabRef--master--latest.jar I do not get any exceptions after a short test. 
The GUI problem also does not show up and it feels more responsive. 

Note: Since the last test I change my setup from centos/kde to fedora28/kde
