### ISSUE TITLE
Science Direct API broken

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3852]
```
ScienceDirect API request failed
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at org.jabref.logic.importer.fetcher.ScienceDirect.getUrlByDoi(ScienceDirect.java:87)
	at org.jabref.logic.importer.fetcher.ScienceDirect.findFullText(ScienceDirect.java:47)
	at org.jabref.logic.importer.FulltextFetchers.findFullTextPDF(FulltextFetchers.java:50)
	at org.jabref.gui.fieldeditors.LinkedFilesEditorViewModel.lambda$fetchFulltext$5(LinkedFilesEditorViewModel.java:181)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:39)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:98)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
	... 14 more
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
	... 15 more
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:106)
	at org.json.JSONArray.<init>(JSONArray.java:145)
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
	... 16 more
```

Full text download seems to be really slow too now...

**Comment by Siedlerchr** [comment]
Is this fixed with your pr?

**Comment by stefan-kolb** [comment]
Not sure, i think this has another cause.

**Comment by stefan-kolb** [comment]
I tested a few downloads and the log did not appear. Tests are also green again, so closing this for now.
