### ISSUE TITLE
On macOS 10.13 no windows/menus shown when starting

### ISSUE THREAD

**Issue by eduardkareletc** [JabRef/jabref#3889]
When starting JabRef only the application name is shown in the menu bar and no windows are presented. The menu system seems disabled as Apple events also do not work (the application does not respond to 'quit' from the taskbar, it can only be terminated by 'force-quit').

However, the application loads the known database and keeps consuming CPU cycles. In fact, at start it also presents a dialog asking if a found backup should be used to reconstruct one of the databases.

This behaviour started some time after  I upgraded to High Sierra and after I installed Java 9. 
- [√ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists (4.2-dev--snapshot--2018-03-23--master--c2b79b866)

JabRef version 4.1 on Mac OS X 10.13.3 (17D47). By running the Jar file I have tested this with Java version 1.8. (141) and (162), without any difference in this respect. (For Java release 141, the message is given that JabRef doesn't support it, yet it runs anyway). 

A similar issue has been reported as #3298, which has been closed without a clear way to resolve the problem. The reference in the comments to that issue to yet another issue seems irrelevant. 

Steps to reproduce, either:
-- double click the application icon
-- run the jar file.
The details show the command line to execute the jar file and the output it produces. It shows that the windowing system has actually been initialised.

<details>
  <summary>Log File</summary>
  + /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java -XX:+UseG1GC -XX:+UseStringDeduplication -XX:StringTableSize=1000003 -jar /Applications/JabRef.app/Contents/java/app/JabRef-4.2-dev--snapshot--2018-03-23--master--c2b79b866.jar --debug
err = 3 ../mach-override-src/mach_override.c:244
err = 3 ../mach-override-src/mach_override.c:258
err = 3 ../mach-override-src/mach_override.c:263
err = 3 ../mach-override-src/mach_override.c:244
err = 3 ../mach-override-src/mach_override.c:258
err = 3 ../mach-override-src/mach_override.c:263
err = 3 ../mach-override-src/mach_override.c:244
err = 3 ../mach-override-src/mach_override.c:258
err = 3 ../mach-override-src/mach_override.c:263
AI: INFO 24-03-2018 18:02, 19: Configuration file has been successfully found as resource
18:02:43.298 [AWT-EventQueue-0] DEBUG org.jabref.logic.logging.JabRefLogger - Showing debug messages
18:02:43.302 [AWT-EventQueue-0] DEBUG org.jabref.cli.ArgumentProcessor - Finished export
18:02:52.180 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Archive/Projects/Dropbox/COPP-PARL/design/documentation/COPP-documentation_own_references.bib
18:02:52.352 [AWT-EventQueue-0] DEBUG org.jabref.logic.importer.OpenDatabase - Synchronized special fields based on keywords
18:02:52.359 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Archive/Projects/Dropbox/papers/-bib/iacr_ascii.bib
18:02:53.550 [AWT-EventQueue-0] DEBUG org.jabref.logic.importer.OpenDatabase - Synchronized special fields based on keywords
18:02:53.552 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Archive/Projects/marsaglia hash/papers/xorshift+.bib
18:02:53.609 [AWT-EventQueue-0] DEBUG org.jabref.logic.importer.OpenDatabase - Synchronized special fields based on keywords
18:02:53.899 [AWT-EventQueue-0] DEBUG org.jabref.JabRefGUI - Initializing frame
File: grouptree.fxml not found, attempting with camel case
18:02:54.835 [JavaFX Application Thread] DEBUG org.jabref.gui.DefaultInjector - Instantiate org.jabref.gui.groups.GroupTreeController
File: grouptree.css not found, attempting with camel case
</details>

**Comment by Siedlerchr** [comment]
@LinusDietz  any idea what this might be? Some path confusing?

**Comment by LinusDietz** [comment]
@Siedlerchr @eduardkareletc Well, it is somewhat unlikely that this is on JabRef's side. However, we really should get it running in any java8/9 environment.
Looking at the log file, my number one suspicion would be that any other instance of JabRef was still running?

**Comment by eduardkareletc** [comment]
No other instance was running. I just rechecked that (with both ps and jps.)

As a further trial I have build the most recent version from the Master 
repo, which still has the same issue. I ran the release jar in /bin/sh 
without  JAVA_PATH and the full path to the JVM binary as in the posted 
log.

An initial modal dialog is shown asking for permission to open a .bib 
backup file. Both buttons in that dialog are responsive. So some part of 
the windowing system is working.

jconsole shows the jabref process  active in allocating and releasing 
heap memory. (every 20+seconds)
-- 
Eduard

Linus Dietz wrote:

**Comment by koppor** [comment]
Refs #3905

**Comment by domhardt** [comment]
All 4.x and development versions of 5 are unusable on MacOS 10.13.6 (fresh install) with Oracle JDK 8. Here are some logs:

**Java Version**
`$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)`

**Latest "stable" version of JabRef**
`$ java -jar JabRef-4.3.1.jar`
starts up with some errors and opens the application window and my bib-file until I click on one table row:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getSlotResource(LogicalFont.java:296)
	at com.sun.javafx.font.CompositeGlyphMapper.getSlotMapper(CompositeGlyphMapper.java:74)
	at com.sun.javafx.font.CompositeGlyphMapper.getAsciiGlyphCode(CompositeGlyphMapper.java:119)
	at com.sun.javafx.font.CompositeGlyphMapper.getGlyphCode(CompositeGlyphMapper.java:142)
	at com.sun.javafx.font.CharToGlyphMapper.charsToGlyphs(CharToGlyphMapper.java:84)
	at com.sun.javafx.font.CharToGlyphMapper.charsToGlyphs(CharToGlyphMapper.java:93)
	at com.sun.javafx.webkit.prism.WCFontImpl.getGlyphCodes(WCFontImpl.java:170)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$49(WebEngine.java:1228)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
17:53:15.565 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at com.sun.javafx.text.PrismTextLayout.getText(PrismTextLayout.java:920) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1015) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.getLogicalBounds(Text.java:358) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.impl_computeGeomBounds(Text.java:1168) ~[jfxrt.jar:?]
	at javafx.scene.Node.updateGeomBounds(Node.java:3577) ~[jfxrt.jar:?]
	at javafx.scene.Node.getGeomBounds(Node.java:3530) ~[jfxrt.jar:?]
	at javafx.scene.Node.getLocalBounds(Node.java:3478) ~[jfxrt.jar:?]
	at javafx.scene.Node.updateTxBounds(Node.java:3641) ~[jfxrt.jar:?]
	at javafx.scene.Node.getTransformedBounds(Node.java:3424) ~[jfxrt.jar:?]
	at javafx.scene.Node.updateBounds(Node.java:559) ~[jfxrt.jar:?]
	at javafx.scene.Parent.updateBounds(Parent.java:1717) ~[jfxrt.jar:?]
	at javafx.scene.Parent.updateBounds(Parent.java:1717) ~[jfxrt.jar:?]
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
17:53:15.602 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
```
![bildschirmfoto 2018-09-19 um 17 54 43](https://user-images.githubusercontent.com/1955290/45765571-9aba7680-bc35-11e8-9b96-43dd7c3a8e5b.png)
Edit box stays blank.

**Latest development version of JabRef**
crashes right after the start without any sign of the application window:
```
$ java -jar JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar
18:01:20.698 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /Users/michael/Desktop/TestBibFile/Literatur.bib
18:01:22.010 [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.lang.NullPointerException: null
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99) ~[jfxrt.jar:?]
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740) ~[jfxrt.jar:?]
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469) ~[jfxrt.jar:?]
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194) ~[jfxrt.jar:?]
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409) ~[jfxrt.jar:?]
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413) ~[jfxrt.jar:?]
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.getTextLayout(Text.java:229) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.access$200(Text.java:95) ~[jfxrt.jar:?]
	at javafx.scene.text.Text$2.invalidated(Text.java:389) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.setText(Text.java:370) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.<init>(Text.java:129) ~[jfxrt.jar:?]
	at org.jabref.gui.icon.InternalMaterialDesignIcon.getGraphicNode(InternalMaterialDesignIcon.java:60) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.gui.icon.IconTheme$JabRefIcons.getGraphicNode(IconTheme.java:339) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.gui.search.SearchTextField.create(SearchTextField.java:14) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.gui.search.GlobalSearchBar.<init>(GlobalSearchBar.java:77) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:153) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:88) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef-5.0-dev--snapshot--2018-09-19--master--d8f6c5cec.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) [jfxrt.jar:?]
```

**Latest working version of JabRef**

$ java -jar JabRef-3.8.2.jar 
```
18:06:09.485 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: /Users/michael/Desktop/TestBibFile/Literatur.bib
18:06:25.147 [AWT-EventQueue-0] WARN  net.sf.jabref.gui.date.DatePickerButton - Unable to parse stored date for field 'date' with current settings. Clear button in calender popup will not work.
```
![bildschirmfoto 2018-09-19 um 18 06 27](https://user-images.githubusercontent.com/1955290/45766026-e0c40a00-bc36-11e8-8f16-863b74cf37ad.png)
Everything works as expected.

My solution for the moment: Meanwhile I use JabRef 3.8.2 and prepare the migration to BibDesk.

**Comment by Siedlerchr** [comment]
Please try restoring the fonts in the Font Book application Apparently this should help https://stackoverflow.com/a/35901263/3450689

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
