### ISSUE TITLE
Cookie configuration for Google Scholar failed

### ISSUE THREAD

**Issue by retostockli** [JabRef/jabref#3975]
JabRef version 4.1 Windows 7.

Steps to reproduce:
1. search Google Scholar with any keyword
2. An error Window Pops up with:

Error while fetching from Google Scholar
Please try again later and/or check your Network Connection.
Cookie configuration for Google Scholar failed.

This does not seem to be related to the traffic Limit of Google Scholar discussed in 2016 and fixed in the official release. On my Web Browser (IE) Google scholar works. Also other JabRef web searches work (like crossref, ieeeexplore etc.), so Proxy itself seems fine.

Could it be that JabRef is not able to store Cookies? We have corporate windows machines which have restrictive user rights. JabRef was installed by the System Administrator for all users. Where are Cookies stored by JabRef?

Here is the log for this Event:

Error while fetching from Google Scholar
org.jabref.logic.importer.FetcherException: Cookie configuration for Google Scholar failed.
	at org.jabref.logic.importer.fetcher.GoogleScholar.obtainAndModifyCookie(GoogleScholar.java:179)
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:110)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:306)
	at org.jabref.logic.net.URLDownload.getCookieFromUrl(URLDownload.java:218)
	at org.jabref.logic.importer.fetcher.GoogleScholar.obtainAndModifyCookie(GoogleScholar.java:173)
	... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 29 more

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.

**Comment by stefan-kolb** [comment]
@Siedlerchr Can you please take a quick look, you recently fixed the IEEE cookie thing.

**Comment by retostockli** [comment]
Hi Stefan

I have tried the current 4.3-dev and the result is the same. I suspect it has to do with either a) permission issues on where cookies are stored or b) corporate network proxy configuration.

Crossref works. IEEEExplore does not work either with the following exception:
Please try again later and/or check your network connection.
Sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

**Comment by Siedlerchr** [comment]
This seem like you have an older version of the JRE8 installed which does not include some certs . Please install the latest JDK/JRE 8-172. 
If it doesn't work, check if you have some proxy or anti virus which fiddles around with HTTPS connections.

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
