### ISSUE TITLE
Freezes caused by the default "Look and Feel"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3980]
JabRef 4.2-dev--snapshot--2018-04-24--master--e690d4397
Linux 4.15.0-15-generic amd64 
Java 1.8.0_171

This issue is at the heart of the discussion in #3304 . 

Steps to reproduce:

1. with JabRef 4.0, set "appearance" to Plastic.  Close JabRef 4.0
2. Open Jabref 4.2, dev snapshot
3. See an error message saying that this look and feel isn't available

![screenshot from 2018-04-25 14-54-36](https://user-images.githubusercontent.com/762246/39272326-d65e2198-4898-11e8-871a-202bc1c0ad7f.png)

4. JR 4.2-dev now starts, but because it's using the GTK look and feel, it freezes within a few keystrokes, whatever one is doing.  Log below.

5. If I set JR 4.2-dev to use "Motif" it won's start.  Commandline messages: 
```
15:03:14.520 [AWT-EventQueue-0] WARN  org.jabref.logic.protectedterms.ProtectedTermsLoader - Cannot find protected terms file /home/dom/Dropbox/bin/jabref protected terms list
java.io.FileNotFoundException: /home/dom/Dropbox/bin/jabref protected terms list (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_171]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_171]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_171]
[...]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_171]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_171]
```

5. Go back to  JR 4.0, which will at least start. Change the look and feel to Windows.  Quit.
6. JR 4.2-dev won't start.  Quit and repeat 5, setting to Metal. 

Summary: 

- GTK  (default), Motif, Windows, Plastic don't work or cause freezes.
- Metal usually works (and is hideous), but right now, none of my versions of JabRef will start, 4.0, 4.1, 4.2-dev.  :-(

<details>

```
Cannot find protected terms file /home/dom/Dropbox/bin/jabref protected terms list
java.io.FileNotFoundException: /home/dom/Dropbox/bin/jabref protected terms list (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.jabref.logic.protectedterms.ProtectedTermsParser.readTermsFromFile(ProtectedTermsParser.java:49)
	at org.jabref.logic.protectedterms.ProtectedTermsLoader.readProtectedTermsListFromFile(ProtectedTermsLoader.java:142)
	at org.jabref.logic.protectedterms.ProtectedTermsLoader.update(ProtectedTermsLoader.java:76)
	at org.jabref.logic.protectedterms.ProtectedTermsLoader.<init>(ProtectedTermsLoader.java:35)
	at org.jabref.JabRefMain.start(JabRefMain.java:151)
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:51)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Unable to find requested look and feel
java.lang.ClassNotFoundException: com.jgoodies.looks.plastic.Plastic3DLookAndFeel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:1874)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:582)
	at org.jabref.JabRefGUI.setLookAndFeel(JabRefGUI.java:254)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:87)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:60)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:191)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
```

</details>

**Comment by Siedlerchr** [comment]
The error indicates a problem with your file. To fix this you should create an empty file
`/home/dom/Dropbox/bin/jabref protected terms list`

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
