### ISSUE TITLE
Fields in Entry Viewer disappear, and cannot be edited

### ISSUE THREAD

**Issue by davidcbenson** [JabRef/jabref#3981]
# Version Information:
JabRef 4.1
Windows 10 10.0 amd64 
Java 1.8.0_171

After opening Jabref and using it for a few entries, the various tabs stop displaying their content. The tabs themselves are visible and selectable most of the time, but none of the fields are. I can restart the program, and solve the problem, but only for a couple more entry edits.

If the entry viewer opens, then it will work fine, as long as I stay within that entry. If I change entries and the entry viewer will not open, nothing I can do (close the viewer, change entries, change views) will affect the display of the entry viewer. It remains as it was.

There are two other bugs, which may or may not be related:
  1. Sometimes the cursor will jump to the beginning of the entry whenever I press space
  2. Sometimes the date field will strangely "autofill" where numbers replicate themselves, and then it turns into a legitimate date, if I keep typing.

I believed the issue to be related to the Java install, so I unistalled all older versions and installed the latest. I uninstalled and reinstalled Jabref (stable version only). Both are 64-bit. All of the display settings except font size are default.

The only other hint as to what is wrong is that there is often a lag when the display changes. It was this lag that led me to think it might be a Java problem. I also though that perhaps Jabref was gobbling memory, but there is no indication of that, and the computer is using less than half of its memory.

# Steps to reproduce:
  1. Open Jabref
  2.  Open or edit a few entries
  3.  The viewer fields disappear

<details>
  <summary>Log File</summary>
  
  Opening: C:\Users\dcbenson.SEAS-S\JabRef\bibMainBibliography.bib
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at com.sun.javafx.text.PrismTextLayout.getRange(PrismTextLayout.java:456)
	at javafx.scene.text.Text.getRange(Text.java:1013)
	at javafx.scene.text.Text.impl_getRangeShape(Text.java:1027)
	at com.sun.javafx.scene.control.skin.TextFieldSkin.getCharacterBounds(TextFieldSkin.java:676)
	at com.sun.javafx.scene.control.skin.TextInputControlSkin$11.getTextLocation(TextInputControlSkin.java:385)
	at javafx.scene.Scene$InputMethodRequestsDelegate.getTextLocation(Scene.java:4011)
	at javafx.embed.swing.InputMethodSupport$InputMethodRequestsAdapter.getTextLocation(InputMethodSupport.java:61)
	at sun.awt.im.InputMethodContext.getTextLocation(Unknown Source)
	at sun.awt.windows.WInputMethod$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Removed date parsing issues related to the bibtex file

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 15) is not a valid range within [0, 15)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184)
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82)
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29)
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

</details>

**Comment by tobiasdiez** [comment]
Thanks for your report. This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Siedlerchr** [comment]
@davidcbenson  You could either use the installer, or just download the 4.2 which has just been released

**Comment by davidcbenson** [comment]
Huh. Had I just waited another day to report I would have gotten the new release. I will use it for a couple of days before reporting back.

**Comment by davidcbenson** [comment]
I have used it for a week with no problems. I believe the problem has been solved.
