### ISSUE TITLE
Unable to launch jabref 4.2

### ISSUE THREAD

**Issue by Char-Aznable** [JabRef/jabref#3986]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 
4.2

Steps to reproduce:

1. java -jar JabRef-4.2.jar

<details>
  <summary>Log File</summary>
  I'm not able to launch jabref and the above command hang with this error:
  ```
11:39:11.538 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ClassCastException: java.awt.Font cannot be cast to javax.swing.plaf.FontUIResource
	at org.jabref.JabRefGUI.setLookAndFeel(JabRefGUI.java:288) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:87) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:60) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:182) ~[JabRef-4.2.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_151]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_151]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_151]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_151]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_151]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_151]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_151]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_151]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_151]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_151]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_151]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_151]
  ```
</details>

The same command works with jabref-4.1 and I'm using jdk 1.8.0-151 on CentOS 6.9

**Comment by Siedlerchr** [comment]
Probably because we removed the jgoodies stuff. Try resetting your preferences, with 
`java -jar Jabref.jar -d all`

**Comment by wujastyk** [comment]
You may have a bad download.  Check the filesize.  Happened to me the first two times I tried (right click, k to choose location).  245 kb.  When I just clicked on the link and sent the file to /Downloads, the full 56 MB file arrived.

**Comment by Char-Aznable** [comment]
The file's SHA256 checksum is correct. The problem is indeed the Look&Feel. But ```java -jar Jabref.jar -d all``` removed all my previous setting including my customized PDF import filename pattern and I'd not recommend doing it. But changing the L&F in version 4.1 and switching back to 4.2 work. However, the L&F in 4.2 will occasionally cause the GUI to freeze and I'm switching back to 4.1 for now.

**Comment by Nnidyu** [comment]
I had the same problem with. Changing
`<entry key="overrideDefaultFonts" value="true"/>`
to `false` in `prefs.xml` solves it.

**Comment by Nnidyu** [comment]
Ok, I can reproduce it with clean preferences. When I use "NimbusLookAndFeel" and set "Override default font settings" in preferences I get `java.lang.ClassCastException: java.awt.Font cannot be cast to javax.swing.plaf.FontUIResource`.

```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

Platform is Linux.

**Comment by Siedlerchr** [comment]
Thanks for reporting, this. Fix is in progress

**Comment by Nnidyu** [comment]
Ok, it seems to be working now. However, "GTKLookAndFeel" is still visible as the default one.

![screenshot from 2018-05-01 15-30-47](https://user-images.githubusercontent.com/293573/39474518-ae18fcce-4d54-11e8-8eba-7c78473863f0.png)
