### ISSUE TITLE
Window content looks messed up

### ISSUE THREAD

**Issue by Bananach** [JabRef/jabref#399]
I attached four screenshots of one and the same search field window, after different resizing and moving around of the containing window. This phenomenon is not restricted to the search field, however. I use Windows 7.
![jabref](https://cloud.githubusercontent.com/assets/16045385/11439263/4f1ceca2-950b-11e5-9079-60ae9426dcca.png)

**Comment by matthiasgeiger** [comment]
Hi,
which version of JabRef and Java are you using? 

Works fine for me with 2.11.1 and 3.0dev builds (on Win10 with recent java version installed).

**Comment by Bananach** [comment]
I am using Jabref 2.11.1 and the problem occurs for both the exe and jar.
I also just updated Java.

**Comment by matthiasgeiger** [comment]
Can you find anything special in the Error Console (Help -> Show Error Console) (esp. "Exceptions" tab)?

**Comment by Bananach** [comment]
Nov 27, 2015 1:59:49 PM org.java.plugin.registry.xml.ManifestParser <init>
INFO: got SAX parser factory - com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl@77afea7d
Nov 27, 2015 1:59:49 PM org.java.plugin.registry.xml.PluginRegistryImpl configure
INFO: configured, stopOnError=false, isValidating=true
Nov 27, 2015 1:59:49 PM org.java.plugin.registry.xml.PluginRegistryImpl register
INFO: plug-in and fragment descriptors registered - 2
Nov 27, 2015 1:59:49 PM net.sf.jabref.plugin.PluginCore initialize
INFO: Found 2 plugin(s):
  - net.sf.jabref.export.misq (jar:file:/C:/Users/wolfersf/Desktop/JabRef-2.11.1.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)
  - net.sf.jabref.core (jar:file:/C:/Users/wolfersf/Desktop/JabRef-2.11.1.jar!/plugins/net.sf.jabref.core/plugin.xml)

Nov 27, 2015 1:59:49 PM org.java.plugin.standard.StandardPluginManager activatePlugin
INFO: plug-in started - net.sf.jabref.core@2.0.0.4b1 (active/total: 1 of 2)
Nov 27, 2015 1:59:49 PM org.java.plugin.standard.StandardPluginManager activatePlugin
INFO: plug-in started - net.sf.jabref.export.misq@1.0.0 (active/total: 2 of 2)
Nov 27, 2015 1:59:50 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: C:\Users\wolfersf\Desktop\jabref.bib
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.sf.jabref.gui.SearchResultsDialog$EntryTableFormat.getColumnValue(Unknown Source)
	at net.sf.jabref.gui.SearchResultsDialog$EntryTableFormat.getColumnValue(Unknown Source)
	at ca.odell.glazedlists.swing.DefaultEventTableModel.getValueAt(DefaultEventTableModel.java:199)
	at javax.swing.JTable.getValueAt(Unknown Source)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Bananach** [comment]
I probably should mention that the problem with searching only occurs when I choose "Show results in dialog" or "Global search"

**Comment by matthiasgeiger** [comment]
Hmm... is this happening for all search results, or only in some special cases? (Where an author/editor/title/... is missing?) 

If you can determine a specific entry that is causing this trouble it would be nice if you can post the BibTeX source here.

**Comment by Bananach** [comment]
Thanks, we are closer :) It is the file field. I am using a BibTex file that I exported from Mendeley, and one (of many) entry that I verified causes the error even if I remove everything else is:

@Book{AttouchHedy;ButtazzoGiuseppe;Michaille,
  Title                    = {{Variational Analysis in Sobolev and BV Spaces}},
  Author                   = {{Attouch, Hedy; Buttazzo, Giuseppe; Michaille}, Gerard},
  File                     = {:C$\backslash$:/Users/[myname]/Dropbox/Studies/Books/Analysis/[Hedy{\_}Attouch,{\_}Giuseppe{\_}Buttazzo,{\_}Gerard{\_}MichailleVariationalBV.pdf:pdf}
}

**Comment by Bananach** [comment]
Actually, the stuff Mendeley gave me looks so wrong, that I am thinking about just building up my library from scratch and not hoping for any other program to fix that for me. 

But I still think JabRef should be able to survive reading that without crashing to not scare away other new users.

**Comment by matthiasgeiger** [comment]
Yes. You are right, there are some major problems with the parsing of the file field, which already caused some other trouble (see #184).

Semi-offtopic: You might use other export formats from mendely (e.g. RIS) and try to import these in JabRef - this is quite ridiculous but maybe the result is cleaner this way.

**Comment by matthiasgeiger** [comment]
I close this issue - the underlying reason will be tracked by #402.

**Comment by Bananach** [comment]
RIS works better in that it doesn't add curly braces around title this way (see another issue I posted). Also  it does solve the search problem, since the file field is not imported (or not exported in the RIS? it doesn't appear anyway).

**Comment by simonharrer** [comment]
@koppor may be relevant for stupro regarding RIS importer
