### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#3994]
JabRef version 4.2 on  Windows 7

1. Select item(s)
2. Contextual menu : copy -> export to clipboard 

Nothing happens (tried different items without success). Normally, it appears a windows with all export formats. 
```

runCommand error: null
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.sort(Unknown Source)
	at org.jabref.gui.exporter.ExportToClipboardAction.run(ExportToClipboardAction.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `clipboard-export`. Please try the latest build from http://builds.jabref.org/clipboard-export.
