### ISSUE TITLE
Import window freezes jabref

### ISSUE THREAD

**Issue by CodeSJS** [JabRef/jabref#3997]
Using either jabref 4.2 or the latest master version, when I
- "import into current library" (control I)
- select a bib file
- hit the "Open" button
the program freezes.  The import window never closes, and I have to hit "Force quit" to exit.

I did not see any error messages in the log file.  

--------------------------------------------------------------------------------------------------------------
Error occurs using either latest development or 4.2

JabRef 4.3-dev--snapshot--2018-04-29--master--f703f3e3f
Linux 4.15.0-20-generic amd64 
Java 1.8.0_171

JabRef 4.2
Linux 4.15.0-20-generic amd64 
Java 1.8.0_171

java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

--------------------------------------------------------------------------------------------------------------
sudo update-alternatives --config java

There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status

------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
* 3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      manual mode

--------------------------------------------------------------------------------------------------------------
When I run jabref from command line, I get the following output.  At the end, you can see that it was killed, but no errors to my eye.  There are some errors concerning finding my journal abbreviations file, but jabref eventually loads the right file.

java -jar /opt/jabref/JabRef-4.2.jar 
Gtk-Message: 08:10:32.436: Failed to load module "canberra-gtk-module"
08:10:35.483 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/singer/Library/TeXInputs/bib/jones.bib
08:10:36.097 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/singer/Projects/Electrokinetics/Notes/Bibliography/ReverseMicelles/ReverseMicelles.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
08:10:37.713 [AWT-EventQueue-0] INFO  org.jabref.logic.journals.JournalAbbreviationLoader - Personal journal list file '/home/singer/Library/TeXInputs/bib/JournalAbbrev' not found.
java.io.FileNotFoundException: /home/singer/Library/TeXInputs/bib/JournalAbbrev (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_171]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_171]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_171]
	at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(AbbreviationParser.java:52) ~[JabRef-4.2.jar:?]
	at org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(JournalAbbreviationLoader.java:51) ~[JabRef-4.2.jar:?]
	at org.jabref.logic.journals.JournalAbbreviationLoader.update(JournalAbbreviationLoader.java:91) ~[JabRef-4.2.jar:?]
	at org.jabref.logic.journals.JournalAbbreviationLoader.getRepository(JournalAbbreviationLoader.java:102) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.autocompleter.JournalsSuggestionProvider.<init>(JournalsSuggestionProvider.java:18) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.autocompleter.SuggestionProviders.initalizeSuggestionProvider(SuggestionProviders.java:66) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.autocompleter.SuggestionProviders.<init>(SuggestionProviders.java:35) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.BasePanel.setupAutoCompletion(BasePanel.java:1442) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1420) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604) ~[JabRef-4.2.jar:?]
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:131) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:60) ~[JabRef-4.2.jar:?]
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:182) ~[JabRef-4.2.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_171]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_171]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_171]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_171]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_171]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_171]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_171]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_171]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_171]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_171]
Killed

**Comment by Siedlerchr** [comment]
This is a linux problem with the Look and Feel. Try switching to another Look and Feel:
https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

**Comment by CodeSJS** [comment]
Fantastic!  It now works.  Thanks for the solution.
