### ISSUE TITLE
UnsatisfiedLinkError, NoClassDefFoundError, NullPointerException

### ISSUE THREAD

**Issue by malaverdiere** [JabRef/jabref#3999]
The log shows many exceptions. JabRef also considers the file that it opens automatically as modified.

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2 on Fedora 26 using OpenJDK 1.8.0_171 and OpenJFX 8.0.152-12.b04.fc26.x86_64

Steps to reproduce: 

1. Open JabRef

<details>
  <summary>Log File</summary>

    21:40:09.251 [AWT-EventQueue-0] WARN  org.jabref.JabRefGUI - There seem to be problems with OpenJDK and the default GTK Look&Feel. Using Metal L&F instead. Change to another L&F with caution.
    21:40:09.274 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/marc-andre/doc/tex/thesis/analysis.bib
    21:40:09.476 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/marc-andre/doc/tex/thesis/proposal.bib
    21:40:09.500 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/marc-andre/doc/tex/thesis/slicing.bib
    File: grouptree.fxml not found, attempting with camel case
    File: grouptree.css not found, attempting with camel case
    21:40:11.166 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
    java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-3.b10.fc26.x86_64/jre/lib/amd64/libjfxwebkit.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827) ~[?:1.8.0_171]
	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_171]
	at java.lang.System.load(System.java:1086) ~[?:1.8.0_171]
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201) ~[jfxrt.jar:?]
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94) ~[jfxrt.jar:?]
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39) ~[jfxrt.jar:?]
	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:131) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.webkit.WebPage.<clinit>(WebPage.java:130) ~[jfxrt.jar:?]
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881) ~[jfxrt.jar:?]
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868) ~[jfxrt.jar:?]
	at javafx.scene.web.WebView.<init>(WebView.java:273) ~[jfxrt.jar:?]
	at org.jabref.gui.PreviewPanel.lambda$new$1(PreviewPanel.java:82) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
    21:40:12.229 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
    java.lang.NullPointerException: null
	at org.jabref.gui.PreviewPanel.lambda$setPreviewLabel$15(PreviewPanel.java:259) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
    21:40:12.234 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
    java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881) ~[jfxrt.jar:?]
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868) ~[jfxrt.jar:?]
	at javafx.scene.web.WebView.<init>(WebView.java:273) ~[jfxrt.jar:?]
	at org.jabref.gui.PreviewPanel.lambda$new$1(PreviewPanel.java:82) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
    21:40:12.294 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
    java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881) ~[jfxrt.jar:?]
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868) ~[jfxrt.jar:?]
	at javafx.scene.web.WebView.<init>(WebView.java:273) ~[jfxrt.jar:?]
	at org.jabref.gui.PreviewPanel.lambda$new$1(PreviewPanel.java:82) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
    21:40:12.410 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
    java.lang.NullPointerException: null
	at org.jabref.gui.PreviewPanel.lambda$setPreviewLabel$15(PreviewPanel.java:259) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

</details>

**Comment by stefan-kolb** [comment]
What are the symptoms of the exceptions? Does your JabRef start? Are there any issues you experience?

**Comment by Siedlerchr** [comment]
Addtionally, it seems your versoins of the jdk8 and the openjfx do not match. 
You have an older version of openjfx 152 but a newer version of the jdk 171
Try updating the version of openjfx:
https://fedora.pkgs.org/26/fedora-updates-i386/java-1.8.0-openjdk-openjfx-devel-1.8.0.171-3.b10.fc26.i686.rpm.html

**Comment by Nnidyu** [comment]
I can comment on this issue, because I have similar errors.
As for @stefan-kolb questions:
- JabRef does start,
- preview panel does not work (only gray rectangle is displayed under articles list), but the edit panel (after double-click) – works.

As for the `UnsatisfiedLinkError` Fedora does not provide `libjfxwebkit.so` file in its OpenJFX package: https://bugzilla.redhat.com/show_bug.cgi?id=1547378
And there is no version of OpenJFX newer than 152. `java-1.8.0-openjdk-openjfx` provides only symlinks to files installed by `openjfx` package.

All these problems are solved with Oracle JDK, so unfortunately that's probably the best solution untill Java 9/10 support.

**Comment by Siedlerchr** [comment]
As we can't do anything about this and it's a Fedora-specific problem with openjdk I close this issue.
