### ISSUE TITLE
Unable to open url links

### ISSUE THREAD

**Issue by maturin6** [JabRef/jabref#4006]
Error when opening url links. Status: External viewer called but noting happens.

JabRef version 4.2 on  Windows 7

Steps to reproduce:

1. copy a url link (e. g. http://stacks.iop.org/0022-3727/47/i=23/a=235301) in the url field
2. click on the link

<details>
  <summary>Log File</summary>
  
 Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://stacks.iop.org/0022-3727/47/i=23/a=235301
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at org.jabref.gui.desktop.os.Windows.openFileWithApplication(Windows.java:58)
	at org.jabref.gui.desktop.JabRefDesktop.openExternalFilePlatformIndependent(JabRefDesktop.java:175)
	at org.jabref.gui.desktop.JabRefDesktop.openBrowser(JabRefDesktop.java:272)
	at org.jabref.gui.desktop.JabRefDesktop.openExternalViewer(JabRefDesktop.java:101)
	at org.jabref.gui.maintable.MainTableSelectionListener.lambda$mouseClicked$3(MainTableSelectionListener.java:259)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

</details>

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`.
What do you mean by click on the link?

**Comment by Siedlerchr** [comment]
maybe he added the link to the file field?

**Comment by maturin6** [comment]
I did a reset of the preferences and it works fine, I probably dit something wrong with preferences. 
Thanks for your help
