### ISSUE TITLE
Problem with web search for ACM

### ISSUE THREAD

**Issue by korrat** [JabRef/jabref#4018]
When trying to fetch an entry from ACM, JabRef seems to 

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version:
JabRef 4.3-dev--snapshot--2018-05-05--master--b8ea55bc2
Windows 7 6.1 amd64 
Java 1.8.0_172

Steps to reproduce:

1. Open web search and select the ACM portal
2. Paste the DOI 10.1145/72551.72553 for example
3. Click fetch
4. The dialog window in the first screenshot below opens
5. Mark "Keep" on the entry
6. Click "Ok"
7. Another dialog window opens which seems to make no progress and does not contain the entry selected previously

<details>
  <summary>Screenshots</summary>
  
  ![grafik](https://user-images.githubusercontent.com/22543341/39743064-fdbfe9b8-529f-11e8-9dbf-a91ca49cf2d4.png)  
  Screenshot of first dialog after searching
  
  ![grafik](https://user-images.githubusercontent.com/22543341/39743370-f7aa5d64-52a0-11e8-9db2-937af5865ce3.png)
  Screenshot of second dialog
</details>

**Comment by Siedlerchr** [comment]
Thanks for your report. I can confirm that. The fetcher runs into an error: 
I'll take a look at that
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960) ~[?:1.8.0_162]
	at org.jabref.gui.importer.fetcher.ACMPortalFetcher.downloadEntryBibTeX(ACMPortalFetcher.java:324) ~[main/:?]
	at org.jabref.gui.importer.fetcher.ACMPortalFetcher.getEntries(ACMPortalFetcher.java:180) ~[main/:?]
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$4(GeneralFetcher.java:198) ~[main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by Siedlerchr** [comment]
There was a problem with recognizing the correct id. 
Should be fixed in this version and soon be in the master:
https://builds.jabref.org/fixacm/

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
