### ISSUE TITLE
JabRef-4.2 CLI does not work

### ISSUE THREAD

**Issue by auge** [JabRef/jabref#4038]
I use JabRef to sanitize my bibfile automatically. (using Jenkins ...)

the newer release 4.2 however does not work from CLI

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2 on Windows 10

Steps to reproduce:

using 4.1: - working
  ```
 $ java -jar JabRef-4.1.jar -n --help
usage: jabref [OPTIONS] [BIBTEX_FILE]

[...]
  ```

using 4.2: - Exception + no return to shell (same with master "4.3-dev")
  ```
$ java -jar JabRef-4.2.jar -n --help
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.jabref.cli.JabRefCLI.printUsage(JabRefCLI.java:262)
        at org.jabref.cli.ArgumentProcessor.processArguments(ArgumentProcessor.java:180)
        at org.jabref.cli.ArgumentProcessor.<init>(ArgumentProcessor.java:71)
        at org.jabref.JabRefMain.start(JabRefMain.java:112)
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:188)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

  ```

**Comment by Siedlerchr** [comment]
@johannes-manner As you recently worked on that CLI stuff, do you have any idea?

**Comment by johannes-manner** [comment]
I will try to reproduce and investigate the bug. Initially, I have no idea, why the CLI is not working in this case in the latest release 4.2.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by auge** [comment]
works for me - thanks!
