### ISSUE TITLE
Jabref crashed with openjdk (redhat version) on Windows

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#4088]
When open `Jabref`, the following dialog windows prompted:

<img width="289" alt="2018-06-03" src="https://user-images.githubusercontent.com/13306020/40882478-baef0238-6715-11e8-8611-3bb0e7d4818b.png">

The texts are

```java
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 
```
> java -version
openjdk version "1.8.0_171-1-redhat"
OpenJDK Runtime Environment (build 1.8.0_171-1-redhat-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

**Comment by psychelzh** [comment]
I wonder if it is possible to run it with this `jdk`?

**Comment by Siedlerchr** [comment]
The version misses the openjfx package. I would recommend installing the oracle version on windows, 1.8.172

**Comment by koppor** [comment]
@psychelzh If that solved your issue, could you please provide a pull request updating our installation instructions? http://help.jabref.org/en/Installation#windows-and-oracle-java

**Comment by Siedlerchr** [comment]
Well, as the openjdk and the oracle jdk are the same code basis (the latter one has some additional things)  I would suggest sticking to the oracle jdk/jre as it already inlcudes the javafx support.  
Therefore I close this here as won't fix as we can't do anything about this.
