### ISSUE TITLE
Exception after startup

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#411]
I want to report an exception after startup of 2.11.1:
Exception in thread "main" java.lang.NoSuchMethodError: localcopy.LocalCopySidePaneComponent.setContent(Ljava/awt/Component;)V
	at localcopy.LocalCopySidePaneComponent.<init>(LocalCopyPane.java:219)
	at localcopy.LocalCopyPane.getSidePaneComponent(LocalCopyPane.java:578)
	at net.sf.jabref.JabRef.startSidePanePlugins(Unknown Source)
	at net.sf.jabref.JabRef.openWindow(Unknown Source)
	at net.sf.jabref.JabRef.start(Unknown Source)
	at net.sf.jabref.JabRefMain.main(Unknown Source)

**Comment by koppor** [comment]
This is because we worked on the internals of JabRef. In the future, we will drop plugin support. See  #152.

A longer discussion is made aT https://github.com/lehner/LocalCopy/issues/7.

So, please disable the LocalCopy plugin and wait for the `3.0` release to happen.
