### ISSUE TITLE
Odd SEVERE exception shown on the console output

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#4149]
Using version 4.3.1 I am getting several copies following exceptions which show up on the console output. This happens when loading the database and just trying to quit, answering "discard"  to the prompt (I have no idea why the database is marked as changed right after starting up and not having done any changes to it at all):

```
SEVERE: Exception thrown by subscriber method listen(org.jabref.model.entry.event.EntryEvent) on subscriber GroupNodeViewModel{displayName='All entries', isRoot=true, icon='DATABASE', children=[], databaseContext=BibDatabaseContext{file=/home/johann/phd/lit/all01.bib, location=LOCAL}, groupNode=GroupTreeNode{group=AbstractGroup{name='All entries', context=INDEPENDENT, color=Optional.empty, isExpanded=true, description=Optional.empty, iconName=Optional[DATABASE]}}, hits=IntegerProperty [value: 2173]} when dispatching event: org.jabref.model.entry.event.FieldChangedEvent@366e14af
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@21a5c4b9 rejected from java.util.concurrent.ThreadPoolExecutor@7a6130fe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.jabref.gui.util.DefaultTaskExecutor.execute(DefaultTaskExecutor.java:81)
	at org.jabref.gui.util.BackgroundTask.executeWith(BackgroundTask.java:111)
	at org.jabref.gui.groups.GroupNodeViewModel.calculateNumberOfMatches(GroupNodeViewModel.java:213)
	at org.jabref.gui.groups.GroupNodeViewModel.listen(GroupNodeViewModel.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.model.database.BibDatabase.relayEntryChangeEvent(BibDatabase.java:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:426)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupSingleField(FieldFormatterCleanup.java:63)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanup(FieldFormatterCleanup.java:34)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applyAllActions(FieldFormatterCleanups.java:71)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applySaveActions(FieldFormatterCleanups.java:61)
	at org.jabref.logic.exporter.BibDatabaseWriter.lambda$applySaveActions$0(BibDatabaseWriter.java:62)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.jabref.logic.exporter.BibDatabaseWriter.applySaveActions(BibDatabaseWriter.java:59)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:184)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:150)
	at org.jabref.logic.autosaveandbackup.BackupManager.performBackup(BackupManager.java:124)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.jabref.logic.autosaveandbackup.BackupManager.lambda$new$0(BackupManager.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
