### ISSUE TITLE
Can't fetch with ISBN (parsing error)

### ISSUE THREAD

**Issue by sebastianbarfurth** [JabRef/jabref#4172]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.3.1 on Windows 10

Steps to reproduce:

1. Add a new entry
2. Select ID type ISBN
3. Enter an ISBN (e.g. 9780262305662)
4. Click "Generate"

> An internal parser error occurred
org.jabref.logic.importer.FetcherException: An internal parser error occurred
	at org.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:93)
	...
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: www.ebook.de

**Note:** I use a corporate Proxy. It is properly configured and searches through some of the databases from within the program work. I believe it is not related to this issue.

<details>
  <summary>Log File</summary>
  
  ```
  Opening: file.bib (edited for privacy)
Could not connect to the updateserver.
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/JabRef/JabRef/releases
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:96)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:55)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:29)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

An internal parser error occurred
org.jabref.logic.importer.FetcherException: An internal parser error occurred
	at org.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:93)
	at org.jabref.logic.importer.fetcher.IsbnFetcher.performSearchById(IsbnFetcher.java:45)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: www.ebook.de
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at org.jabref.logic.importer.IdBasedParserFetcher.performSearchById(IdBasedParserFetcher.java:67)
	... 9 more
Caused by: java.net.UnknownHostException: www.ebook.de
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 11 more

  ```
</details>

**Comment by tobiasdiez** [comment]
It looks like you are having problems with your network connection or JabRef is blocked by your firewall. The log file tells you that JabRef was not able to connect a) github (to check for updates) and b) ebook.de to get bibliographic information about the book.

**Comment by stefan-kolb** [comment]
Duplicate #4198

**Comment by sebastianbarfurth** [comment]
Considering I opened mine first it's hardly a duplicate. Thanks for the quick responses, hope #4198 gets fixed soon!

**Comment by stefan-kolb** [comment]
Yah technically it's not 😉  but the other one describes the root cause, so I closed this one sorry 😄

**Comment by sebastianbarfurth** [comment]
Haha, I'm not mad. Doing good work here!
