### ISSUE TITLE
Silently fails when saving library to unavailable network drive (wrongfully claims "Status: Saved library '\\SERVER\\...' without indication to user that something went wrong)

### ISSUE THREAD

**Issue by Ede123** [JabRef/jabref#4173]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.3.1
Windows 10 10.0 x86 
Java 1.8.0_172

Steps to reproduce:

1. Save a library onto a network drive (UNC path like `\\SERVER\folder\library.bib`)
2. Make sure the network drive is not available anymore
3. Save the (already opened) library in JabRef

Result:

JabRef fails silently. It claims "Status: Saved library '\\SERVER\folder\library.bib'." in the status bar when it actually did *not* save the library leading to potential data loss.

Errors are logged but not reported to the user.

<details>

```
Error when creating lock file.
java.nio.file.FileSystemException: \\SERVER\folder\library.bib.lock: Der Netzwerkpfad wurde nicht gefunden.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.nio.file.Files.newOutputStream(Unknown Source)
	at java.nio.file.Files.write(Unknown Source)
	at org.jabref.logic.util.io.FileBasedLock.createLockFile(FileBasedLock.java:115)
	at org.jabref.logic.exporter.FileSaveSession.commit(FileSaveSession.java:78)
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:256)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

Error while getting file information
java.nio.file.FileSystemException: \\SERVER\folder\library.bib: Der Netzwerkpfad wurde nicht gefunden.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at java.nio.file.Files.getLastModifiedTime(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:145)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1830)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

Error while getting file information
java.nio.file.FileSystemException: \\SERVER\folder\library.bib: Der Netzwerkpfad wurde nicht gefunden.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at java.nio.file.Files.getLastModifiedTime(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:145)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1830)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

Error while getting file information
java.nio.file.FileSystemException: \\SERVER\folder\library.bib: Der Netzwerkpfad wurde nicht gefunden.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at java.nio.file.Files.getLastModifiedTime(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:145)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1830)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
