### ISSUE TITLE
Saving causes NullPointerException

### ISSUE THREAD

**Issue by blegat** [JabRef/jabref#4187]
I have just updated to JabRef 4.3.1. I am using the [AUR package](https://aur.archlinux.org/packages/jabref/).
When I create a new bib file and choose the name to save it I get the following exception
```
17:42:13.660 [AWT-EventQueue-0] ERROR org.jabref.gui.collab.DatabaseChangeMonitor - Error while trying to monitor /home/blegat/testtest.bib
java.io.IOException: User limit of inotify watches reached
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[?:1.8.0_172]
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[?:1.8.0_172]
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364) ~[?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
```
It then says that the file has be modified externally.
If I choose "Review changes", I get the error
```
17:39:20.701 [JabRef CachedThreadPool] ERROR org.jabref.JabRefExecutorService - Problem executing command
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_172]
	at org.jabref.JabRefExecutorService.executeInterruptableTaskAndWait(JabRefExecutorService.java:108) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.exporter.SaveDatabaseAction.lambda$checkExternalModification$4(SaveDatabaseAction.java:425) ~[JabRef-4.3.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at org.jabref.gui.collab.ChangeScanner.run(ChangeScanner.java:125) ~[JabRef-4.3.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	... 3 more
```
and it gets back to the prompt. When I choose "Save" I get
```
[AWT-EventQueue-0] ERROR org.jabref.gui.BasePanel - runCommand error: null
java.lang.NullPointerException: null
	at java.nio.file.Files.provider(Files.java:97) ~[?:1.8.0_172]
	at java.nio.file.Files.exists(Files.java:2385) ~[?:1.8.0_172]
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:158) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148) ~[JabRef-4.3.1.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_172]
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143) ~[JabRef-4.3.1.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_172]
	at org.jabref.gui.BasePanel.updateTimeStamp(BasePanel.java:1983) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:146) ~[JabRef-4.3.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at spin.Invocation.evaluate(Invocation.java:175) ~[JabRef-4.3.1.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) ~[JabRef-4.3.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
```
and then every time I save, I directly get this error without the prompt warning that it has been changed externally.
Any idea of what is going on ?

**Comment by stefan-kolb** [comment]
Is this folder `/home/blegat/testtest.bib` a mounted folder (network, dropbox,...) or a local one?

**Comment by blegat** [comment]
A local one

**Comment by stefan-kolb** [comment]
Is this reproducible and happens all the time? @JabRef/developers can anyone of the Linux guys reproduce this? Otherwise, you could do something like that to prevent this: https://askubuntu.com/questions/770374/user-limit-of-inotify-watches-reached-on-ubuntu-16-04

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
