### ISSUE TITLE
snapshot from last week removes any connection to DOI or Medline

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4207]
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Windows 7 6.1 amd64 
Java 1.8.0_172
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

I experienced a "can not connect to DOI, please check your internet connection" in the snapshot.

However, what I did not expect, that all the earlier version of Jabref (4.1, 4.3) now have the same error. Pubmed search is equally disabled. My internet connection otherwise is working smoothly otherwise.

<details>
  <summary>Log File</summary>
  
  ```
  Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism20170608VS4.0.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism20170608VS4.0.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism20170608VS4.0.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism20170608VS4.0.0.bib
Could not connect to the updateserver.
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:96)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:56)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:30)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Verbindungsfehler
org.jabref.logic.importer.FetcherException: Verbindungsfehler
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:311)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:201)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:215)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more

  ```
</details>

**Comment by bernhard-kleine** [comment]
The log from 
JabRef 4.1
Windows 7 6.1 amd64 
Java 1.8.0_172
<details>
  <summary>Log File</summary>
  
  ```
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20171208VS4.1.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\thyroidHormon.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\hibernation.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\FatMetabolism20170608VS4.0.0.bib
Duplicate journal abbreviation - old one will be overwritten by new one
OLD: Abbreviation{name=Journal of Nippon Medical School, iso=J. Nippon Med. Sch., medline=J Nippon Med Sch}
NEW: Abbreviation{name=Journal of Nippon Medical School, iso=Nippon Ika Daigaku zasshi|J Nippon Med Sch|1345-4676|J-STAGE, Japan Science and Technology Information Aggregator, Electronic|JSTAGE|2000-2015, medline=Nippon Ika Daigaku zasshi|J Nippon Med Sch|1345-4676|J-STAGE, Japan Science and Technology Information Aggregator, Electronic|JSTAGE|2000-2015}
Duplicate journal abbreviation - old one will be overwritten by new one
OLD: Abbreviation{name=Journal of the Formosan Medical Association, iso=J. Formos. Med. Assoc., medline=J Formos Med Assoc}
NEW: Abbreviation{name=Journal of the Formosan Medical Association, iso=Taiwan yi zhi|J Formos Med Assoc|0929-6646|Clinical Key|clinicalk|2007-2016, medline=Taiwan yi zhi|J Formos Med Assoc|0929-6646|Clinical Key|clinicalk|2007-2016}
Could not connect to the updateserver.
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:96)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:55)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:29)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Error while fetching from Medline/PubMed
org.jabref.logic.importer.FetcherException: Es ist nicht möglich die PubMed ID's zu bekommen
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:117)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:167)
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37)
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:79)
	... 6 more

  ```
</details>

**Comment by Siedlerchr** [comment]
This could be a problem with ipv4/ipv6. You could try starting it from commandline with the option
`java -Djava.net.preferIPv4Stack=true -jar JabRef.jar`

**Comment by bernhard-kleine** [comment]
Actually by removing any installation of Jabref which was on my desktop _and_ shutting down the system, I could at least get a functional internet search from Jabref 4.1. Without shutting down I was impossible.

**Comment by bernhard-kleine** [comment]
it works again from the latest master.

**Comment by bernhard-kleine** [comment]
This problem is not solved: When I have freshly started the computer, the control-N feature works, however, after some time retrying to add an PMID fails. There is obviously some fault which is not solved.
JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_172
When it happens the next time I will provide the error log.

**Comment by bernhard-kleine** [comment]
@Siedlerchr: as this was working for a while, I am sure it is not related to an ipv4/ipv6 issue, since I did not change anything on my internet connection and used only I think save programs: firefox, jabref, oxygen, gimp, lightroom which depend on an internet connection but not try to change anything.

**Comment by tobiasdiez** [comment]
It's actually not a problem with the fetcher but some internal issue...

**Comment by Siedlerchr** [comment]
The fetcher itself works, but if you fetch and add the same entry multiple times, the FileUpdateMonitor throws an Not on FX thread exception:
```
18:06:51.479 [FileUpdateMonitor] ERROR org.jabref.JabRefExecutorService - Problem executing command - java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef LowPriorityCachedThreadPool
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jabref.JabRefExecutorService.executeInterruptableTaskAndWait(JabRefExecutorService.java:108)
	at org.jabref.gui.collab.DatabaseChangeMonitor.fileUpdated(DatabaseChangeMonitor.java:80) 
18:06:51.480 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main] - java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.clear(VetoableListDecorator.java:294) 

```

**Comment by bernhard-kleine** [comment]
I did not test it with the same PMID multiple times. I was working on my text. At first it worked and than some time later with jabref in the background all the time it stopped working.

**Comment by Siedlerchr** [comment]
Does this still occur in the latest snapshot?

**Comment by bernhard-kleine** [comment]
On 26. Juli 2018 23:14:15 MESZ, Christoph <notifications@github.com> wrote:
|Does this still occur in the latest snapshot? 
|
|-- 
|You are receiving this because you authored the thread.
|Reply to this email directly or view it on GitHub:
|https://github.com/JabRef/jabref/issues/4207#issuecomment-408237235

I tested it once today. It worked.
Regards 
-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
