### ISSUE TITLE
Cant get search going in pubmed and google scholar. I get error answer, check internet connection while it is working fine

### ISSUE THREAD

**Issue by sn0m** [JabRef/jabref#4218]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persis

java -jar JabRef-4.3.1.jar 
Gtk-Message: 10:09:54.859: Failed to load module "canberra-gtk-module"
10:09:58.317 [AWT-EventQueue-0] WARN  org.jabref.JabRefGUI - There seems to be problems with GTK Look&Feel. Using Nimbus L&F instead. Change to another L&F with caution.
10:09:58.763 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/koli/Dropbox/evidence_based_medical_notes/Databases/high_flow_oxygen_nasal_cannulae_niv.bib
10:09:58.969 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/koli/Dropbox/evidence_based_medical_notes/Databases/av_malformation_ic_bleeding.bib
10:09:58.985 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/koli/Dropbox/evidence_based_medical_notes/Databases/dka_paediatics.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
10:10:03.133 [SwingWorker-pool-11-thread-1] WARN  org.jabref.gui.worker.VersionWorker - Could not connect to the updateserver.
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171]
	at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:96) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:55) [JabRef-4.3.1.jar:?]
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:29) [JabRef-4.3.1.jar:?]
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at javax.swing.SwingWorker.run(SwingWorker.java:334) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91) ~[?:1.8.0_171]
	at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	... 15 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[?:1.8.0_171]
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[?:1.8.0_171]
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[?:1.8.0_171]
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89) ~[?:1.8.0_171]
	at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	... 15 more
10:10:09.317 [JabRef CachedThreadPool] ERROR org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher - Error while fetching from Medline/PubMed
org.jabref.logic.importer.FetcherException: Unable to get PubMed IDs
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:117) ~[JabRef-4.3.1.jar:?]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(MedlineFetcher.java:167) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.importer.fetcher.SearchBasedEntryFetcher.processQuery(SearchBasedEntryFetcher.java:37) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.importer.fetcher.GeneralFetcher.lambda$actionPerformed$5(GeneralFetcher.java:216) ~[JabRef-4.3.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_171]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:79) ~[JabRef-4.3.1.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91) ~[?:1.8.0_171]
	at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_171]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:79) ~[JabRef-4.3.1.jar:?]
	... 6 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[?:1.8.0_171]
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[?:1.8.0_171]
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[?:1.8.0_171]
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89) ~[?:1.8.0_171]
	at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_171]
	at org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(MedlineFetcher.java:79) ~[JabRef-4.3.1.jar:?]

Steps to reproduce:

1. ...start java jar latest stable in linux ( i tried latest snap java (V5) in linux, can't even get to enter text to do a search on it)
2. ...perform web search choosing either medline or google scholar
3. ...error connection

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here

</details>

**Comment by Siedlerchr** [comment]
Hi, this seems to be a problem with Java and Linux, I found this topic or answer and it seems you have to install a missing dependency 

Google Scholar is currently broken (we currently can't do anything about it) but medline should work 

https://stackoverflow.com/a/30699960/3450689

**Comment by Siedlerchr** [comment]
Is this problem still active with the current snapshot? (Google scholar seems to be broken again on the server side, but Medline etc should work fine)

**Comment by sn0m** [comment]
Hi Chris, thanks for your email.
Working fine now.
Koli
