### ISSUE TITLE
NullPointerException in Settings for External Applications

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#4244]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version: 5.0dev latest master on Windows 10

Steps to reproduce:

1. Open Preferences Dialog -> External programs
2. click on one of the "Settings for xxx" buttons
3. NullPointerException is thrown (see log below)

<details>
  <summary>Log File</summary>
  
  ```
17:10:47.869 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at org.jabref.gui.push.PushToApplicationSettings.getSettingsPanel(PushToApplicationSettings.java:33) ~[JabRef--master--latest(2).jar:?]
        at org.jabref.gui.push.PushToApplicationSettingsDialog.showSettingsDialog(PushToApplicationSettingsDialog.java:25) ~[JabRef--master--latest(2).jar:?]
        at org.jabref.gui.preftabs.ExternalTab.lambda$addSettingsButton$5(ExternalTab.java:204) ~[JabRef--master--latest(2).jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:1.8.0_181]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:1.8.0_181]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:1.8.0_181]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:1.8.0_181]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[?:1.8.0_181]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_181]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_181]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_181]
  ```
</details>

**Comment by Siedlerchr** [comment]
Could be part of #4253

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
