### ISSUE TITLE
Exception when exporting to clipboard

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4285]
Right-click on entry -> Copy -> Export to clipboard.

<details>
<summary>Detail information:</summary>

```
Opening: D:\Research\A_Central\Latex\bibtex\bib\Literature.bib
Opening: D:\Research\A_Central\Latex\bibtex\bib\Literature.bib
Error exporting to clipboard
java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-5
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.input.Clipboard.setContent(Clipboard.java:231)
	at org.jabref.gui.ClipBoardManager.setContent(ClipBoardManager.java:53)
	at org.jabref.gui.exporter.ExportToClipboardAction.exportToClipboard(ExportToClipboardAction.java:102)
	at org.jabref.gui.exporter.ExportToClipboardAction.lambda$action$0(ExportToClipboardAction.java:56)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:40)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:110)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Fixed by #4286
