### ISSUE TITLE
Fallback Exception Handler (Uncaught Exceptions for Threads) hides real origin of error

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4328]
When you remove the Handler, the whole stack trace is printed and reveals the origin.
The log4j2.xml needs probably be adapted  but I couldn't get it work.
https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout

```
13:41:42.223 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,5,main] - java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) 
```

**Comment by Siedlerchr** [comment]
No longer a Problem I think
