### ISSUE TITLE
Jabref hangs when clicking on Optional fields Tab

### ISSUE THREAD

**Issue by nilsfortheinternet** [JabRef/jabref#4331]
I'm not familiar to bug reports, but I'll try my best. Unfortunately Jabref runs very unstable on my system. One error I can reproduce is when I click on the Optional fields Tab of the entry in the attached database, CPU load goes to max and the whole system does not react on mouse clicks anymore. It reacts on keyboard strokes though.

- [ x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-09-11--master--4c3e520a3
Linux 4.9.0-8-amd64 amd64 
Java 1.8.0_181

Steps to reproduce:

1. Open the database
2. Click on entry
3. Click on optional fields

Here is the bibtex file:

<details>
<summary>Bibtex File</summary>

% Encoding: UTF-8

@Article{Punj2013NatureNanotechnology,
  author    = {Punj, Deep and Mivelle, Mathieu and Moparthi, Satish Babu and van Zanten, Thomas S. and Rigneault, Herv{\'e} and van Hulst, Niek F. and Garc{\'i}a-Paraj{\'o}, Mar{\'i}a F. and Wenger, J{\'e}r{\^o}me},
  title     = {A plasmonic 'antenna-in-box' platform for enhanced single-molecule analysis at micromolar concentrations},
  journal   = {Nature Nanotechnology},
  year      = {2013},
  volume    = {8},
  pages     = {512 - 517},
  month     = {Jun},
  abstract  = {Single-molecule fluorescence techniques are key for a number of applications, including DNA sequencing, molecular and cell biology and early diagnosis. Unfortunately, observation of single molecules by diffraction-limited optics is restricted to detection volumes in the femtolitre range and requires pico- or nanomolar concentrations, far below the micromolar range where most biological reactions occur. This limitation can be overcome using plasmonic nanostructures, which enable the confinement of light down to nanoscale volumes. Although these nanoantennas enhance fluorescence brightness, large background signals and/or unspecific binding to the metallic surface have hampered the detection of individual fluorescent molecules in solution at high concentrations. Here we introduce a novel ‘antenna-in-box’ platform that is based on a gap-antenna inside a nanoaperture. This design combines fluorescent signal enhancement and background screening, offering high single-molecule sensitivity (fluorescence enhancement up to 1,100-fold and microsecond transit times) at micromolar sample concentrations and zeptolitre-range detection volumes. The antenna-in-box device can be optimized for single-molecule fluorescence studies at physiologically relevant concentrations, as we demonstrate using various biomolecules.},
  day       = {09},
  doi       = {10.1038/nnano.2013.98},
  groups    = {Unread},
  keywords  = {Fluorescence enhancement, Nanoantenna},
  publisher = {Nature Publishing Group},
  url       = {http://dx.doi.org/10.1038/nnano.2013.98}
}

@Comment{jabref-meta: databaseType:biblatex;}

  <summary>Log File</summary>
  

Here is what is printed in the terminal: 

17:22:45.985 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,5,main]
java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabelSkin.handleControlPropertyChanged(LabelSkin.java:49) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$0(BehaviorSkinBase.java:197) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55) ~[jfxrt.jar:?]
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49) ~[jfxrt.jar:?]
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65) ~[jfxrt.jar:?]
	at javafx.scene.control.Labeled.setText(Labeled.java:145) ~[jfxrt.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:199) ~[JabRef.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:195) ~[JabRef.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:179) ~[JabRef.jar:?]
	at org.jabref.gui.JabRefFrame.output(JabRefFrame.java:1025) ~[JabRef.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:200) ~[JabRef.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:174) ~[JabRef.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
17:22:46.026 [JabRef CachedThreadPool] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/nils/Schreibtisch/test.bib
17:22:46.039 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,5,main]
java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.LabelSkin.handleControlPropertyChanged(LabelSkin.java:49) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$0(BehaviorSkinBase.java:197) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55) ~[jfxrt.jar:?]
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49) ~[jfxrt.jar:?]
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65) ~[jfxrt.jar:?]
	at javafx.scene.control.Labeled.setText(Labeled.java:145) ~[jfxrt.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:199) ~[JabRef.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:195) ~[JabRef.jar:?]
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:179) ~[JabRef.jar:?]
	at org.jabref.gui.JabRefFrame.output(JabRefFrame.java:1025) ~[JabRef.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.addNewDatabase(OpenDatabaseAction.java:278) ~[JabRef.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:256) ~[JabRef.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:174) ~[JabRef.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
</details>

**Comment by Siedlerchr** [comment]
Hi, this is a bug which I noticed and which  will be fixed with #4327

**Comment by Siedlerchr** [comment]
Hi,
could you please test with the latest master version from here?  http://builds.jabref.org/master/

**Comment by nilsfortheinternet** [comment]
Hi,

I just downloaded the Jar --master-latest and tried the same on the entry from the sample database provided. The cpu still goes to 100% but the mouse still works. I then killed the application after few seconds.
There is no special error in the terminal given. Is there a verbose mode to get more info about the error?

Thank you for your quick effort.

**Comment by Siedlerchr** [comment]
Try to run with` java -Djavafx.embed.singleThread=true -jar JabRef.jar `

**Comment by nilsfortheinternet** [comment]
I just downloaded the latest version, and this specific error did not occur anymore. Thanks.
