### ISSUE TITLE
XMP-annotated PDF "Export" from library does not work

### ISSUE THREAD

**Issue by TPuupera** [JabRef/jabref#4399]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 
JabRef 5.0-dev--snapshot--2018-10-22--master--b9f9720d0
Windows 10 10.0 amd64 
Java 1.8.0_191

Tested also with stable version with same results:
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_191

Steps to reproduce:

1. Open BibTeX library.
2. Select from menu File->Import & Export->Export.
3. Enter "File name" and "Target location".
4. Select "Save as type" XMP-annotated PDF (*.pdf).
5. Click Save.

This will produce "Save library" error.
C:\testing\testing.pdf (The system cannot find the file specified)

It does not help if you try to overwrite some already existing PDF file.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
java.io.FileNotFoundException: C:\testing\testing.pdf (The system cannot find the file specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at org.apache.pdfbox.io.RandomAccessBufferedFileInputStream.<init>(RandomAccessBufferedFileInputStream.java:99)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1021)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:984)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:932)
	at org.jabref.logic.xmp.XmpUtilWriter.writeXmp(XmpUtilWriter.java:344)
	at org.jabref.logic.exporter.XmpPdfExporter.export(XmpPdfExporter.java:32)
	at org.jabref.gui.exporter.ExportCommand.lambda$export$601(ExportCommand.java:100)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:116)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</details>

**Comment by Siedlerchr** [comment]
Hi, the dialog is a bit unclear. You need to have an existing pdf. the xmp information will be written to the existing pdf. 
In the latest development version  it worked when I selected an existing pdf file and chose export.
Please try again with the version from https://builds.jabref.org/master/

**Comment by Siedlerchr** [comment]
I just tested and it works fine with Foxit Reader, at least if I exported one entry

**Comment by TPuupera** [comment]
Still the same problem. PDF reader displays title of the first exported entry as name for a blank document. Can someone else verify this feature?

**Comment by stefan-kolb** [comment]
@Siedlerchr Is this related to https://github.com/JabRef/jabref/issues/5605?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
