### ISSUE TITLE
Import pdf file into current library doesn't work in second time.

### ISSUE THREAD

**Issue by atteti** [JabRef/jabref#4422]
Tested with JabRef 4.21 64 bit Windows

1. Create new BibTeX library
2. Import into current library
3. Select PDFContent and choose pdf file.
4. Select Open
file is opened
//import second pdf file
5. Import into current library
6. Select PDFContent and choose pdf file.
7. Select Open
file is not opened
status. importing in unknown format...

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jabref.logic.importer.fileformat.PdfContentImporter.proceedToNextNonEmptyLine(PdfContentImporter.java:525)
	at org.jabref.logic.importer.fileformat.PdfContentImporter.importDatabase(PdfContentImporter.java:228)
	at org.jabref.gui.importer.ImportMenuItem$MyWorker.run(ImportMenuItem.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:120)
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85)
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102)
	at com.sun.proxy.$Proxy30.run(Unknown Source)
	at org.jabref.gui.importer.ImportMenuItem.automatedImport(ImportMenuItem.java:78)
	at org.jabref.gui.importer.ImportFormats$1ImportAction.doImport(ImportFormats.java:88)
	at org.jabref.gui.importer.ImportFormats$1ImportAction.lambda$actionPerformed$0(ImportFormats.java:75)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.importer.ImportFormats$1ImportAction.lambda$actionPerformed$1(ImportFormats.java:75)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by atteti** [comment]
Sorry, the version used is 4.3.1

**Comment by Siedlerchr** [comment]
Could you please test with the latest development version? https://builds.jabref.org/master/

**Comment by atteti** [comment]
I tested with the latest development version and it doesn't open pdf file second time. It opens only first time.
So there is same bug.

**Comment by atteti** [comment]
using css jar:file:/C:/jabref2/JabRef-5.0-dev--snapshot--2018-10-28--master--9a3f2d627.jar!/org/jabref/gui/Base.css is the verstion which I tested.

**Comment by atteti** [comment]
JabRef_windows-x64_5_0-dev--snapshot--2018-10-28--master--9a3f2d627.exe 28.10.2018 13:43 68.6 
  sorry, this version I tested.

**Comment by Siedlerchr** [comment]
I could confirm this. This is very odd. In fact it's still an ArrayIndexOutOfBoundsException which is thrown and then somehow swallowed from the executor

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
