### ISSUE TITLE
Problem while saving

### ISSUE THREAD

**Issue by mfoitlr** [JabRef/jabref#4442]
JabRef 4.3.1
Windows 7 6.1 amd64 
Java 1.8.0_191

Steps to reproduce:

1. make a change in the bibliography file
2. save the bibliography
3. Jabref freezes

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Opening: U:\mfo_shared_folder\Dokumente\ITLR\Literatur\literature_total.bib
Error while trying to monitor U:\mfo_shared_folder\Dokumente\ITLR\Literatur\literature_total.bib
java.io.IOException: Unzulässige Funktion.

	at sun.nio.fs.WindowsWatchService$Poller.implRegister(Unknown Source)
	at sun.nio.fs.AbstractPoller.processRequests(Unknown Source)
	at sun.nio.fs.WindowsWatchService$Poller.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Problem occured while saving.
java.lang.NullPointerException
	at java.nio.file.Files.provider(Unknown Source)
	at java.nio.file.Files.exists(Unknown Source)
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:158)
	at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1830)
	at org.jabref.gui.exporter.SaveDatabaseAction.checkExternalModification(SaveDatabaseAction.java:448)
	at org.jabref.gui.exporter.SaveDatabaseAction.init(SaveDatabaseAction.java:89)
	at org.jabref.gui.BasePanel.runWorker(BasePanel.java:293)
	at org.jabref.gui.exporter.SaveDatabaseAction.runCommand(SaveDatabaseAction.java:284)
	at org.jabref.gui.dialogs.AutosaveUIManager.listen(AutosaveUIManager.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(AutosaveManager.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Problem occured while saving.
java.lang.NullPointerException
	at java.nio.file.Files.provider(Unknown Source)
	at java.nio.file.Files.exists(Unknown Source)
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:158)
	at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.updateTimeStamp(BasePanel.java:1983)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:120)
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85)
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102)
	at com.sun.proxy.$Proxy30.run(Unknown Source)
	at org.jabref.gui.BasePanel.runWorker(BasePanel.java:299)
	at org.jabref.gui.exporter.SaveDatabaseAction.runCommand(SaveDatabaseAction.java:284)
	at org.jabref.gui.dialogs.AutosaveUIManager.listen(AutosaveUIManager.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(AutosaveManager.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Maybe related to #4352

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
