### ISSUE TITLE
Preference screen doesn't display

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4469]
JabRef version

JabRef 5.0-dev--snapshot--2018-11-07--master--144522d61
Linux 4.15.0-38-generic amd64 
Java 1.8.0_191

- [ yes] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Start Jabref
2. Click "Options".  Menu appears.
3. Select "Preferences".  Nothing happens.  Ever.  The program doesn't freeze.  But no options ever appear.

Here's the log:

Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]

**Comment by Siedlerchr** [comment]
Seems all normal to me in todays version 144522d

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2018-11-07--master--144522d61
Linux 4.15.0-38-generic amd64 
Java 1.8.0_191

Wrong (non) behaviour still there on my system.

**Comment by Siedlerchr** [comment]
Hi, please try to post a complete error mesage/stack trace from the console/terminal if you run it via java -jar JabRef.jar

Another option would be to try resetting the preferences: http://help.jabref.org/en/CommandLine#reset-preferences--d-key

**Comment by AEgit** [comment]
I cannot reproduce this bug with:

JabRef 5.0-dev--snapshot--2018-11-07--master--144522d61
Windows 10 10.0 amd64 
Java 1.8.0_191

**Comment by wujastyk** [comment]
Here's the error trace from the console:
java -jar ~/Dropbox/bin/JabRef--master--latest.jar 
13:52:33.208 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
13:52:48.050 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NegativeArraySizeException: null
	at org.jabref.gui.preferences.TableColumnsTab.setValues(TableColumnsTab.java:343) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.preferences.PreferencesDialog.setValues(PreferencesDialog.java:225) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.preferences.PreferencesDialog.construct(PreferencesDialog.java:151) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.preferences.PreferencesDialog.<init>(PreferencesDialog.java:95) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.actions.ShowPreferencesAction.execute(ShowPreferencesAction.java:15) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.actions.JabRefAction.lambda$new$1023(JabRefAction.java:29) ~[JabRef--master--latest.jar:?]
	at org.controlsfx.control.action.Action.handle(Action.java:419) ~[JabRef--master--latest.jar:?]
	at org.controlsfx.control.action.Action.handle(Action.java:64) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:?]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:?]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:?]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431) ~[jfxrt.jar:?]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:?]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by wujastyk** [comment]
I reset all the preferences, using -d all, and now JabRef is behaving properly again, and I can reach the Options screen.

If I change an option and save the preferences, and then run JabRef--master--latest.jar witout "-d all" then the behaviour reverts to the original problem.  I can't get to the Options screen.

JabRef 5.0-dev--snapshot--2018-11-09--master--bab9ae819
Linux 4.15.0-38-generic amd64 
Java 1.8.0_191

**Comment by wujastyk** [comment]
I deleted all findable config files for jabref, inlcuding in ~/.java/.UserPrefs/org/jabref, and now I can open and edit Options.

**Comment by Siedlerchr** [comment]
Okay, thanks for your feedback. The error looks like the underlying reason is somehow related to  #4459
