### ISSUE TITLE
NullPointerException when starting JabRef 4.3.1

### ISSUE THREAD

**Issue by hrittich** [JabRef/jabref#4471]
Hi,

I am trying to use JabRef version 4.3.1 on my Fedora 28. Unfortunately, I get the following error when starting.

    $ java -version
    openjdk version "1.8.0_191"
    OpenJDK Runtime Environment (build 1.8.0_191-b12)
    OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
    $ java -jar JabRef-4.3.1.jar
    17:12:37.963 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/[...]/documents.bib
    17:12:38.496 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
    java.lang.ExceptionInInitializerError: null
        at org.jabref.gui.IconTheme$JabRefIcon.<init>(IconTheme.java:287) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.IconTheme$JabRefIcon.<clinit>(IconTheme.java:172) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.GUIGlobals.init(GUIGlobals.java:79) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:101) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-4.3.1.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_191]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_191]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_191]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_191]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_191]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_191]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_191]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_191]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_191]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_191]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_191]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_191]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_191]
    Caused by: java.lang.NullPointerException
        at com.sun.javafx.font.PrismFontLoader.loadFont(PrismFontLoader.java:93) ~[jfxrt.jar:?]
        at javafx.scene.text.Font.loadFont(Font.java:455) ~[jfxrt.jar:?]
        at org.jabref.gui.IconTheme.<clinit>(IconTheme.java:63) ~[JabRef-4.3.1.jar:?]
        ... 20 more

Do you have any hint on what could go wrong?

Regards

**Comment by hrittich** [comment]
Hi,
I am sorry for bothering you. It is a bug in Fedora. The solution can be found [at reddit](https://www.reddit.com/r/Fedora/comments/84esww/openjfx_on_fedora_is_not_working/).

The following command resolves the issue:

    sudo dnf install java-1.8.0-openjdk-openjfx java-1.8.0-openjdk-openjfx-devel

Regards

**Comment by Siedlerchr** [comment]
Yeah, you were missing openjfx. Would you please be so kind and edit the fedora section?
We had already installation instructions for Fedora 23. 
http://help.jabref.org/en/Installation#fedora-23-and-oracle-java
