### ISSUE TITLE
Exception when downloading file with parameters

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4480]
JabRef version 5dev on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open entry editor > General fields tab
2. Using the "Download button" next to the file field, try to download an url with parameters like `https://www.jstor.org/stable/pdfplus/10.2307/2373250.pdf?acceptTC=true`
3. Get exception

  
  ```
  java.nio.file.InvalidPathException: Illegal char <?> at index 65: Smale1965 - An Infinite Dimensional Version of Sard's Theorem.pdf?accepttc=true
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
	at org.jabref.gui.fieldeditors.LinkedFileViewModel.lambda$download$375(LinkedFileViewModel.java:370)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.BackgroundTask$3.call(BackgroundTask.java:171)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:116)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

  ```

**Comment by Siedlerchr** [comment]
Hi thanks for your interest. This issue was solved a couple of days ago but we forgot to close the issue. Sorry! But there are plenty of other issues you can take.
