### ISSUE TITLE
4.3.1 fails to build on Slackware-14.2/x86_64

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#4497]
I'm configuring a new desktop running Slackware-14.2/x86_64. The jdks
available are openjdk-8u171_b11 and openjdk7-7u181_b01. This is the result
when I try to load the application:

]$ java -jar JabRef-4.3.1.jar Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jabref/JabRefMain :
Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

  What might be causing this?

**Comment by Siedlerchr** [comment]
The error indicates that the Java version or the Java home path environnement variable is not set correctly. You need jdk 8 and openjfx 8.

**Comment by rs-aesi** [comment]
On Fri, 16 Nov 2018, Christoph wrote:

> Well, you need `openjfx` for JabRef >4.x and the error indicates that java
> 7 is still in the path somewhere or the default java.

Christoph,

   Okay. I'll install it; there's a SlackBuilds.org package for it.

   There might be a java application here that still depends on java7. I'll
uninstall it, and only build it if an application complains.

> Check the version output if you run` java -version` in the terminal
> Try to change the java version with:
> ```
> sudo update-alternatives --config java
> sudo update-alternatives --config javac
> ```

   No update-alternatives on Slackware.

Regards,

Rich

**Comment by rs-aesi** [comment]
On Fri, 16 Nov 2018, Christoph wrote:

> Well, you need `openjfx` for JabRef >4.x and the error indicates that java
> 7 is still in the path somewhere or the default java. Check the version
> output if you run` java -version` in the terminal

Christoph,

   I removed the jdk packages and installed openjdk(7) because it's a
prerequisite for openjdk8 (at least on Slackware) and openjfk which mates
with openjdk8. Although I expected this to allow JabRef-4.3.1 to load it
didn't:

Installed packages:
openjdk-7u181-x86_64-1_SBo
openjdk8-8u181-x86_64-1_SBo
openjfx-8u60-x86_64-1_SBo

$ JabRef
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jabref/JabRefMain : Unsupported major.minor version 52.0
 	at java.lang.ClassLoader.defineClass1(Native Method)
 	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

   Please point me to what is still missing here. I appreciate your
assistance and look forward to getting JabRef working on the new desktop.

Best regards,

Rich

**Comment by rs-aesi** [comment]
On Sun, 18 Nov 2018, Christoph wrote:

> Maybe this article helps you
> https://medium.com/@swhp/installed-java-development-kit-jdk-on-slackware-14-2-ea133da179d0
> Try t

Christoph,

   Unfortunately, it doesn't have the solution.

   When I try to invoke JabRef I get this error:

$ JabRef
Error: Could not find or load main class org.jabref.JabRefMain

   Installed on this host are:

$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (linux-gnu build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

$ javac -version
javac 1.8.0_181

openjfx-8u60

   Are there other tests I can run to identify the source of the problem?

Regards,

Rich

**Comment by Siedlerchr** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
