### ISSUE TITLE
#4365 is back: preview copy fails

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4570]
JabRef 5.0-dev--snapshot--2019-01-05--master--d281ece4b
Linux 4.15.0-43-generic amd64
Java 1.8.0_191

The

null
null
null
null
null
null
null
null
null
null
null
null
null
null

behaviour reported on 9 December is back. :-(

As before, selecting the preview and copying it with ctrl+C does put an un-tagged copy into the buffer correctly. But ctrl+shft+C isn't working properly, either from the mouse right-click, the dropdown edit menu or by key presses.

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2019-01-28--master--fbf1cc9a4
Linux 4.15.0-44-generic amd64 
Java 1.8.0_201

Problem continues.
On using the menu to copy/preview/text, I get this popup error message:

![screenshot from 2019-01-29 12-55-33](https://user-images.githubusercontent.com/762246/51936539-a1b47b00-23c5-11e9-92c2-6f1c4274644a.png)

Event log below.



<details>
<summary>Detail information:</summary>

```
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Opening: /tmp/jabref485478443835204735.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Opening: /tmp/jabref485478443835204735.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.input.Clipboard.setContent(Clipboard.java:231)
	at org.jabref.gui.ClipBoardManager.setContent(ClipBoardManager.java:53)
	at org.jabref.gui.worker.CitationStyleToClipboardWorker.done(CitationStyleToClipboardWorker.java:188)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.input.Clipboard.setContent(Clipboard.java:231)
	at org.jabref.gui.ClipBoardManager.setContent(ClipBoardManager.java:53)
	at org.jabref.gui.worker.CitationStyleToClipboardWorker.done(CitationStyleToClipboardWorker.java:188)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

</details>

**Comment by Siedlerchr** [comment]
Thanks for your report. I think the underlying error is the same or similiar to the one I encounterd  in  #4622 
The citation style worker is a leftover from the old GUI technology.

**Comment by Siedlerchr** [comment]
Should be fixed now in the latest master.
Note that the Copy Preview copies both the HTML content and the plaintext content to the  clipboard. 
If you paste it into a word processor or tool that excepts html content (email for example) then it is correctly formatted with bold italics etc.
If you paste it into a plain text editor which does not support HTML formatting it is pasted as plain text.
