### ISSUE TITLE
Update check error 403 and wrong isbn

### ISSUE THREAD

**Issue by accon** [JabRef/jabref#4573]
JabRef 4.3.1
Windows 7 6.1 amd64 
Java 1.8.0_191

Steps to reproduce:

1. Open JabRef
2. New BibTexEntry
3. Enter ISBN 978-3-9817048-9-1 to the ID-based entry generator and click "Generate". 

I'm new to JabRef and don't know a lot about the background workings and setup. I have also found similar issues online and assume this problem has been solved, however I wasn't able to reproduce the solution on my machine, so it'd be great if someone could walk me through the necessary steps.

Log:
<details>
<summary>Detail information:</summary>

```
Opening: C:\Users\wulf_ni\Documents\03 Projects\BEniVer\Literature\JabRef\Meta-Scenarios.bib
Could not connect to the updateserver.
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/JabRef/JabRef/releases
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.util.Version.getAllAvailableVersions(Version.java:96)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:55)
	at org.jabref.gui.worker.VersionWorker.doInBackground(VersionWorker.java:29)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Can only load style files: Preview
Can only load style files: Preview
Fix SSL exceptions by accepting ALL certificates

Error while retrieving data from chimbori.com: @comment{
Error fetching metadata for ISBN 9783981704891. Check if it is valid by searching at Amazon.com.
AWS.InvalidParameterValue : 9783981704891 is not a valid value for ItemId. Please change this value and retry your request.
}
org.jabref.logic.importer.FetcherException: Error while retrieving data from chimbori.com: @comment{
Error fetching metadata for ISBN 9783981704891. Check if it is valid by searching at Amazon.com.
AWS.InvalidParameterValue : 9783981704891 is not a valid value for ItemId. Please change this value and retry your request.
}
	at org.jabref.logic.importer.fetcher.IsbnViaChimboriFetcher.performSearchById(IsbnViaChimboriFetcher.java:58)
	at org.jabref.logic.importer.fetcher.IsbnFetcher.performSearchById(IsbnFetcher.java:50)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Hi,
the first one is simply an error from the Update check, probably some temporary thing. 

Well, the other exception is related to the ISBN fetcher. JabRef checks two sites (ebook.de and Amazon) for bibtesx data from an isbn.
This error indicates that no data for the ISBN could not be received (using Amazon). This is a problem on the Amazon side, I checked it. Other isbns work fine and therefore in JabRef, too.  Nothing we can do about.
In such cases you could manually try http://ottobib.com in your browser:
Here is the result I got from it using your ISBN.
You can simply copy the bibtex code and directly paste it on the maintable and your entry will be created.

```
@Book{ausfelder2017sektorkopplung",
 author = {Ausfelder, Florian},
 title = {Sektorkopplung" - Untersuchungen und Überlegungen zur Entwicklung eines integrierten Energiesystems},
 publisher = {acetech - Deutsche Akademie der Technikwissenschaften e.V.,Deutsche Akademie der Naturforscher Leopoldina e.V. - Nationale Akademie der WissenschaftenUnion der Deutschen Akademien der Wissenschaften e.V},
 year = {2017},
 address = {München Halle (Saale) Mainz},
 isbn = {978-3981704891}
 }

```
