### ISSUE TITLE
Opening preference window leads to uncaught exception

### ISSUE THREAD

**Issue by CaptainDaVinci** [JabRef/jabref#4751]
JabRef development version, Arch Linux.

Opening preferences window after making certain changes lead to `Uncaught exception occurred in Thread[JavaFX Application Thread, 5, main]`

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce the behavior: Not sure.

<details>
  <summary>Log File</summary>
  
  ```
java.nio.file.ClosedWatchServiceException
	at sun.nio.fs.AbstractPoller.invoke(AbstractPoller.java:216)
	at sun.nio.fs.AbstractPoller.register(AbstractPoller.java:125)
	at sun.nio.fs.LinuxWatchService.register(LinuxWatchService.java:90)
	at sun.nio.fs.UnixPath.register(UnixPath.java:897)
	at sun.nio.fs.AbstractPath.register(AbstractPath.java:104)
	at org.jabref.gui.util.DefaultFileUpdateMonitor.addListenerForFile(DefaultFileUpdateMonitor.java:78)
	at org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:100)
	at org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:81)
	at org.jabref.gui.util.BaseDialog.<init>(BaseDialog.java:30)
	at org.jabref.gui.preferences.PreferencesDialog.<init>(PreferencesDialog.java:63)
	at org.jabref.gui.actions.ShowPreferencesAction.execute(ShowPreferencesAction.java:19)
	at org.jabref.gui.actions.JabRefAction.lambda$2(JabRefAction.java:29)
	at org.controlsfx.control.action.Action.handle(Action.java:419)
	at org.controlsfx.control.action.Action.handle(Action.java:64)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$6(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

  ```
</details>

**Comment by Siedlerchr** [comment]
The error is coming from the CSS watcher. It watches the base.css for changes, if you run JabRef from code.
This enables on the fly debugging of styles. Maybe you have somehow another instance open which has a lock on the file or some other thread?
```
 at org.jabref.gui.util.DefaultFileUpdateMonitor.addListenerForFile(DefaultFileUpdateMonitor.java:78)
  at org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:100)
  at org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:81)
```
