### ISSUE TITLE
External addition/removal of new entry causes NullPointerException in review dialog

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#4786]
JabRef version 5.0dev (latest) on Windows 10
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In case you add an entry externally and check the change in the review dialog a `NullPointerException` is thrown.

1. Open a bib file.
2. Add an entry in external text editor
3. Review change "Added Entry"

<details>
  <summary>Log File</summary>
  
  ```
 java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_121]
	at org.jabref.gui.PreviewPanel.<init>(PreviewPanel.java:90) ~[classes/:?]
	at org.jabref.gui.collab.EntryAddChangeViewModel.description(EntryAddChangeViewModel.java:32) ~[classes/:?]
	at org.jabref.gui.collab.ChangeDisplayDialog.selectedChangeChanged(ChangeDisplayDialog.java:77) ~[classes/:?]
	at org.fxmisc.easybind.EasyBind.lambda$subscribe$12(EasyBind.java:263) ~[easybind-1.0.3.jar:?]
  ```
</details>

Reason is quite obvious as a `null` database context is passed to `PreviewPanel` constructor which is stating: `Objects.requireNonNull(databaseContext);`

Apart from `EntryAddChangeViewModel` also `EntryDeleteChangeViewModel` is affected

**Comment by Siedlerchr** [comment]
Just pass a new BibDatabase() as parameter. That should work. It's done in the settings as well

**Comment by Siedlerchr** [comment]
Should be fixed now in the latest version
