### ISSUE TITLE
Importing from Medline gives an error

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4840]
JabRef 5.0-dev--snapshot--2019-04-03--master--a273eb1fa
Windows 7 6.1 amd64 
Java 1.8.0_201
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The error is new since the latest version I tested (2019-03-30--master--40600b354)
1. ...
2. ...
3. ...

`java.lang.NullPointerException
	at com.jfoenix.controls.JFXSnackbar.refreshPopup(JFXSnackbar.java:269)
	at com.jfoenix.controls.JFXSnackbar.lambda$new$1(JFXSnackbar.java:87)
	at com.jfoenix.controls.JFXSnackbar$$Lambda$2.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.Node$LazyBoundsProperty.invalidate(Node.java:9316)
	at javafx.scene.Node.impl_layoutBoundsChanged(Node.java:3401)
	at javafx.scene.Node.impl_notifyLayoutBoundsChanged(Node.java:3814)
	at javafx.scene.Node.impl_geomChanged(Node.java:3765)
	at javafx.scene.Parent.childBoundsChanged(Parent.java:1757)
	at javafx.scene.Node.notifyParentOfBoundsChange(Node.java:3836)
	at javafx.scene.Node.transformedBoundsChanged(Node.java:3798)
	at javafx.scene.Node.localBoundsChanged(Node.java:3780)
	at javafx.scene.Node.impl_geomChanged(Node.java:3766)
	at javafx.scene.Parent$1.onChanged(Parent.java:343)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$22(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:142)
	at com.jfoenix.controls.JFXSnackbar.lambda$enqueue$10(JFXSnackbar.java:242)
	at com.jfoenix.controls.JFXSnackbar$$Lambda$10.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
`
<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
@r0light  Seems like a follow up error of the Snackbar move. Could you please look into this?

**Comment by r0light** [comment]
ok, i will have a look

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
