### ISSUE TITLE
Borderless program launch under Linux Mint

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4911]
JabRef 5.0-dev--snapshot--2019-04-20--master--e63bc21ab
Linux 4.15.0-47-generic amd64 
Java 1.8.0_191

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Launch Jabref 5.0 dev from a shell script:
```
#!/bin/bash
# development snapshot
java -jar /home/dom/Dropbox/bin/JabRef--master--latest.jar

```
2. the program opens and fills the whole screen with no window bars.  One can minimize the JabRef display but cannot change the size of the display.

3. Going to a terminal and typing the CLI command
```
java -jar /home/dom/Dropbox/bin/JabRef--master--latest.jar
```
the program starts with window borders, but with all options reverted to default (I think).

After this, the behaviour described in 2. doesn't happen for a couple of launches, and then it reverts to the borderless behaviour again.

4. While there was a border and things seemed okay, I went to Options and got an uncaught exception error

![image](https://user-images.githubusercontent.com/762246/56553117-94cda080-654a-11e9-94d7-802a3614195f.png)

```
java.lang.NegativeArraySizeException
	at org.jabref.gui.preferences.TableColumnsTab.setValues(TableColumnsTab.java:319)
	at org.jabref.gui.preferences.PreferencesDialog.setValues(PreferencesDialog.java:256)
	at org.jabref.gui.preferences.PreferencesDialog.construct(PreferencesDialog.java:181)
	at org.jabref.gui.preferences.PreferencesDialog.<init>(PreferencesDialog.java:105)
	at org.jabref.gui.actions.ShowPreferencesAction.execute(ShowPreferencesAction.java:19)
	at org.jabref.gui.actions.JabRefAction.lambda$new$942(JabRefAction.java:29)
	at org.controlsfx.control.action.Action.handle(Action.java:419)
	at org.controlsfx.control.action.Action.handle(Action.java:64)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$6(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

<details>
  <summary>Log File</summary>
  
  ```
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Preview style changed to: Springer - Humanities (author-date)
Copied version to clipboard
Copied version to clipboard
  ```
</details>

**Comment by Siedlerchr** [comment]
I was able to partly reproduce this, I enabled the extra columns for arxiv etc in the options and after a restart I am getting the same same error. The borderless thing is another issue I think.

**Comment by Siedlerchr** [comment]
The bug with opening the preferences should be fixed now in the next build. It was coming from the "Enable extra columns" in the Table Column preferences tab, I submitted a hotfix for this problem.
The preferences tab will be redesigned soon.

The border less thing is mysterious but might have been somehow related.
Please report back if it's working
