### ISSUE TITLE
Starting Jabref works, but there is no visible application

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#4925]
JabRef version 4.3.1

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists
- [x] The development version for my system is flagged out-of-date since November 2018

1. I run Jabref
2. It seems to be running (I see the java process)
3. There is no visible application

<details>
  <summary>Console output</summary>
  
```
09:22:36.302 [AWT-EventQueue-0] DEBUG org.jabref.logic.logging.JabRefLogger - Showing debug messages
09:22:36.305 [AWT-EventQueue-0] DEBUG org.jabref.cli.ArgumentProcessor - Finished export
09:22:36.423 [AWT-EventQueue-0] DEBUG org.jabref.logic.remote.client.RemoteClient - Could not ping server at port 6050
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_212]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_212]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_212]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_212]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_212]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_212]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_212]
        at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_212]
        at java.net.Socket.<init>(Socket.java:244) ~[?:1.8.0_212]
        at org.jabref.logic.remote.client.RemoteClient.openNewConnection(RemoteClient.java:64) ~[JabRef-4.3.1.jar:?]
        at org.jabref.logic.remote.client.RemoteClient.ping(RemoteClient.java:28) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.handleMultipleAppInstances(JabRefMain.java:136) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.start(JabRefMain.java:121) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:51) ~[JabRef-4.3.1.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_212]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_212]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_212]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_212]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_212]
09:22:38.252 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /x/y/z.bib
09:22:38.475 [AWT-EventQueue-0] DEBUG org.jabref.logic.importer.OpenDatabase - Synchronized special fields based on keywords
09:22:38.527 [AWT-EventQueue-0] DEBUG org.jabref.JabRefGUI - Initializing frame
09:22:38.894 [AWT-EventQueue-0] DEBUG org.jabref.gui.SidePaneManager - Following side pane could not be found: WEB_SEARCH
java.lang.ClassNotFoundException: WEB_SEARCH
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
        at org.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.fillMenu(JabRefFrame.java:1154) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.initLayout(JabRefFrame.java:901) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.init(JabRefFrame.java:586) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:468) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:104) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-4.3.1.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_212]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_212]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_212]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_212]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_212]
09:22:38.895 [AWT-EventQueue-0] DEBUG org.jabref.gui.SidePaneManager - Following side pane could not be found: GROUPS
java.lang.ClassNotFoundException: GROUPS
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
        at org.jabref.gui.SidePaneManager.getPreferredPositions(SidePaneManager.java:167) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.access$000(SidePaneManager.java:25) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager$PreferredIndexSort.<init>(SidePaneManager.java:213) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.show(SidePaneManager.java:124) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.SidePaneManager.show(SidePaneManager.java:96) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.fillMenu(JabRefFrame.java:1154) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.initLayout(JabRefFrame.java:901) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.init(JabRefFrame.java:586) ~[JabRef-4.3.1.jar:?]
        at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:468) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:104) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67) ~[JabRef-4.3.1.jar:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-4.3.1.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_212]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_212]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_212]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_212]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_212]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_212]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_212]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_212]
File: grouptree.fxml not found, attempting with camel case
09:22:39.022 [JavaFX Application Thread] DEBUG org.jabref.gui.DefaultInjector - Instantiate org.jabref.gui.groups.GroupTreeController
File: grouptree.css not found, attempting with camel case
09:22:40.174 [AWT-EventQueue-0] DEBUG org.jabref.JabRefGUI - Finished adding panels
```
</details>

**Comment by Siedlerchr** [comment]
Hi,
First of all we need some more information. Which OS are you running on? 
Have you installed the latest java 8 version?

What do you mean with the "The development version for my system is flagged out-of-date since November 2018"?

**Comment by j0hannes** [comment]
Hi,

I'm running Arch and this is the package for Arch that is outdated: https://aur.archlinux.org/packages/jabref-git/

The long-running problem of the OS picking the newest Java version (10) instead of the required old one (8) has been solved in the meantime:
```
% cat /usr/bin/jabref 
#!/bin/sh

/usr/bin/archlinux-java-run --min 8 --max 8 --feature javafx -- -jar /usr/share/java/jabref/JabRef-4.3.1.jar "$@"
```

Java 8 is provided by the package java-openjfx  8.u172-2.

**Comment by Siedlerchr** [comment]
Hi,

we do not maintain the Linux packages for JabRef. This is done by others.
However, you can simply replace the jar with the latest one from the https://builds.jabref.org/master/

or you can try to use the snap version
`snap install jabref --edge`

**Comment by j0hannes** [comment]
I'll try that when I'm back on that machine.

Independent of the version, what can make the application running without interface? I do see the obligatory "Backup found" dialogues but after clicking "no", nothing will happen anymore, but the process consuming some CPU cycles.

**Comment by stefan-kolb** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
