### ISSUE TITLE
Field right-click 'Protect terms' resulting in error

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4958]
JabRef 5.0-dev--snapshot--2019-05-06--master--c168c4978
Windows 10 10.0 amd64 
Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add author field, ie: Directorate-General for Research and Innovation
2. Right-click and select Protect terms > Add {} around selected text
3. Error (see screenshot)
4. Even if the {} brackets are manually added, it is ignored in the main list

![image](https://user-images.githubusercontent.com/10846169/57295300-7929d480-70ca-11e9-96e6-e48c609ef328.png)

<details>
  <summary>Log File</summary>

  ```
  java.lang.IllegalStateException: Task must only be used from the FX Application Thread
	at javafx.concurrent.Task.checkThread(Task.java:1218)
	at javafx.concurrent.Task.isRunning(Task.java:985)
	at org.controlsfx.control.textfield.AutoCompletionBinding.onUserInputChanged(AutoCompletionBinding.java:333)
	at org.controlsfx.control.textfield.AutoCompletionBinding.setUserInput(AutoCompletionBinding.java:135)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.setUserInputText(AutoCompletionTextInputBinding.java:136)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.lambda$new$1074(AutoCompletionTextInputBinding.java:54)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
	at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
	at javafx.scene.control.TextInputControl.lambda$new$162(TextInputControl.java:139)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:87)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1204)
	at javafx.scene.control.TextInputControl.filterAndSet(TextInputControl.java:1171)
	at javafx.scene.control.TextInputControl.access$900(TextInputControl.java:79)
	at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1410)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1323)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1300)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:601)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked(BindingsHelper.java:234)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedB(BindingsHelper.java:227)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:320)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:169)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:413)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupSingleField(FieldFormatterCleanup.java:63)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupAllTextFields(FieldFormatterCleanup.java:88)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanup(FieldFormatterCleanup.java:32)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applyAllActions(FieldFormatterCleanups.java:71)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applySaveActions(FieldFormatterCleanups.java:61)
	at org.jabref.logic.exporter.BibDatabaseWriter.lambda$applySaveActions$192(BibDatabaseWriter.java:60)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.logic.exporter.BibDatabaseWriter.applySaveActions(BibDatabaseWriter.java:57)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:172)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:143)
	at org.jabref.logic.autosaveandbackup.BackupManager.performBackup(BackupManager.java:124)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.logic.autosaveandbackup.BackupManager.lambda$new$132(BackupManager.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
  ```
</details>

**Comment by Siedlerchr** [comment]
Threading problem in Cleanup/setFields. I think we had simliar issues already with the cleanup dialog and could solve this somewhow.

**Comment by Siedlerchr** [comment]
@DOFfactory It seems like you have save actions enabled. Do you maybe have Latex2Unicode formatting enabled as save actions?
Please look at the  LIbrary-> Library Propertes menu and post the list of save actions

**Comment by DOFfactory** [comment]
Hi @Siedlerchr, you are right, whenever I create a biblatex library, I usually set up the user-specific library for the respective library (instead of one single library location), and I also click at the Save actions - Enable save actions > Recommended for biblatex.

This last action automatically enables the all-text-fields: Latex to Unicode option. While I can disable it, I think it is a useful conversion, and it should be rather Latex to UTF-8 instead and not firing an error mentioned in my 1st post.

**Comment by Siedlerchr** [comment]
@DOFfactory  Okay thanks! Now I could reproduce the error. 
Regarding the protected terms: This is a known issue with the Latex2Unicode conversion: 
#4152

**Comment by DOFfactory** [comment]
Thanks. Sorry, I was not aware of the fact that it has been already reported. Something similar happens also if one copy&pastes a text from the website directly to the `Abstract` field.

**Comment by Siedlerchr** [comment]
@DOFfactory  This are two different issues. The error reported from your log comes from the save actions and is defintively a bug. And the same underlying error for every other field.

The other issue you noticed is that the braces of corporate authors vanish. That is the issue  #4152

**Comment by dimmonn** [comment]
hi guys, can I pick this one?

**Comment by homocomputeris** [comment]
Latest Git version
JabRef 5.0-dev
Linux 5.1.8-zen1-1-zen amd64 
Java 1.8.0_212
```
java.lang.IllegalStateException: Task must only be used from the FX Application Thread
	at javafx.concurrent.Task.checkThread(Task.java:1218)
	at javafx.concurrent.Task.isRunning(Task.java:985)
	at org.controlsfx.control.textfield.AutoCompletionBinding.onUserInputChanged(AutoCompletionBinding.java:333)
	at org.controlsfx.control.textfield.AutoCompletionBinding.setUserInput(AutoCompletionBinding.java:135)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.setUserInputText(AutoCompletionTextInputBinding.java:136)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.lambda$new$394(AutoCompletionTextInputBinding.java:54)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
	at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
	at javafx.scene.control.TextInputControl.lambda$new$0(TextInputControl.java:139)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:87)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1204)
	at javafx.scene.control.TextInputControl.filterAndSet(TextInputControl.java:1171)
	at javafx.scene.control.TextInputControl.access$900(TextInputControl.java:79)
	at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1410)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1323)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1300)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:601)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked(BindingsHelper.java:234)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedB(BindingsHelper.java:227)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:320)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:169)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:413)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupSingleField(FieldFormatterCleanup.java:63)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanup(FieldFormatterCleanup.java:34)
	at org.jabref.logic.cleanup.CleanupWorker.cleanup(CleanupWorker.java:31)
	at org.jabref.gui.cleanup.CleanupAction.doCleanup(CleanupAction.java:90)
	at org.jabref.gui.cleanup.CleanupAction.cleanup(CleanupAction.java:133)
	at org.jabref.gui.cleanup.CleanupAction.lambda$action$708(CleanupAction.java:65)
	at org.jabref.gui.util.BackgroundTask$2.call(BackgroundTask.java:55)
	at org.jabref.gui.util.BackgroundTask$2.call(BackgroundTask.java:52)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:122)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
