### ISSUE TITLE
Libre Office + JabRef 4.3.1 : manage citations errors

### ISSUE THREAD

**Issue by andrejdam** [JabRef/jabref#5015]
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_181
LibreOffice Version: 6.1.3.2 (x64)

Steps to reproduce:

1. Connect JabRef with LibreOffice Version: 6.1.3.2 (x64). Connection with a document with already present JabRef citations works fine.
2. Click on [Manage citations] in JabRef's LibreOffice connector. Nothing happens.
3. But an error log is created:

I'd appreciate your help with this because JabRef was working just fine with LibreOffice just a day ago. Yesterday something broke, have no idea what, and now I cannot manage or synchronize my references.

<details>
<summary>Detail information:</summary>

```
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
com.sun.star.uno.RuntimeException: End of content node doesn't have the proper start node
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:158)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:122)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:312)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:281)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:81)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:618)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:145)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:129)
	at com.sun.proxy.$Proxy49.createTextCursorByRange(Unknown Source)
	at org.jabref.gui.openoffice.OOBibBase.getCitationContext(OOBibBase.java:947)
	at org.jabref.gui.openoffice.CitationManager.<init>(CitationManager.java:70)
	at org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$11(OpenOfficePanel.java:259)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Hi,

could you please test the latest master version? There have been some changes to the manage citations dialog and error handling.

Your error indicates that somewhere a citation in your document is not correct. Maybe you deleted one citaiton that still has a marker left

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by andrejdam** [comment]
Hello,

I ran the .jar file and tried the same thing. The error log is below. However, before I go into that, I must say that I really appreciate what you've done with the user interface, and the new dark theme! Great job.

Here's the error log. It shows me an [Exception Details] window with this content: 

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]

Cannot load org.jabref.gui.openoffice.managecitationsdialog

The exception stacktrace was:

<code>
java.lang.IllegalStateException: Cannot load org.jabref.gui.openoffice.managecitationsdialog
	at com.airhacks.afterburner.views.ViewLoader.load(ViewLoader.java:174)
	at org.jabref.gui.openoffice.ManageCitationsDialogView.<init>(ManageCitationsDialogView.java:45)
	at org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$647(OpenOfficePanel.java:271)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
file:/D:/%d0%a1%d0%b8%d0%bc%d0%bd%d1%83%d0%b2%d0%b0%d1%9a%d0%b0/%d0%9f%d1%80%d0%be%d0%b3%d1%80%d0%b0%d0%bc%d0%b8/%d0%90%d0%bb%d0%b0%d1%82%d0%ba%d0%b8/%d0%90%d0%ba%d0%b0%d0%b4%d0%b5%d0%bc%d1%81%d0%ba%d0%b8/JabRef/JabRef--master--latest%20(5.0).jar!/org/jabref/gui/openoffice/ManageCitationsDialog.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.airhacks.afterburner.views.ViewLoader.load(ViewLoader.java:172)
	... 57 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 60 more
Caused by: com.sun.star.uno.RuntimeException: End of content node doesn't have the proper start node
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:158)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:122)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:312)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:281)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:81)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:618)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:145)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:129)
	at com.sun.proxy.$Proxy45.createTextCursorByRange(Unknown Source)
	at org.jabref.gui.openoffice.OOBibBase.getCitationContext(OOBibBase.java:955)
	at org.jabref.gui.openoffice.ManageCitationsDialogViewModel.<init>(ManageCitationsDialogViewModel.java:43)
	at org.jabref.gui.openoffice.ManageCitationsDialogView.initialize(ManageCitationsDialogView.java:61)
	... 70 more
</code>

**Comment by Siedlerchr** [comment]
Okay, thanks for the test! I already feared that. The error is with one of the citation markers in your document. 
. You need to try to narrow it down a bit. Have you deleted or removed a part of a citation recently? That could explain the error. There's unfortunately nothing we can do about on the JabRef side

**Comment by andrejdam** [comment]
This problem might be even weirder than what you suspect. I can see that you are right about stemming from the citation markers - but what I noticed is that multiple citation markers exist for the same citation, probably playing foul with JabRef.

<img width="851" alt="JabRef references issue" src="https://user-images.githubusercontent.com/51234066/58710299-86756e80-83ab-11e9-8d16-13c0bdf4956b.png">

The picture shows that in LibreOffice's Navigator, in the [References] list item, there are references that exist multiple times, even though they are cited only once in the document. Some of the references in the list take me to their position when double-clicked, some don't. 

What I did try to do yesterday before this is to add references before already existing ones, and then delete the old ones (i.e. cite (Fagella 2019) before already existing (Fagella 2019) citation in the text, and then delete, now the second one). This can explain why the list contains multiple copies of the same citation.

However, I cannot figure out how to fix this i.e. how to delete the citation markers, or how to convert them to plain text, so that I can add the citations again while remembering where they are located in the document.

Do you have any idea in this regards?

Thanks,
And

**Comment by Siedlerchr** [comment]
@andrejdam 
I tried the solution outlined in the help docs of Libre Office,  which works, replacing the field marker with the text:
>References are fields. To remove a reference, delete the field. If you set a longer text as a reference and you do not want to reenter it after deleting the reference, select the text and copy it to the clipboard. You can then reinsert it as "unformatted text" at the same position using the command Edit - Paste special. The text remains intact while the reference is deleted.

https://help.libreoffice.org/6.1/en-US/text/swriter/01/04090002.html

**Comment by andrejdam** [comment]
@Siedlerchr , thanks for that comment. Unfortunately, it doesn't work. Yes, I can delete **one** of the cited references when I delete the citation marker in the text - but the others remain (see the picture below) As you can see, one of the 3 reference objects per citation was deleted (i.e. JR_cite0_1_Azoulay2018), but the other two remain in the document - and they are nowhere to be found (double-clicking them takes me nowhere). 

I guess it must be something with how JabRef creates those objects inside LibreOffice. And the damn Navigator does not allow to delete the cited objects directly from there - so I am stuck now with objects that don't exist, but mess up with my JabRef sync.

<img width="864" alt="JabRef references issue 2" src="https://user-images.githubusercontent.com/51234066/58712334-ebcb5e80-83af-11e9-981b-5164a92f1f2f.png">

**Comment by Siedlerchr** [comment]
@andrejdam  Try CTRL + F9, that should show the marker name itself e.g. JR_CITE_ and not the content
(I remember that shortcut from word, works also in writer)

**Comment by andrejdam** [comment]
@Siedlerchr Thanks, I tried that again to no avail. It doesn't show the fields anywhere in the text, unfortunately.

I also asked a question on how to remove fields like those on LO's forum (since they cannot be deleted through the Navigator, which is very weird), hope to get a timely response.

**Comment by Siedlerchr** [comment]
Hm that is very odd. Agree with you, a right click option in the navigator -> delete reference would be cool.
You could also send me your doc + bib file privately via mail (developers@jabref.org) and I could also try to find a way to remove these things.

**Comment by andrejdam** [comment]
OK, I resolved the problem. The problem was with LibreOffice tracking of changes. The tracking kept the objects existing while they were deleted in the text. When I accepted all changes, the ghost fields were deleted, and I can synchronize my citations and references again.

I don't know if there's anything you can do on your side to amend people when working on their documents with track changes. This sucks, as I cannot track my changes anymore if I am to work with JabRef. I guess I will survive.

Thanks for your assistance @Siedlerchr

**Comment by Siedlerchr** [comment]
@andrejdam  As this original issue is resolved, could you please open a new one stating the feature request regarding the tracking changes problem so that it doesn't get lost.
