### ISSUE TITLE
drag and drop file into file field in entry editor throws exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5020]
JabRef 5.0-dev (latest snap release)
Linux 5.1.5-300.fc30.x86_64 amd64 
Java 1.8.0_212

Steps to reproduce:

drag and drop file into file field in entry editor

Paste your log details here.

<details>
<summary>Detail information:</summary>

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException
	at javafx.scene.Scene$DnDGesture.access$6000(Scene.java:2909)
	at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2876)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$226(GlassSceneDnDEventHandler.java:95)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$309(GlassViewEventHandler.java:672)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:671)
	at com.sun.glass.ui.View.handleDragDrop(View.java:712)
	at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

</details>

**Comment by ilippert** [comment]
also, maybe this is a different bug(?), the file dragged onto the file field is renamed and stays in the origin folder, and a copy of the not-renamed file is saved within the default file folder of jabref.

**Comment by ilippert** [comment]
this is from an up to date snap version on fedora 30
drag and drop of file onto a file field in entry editor still produces this exception:

sorry for tagging you, @tobiasdiez I am not sure whether this issue old has fallen of the radar ;) would be great to know if you need any more information to serve the community approaching this.

<summary>Detail information:</summary>
java.lang.NullPointerException
	at javafx.scene.Scene$DnDGesture.access$6000(Scene.java:2909)
	at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2876)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$226(GlassSceneDnDEventHandler.java:95)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$309(GlassViewEventHandler.java:672)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:671)
	at com.sun.glass.ui.View.handleDragDrop(View.java:712)
	at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

</details>

**Comment by Siedlerchr** [comment]
This might be a problem with the snap functionality and the interaction with the file system.
Maybe @LyzardKing  can reproduce this error?
 However, I am unsure if we can do anything about this, as the error is coming directly from the java run time classes.

**Comment by ilippert** [comment]
thanks for looking into this! interestingly, when using the + button next to the file field in the entry editor, the file selection window interacts well with nautilus

**Comment by Siedlerchr** [comment]
I will try to test this with Ubuntu in my VM and a snap, see if I get the same error

**Comment by LyzardKing** [comment]
Hi.
I tried now on ubuntu 19.04 with the updated snap.. the drag and drop feature works..

**Comment by LyzardKing** [comment]
@Siedlerchr Have you done any more testing?

**Comment by Siedlerchr** [comment]
@LyzardKing  Jus tested it. Works fine under Ubuntu 18.04 
Just one thing, I get a message in console that the snap java version is 8u60 although my global runtime is 1.8.0_171.

Do snaps ship with their own jre/jdk version?
```
Jul 12, 2019 8:37:07 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
```

**Comment by LyzardKing** [comment]
The snap has it's own jdk/jre version, which is the one from the ubuntu 16.04 repos.
it should be 8u212-b03-0ubuntu1.16.04.1 according to packages.ubuntu.com
8u60 is the version of openjfx.
When I last tested the snap it would not work with 18.04 as a source. But I test it every once in a while to see if it works with the later versions of openjfx

**Comment by ilippert** [comment]
I updated my snap version and dragging/dropping a file onto the entry-editor's file field gives me this e

<details>
java.lang.NullPointerException
	at javafx.scene.Scene$DnDGesture.access$6000(Scene.java:2909)
	at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2876)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$226(GlassSceneDnDEventHandler.java:95)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$309(GlassViewEventHandler.java:672)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:671)
	at com.sun.glass.ui.View.handleDragDrop(View.java:712)
	at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by Siedlerchr** [comment]
@ilippert  Which GUI/OS are you running`? Fedora? GTK2/GTK3?
Seems to be at ting of your OS then which differs.

**Comment by ilippert** [comment]
Sorry, yes, Fedora30

Copy version has this output:
JabRef 5.0-dev
Linux 5.1.16-300.fc30.x86_64 amd64 
Java 1.8.0_212

sorry, not sure about how to test for GTK2/GTK3.

**Comment by LyzardKing** [comment]
being a strict snap I believe it should work...
I'm not sure though

**Comment by Siedlerchr** [comment]
@ilippert  Could you please test if this issue still occurs with the latest snap version which uses java + gtk 3?

**Comment by ilippert** [comment]
I updated the snap version. 
adding a file via the "+" file selector works.
drag and drop did not throw an exception but did not generate any link, no effect.
Cheers
Ingmar

**Comment by Siedlerchr** [comment]
@ilippert  This is because drag and drop  now respects the systems modifiers :
For Ubuntu Xfcethe following modifiers are avaiable:
```
Shift+Drag: Move
Ctrl+Drag: Copy
Ctr+Shift+Drag: Link
```

In addtion you can specify in the preferences what happens when you drop on the maintable.

**Comment by ilippert** [comment]
I confirm the modifier Shift+Drag to work.
The Preferences | Import section does not make clear to me where I can define a default event that happens when I drop something on the file field of the entry table (maybe add a help section?). To me, it is not intuitive that I need to use the key modifiers. Now that I know about these I appreciate these. But I wonder whether a "simple" question to the user might be helpful... e.g. "you dropped a file on the entry editor. what do you want to do? move, copy, link? select one. should this be default? check box vs ask me again..."

sorry, this is an UI issue - should I open another issue for this?

**Comment by Siedlerchr** [comment]
Yes, it lacks the documentation in the help. Feel free to edit the section. For the dialog you might want to add another issue,
