### ISSUE TITLE
Unable to save library

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#5053]
JabRef 5.0-dev
Linux 5.1.8-zen1-1-zen amd64 
Java 1.8.0_212

**Steps to reproduce:**
Try to save library

<details>
<summary>Detail information:</summary>

```
Doing a cleanup for 1 entries...
One entry needed a clean up
Doing a cleanup for 1 entries...
No entry needed a clean up
Updated entry with info from ArXiv
Doing a cleanup for 1 entries...
No entry needed a clean up
Doing a cleanup for 1 entries...
One entry needed a clean up
Updated entry with info from DOI
Doing a cleanup for 1 entries...
One entry needed a clean up
Updated entry with info from DOI
Doing a cleanup for 1 entries...
One entry needed a clean up
Updated entry with info from DOI
Doing a cleanup for 1 entries...
One entry needed a clean up
Deleted 1 entry.
Saving library...
A problem occurred when trying to save the file /home/user/Documents/TeX/Bibliography/library.bib
org.jabref.logic.exporter.SaveException: Problems saving:
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:86)
	at org.jabref.gui.exporter.SaveDatabaseAction.doSave(SaveDatabaseAction.java:123)
	at org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:163)
	at org.jabref.gui.JabRefFrame.confirmClose(JabRefFrame.java:1137)
	at org.jabref.gui.JabRefFrame.quit(JabRefFrame.java:429)
	at org.jabref.JabRefGUI.lambda$openWindow$70(JabRefGUI.java:148)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$3(GlassWindowEventHandler.java:151)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1270)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1174)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error in field 'abstract': Unescaped '}' character without opening bracket ends string prematurely. Field value: This book is devoted to basic results with the generally accepted name implicit function theorem (sometimes inverse function theorem) and which appear everywhere, beginning with elementary courses of calculus and ending up with fundamental monographs on functional analysis, differential and integral equations, calculus of variations, and so on.par the book consists of 6 chapters. chapter 1 ``introduction to the implicit function theorem'' presents an informal version of the implicit function theorem and its paradigm. chapter 2 ``history'' describes the basic steps on the way from heuristic thinking on implicit functions to up-to-date formulations of the implicit function theorem (newton, lagrange, cauchy). chapter 3 ``basic ideas'' deals with the classical implicit function theorem and gives its different proofs: inductive, classical (on the base of construction leading to the theorem about conditions for local homeomorphism), and goursat's (on the base of successive approximations or banach-caccioppoli fixed point principle); in this chapter one can find also the classical rank theorem and decomposition theorem. chapter 4 ``applications'' is devoted to standard applications of the implicit function theorem to ordinary differential equations, the theory of surfaces and others. chapter 5 ``variations and generalizations'' presents the weierstrass preparation theorem, a variant of the implicit function theorem without differentiability, an inverse function theorem for continuous mapping, and some singular cases of the implicit function theorem. the last chapter ``advanced implicit function theorem'' deals with the analytic implicit function theorem, hadamard's global implicit function theorem, the implicit function theorem via the newton-kantorovich method, and the nash-moser implicit function theorem.par it seems that the book is concerned with all problems related to implicit function theorems. however, this book really does not cover all fields with the name ``implicit function theorem''. so, the authors do not recall g. peano, e. goursat, g. a. bliss, young, a. lamson, s. m. lozinskii, and others, who made a significant contribution in this field; the authors do not consider different variants of the implicit function theorem in banach spaces for operators differentiable only in separate points, or variants of the implicit function theorem based on fixed point principles different from banach-caccioppoli; the authors also omitted variants of the implicit function theorem for operators in locally convex spaces or for operators in spaces of formal power series. one can find some information in this direction in [{it J. Appell}, {it A. Vignoli} and {it P. P. Zabreiko
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:167)
	at org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(BibEntryWriter.java:136)
	at org.jabref.logic.bibtex.BibEntryWriter.write(BibEntryWriter.java:65)
	at org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(BibtexDatabaseWriter.java:132)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:190)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:143)
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:75)
	... 26 more
Caused by: org.jabref.logic.bibtex.InvalidFieldValueException: Unescaped '}' character without opening bracket ends string prematurely. Field value: This book is devoted to basic results with the generally accepted name implicit function theorem (sometimes inverse function theorem) and which appear everywhere, beginning with elementary courses of calculus and ending up with fundamental monographs on functional analysis, differential and integral equations, calculus of variations, and so on.par the book consists of 6 chapters. chapter 1 ``introduction to the implicit function theorem'' presents an informal version of the implicit function theorem and its paradigm. chapter 2 ``history'' describes the basic steps on the way from heuristic thinking on implicit functions to up-to-date formulations of the implicit function theorem (newton, lagrange, cauchy). chapter 3 ``basic ideas'' deals with the classical implicit function theorem and gives its different proofs: inductive, classical (on the base of construction leading to the theorem about conditions for local homeomorphism), and goursat's (on the base of successive approximations or banach-caccioppoli fixed point principle); in this chapter one can find also the classical rank theorem and decomposition theorem. chapter 4 ``applications'' is devoted to standard applications of the implicit function theorem to ordinary differential equations, the theory of surfaces and others. chapter 5 ``variations and generalizations'' presents the weierstrass preparation theorem, a variant of the implicit function theorem without differentiability, an inverse function theorem for continuous mapping, and some singular cases of the implicit function theorem. the last chapter ``advanced implicit function theorem'' deals with the analytic implicit function theorem, hadamard's global implicit function theorem, the implicit function theorem via the newton-kantorovich method, and the nash-moser implicit function theorem.par it seems that the book is concerned with all problems related to implicit function theorems. however, this book really does not cover all fields with the name ``implicit function theorem''. so, the authors do not recall g. peano, e. goursat, g. a. bliss, young, a. lamson, s. m. lozinskii, and others, who made a significant contribution in this field; the authors do not consider different variants of the implicit function theorem in banach spaces for operators differentiable only in separate points, or variants of the implicit function theorem based on fixed point principles different from banach-caccioppoli; the authors also omitted variants of the implicit function theorem for operators in locally convex spaces or for operators in spaces of formal power series. one can find some information in this direction in [{it J. Appell}, {it A. Vignoli} and {it P. P. Zabreiko
	at org.jabref.logic.bibtex.LatexFieldFormatter.checkBraces(LatexFieldFormatter.java:66)
	at org.jabref.logic.bibtex.LatexFieldFormatter.formatWithoutResolvingStrings(LatexFieldFormatter.java:195)
	at org.jabref.logic.bibtex.LatexFieldFormatter.format(LatexFieldFormatter.java:102)
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:164)
	... 32 more

Unable to save library
Saving library...
A problem occurred when trying to save the file /home/user/Documents/TeX/Bibliography/library.bib
org.jabref.logic.exporter.SaveException: Problems saving:
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:86)
	at org.jabref.gui.exporter.SaveDatabaseAction.doSave(SaveDatabaseAction.java:123)
	at org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:163)
	at org.jabref.gui.JabRefFrame.confirmClose(JabRefFrame.java:1137)
	at org.jabref.gui.JabRefFrame.quit(JabRefFrame.java:429)
	at org.jabref.JabRefGUI.lambda$openWindow$70(JabRefGUI.java:148)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:88)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:122)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$3(GlassWindowEventHandler.java:151)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1270)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1174)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error in field 'abstract': Unescaped '}' character without opening bracket ends string prematurely. Field value: This book is devoted to basic results with the generally accepted name implicit function theorem (sometimes inverse function theorem) and which appear everywhere, beginning with elementary courses of calculus and ending up with fundamental monographs on functional analysis, differential and integral equations, calculus of variations, and so on.par the book consists of 6 chapters. chapter 1 ``introduction to the implicit function theorem'' presents an informal version of the implicit function theorem and its paradigm. chapter 2 ``history'' describes the basic steps on the way from heuristic thinking on implicit functions to up-to-date formulations of the implicit function theorem (newton, lagrange, cauchy). chapter 3 ``basic ideas'' deals with the classical implicit function theorem and gives its different proofs: inductive, classical (on the base of construction leading to the theorem about conditions for local homeomorphism), and goursat's (on the base of successive approximations or banach-caccioppoli fixed point principle); in this chapter one can find also the classical rank theorem and decomposition theorem. chapter 4 ``applications'' is devoted to standard applications of the implicit function theorem to ordinary differential equations, the theory of surfaces and others. chapter 5 ``variations and generalizations'' presents the weierstrass preparation theorem, a variant of the implicit function theorem without differentiability, an inverse function theorem for continuous mapping, and some singular cases of the implicit function theorem. the last chapter ``advanced implicit function theorem'' deals with the analytic implicit function theorem, hadamard's global implicit function theorem, the implicit function theorem via the newton-kantorovich method, and the nash-moser implicit function theorem.par it seems that the book is concerned with all problems related to implicit function theorems. however, this book really does not cover all fields with the name ``implicit function theorem''. so, the authors do not recall g. peano, e. goursat, g. a. bliss, young, a. lamson, s. m. lozinskii, and others, who made a significant contribution in this field; the authors do not consider different variants of the implicit function theorem in banach spaces for operators differentiable only in separate points, or variants of the implicit function theorem based on fixed point principles different from banach-caccioppoli; the authors also omitted variants of the implicit function theorem for operators in locally convex spaces or for operators in spaces of formal power series. one can find some information in this direction in [{it J. Appell}, {it A. Vignoli} and {it P. P. Zabreiko
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:167)
	at org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(BibEntryWriter.java:136)
	at org.jabref.logic.bibtex.BibEntryWriter.write(BibEntryWriter.java:65)
	at org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(BibtexDatabaseWriter.java:132)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:190)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:143)
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:75)
	... 26 more
Caused by: org.jabref.logic.bibtex.InvalidFieldValueException: Unescaped '}' character without opening bracket ends string prematurely. Field value: This book is devoted to basic results with the generally accepted name implicit function theorem (sometimes inverse function theorem) and which appear everywhere, beginning with elementary courses of calculus and ending up with fundamental monographs on functional analysis, differential and integral equations, calculus of variations, and so on.par the book consists of 6 chapters. chapter 1 ``introduction to the implicit function theorem'' presents an informal version of the implicit function theorem and its paradigm. chapter 2 ``history'' describes the basic steps on the way from heuristic thinking on implicit functions to up-to-date formulations of the implicit function theorem (newton, lagrange, cauchy). chapter 3 ``basic ideas'' deals with the classical implicit function theorem and gives its different proofs: inductive, classical (on the base of construction leading to the theorem about conditions for local homeomorphism), and goursat's (on the base of successive approximations or banach-caccioppoli fixed point principle); in this chapter one can find also the classical rank theorem and decomposition theorem. chapter 4 ``applications'' is devoted to standard applications of the implicit function theorem to ordinary differential equations, the theory of surfaces and others. chapter 5 ``variations and generalizations'' presents the weierstrass preparation theorem, a variant of the implicit function theorem without differentiability, an inverse function theorem for continuous mapping, and some singular cases of the implicit function theorem. the last chapter ``advanced implicit function theorem'' deals with the analytic implicit function theorem, hadamard's global implicit function theorem, the implicit function theorem via the newton-kantorovich method, and the nash-moser implicit function theorem.par it seems that the book is concerned with all problems related to implicit function theorems. however, this book really does not cover all fields with the name ``implicit function theorem''. so, the authors do not recall g. peano, e. goursat, g. a. bliss, young, a. lamson, s. m. lozinskii, and others, who made a significant contribution in this field; the authors do not consider different variants of the implicit function theorem in banach spaces for operators differentiable only in separate points, or variants of the implicit function theorem based on fixed point principles different from banach-caccioppoli; the authors also omitted variants of the implicit function theorem for operators in locally convex spaces or for operators in spaces of formal power series. one can find some information in this direction in [{it J. Appell}, {it A. Vignoli} and {it P. P. Zabreiko
	at org.jabref.logic.bibtex.LatexFieldFormatter.checkBraces(LatexFieldFormatter.java:66)
	at org.jabref.logic.bibtex.LatexFieldFormatter.formatWithoutResolvingStrings(LatexFieldFormatter.java:195)
	at org.jabref.logic.bibtex.LatexFieldFormatter.format(LatexFieldFormatter.java:102)
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:164)
	... 32 more

Unable to save library
```

</details>

**Comment by stefan-kolb** [comment]
Error in field 'abstract': Unescaped '}' character without opening bracket ends string prematurely.

> This book is devoted to basic results with the generally accepted name implicit function theorem (sometimes inverse function theorem) and which appear everywhere, beginning with elementary courses of calculus and ending up with fundamental monographs on functional analysis, differential and integral equations, calculus of variations, and so on.par the book consists of 6 chapters. chapter 1 ``introduction to the implicit function theorem'' presents an informal version of the implicit function theorem and its paradigm. chapter 2 ``history'' describes the basic steps on the way from heuristic thinking on implicit functions to up-to-date formulations of the implicit function theorem (newton, lagrange, cauchy). chapter 3 ``basic ideas'' deals with the classical implicit function theorem and gives its different proofs: inductive, classical (on the base of construction leading to the theorem about conditions for local homeomorphism), and goursat's (on the base of successive approximations or banach-caccioppoli fixed point principle); in this chapter one can find also the classical rank theorem and decomposition theorem. chapter 4 ``applications'' is devoted to standard applications of the implicit function theorem to ordinary differential equations, the theory of surfaces and others. chapter 5 ``variations and generalizations'' presents the weierstrass preparation theorem, a variant of the implicit function theorem without differentiability, an inverse function theorem for continuous mapping, and some singular cases of the implicit function theorem. the last chapter ``advanced implicit function theorem'' deals with the analytic implicit function theorem, hadamard's global implicit function theorem, the implicit function theorem via the newton-kantorovich method, and the nash-moser implicit function theorem.par it seems that the book is concerned with all problems related to implicit function theorems. however, this book really does not cover all fields with the name ``implicit function theorem''. so, the authors do not recall g. peano, e. goursat, g. a. bliss, young, a. lamson, s. m. lozinskii, and others, who made a significant contribution in this field; the authors do not consider different variants of the implicit function theorem in banach spaces for operators differentiable only in separate points, or variants of the implicit function theorem based on fixed point principles different from banach-caccioppoli; the authors also omitted variants of the implicit function theorem for operators in locally convex spaces or for operators in spaces of formal power series. one can find some information in this direction in [{it J. Appell}, {it A. Vignoli} and {it P. P. Zabreiko

**Comment by homocomputeris** [comment]
Yeah, thanks. It might be escaped and saved anyway.
