### ISSUE TITLE
JabRef only appears in taskbar.

### ISSUE THREAD

**Issue by alamzaib-farooq** [JabRef/jabref#5078]
Here is the message when I open jar file.
```
[JabRef - Remote Listener Server on port 6050] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef - Remote Listener Server on port 6050,6,main]
java.lang.IllegalStateException: Could not start JabRef with arguments []
        at org.jabref.gui.remote.JabRefMessageHandler.handleCommandLineArguments(JabRefMessageHandler.java:17) ~[JabRef-4.3.1.jar:?]
        at org.jabref.logic.remote.server.RemoteListenerServer.handleMessage(RemoteListenerServer.java:62) ~[JabRef-4.3.1.jar:?]
        at org.jabref.logic.remote.server.RemoteListenerServer.run(RemoteListenerServer.java:42) ~[JabRef-4.3.1.jar:?]
        at org.jabref.logic.remote.server.RemoteListenerServerThread.run(RemoteListenerServerThread.java:32) ~[JabRef-4.3.1.jar:?]
```

JabRef version  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by tobiasdiez** [comment]
Could you please also report the output of the 5.0 development version (we did some changes to the code responsible for starting JabRef and thus the line numbers are different now). Thanks

**Comment by LinusDietz** [comment]
Closed due to inactivity.
