### ISSUE TITLE
Automatic Bug Report - 20190708155558

### ISSUE THREAD

**Issue by laurabellows** [JabRef/jabref#5106]
JabRef 4.3.1
Mac OS X 10.12.6 x86_64 
Java 1.8.0_191

Steps to reproduce:

I am trying to open my .bib file (created in BibDesk) in JabRef and keep getting these errors. 

Opening: /Users/laurabellows/Box Sync/Home Folder leb58/Sync/Research/Literature/Bibliography.bib
Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.IllegalArgumentException: The field name 'id' is reserved
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:414)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:445)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseField(BibtexParser.java:574)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseEntry(BibtexParser.java:539)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseAndAddEntry(BibtexParser.java:237)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(BibtexParser.java:203)
	at org.jabref.logic.importer.fileformat.BibtexParser.parse(BibtexParser.java:144)
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:72)
	at org.jabref.logic.importer.Importer.importDatabase(Importer.java:88)
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:66)
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:73)
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:52)
	at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:235)
	at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Can only load style files: Preview
Opening: /Users/laurabellows/Box Sync/Home Folder leb58/Sync/Research/Literature/Bibliography.bib
Uncaught exception occurred in Thread[JabRef CachedThreadPool,6,main]
java.lang.IllegalArgumentException: The field name 'id' is reserved
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:414)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:445)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseField(BibtexParser.java:574)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseEntry(BibtexParser.java:539)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseAndAddEntry(BibtexParser.java:237)
	at org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(BibtexParser.java:203)
	at org.jabref.logic.importer.fileformat.BibtexParser.parse(BibtexParser.java:144)
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:72)
	at org.jabref.logic.importer.Importer.importDatabase(Importer.java:88)
	at org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(BibtexImporter.java:66)
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:73)
	at org.jabref.logic.importer.OpenDatabase.loadDatabase(OpenDatabase.java:52)
	at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:235)
	at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
