### ISSUE TITLE
Error dialog is opened behind "New entry" dialog and gets focus after clicking on the application

### ISSUE THREAD

**Issue by dwld** [JabRef/jabref#5119]
JabRef 4.3.1
Mac OS X 10.14.5 x86_64 
Java 1.8.0_172

Steps to reproduce:

1. Open "New entry" dialog
2. Enter, e.g., a DOI in the "ID-based entry generator"
3. Click on "Generate"
4. When the search fails, the "New entry" dialog looses its focus, but the error message is somewhere in the background. The error cannot be directly seen.
5. Another click on the "New entry" dialog or somewhere else on JabRef brings the error dialog in focus.

<details><summary>Log entry for failed search</summary>
<p>
```
Connection error
org.jabref.logic.importer.FetcherException: Connection error
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://data.crossref.org/10.1016%2Fj.chb.2017.06.019
	at sun.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:196)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:210)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://data.crossref.org/10.1016%2Fj.chb.2017.06.019
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:306)
	... 11 more
```
</p>
</details>

**Comment by AEgit** [comment]
Please check whether the current Master branch still contains the issue you report:
https://builds.jabref.org/master/

Before installing the current development snapshot from the Master branch make sure, that you have a separate backup of your database.

**Comment by dwld** [comment]
I just tested it with JabRef 5.0-dev--snapshot--2019-07-11--master--901261ae9. The dialog focus is working correctly there.
