### ISSUE TITLE
Window turns black when fullscreen

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5130]
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Some operations make the whole window turn black.

1. open a library
2. sort by title

This also happened in other context. When trying to reproduce the behaviour to take a screenshot it got even weirder...
![Screenshot_20190714_181725](https://user-images.githubusercontent.com/3944397/61186307-fee67500-a663-11e9-97fa-018b47b02bd4.png)

<details>
  <summary>Exception</summary>
  
  ```
java.lang.ArrayIndexOutOfBoundsException: -27
        at com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:332)
        at com.sun.prism.impl.GlyphCache.render(GlyphCache.java:147)
        at com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2101)
        at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
        at com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
        at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.CacheFilter.impl_renderNodeToCache(CacheFilter.java:671)
        at com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:575)
        at com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2358)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2044)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:323)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:748)

  ```
</details>

**Comment by AEgit** [comment]
Cannot confirm for:

JabRef 5.0-dev--snapshot--2019-07-14--master--7561724b1
Windows 10 10.0 amd64 
Java 1.8.0_211

What operating system are you using?

**Comment by j0hannes** [comment]
It doesn't always happen but sometimes. That's why I attached the screenshot. For the other case, just imagine everything to be black.

I'm using Arch.

**Comment by AEgit** [comment]
Tried to make a screenshot as well. Under Windows 10 no such behaviour is displayed. Might be Linux-specific.

**Comment by Siedlerchr** [comment]
Which Java 8 version are you using?

**Comment by j0hannes** [comment]
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)

**Comment by koppor** [comment]
@j0hannes Could you please try with Java 11 and the latest build from http://builds.jabref.org/master/? Maybe, we have some "healing effects" by switching to Java 11.

**Comment by j0hannes** [comment]
yes, I will have to update the package and try everything again

**Comment by tobiasdiez** [comment]
any updates?

**Comment by j0hannes** [comment]
I haven't seen the issue since switching to the new Java version. However, I have not been using Jabref for a while as I have been occupied with other things. Once I'm back to writing and use it on a daily basis, I will find this thread if I experience it again.
