### ISSUE TITLE
Author search results in Uncaught Exception Occurred in Thread

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#5165]
I encountered the following exception when searching for authors.

JabRef version 
I installed JabRef via Snap on Ubuntu 18.04. This should be the latest development version.
I have refreshed the snap.

JabRef 5.0-dev
Linux 4.15.0-55-generic amd64 
Java 1.8.0_212

1. Open latest JabRef 5.0 dev version with a bibtex file
2. Type author last name into search field
3. Double click on one of the filtered entries so that the article info window appears (with the Required Fields, Optional Fields, etc. tabs)
4. Clear author field and type in new author to search again
5. An exception is now thrown: Uncaught Exception Occurred in Thread[JavaFX Application thread,5,main

<details>
  <summary>Log File</summary>
  
  ```
netscape.javascript.JSException: TypeError: undefined is not a function
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:103)
	at org.jabref.gui.preview.PreviewViewer.lambda$new$527(PreviewViewer.java:94)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$10(WebEngine.java:1201)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:211)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:170)
	at org.jabref.FallbackExceptionHandler.lambda$uncaughtException$372(FallbackExceptionHandler.java:26)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)


  ```
</details>

**Comment by 2ndK16** [comment]
I've encountered a similar issue: as soon as I enter _anything_ into the search/filter field, _any_ interaction with JabRef results in several such exceptions. As soon as I clear the search field, JabRef works just fine again.

Almost the same setting: refreshed snap, JabRef 5.0-dev, Java 1.8.0_212, Linux 4.18.0-25-generic amd64.

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

I can confirm this issue.

**Comment by Siedlerchr** [comment]
This is interesting seems like the JavaScript method for highlighting is somehow not working in the WebView

**Comment by 2ndK16** [comment]
Great! Thank you so much for the quick resolution!

**Comment by juejung** [comment]
That's great, thank you. I just checked it and can also confirm that JabRef via Snap on Ubuntu 18.04 now works which is version:
JabRef 5.0-dev
Linux 4.15.0-55-generic amd64
Java 1.8.0_212
