### ISSUE TITLE
Preferences -> External Programs throws NPE (Icon related)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5245]
latest master version.

1. Go to preferences
2. Open External Programs tab 
3. You will receive an NPE:

```
java.lang.RuntimeException: java.lang.NullPointerException
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.loadFont(GlyphsFactory.java:64)
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.<init>(GlyphsFactory.java:38)
	at de.jensd.fx.fontawesomefx.materialdesignicons/de.jensd.fx.glyphs.materialdesignicons.utils.MaterialDesignIconFactory.<init>(MaterialDesignIconFactory.java:28)
	at de.jensd.fx.fontawesomefx.materialdesignicons/de.jensd.fx.glyphs.materialdesignicons.utils.MaterialDesignIconFactory.get(MaterialDesignIconFactory.java:33)
	at org.jabref/org.jabref.gui.util.ViewModelListCellFactory.lambda$withIcon$0(ViewModelListCellFactory.java:60)
	at org.jabref/org.jabref.gui.util.ViewModelListCellFactory$1.updateItem(ViewModelListCellFactory.java:166)
	at javafx.controls/javafx.scene.control.ListCell.updateItem(ListCell.java:478)
	at javafx.controls/javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayNode(ComboBoxListViewSkin.java:352)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.getDisplayNode(ComboBoxListViewSkin.java:266)
	at javafx.controls/javafx.scene.control.skin.ComboBoxBaseSkin.updateDisplayArea(ComboBoxBaseSkin.java:289)
	at javafx.controls/javafx.scene.control.skin.ComboBoxBaseSkin.computePrefHeight(ComboBoxBaseSkin.java:207)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.computePrefHeight(ComboBoxListViewSkin.java:308)
	at javafx.controls/javafx.scene.control.Control.computePrefHeight(Control.java:570)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.graphics/javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.graphics/javafx.scene.layout.GridPane.computePrefHeights(GridPane.java:1436)
	at javafx.graphics/javafx.scene.layout.GridPane.computePrefHeight(GridPane.java:1265)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.graphics/javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.graphics/javafx.scene.layout.Region.getMaxAreaHeight(Region.java:2197)
	at javafx.graphics/javafx.scene.layout.Region.computeMaxPrefAreaHeight(Region.java:2095)
	at javafx.graphics/javafx.scene.layout.HBox.computePrefHeight(HBox.java:446)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.graphics/javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1980)
	at javafx.graphics/javafx.scene.layout.VBox.getAreaHeights(VBox.java:452)
	at javafx.graphics/javafx.scene.layout.VBox.computeContentHeight(VBox.java:528)
	at javafx.graphics/javafx.scene.layout.VBox.computePrefHeight(VBox.java:427)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1031)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.computeScrollNodeSize(ScrollPaneSkin.java:1046)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.layoutChildren(ScrollPaneSkin.java:504)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.loadFont(GlyphsFactory.java:62)
	... 54 more

```

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`.

**Comment by stefan-kolb** [comment]
I have tested the described behavior, but cannot reproduce it.

**Comment by calixtus** [comment]
I can reproduce it by starting with Gradle. Latest Master from server seems to work.

Some resource files cannot be located.

**Comment by r0light** [comment]
I can reproduce the same issue when running via Gradle. It also happens when trying to access the "General" Tab of an entry with a linked file.

I tried to investigate it and it seems that inside the Class `de.jensd.fx.glyphs.GlyphsFactory` the line `Font.loadFont(GlyphsFactory.class.getResource(pathToIconFont).openStream(), 10.0);` throws the NPE, because it cannot find the resource `/de/jensd/fx/glyphs/materialdesignicons/materialdesignicons-webfont.ttf`. 

Therefore it probably occurs everytime when MaterialDesignIcons are used.
But it only happens for the `gradle run` task and not for the built `jar`, therefore it seems to be an issue with resources being available during the `gradle run`.

**Comment by tobiasdiez** [comment]
I guess the reason is the following change in behavior of `getResource` in Java 9+:
> If this class is in a named Module then this method will attempt to find the resource in the module. This is done by delegating to the module's class loader findResource(String,String) method, invoking it with the module name and the absolute name of the resource. Resources in named modules are subject to the rules for encapsulation specified in the Module getResourceAsStream method and so this method returns null when the resource is a non-".class" resource in a package that is not open to the caller's module. 

>  A resource in a named module may be encapsulated so that it cannot be located by code in other modules. Whether a resource can be located or not is determined as follows:
    If the resource name ends with ".class" then it is not encapsulated.
    A package name is derived from the resource name. If the package name is a package in the module then the resource can only be located by the caller of this method when the package is open to at least the caller's module. If the resource is not in a package in the module then the resource is not encapsulated.

Maybe somebody else finds the time to investigate this further and look for a fix.

**Comment by r0light** [comment]
So the problem here is that `de.jensd.fx.glyphs.GlyphsFactory` is in the module `de.jensd.fx.fontawesomefx.commons`, but wants to access the resource `/de/jensd/fx/glyphs/materialdesignicons/materialdesignicons-webfont.ttf` in the module `de.jensd.fx.fontawesomefx.materialdesignicons`.

I guess the proper way to address this would be to open an issue at [https://bitbucket.org/Jerady/fontawesomefx/issues](https://bitbucket.org/Jerady/fontawesomefx/issues). 

In the meantime, it would be possible to use a workaround and not use the `MaterialDesignIconFactory` (which internally uses `GlyphsFactory`). So for example in `org.jabref.gui.fieldeditors.LinkedFilesEditor` this would be working:

```java
// current code; not working
Button acceptAutoLinkedFile = MaterialDesignIconFactory.get().createIconButton(MaterialDesignIcon.BRIEFCASE_CHECK);

// workaround
Button acceptAutoLinkedFile = new Button();
GlyphIcon<MaterialDesignIcon> linkedFileIcon = new MaterialDesignIconView(MaterialDesignIcon.BRIEFCASE_CHECK);
acceptAutoLinkedFile.setGraphic(linkedFileIcon);
```

Although I'm not sure whether this works at all places where those Icons are used..

What do you think?

I could try to implement the workaround.

**Comment by Siedlerchr** [comment]
@r0light  If this works it would be best to create  a "wrapper" in JabRef, maybe a "JabRefMaterialDesignFactory" which has the same methods as the original but withouth the glyph factory so we could later easily replace it again when it's fixed.

**Comment by r0light** [comment]
Ok and what would be a good place for this wrapper?
Maybe `org.jabref.gui.icon`?

**Comment by Siedlerchr** [comment]
Yes, gui.icon is good, there are also these other icon-related classes

**Comment by tobiasdiez** [comment]
Thanks for investigating this. The wrapper sounds like a good idea indeed. Moreover, every used icon should be put in this list https://github.com/JabRef/jabref/blob/854cd51e39b000deb55a368eb038316747904ba2/src/main/java/org/jabref/gui/icon/IconTheme.java#L149. Would be nice if you could fix this along the way (and maybe even add an architectur test for it).

**Comment by r0light** [comment]
Ok, so i opened an issue here: [https://bitbucket.org/Jerady/fontawesomefx/issues/70/nullpointerexception-in](https://bitbucket.org/Jerady/fontawesomefx/issues/70/nullpointerexception-in) 
And i opened a pull request which should solve the problem: It covers all places where `MaterialDesignIconFactory` was used and simply replaced it with `JabRefMaterialDesignIconFactory` as a temporary workaround.
I also added all icons used that i found to the list in IconTheme
@tobiasdiez Considering the architecture test: What exactly do you have in mind there, what should be tested?

**Comment by Siedlerchr** [comment]
Thanks to @r0light  this should be fixed now.
