### ISSUE TITLE
Jabref 5: today's development version won't start

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5248]
1. $java -jar ./JabRef--master--latest.jar  [today's version, 2019-08-27]

output:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jabref/JabRefLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by Siedlerchr** [comment]
JabRef now requires java 11 as minimum version. So you can now finally upgrade to openjdk11

**Comment by AEgit** [comment]
JabRef 5.0-dev--snapshot--2019-08-27--master--84436d795
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

I can confirm this issue when JabRef is started from the command line as invoked above (under Windows).

If JabRef is started like a normal GUI application using a shortcut, there appear to be no issues.

**Comment by tobiasdiez** [comment]
You need to modify the JAVA_HOME environment variable to point to your java 11 installation (or specify the complete path for the java executable).

**Comment by Siedlerchr** [comment]
@AEgit  That's probably because you have an old java version still in your environment path variables.
Check the system and user environment variables. Simply remove the java 8 entries or move the java 11 path to the top.

**Comment by AEgit** [comment]
@tobiasdiez and @Siedlerchr : Cheers, thanks for the advice! I personally will not change anything at the moment, since I generally don't start JabRef from the command line anyway (at least under Windows - it is different for Linux). But your comments should help @wujastyk to overcome the problem.

**Comment by AEgit** [comment]
Have you tried running the Snap package for JR5? I haven't tried it myself, but as far as I understand the Snap architecture, exactly this use case should be covered, i. e. you shouldn't need to switch manually between the versions.

**Comment by wujastyk** [comment]
That's a really good idea.  I've installed it (--edge), and it works fine.
Thanks!  I am uncertain how often the --edge snap is updated, but we'll see.

Best,
Dominik
