### ISSUE TITLE
Installation issues for version 4.3.1

### ISSUE THREAD

**Issue by sebastian-brunner** [JabRef/jabref#5258]
I try to use the newest Jabref version, as I get these freezes you reported at (http://help.jabref.org/en/Installation#freezes-when-running-jabref). However, I am continuously getting the following error:

```
Error: Could not find or load main class org.jabref.JabRefMain
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

I use Ubuntu 18.04 and try with Jabref version 4.3.1 from https://www.fosshub.com/JabRef.html

So far I tried:

Your install instructions: http://help.jabref.org/en/Installation#jabref-4x-1
They fail at line: `Install: sudo apt-get install oracle-java8-installer`

You claim at https://github.com/JabRef/jabref#installation that jabref is supporting Java 11 or higher, however in your installation instructions (http://help.jabref.org/en/Installation#jabref-4x-1) you say it does not support java 11.

Nevertheless, I tried java 11 using the `default-jdk` package including `openjfx` which was reported to work:  http://discourse.jabref.org/t/jabref-4-3-1-with-debian-stable/1197 => no luck, see error above

As you claim supporting 11 or higher I installed oracle java 12 as well (similar to https://tecadmin.net/install-oracle-java-11-ubuntu-18-04-bionic/) => see error above

Then I went back to good old java 8 (openjdk) using your install instructions for openjfx from http://help.jabref.org/en/Installation#jabref-4x-1 

The version launches, however I get weird behavior using the search field in the top bar (the cursor does not move, when using the arrow keys) and I get the stacktrace appended at the end of the issue.

For now I switch back to the Jabref version from the Ubuntu packages by using `sudo apt-get install jabref`

Stacktrace:

```
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
java.lang.NullPointerException
	at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:297)
	at com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
	at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2047)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:323)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:134)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
10:21:32.777 [AWT-EventQueue-1] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-1,6,main]
java.lang.NullPointerException: null
	at com.sun.javafx.text.PrismTextLayout.getCaretShape(PrismTextLayout.java:317) ~[jfxrt.jar:?]
	at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1787) ~[jfxrt.jar:?]
	at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1777) ~[jfxrt.jar:?]
	at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:153) ~[jfxrt.jar:?]
	at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:50) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.get(ObjectPropertyBase.java:132) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.TextFieldSkin.lambda$new$4(TextFieldSkin.java:233) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.access$000(ObjectPropertyBase.java:51) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:233) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.impl_geomChanged(Text.java:769) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.needsTextLayout(Text.java:194) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:189) ~[jfxrt.jar:?]
	at javafx.scene.text.Text.access$200(Text.java:95) ~[jfxrt.jar:?]
	at javafx.scene.text.Text$2.invalidated(Text.java:389) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase.access$000(StringPropertyBase.java:49) ~[jfxrt.jar:?]
	at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:230) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:171) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389) ~[jfxrt.jar:?]
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393) ~[jfxrt.jar:?]
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1324) ~[jfxrt.jar:?]
	at javafx.scene.control.TextInputControl.setText(TextInputControl.java:349) ~[jfxrt.jar:?]
	at org.jabref.gui.search.GlobalSearchBar.clearSearch(GlobalSearchBar.java:328) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.search.GlobalSearchBar.performSearch(GlobalSearchBar.java:356) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.BasePanel$SearchListener.listen(BasePanel.java:2095) ~[JabRef-4.3.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) ~[JabRef-4.3.1.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:212) ~[JabRef-4.3.1.jar:?]
	at org.jabref.model.database.BibDatabase.relayEntryChangeEvent(BibDatabase.java:582) ~[JabRef-4.3.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) ~[JabRef-4.3.1.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108) ~[JabRef-4.3.1.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:212) ~[JabRef-4.3.1.jar:?]
	at org.jabref.model.entry.BibEntry.clearField(BibEntry.java:483) ~[JabRef-4.3.1.jar:?]
	at org.jabref.model.entry.BibEntry.clearField(BibEntry.java:455) ~[JabRef-4.3.1.jar:?]
	at org.jabref.migrations.MergeReviewIntoCommentMigration.updateFields(MergeReviewIntoCommentMigration.java:73) ~[JabRef-4.3.1.jar:?]
	at org.jabref.migrations.MergeReviewIntoCommentMigration.migrate(MergeReviewIntoCommentMigration.java:66) ~[JabRef-4.3.1.jar:?]
	at org.jabref.migrations.MergeReviewIntoCommentMigration.lambda$performMigration$2(MergeReviewIntoCommentMigration.java:32) ~[JabRef-4.3.1.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_222]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_222]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_222]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_222]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_222]
	at org.jabref.migrations.MergeReviewIntoCommentMigration.performMigration(MergeReviewIntoCommentMigration.java:32) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.importer.actions.MergeReviewIntoCommentAction.performAction(MergeReviewIntoCommentAction.java:21) ~[JabRef-4.3.1.jar:?]
	at org.jabref.gui.importer.actions.OpenDatabaseAction.performPostOpenActions(OpenDatabaseAction.java:93) ~[JabRef-4.3.1.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:186) ~[JabRef-4.3.1.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67) ~[JabRef-4.3.1.jar:?]
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128) ~[JabRef-4.3.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_222]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_222]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_222]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_222]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_222]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_222]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_222]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_222]
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715) [java-atk-wrapper.jar:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_222]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_222]




```

**Comment by Siedlerchr** [comment]
4.3.1 still requires java 8 and openjfx 8.
5.0 alpha and all newer releases require java 11.

Please not that we lack resources to support more than the most current master version. 
Ubuntu apt package has the very old 3.8 version I think.

Alternatively you can also install the snap version  of JabRef: 
https://snapcraft.io/jabref (edge for the latest master release)
