### ISSUE TITLE
Bug when clicking on a reference with dev version

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#5285]
JabRef version last dev version on Mac OS X 10.14.6

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Click on a reference and I get
<img width="727" alt="image" src="https://user-images.githubusercontent.com/15056323/64382142-2ab72300-d035-11e9-85fe-dada9985226e.png">

<details>
  <summary>Log File</summary>
  
  ```
java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: [/Users/pierremarchand/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
	at java.base/java.lang.System.loadLibrary(System.java:1902)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
	at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
	at javafx.scene.web.WebView.<init>(WebView.java:260)
	at org.jabref.gui.preview.PreviewViewer.<init>(PreviewViewer.java:81)
	at org.jabref.gui.preview.PreviewPanel.<init>(PreviewPanel.java:53)
	at org.jabref.gui.entryeditor.FieldsEditorTab.initPanel(FieldsEditorTab.java:211)
	at org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(FieldsEditorTab.java:189)
	at org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(EntryEditorTab.java:42)
	at org.jabref.gui.entryeditor.EntryEditor.lambda$new$0(EntryEditor.java:116)
	at org.fxmisc.easybind.EasyBind.lambda$subscribe$12(EasyBind.java:263)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:733)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:751)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.findNearestAvailableTab(TabPane.java:807)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$0(TabPane.java:707)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at org.jabref.gui.entryeditor.EntryEditor.recalculateVisibleTabs(EntryEditor.java:324)
	at org.jabref.gui.entryeditor.EntryEditor.setEntry(EntryEditor.java:349)
	at org.jabref.gui.BasePanel.lambda$createMainTable$19(BasePanel.java:663)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.jabref.gui.BasePanel.lambda$createMainTable$20(BasePanel.java:662)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$1(SelectedItemsReadOnlyObservableList.java:103)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(ReadOnlyUnbackedObservableList.java:64)
	at javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(MultipleSelectionModelBase.java:896)
	at javafx.scene.control.ControlUtils.updateSelectedIndices(ControlUtils.java:202)
	at javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(TableView.java:3031)
	at javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(TableView.java:2485)
	at javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(TableView.java:1969)
	at com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(TableCellBehaviorBase.java:213)
	at com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(TableCellBehaviorBase.java:195)
	at com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(CellBehaviorBase.java:176)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
  ```
</details>

**Comment by Siedlerchr** [comment]
Hi, seems like your Java version does not include all javafx libraries.Please try this version
https://bell-sw.com/pages/java-11.0.4/

**Comment by PierreMarchand20** [comment]
Ok, but I thought that I had the last versions of java from oracle:
```
❯ java -version
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
```
and 
```
❯ javac -version
javac 12
```
It is not enough ?

**Comment by Siedlerchr** [comment]
Currently JabRef requires Java 11 (it's an LTS version) and does not run yet with Java 12.

**Comment by PierreMarchand20** [comment]
Ok, and will it support Java 12 in its release version ?

**Comment by Siedlerchr** [comment]
No. This is very unlikely. JabRef depends on external libraries which also need to be compatible then.
You can just downgrade to java 11. It's supported until at least 2022.

**Comment by PierreMarchand20** [comment]
I installed java 11:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/15056323/65395043-d5e60d00-dd95-11e9-94cb-c65d81051c5f.png">
and I get the following error 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/15056323/65395047-e1393880-dd95-11e9-9477-639ec2acc1b5.png">

**Comment by Siedlerchr** [comment]
The new version is no longer startable as jar. Please use the installer in the meantime or for Linux the tar.gz archive

**Comment by PierreMarchand20** [comment]
Ok, I tried on macOS. It worked at first but after restarting my computer, when I call jabref it is the old version that is used.
