### ISSUE TITLE
Exception error for any keystroke & "library has been modified"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5296]
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

This is the snap beta channel

name:      jabref
summary:   Bibliography manager
publisher: Oliver Kopp (koppor)
contact:   https://github.com/koppor
license:   unset
description: |
  JabRef is an open source bibliography reference manager. The native file
  format used by JabRef is BibTeX, the standard LaTeX bibliography format.
commands:
  - jabref
snap-id:      T5x6neyM0Uc9OWDHGorm61NKxh3Bd47k
tracking:     beta
refresh-date: 10 days ago, at 11:10 MDT
channels:
  stable:    –                              
  candidate: –                              
  beta:      5.0-dev 2019-08-26 (530) 212MB -
  edge:      5.0-dev 2019-08-24 (530) 212MB -
installed:   5.0-dev            (530) 212MB -

1. type a character into the entry editor
2. an error window pops up.  Actually  two, I believe.

Coincidentally, the screenshot below also shows the "the library hs been modified by another program" error message.

![Screenshot from 2019-09-09 13-37-10](https://user-images.githubusercontent.com/762246/64561348-c384c180-d307-11e9-9bc1-22c3854ce422.png)

<details>
  <summary>Log File</summary>
  
  ```
  netscape.javascript.JSException: TypeError: undefined is not a function
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:103)
	at org.jabref.gui.preview.PreviewViewer.lambda$new$260(PreviewViewer.java:94)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$10(WebEngine.java:1201)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:211)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:170)
	at org.jabref.FallbackExceptionHandler.lambda$uncaughtException$1342(FallbackExceptionHandler.java:26)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

  ```

**Comment by Siedlerchr** [comment]
This is a duplicate of the search error issue with the highlight function

**Comment by Siedlerchr** [comment]
I see that the snap no longer builds, Will try to configure the snap for java 11

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-29-generic amd64 
Java 11.0.4

Cannot confirm the popup error message.

**Comment by wujastyk** [comment]
Yes, I got the error today,

JabRef 5.0-dev
Linux 5.0.0-29-generic amd64
Java 11.0.4


[image: Screenshot from 2019-09-21 11-28-43.png]

**Comment by AEgit** [comment]
@wujastyk 
Are you talking about the "Uncaught exception error" reported in the original post (https://github.com/JabRef/jabref/issues/5296#issue-491290093) or just the "The library has been modified by another program" message (I only see the latter in the screenshot you posted)?

**Comment by wujastyk** [comment]
"library has been modified"

**Comment by AEgit** [comment]
Ok, in that case I would probably suggest to close this issue, because the main problem appears to be fixed. The "library has been modified" message, on the other hand, has already been reported in various other bug tickets, e.g.:

https://github.com/JabRef/jabref/issues/5257
https://github.com/JabRef/jabref/issues/5085
https://github.com/JabRef/jabref/issues/4877
https://github.com/JabRef/jabref/issues/4810
(also present in older versions: https://github.com/JabRef/jabref/issues/4143)

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by wujastyk** [comment]
JabRef 5.0-beta.352--2020-01-18--49e8ee2
Linux 5.3.0-26-generic amd64
Java 13.0.2

So far so good!  Thank you!

**Comment by wujastyk** [comment]
JabRef 5.16--2024-08-04--db9f83c
Linux 6.8.0-39-generic amd64 
Java 21.0.2 
JavaFX 22.0.2+4

I would like to return to this issue.  With every single edit that I make to an entry, I get this popup screen multiple times.  I've kind of learned to live with it, hitting "dismiss" all the time, but it needs to be sorted out definitively.

![image](https://github.com/user-attachments/assets/90522db5-e94c-4911-9283-e6b44dac026e)

**Comment by Siedlerchr** [comment]
pIng @koppor

**Comment by koppor** [comment]
@wujastyk do we have a copy of the library? It has surely something to do with library properties such as save actions.

**Comment by koppor** [comment]
I also would like to see what differences are shown.

**Comment by wujastyk** [comment]
The library is rather big, 4.3 MB.  Here's a [link](https://www.dropbox.com/scl/fi/j1b056gg45mbc3ny5odin/biblio4-utf8.bib?rlkey=ojwrm5u2ynyey6pukdbfrwvqm&dl=0).

The differences are often nothing at all.  But I'll start collecting.

**Comment by wujastyk** [comment]
I turned off "autosave local libraries" and I haven't seen the problem since.  Still watching.

**Comment by wujastyk** [comment]
JabRef 5.16--2024-08-04--db9f83c
Linux 6.8.0-39-generic amd64 
Java 21.0.2 
JavaFX 22.0.2+4

1. I constructed a library using tools/new sub based on latex aux.  It was called "untitled".
2. I saved it and named it.
3. Got the screen below.

![image](https://github.com/user-attachments/assets/d528b94c-ecfd-4be3-962c-0d8882e7cbcb)
