### ISSUE TITLE
JabRef not working on Arch Linux

### ISSUE THREAD

**Issue by aytekinar** [JabRef/jabref#5299]
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I am on an Arch Linux machine with the following:
```
~/JabRef> git branch -vv
* master 4add3167c [origin/master] Bump jaxb-xjc from 2.2.4-1 to 2.3.2 (#4956)
~/JabRef> pacman -Q | grep -i java
java-environment-common 3-1
java-runtime-common 3-1
~/JabRef> archlinux-java status
Available Java environments:
  java-11-openjdk (default)
~/JabRef> java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11)
OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)
~/JabRef> git submodule status 
 e89e6b08b5c621a414fc7114f2129efac5f8c7d5 src/main/resources/csl-locales (heads/master)
 83603de7a7f4652f8d1733f18f0c00be8974948e src/main/resources/csl-styles (heads/master)
```

1. `gradle releaseJar` or `gradle shadowJar` (see log)
2. `java -jar build/releases/JabRef-5.0-dev.jar`

I have a failure with the following error:
```
Error: Could not find or load main class org.jabref.org.jabref.JabRefLauncher
Caused by: java.lang.ClassNotFoundException: org.jabref.org.jabref.JabRefLauncher
```

<details>
  <summary>Log File</summary>
  
  ```
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes
> Task :buildSrc:jar
> Task :buildSrc:assemble
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build

> Configure project :
Found module name 'org.jabref'

> Task :generateBibtexmlSource
> Task :generateBstGrammarSource
> Task :generateEndnoteSource
> Task :generateMedlineSource
> Task :generateModsSource
> Task :generateSearchGrammarSource
> Task :generateSource

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :processResources
> Task :classes
> Task :shadowJar
> Task :releaseJar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 37s
10 actionable tasks: 10 executed
  ```
</details>

**Comment by Siedlerchr** [comment]
I also experience this under windows when I use the jar. @tobiasdiez  any idea?

**Comment by tobiasdiez** [comment]
With modularized Java 11 applications, the `jar` file does no longer work / is no longer the supported distribution mechanism. Instead, you should create a runtime image using `gradle jlink` and then run it via `java -m org.jabref/org.jabref.JabRefLauncher`.

**Comment by aytekinar** [comment]
Thanks to both of you for your fast responses.

@tobiasdiez, I can confirm that running
```
gradle jlink
gradle run
```
compiles and runs JabRef without any problems. However, I cannot make it work with
```
gradle jlink
java -m org.jabref/org.jabref.JabRefLauncher
```
when working under the source tree. `tree -L 2 build` gives the following:
```
build
├── classes
│   └── java
├── generated
│   └── sources
├── image
│   ├── bin
│   ├── conf
│   ├── legal
│   ├── lib
│   └── release
├── jlinkbase
│   ├── delegating
│   ├── jlinkjars
│   ├── mergedjars
│   ├── nonmodjars
│   ├── tmpjars
│   ├── tmpmerged
│   └── tmpmodinfo
├── libs
│   └── JabRef-5.0-dev.jar
├── resources
│   └── main
└── tmp
    ├── compileJava
    └── jar
```
I am assuming that
  - either I need to move some parts of `build` to a specific path under my user space, or
  - I need to use the `--module-path` switch to `java` when running the module.

I would appreciate if you provided a minimal working example. Then, I can write a `PKGBUILD` file for my system or update the paths under my user space accordingly.

**Comment by aytekinar** [comment]
Final comment...

As of 18cf80f95d, the following `PKGBUILD` file works for Arch Linux:
```
pkgname=jabref
pkgver=r13251.18cf80f95d
pkgrel=1
pkgdesc='Graphical Java application for managing BibTeX and biblatex (.bib) databases.'
arch=('x86_64')
url='https://www.jabref.org'
license=('MIT')

source=("git+https://github.com/JabRef/jabref")
sha256sums=('SKIP')

makedepends=('gendesk' 'gradle' 'jdk-openjdk')

provides=('jabref')
conflicts=('jabref')

prepare() {
  gendesk ../PKGBUILD
  sed 's|Exec=jabref|Exec=/opt/jabref/image/bin/JabRefMain|g' --in-place jabref.desktop
}

pkgver() {
  cd "${pkgname}"
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
  cd "${srcdir}/${pkgname}"
  git submodule update --init
  gradle jlink
}

package() {
  cd "${srcdir}"
  install -d "${pkgdir}/opt"
  cp -R "${pkgname}/build" "${pkgdir}/opt/jabref"
  install -D jabref.desktop "${pkgdir}/usr/share/applications/jabref.desktop"
  install -D jabref.png "${pkgdir}/usr/share/pixmaps/jabref.desktop"
}
```
Basically, after `gradle jlink`ing, moving everything under `build` to `/opt/jabref` and running `/opt/jabref/image/bin/JabRefMain` from a desktop file works. The only problem, though, is the installed package size: 705.38 MiB. I would appreciate if there were a way to make the package smaller (i.e., perhaps installing things the "jar" way).

**Comment by Siedlerchr** [comment]
Thanks for the update. That size is indeed huge, I found out that this is somehow a linux issue with jlink and that there is a workaround for reducing the size:
`$ strip -p --strip-unneeded lib/server/libjvm.so`
https://github.com/docker-library/openjdk/issues/217#issuecomment-436275472

**Comment by tobiasdiez** [comment]
@aytekinar It should suffice to use what is inside of `build/image` after `gradle jlink`. The `bin` folder should contain a luncher script (`JabRefMain.bat` on Windows).

**Comment by tobiasdiez** [comment]
So I've managed to make jpackage work on all platforms. @j0hannes @aytekinar what would be the most convenient distribution format for package maintainers and users on linux:
- deb package
- rpm package
- a folder (or tar archive) with everything that is needed to run JabRef including luncher scripts

(one of the questions is if the last one is necessary or if the first two are actually sufficient).

Refs: https://github.com/JabRef/jabref/pull/5312#issuecomment-531394599  (you are invited to try out the builds referenced there)

**Comment by aytekinar** [comment]
@tobiasdiez IMHO, the last one is necessary and sufficient. Of course, Arch's packaging system knows how to interpret/unpack `deb` and `rpm` packages/archives so that we can just point to those files in `PKGBUILD` and do necessary directory changes (move parts to places which Arch suggests). However, a `tar` or `tar.gz` archive is more generic and already enough. In a sense, you decide (as the developers) what files are needed for the application to run, pack them properly, and let the package maintainers do their work. `deb` is good for your Debian-based users (Debian and *buntu distros) while `rpm` will cover RedHat-based users (RedHat, Fedora, etc.). In any case, if you want to let other distros use JabRef easily, you

  - either provide directions to how to build it from source (we already have some text in docs now),
  - or provide an archive (`tar.gz` in this case) that contains the self-contained cross-platform compatible binaries.

For this reason, I think that `tar.gz` is necessary and sufficient. A nice talk on this is [here](https://youtu.be/NSemlYagjIU) if you have some time to spend and smile :smile:

**Comment by stefanhusmann** [comment]
I tried to provide a working jabref-git PKGBUILD for Arch Linux, but it fails atte gradle jlink step. 
This is what I have:
```

**Comment by aytekinar** [comment]
@stefanhusmann, please check my [PKGBUILD](https://github.com/aytekinar/PKGBUILDs/blob/master/JabRef/PKGBUILD). It is building on my machine with `i3-wm` as the window manager. Note that JabRef is using submodules now, and hence, `git submodule update --init` on [this line](https://github.com/aytekinar/PKGBUILDs/blob/bca67fd927d0c116dcf5c7f1b2584fba83f7898f/JabRef/PKGBUILD#L29) should be enough (i.e., you should not track submodules separately). Moreover, you do not need to depend on `java11-openjfx` or similar anymore --- making them [make dependencies](https://github.com/aytekinar/PKGBUILDs/blob/bca67fd927d0c116dcf5c7f1b2584fba83f7898f/JabRef/PKGBUILD#L12) should be enough.

**Comment by stefanhusmann** [comment]
I checked it, an I get the same error message as with my PKGBUILD.

**Comment by Siedlerchr** [comment]
Please check if gradle is running under the correct java version: ` gradle -v:`

**Comment by stefanhusmann** [comment]
gradlew picks the Gradle 5.6, which is coming with the jabref sources, but I also tried with gradle 5.6.2 which is coming with the official Arch Linux package.

**Comment by stefanhusmann** [comment]
Hello, I now was able to build jabref. It seems that sowehow the java11-openjfx (the system package delivered by Arch Linux) interferes with the build process. It needs to be uninstalled.

JabRef is also launchable with /opt/jabref/bin/JabRefMain, but something still seems wrong:

```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using Simple
Logger to log to the console...
ERROR ThemeLoader Could not watch css file for changes jrt:/org.jabref/org/jabref/gui/Base.css
 java.lang.UnsupportedOperationException
        at java.base/jdk.internal.jrtfs.JrtPath.register(Unknown Source)
        at java.base/jdk.internal.jrtfs.JrtPath.register(Unknown Source)
        at org.jabref/org.jabref.gui.util.DefaultFileUpdateMonitor.addListenerForFile(Unknown Source)
        at org.jabref/org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(Unknown Source)
        at org.jabref/org.jabref.gui.util.ThemeLoader.installCss(Unknown Source)
        at org.jabref/org.jabref.JabRefGUI.openWindow(Unknown Source)
        at org.jabref/org.jabref.JabRefGUI.<init>(Unknown Source)
        at org.jabref/org.jabref.JabRefMain.start(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Siedlerchr** [comment]
The log4j error should be fixed in the latest master version. 
Generally you should only need to run `./gradlew assemble` and  `gradlew jlink` to build jabref. The latter one creates the necessary dependencies and launch configuration.

**Comment by homocomputeris** [comment]
@j0hannes Could you update the package?

**Comment by j0hannes** [comment]
@homocomputeris, I will, I have just been travelling for two weeks now.

**Comment by homocomputeris** [comment]
@j0hannes Thanks a lot!

**Comment by j0hannes** [comment]
@homocomputeris, I have adapted the package, could you try?

**Comment by homocomputeris** [comment]
@j0hannes Great, it works, thanks a lot!.
Two small issues: there is no `.desktop` file in Gnome 3 anymore, and
```
ERROR StatusLogger Log4j2 could not find a logging implementation. 
Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```
which is a dependency, probably?

**Comment by Siedlerchr** [comment]
@homocomputeris  The logger issue is a known problem. We are working on it.
Regarding the desktop file see #5444

**Comment by j0hannes** [comment]
@homocomputeris, there should be a .desktop file: /usr/share/applications/JabRef.desktop

**Comment by homocomputeris** [comment]
@j0hannes I have found it (see above) but it has old paths:
```
Icon=JabRef
Exec=JabRef %U
Path=/opt/JabRef/bin
```

**Comment by j0hannes** [comment]
@homocomputeris, what do you mean by "old paths"?

The icon is stored in /usr/share/pixmaps/ and doesn't need a full path here. On my machines, the icon is shown in the launcher, and clicking on it starts the application.

![Screenshot_20191015_134248](https://user-images.githubusercontent.com/3944397/66828580-b33cb380-ef51-11e9-9e74-511bcebd88f8.png)

**Comment by homocomputeris** [comment]
@j0hannes Well, I don't know why it doesn't appear in my system's Gnome menu.

I've reinstalled the package, and I have
```console
$ lsa /usr/share/applications/JabRef.desktop 
-rw-r--r-- 1 root root 412 oct 15 12:46 /usr/share/applications/JabRef.desktop
```
```console
$ cat lsa /usr/share/applications/JabRef.desktop
[Desktop Entry]
Name=JabRef
GenericName=BibTeX Editor
Comment=JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.
Type=Application
Terminal=false
Icon=JabRef
Exec=JabRef %U
Path=/opt/JabRef/bin
Keywords=bibtex;biblatex;latex;bibliography
Categories=Office;
StartupWMClass=org-jabref-JabRefMain
MimeType=text/x-bibtex;
```

**Comment by j0hannes** [comment]
@homocomputeris, according to [this page](https://developer.gnome.org/integration-guide/stable/desktop-files.html.en) it should work like that.

**Comment by LyzardKing** [comment]
Does `desktop-file-validate /usr/share/applications/JabRef.desktop` return anything?

**Comment by j0hannes** [comment]
In my case it doesn't; I did that check before pushing the new version.

**Comment by LyzardKing** [comment]
> In my case it doesn't; I did that check before pushing the new version.

Your launcher is shown in the menu, so it's correct.
The command only shows errors.
