### ISSUE TITLE
uncaught exception occurred in Thread[JavaFX Application Thread,5,main]

### ISSUE THREAD

**Issue by aothmane-control** [JabRef/jabref#5412]
JabRef 5.0-dev
Linux 4.15.0-65-generic amd64 
Java 1.8.0_222

Steps to reproduce:

1. search for an entry or write something in the bibtex source

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
netscape.javascript.JSException: TypeError: undefined is not a function
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:103)
	at org.jabref.gui.preview.PreviewViewer.lambda$new$260(PreviewViewer.java:94)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$10(WebEngine.java:1201)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:211)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:170)
	at org.jabref.FallbackExceptionHandler.lambda$uncaughtException$1342(FallbackExceptionHandler.java:26)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

</details>

**Comment by Siedlerchr** [comment]
This should normally be fixed in the latest master version. @davidemdot  can you check this please on linux?

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

Might be a duplicate of https://github.com/JabRef/jabref/issues/5446#issuecomment-542845715 which is fixed in the most recent version.

**Comment by petersaly** [comment]
Hi All,

Unfortunately I have the same issue.

I use

Ubuntu 2204
JabRef 5.9.

How to reproduce:
1. Open .odt document.
2. Connect JabRef to the open document.
3. Select an entry in the library.
4. Click 'Cite'.

Formerly, the version JabRef 5.3 worked perfectly on the same computer with the same configuration.

Could anyone suggest a solution?

Thank you.

**Comment by ThiloteE** [comment]
I think if it wasn't already fixed, it will be fixed with the release of JabRef 6.0 (as I cannot reproduce this). Please head to https://builds.jabref.org/main to download a development build and try out the latest alpha version.

Closing for now. If you still can reproduce, you can reopen.

**Comment by koppor** [comment]
Somehow refs https://github.com/JabRef/jabref-koppor/issues/135

**Comment by ThiloteE** [comment]
Could also refer to
- https://stackoverflow.com/questions/33612267/error-calling-javascript-from-java
- https://kasata.medium.com/how-to-fix-the-undefined-is-not-a-function-error-in-javascript-9d5fa35d809a
