### ISSUE TITLE
Uncaught Exception occurred in Thread[JavaFX Application Thread,5,main]

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#5446]
JabRef version 
JabRef 5.0.0-dev--2019-10-14----824b10363
Linux 5.0.0-31-generic amd64 
Java 12.0.2
on Linux 18.04 installed from .deb file downloaded from  https://builds.jabref.org/master/jabref_5.0.0-1_amd64.deb

1. Open JabRef with .bib file
2. Double click on entry to open entry editor
3. Exception is thrown

<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException
	at org.jabref/org.jabref.gui.fieldeditors.FieldEditors.getSuggestionProvider(Unknown Source)
	at org.jabref/org.jabref.gui.fieldeditors.FieldEditors.getForField(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.EntryEditor.lambda$new$0(Unknown Source)
	at org.jabref.merged.module/org.fxmisc.easybind.EasyBind.lambda$subscribe$12(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TabPane$TabPaneSelectionModel.findNearestAvailableTab(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$0(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.EntryEditor.recalculateVisibleTabs(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.EntryEditor.setEntry(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.lambda$createMainTable$21(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.lambda$createMainTable$22(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
Could confirm this under windows, too:
1. Create a new biblatex library
2. Paste a doi 
3. Double click to open the entry editor

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-14----d2ddff574
Windows 10 10.0 amd64 
Java 12.0.2

I can confirm this issue as well.

**Comment by j0hannes** [comment]
JabRef 5.0.0-dev--2019-10-14----d2ddff574
Linux 5.3.6-arch1-1-arch amd64 
Java 12.0.2

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by j0hannes** [comment]
Now Java just crashed when starting Jabref, core dump attached.

[hs_err_pid78360.log](https://github.com/JabRef/jabref/files/3735996/hs_err_pid78360.log)

Note that "The crash happened outside the Java Virtual Machine in native code."

**Comment by Siedlerchr** [comment]
The exception is thrown from some network/proxy detection class in the VM. Do you maybe have an old instance of java or jabref lurking around?

**Comment by j0hannes** [comment]
I have Java 12.0.2 and the JabRef version from today.

**Comment by juejung** [comment]
@tobiasdiez Thanks, it works again under:
Ubuntu 18.04 with Gnome desktop with the latest .deb build.

JabRef 5.0.0-dev--2019-10-16----e36daae20
Linux 5.0.0-31-generic amd64 
Java 12.0.2

**Comment by j0hannes** [comment]
@Siedlerchr, you were right, the problem's gone now.

**Comment by YetiXie1994** [comment]
how to fix it?

**Comment by antonallote** [comment]
I am getting this exception still in 2021..

**Comment by AEgit** [comment]
You need to report which JabRef version you are using.

**Comment by quade-butler** [comment]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

I am also running into this issue. It is only occurring with one of my libraries and not any others.

**Comment by AEgit** [comment]
Cheers!

**Comment by phyzhenli** [comment]
> This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

This version is OK.

**Comment by petersaly** [comment]
Hi All,

I have just installed version JabRef 5.10 as 'phyzhenli' suggested that works. Unfortunately it does not work. The error message sent is:

"Uncaught Exception occurred in Thread[#31,JavaFX Application Thread,5,main]
class java.lang.String cannot be cast to class java.lang.Boolen (java.lang.String and java.lang.Boolen are in module java.base of loader 'bootstrap')"

I use

Ubuntu 2204
JabRef 5.10
openjdk version "11.0.17" 2022-10-18.

JabRef version 5.3 worked fine.


Could anyone suggest a solution?

Thanks.

**Comment by ThiloteE** [comment]
> Ubuntu 2204
> JabRef 5.10
> openjdk version "11.0.17" 2022-10-18.

@petersaly
JabRef comes with its own bundled version of JDK (if I remember correctly, version 19.xx right now). Which method did you use to install JabRef? Is this a snap/flatpak/deb or portable version? - See here: https://docs.jabref.org/installation

**Comment by Siedlerchr** [comment]
Can you past the whole stack trace/the whole content of the error message?
For your other issue https://docs.jabref.org/cite/openofficeintegration#known-issues

**Comment by petersaly** [comment]
Thank you for answering.

Meanwhile, I upgraded my opendk java to version 17. It was effectless, and it is understandable because ThiloteE writes that JabRef comes with its own bundled java version. It is OK. I did not know this information. Further, I downgraded to JabRef version 5.3, which version worked for me in last summer. However, this time version 5.3 also produced the same error. After that, I re-installed version 5.10. 

I install JabRef versions from .deb package via GDebi package installer.

Here, I attach a text file with the details of the error message sent by version 5.10 and a screenshot
[MessageDetails.txt](https://github.com/JabRef/jabref/files/10822310/MessageDetails.txt)
![Screenshot_2023-02-24](https://user-images.githubusercontent.com/56521459/221135090-731ed46c-5390-4fcc-bd9b-c8f8543ceb16.png)
:

**Comment by petersaly** [comment]
I have forgotten to write how to reproduce:

1. Open an .odt or .doc document in LibreOffice
2. Start Jabref
3. Connect OpenOpenOffice/LibreOffice document
4. Select an entry in your bibtex library
5. Click 'Cite' button (or any other) in the OpenOpenOffice/LibreOffice panel

**Comment by ThiloteE** [comment]
Try:

> The connection from JabRef to Libre Office requires some office related jar-archives to be present. For this, you have to install the package `libreoffice-java-common`.


in addition, you also could try to

- reset your preferences
- try the "Linux portable" from https://www.fosshub.com/JabRef.html. Not even once have I encountered any javafx version issues using the portable version of JabRef.

if the portable version works, we know it has something to do with your system or the gdebi package manager.

**Comment by Siedlerchr** [comment]
Hi, there seems to be something wrong with the OO style. Can you try to reset your preferences?

**Comment by petersaly** [comment]
Hi,

The package 'libreoffice-java-common' is installed on my computer.

Before I try the portable version, could give me some instruction how to reset my preferences, please?
