### ISSUE TITLE
JabRef 3.0: ACM Fetcher: Cannot parse number of hits

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#545]
When I do a search in the ACM in JabRef (no matter which one ), I get the following error.
```
java.io.IOException: Cannot parse number of hits
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.getNumberOfHits(ACMPortalFetcher.java:427)
	at net.sf.jabref.importer.fetcher.ACMPortalFetcher.processQueryGetPreview(ACMPortalFetcher.java:136)
	at net.sf.jabref.importer.fetcher.GeneralFetcher$3.run(GeneralFetcher.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by oscargus** [comment]
I can confirm this. I've started to see if I can solve it, and have passed the hits parsing. However, many other things have changed in the search results so it may take a while to get it back.

**Comment by oscargus** [comment]
OK, seems like I got some time on my hands anyway...

Try it out at http://builds.jabref.org/acmfetcher/
