### ISSUE TITLE
NPE when using GooglerScholarFetcher

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#563]
When I search for "Differentiation of oligodendroglial progenitors derived from cortical multipotent cells" in Google Scholar and add the only found entry, I get an NPE:

```
Exception in thread "JabRef CachedThreadPool" java.lang.NullPointerException: field value must not be null
        at java.util.Objects.requireNonNull(Unknown Source)
        at net.sf.jabref.model.entry.BibtexEntry.setField(BibtexEntry.java:329)
        at net.sf.jabref.importer.fetcher.GoogleScholarFetcher.downloadEntry(GoogleScholarFetcher.java:275)
```

**Comment by koppor** [comment]
Fixed in latest master.
