### ISSUE TITLE
Cannot open integrity check dialog (Error from controlsfx)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5643]
latest master:

Problem is the following line in controlsfx:
`    private static final Image filterIcon = new Image("/impl/org/controlsfx/table/filter.png");`

```
java.lang.IllegalStateException: Cannot load org.jabref.gui.integrity.integritycheckdialog
	at com.airhacks.afterburner.views.ViewLoader.load(ViewLoader.java:174) ~[afterburner.fx.jar:?]
	at org.jabref.gui.integrity.IntegrityCheckDialog.<init>(IntegrityCheckDialog.java:37) ~[main/:?]
	at org.jabref.gui.integrity.IntegrityCheckAction.lambda$1(IntegrityCheckAction.java:75) ~[main/:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[javafx.base:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[javafx.base:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx.base:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx.base:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx.base:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx.base:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[javafx.base:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[javafx.base:?]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) ~[javafx.graphics:?]
	at javafx.concurrent.Task.fireEvent(Task.java:1358) ~[javafx.graphics:?]
	at javafx.concurrent.Task.setState(Task.java:725) ~[javafx.graphics:?]
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1436) ~[javafx.graphics:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx.graphics:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx.graphics:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: javafx.fxml.LoadException: 
/C:/Users/Christoph/workspace/jabref/build/resources/main/org/jabref/gui/integrity/integritycheckdialog.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435) ~[javafx.fxml:?]
	at com.airhacks.afterburner.views.ViewLoader.load(ViewLoader.java:172) ~[afterburner.fx.jar:?]
	... 21 more

```

**Comment by koppor** [comment]
Maybe, this will be fixed with https://github.com/controlsfx/controlsfx/pull/1214 and a new release of @controlsfx.
