### ISSUE TITLE
changing \{degree\} to ° results in an error

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5745]
JabRef 5.0-alpha--2019-12-07--673e53b
Windows 7 6.1 amd64 
Java 13.0.1 

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  ERROR FallbackExceptionHandler Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
 java.lang.StringIndexOutOfBoundsException: begin 29, end 40, length 31
        at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
        at java.base/java.lang.String.substring(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl$2.computeValue(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringBinding.get(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringBinding.get(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.StringPropertyBase.get(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper$ReadOnlyPropertyImpl.get(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper$ReadOnlyPropertyImpl.get(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringPropertyBase.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
        at org.jabref.merged.module/javafx.beans.property.StringPropertyBase$Listener.invalidated(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.beans.binding.StringBinding.invalidate(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.markInvalid(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(UnknownSource)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl.lambda$new$0(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextField$TextFieldContent.insert(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl.updateContent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
        at org.jabref.merged.module/javafx.scene.control.skin.TextFieldSkin.replaceText(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.Scene$KeyHandler.process(Unknown Source)
        at org.jabref.merged.module/javafx.scene.Scene.processKeyEvent(Unknown Source)
        at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
        at org.jabref.merged.module/com.sun.glass.ui.View.notifyKey(Unknown Source)
        at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
Cannot reproduce. And you should already know the procedure. Please add some more details next time.

**Comment by bernhard-kleine** [comment]
abRef 5.0-alpha--2019-12-07--673e53b
Windows 7 6.1 amd64
Java 13.0.1

    I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce the behavior:

1. I opened Jabref
2. I searched Pubmed with DOI 10.1126/science.228.4696.177
3. Using Zotero 5.0.80, I saved the Pubmedentry to Zotero. From there, I exported a bib-file.
4. This bib-file I imported into jabref. The bibfile is:

> @article{heinrich_flight_1985,
> 	title = {Flight of Winter Moths Near 0\{degrees\}C},
> 	volume = {228},
> 	issn = {0036-8075},
> 	doi = {10.1126/science.228.4696.177},
> 	abstract = {Some noctuid winter moths fly at near 0 degrees C by maintaining an elevated(30 degrees to 35 degrees C) thoracic muscle temperature. Geometrid winter moths sustain themselves in free flight at subzero muscle temperatures. However, the temperature characteristics of citrate synthase and pyruvate kinase from both of these different kinds of moths and from a sphinx moth that flies with a muscles temperature of 40 degrees C are nearly identical. Furthermore, mass-specific rates of energy expenditure of both kinds of winter moths are also similar at given thoracic temperature (near 0 degrees C). The geometrids that are able to fly with a thoracic temperature near 0 degrees C do so largely because of unusually low wing-loading, which permits a low energetic cost of flight.},
> 	pages = {177--179},
> 	number = {4696},
> 	journaltitle = {Science},
> 	author = {Heinrich, B. and Mommsen, T. P.},
> 	date = {1985-04-12},
> 	pmid = {17779640}
> }
5. in the entry editor I exchanged "Flight of Winter Moths Near 0\{degrees\}C" into "Flight of Winter Moths Near 0°C"
6. Immediately I get the following error
    ...
Flight of Winter Moths Near 0°C
    ...

**Comment by Siedlerchr** [comment]
Seems like a bug from the alpha which is fixed in the master.

**Comment by bernhard-kleine** [comment]
This is still errorneous in the latest master:

JabRef 5.0-beta.1--2019-12-14--2e056e6
Windows 7 6.1 amd64 
Java 13.0.1

**Comment by bernhard-kleine** [comment]
obiously related to https://github.com/JabRef/jabref/issues/5708

**Comment by bernhard-kleine** [comment]
Importing via zotero has now the title is (bibtexsource)
`title = {Flight of Winter Moths Near 0°C},`
however via medline the title is still
`title = {Flight of Winter Moths Near 0{degrees}C},`

Changing the {degrees} into ° raises still the error, but only once. By repeating the substitution it works.

**Comment by Siedlerchr** [comment]
Is this still an issue in the latest master?

**Comment by bernhard-kleine** [comment]
@Siedlerchr Thank you for reminding me. 

- The issue does not happend any further. 
- Interestingly the way along the depicted line no longer imports instead of (degree)C  now °C, 
- while importing via Pubmed it imports {degrees}C. 
- JabFox imports °C. Pubmed cannot work with UTF8 obviously. 

But the original bug changing {degrees} into ° does not result in a bug with the actual snapshot.
