### ISSUE TITLE
Getting FileSystemNotFoundException

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#5798]
I have been using the version 5 nightlies and beta on linux (Ubuntu 18.04) and found a method to make this work: using OpenJDK 11 with basically the following command to run:
`${OJDK11}/bin/java -Xmx5G -p ${JABREF_HOME}/lib/app/mods -m org.jabref/org.jabref.JabRefLauncher`

This stopped to work now though and I get this when I try to use OpenJDK 11:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /home/johann/software/jabref/JabRef/lib/app/mods/java-string-similarity-1.2.1.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 57.0
```

When I use OpenJDK 13 instead, I get this:
```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
ERROR JabRefMain Unexpected exception
 java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:172)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:158)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at org.jabref/org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:96)
	at org.jabref/org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:81)
	at org.jabref/org.jabref.JabRefGUI.openWindow(JabRefGUI.java:90)
	at org.jabref/org.jabref.JabRefGUI.<init>(JabRefGUI.java:54)
	at org.jabref/org.jabref.JabRefMain.start(JabRefMain.java:76)
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by johann-petrak** [comment]
This is a configuration that still worked:
* JabRef 5.0.0-dev--2019-10-07----facda00c1
* Linux 4.15.0-70-generic amd64 
* Java 11.0.5

**Comment by tobiasdiez** [comment]
The most recent development versions (and the beta release) already contain the Java Runtime. Thus, there is no need to install or invoke java separately.
The easiest way to install JabRef on Linux is to use the deb (or rpm) files. You can also use the portable version and then lunch it using `JabRefMain` (not sure about the exact name of the launcher - maybe the help needs to be updated in this regard: https://docs.jabref.org/general/installation#using-prebuilt-binaries)

**Comment by johann-petrak** [comment]
The page linked from the jabref download section and from the docs page you shared, http://builds.jabref.org/master/ is empty as of now.

**Comment by tobiasdiez** [comment]
We run out of space on our build server 😸  @koppor

**Comment by koppor** [comment]
When using the gradle shadowJar plugin, fixing the `MANIFEST.md` (removing `org.jabref/` in front), then I get the same output.

```text
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Windows 10 amd64-64-Bit 20191016_111 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

**Comment by koppor** [comment]
Files are back again at http://builds.jabref.org/master/.

**Comment by koppor** [comment]
Maybe, it is because we use Java 13. - @johann-petrak Could you check with Java 13?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
