### ISSUE TITLE
Making paths of linked files relative breaks urls

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5861]
I am using the latest JabRef 5 master build:
JabRef-5.0-portable_linux.tar.gz
JabRef 5.0-beta.360--2020-01-21--7ddfd9f
Linux 4.4.0-171-generic amd64
Java 13.0.2
on Ubuntu 16.04
biblatexmode enabled

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists.

**Steps to reproduce the behavior:**

1. Create a reference which contains, among others, the following line:

```
file = {Full Text PDF:https\://www.jair.org/index.php/jair/article/download/11675/26513:application/pdf;Snapshot:https\://www.jair.org/index.php/jair/article/view/11675:text/html},
```

2. Save library.
3. Select the newly created reference.
4. Click on "Quality" > "Clean up entries", only tick "Make paths of linked files relative (if possible)" and click "OK".
5. Now the value of the "file" field has changed to the following:

```
file = {Full Text PDF:https\:/www.jair.org/index.php/jair/article/download/11675/26513:application/pdf;Snapshot:https\:/www.jair.org/index.php/jair/article/view/11675:text/html},
```

So both urls are broken now and cannot be used any more.

**Comment by Siedlerchr** [comment]
Olay, so the cleaning changed the type to URL. But the links still work.
I don't see any problem with this

**Comment by systemoperator** [comment]
In my opinion, cleaning up entries should not mess with web urls. In the end, the value changes from
`https://www.jair.org/index.php/jair/article/download/11675/26513`
to
`https:/www.jair.org/index.php/jair/article/download/11675/26513`.

Furthermore, malformed urls as the one shown above result in different other problems in JabRef:

Given a reference which e.g. contains, among others, the following line:

```
file = {IEEE Xplore Full Text PDF:https\://ieeexplore.ieee.org/ielx7/8938397/8946120/08946277.pdf?tp=\&arnumber=8946277\&isnumber=8946120\&ref=:application/pdf;IEEE Xplore Abstract Record:https\://ieeexplore.ieee.org/document/8946277:text/html}
```

I performed a cleanup on this reference. This results in:

```

```

When I then select this reference, where the urls are malformed now, and I switch to the tab "General" in the entry editor then sometimes several or at least one exception occurs, stating:

**Uncaught excetion occured in Thread[JavaFX Application Thread,5,main]**

**protocol = https host = null**

![image](https://user-images.githubusercontent.com/3658393/73000835-c9d09180-3e01-11ea-80e2-bca3bf3e3cf5.png)

Full stacktrace:

```
java.lang.IllegalArgumentException: protocol = https host = null
	at java.base/sun.net.spi.DefaultProxySelector.select(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at org.jabref/org.jabref.model.util.FileHelper.getFileExtension(Unknown Source)
	at org.jabref/org.jabref.logic.externalfiles.LinkedFileHandler.getSuggestedFileName(Unknown Source)
	at org.jabref/org.jabref.gui.fieldeditors.LinkedFileViewModel.isGeneratedNameSameAsOriginal(Unknown Source)
	at org.jabref/org.jabref.gui.fieldeditors.LinkedFilesEditor.createContextMenuForFile(Unknown Source)
	at org.jabref/org.jabref.gui.util.ViewModelListCellFactory$1.updateItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.ListCell.updateItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.ListCell.indexChanged(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.addTrailingCells(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Additionally, the tab "General" breaks, as it does not get rendered completely any more.

Furthermore, when I subsequently switch to another reference and switch back to the previously cleaned up reference, then no content of the the tab "General" can be rendered any more.

![image](https://user-images.githubusercontent.com/3658393/73002730-c5f23e80-3e04-11ea-8b55-6be8e42c7244.png)

Sometimes the whole entry editor breaks, so that no tabs and no content is shown any more. Every now and then it also results that the entry editor's "General" tab cannot be rendered any more for other references in this library, which have not been cleaned up. Sometimes the library's search functionality breaks as well for this library due to the malformed urls.

Sometimes the whole library must be closed so that JabRef recovers.

Actually, I started digging into this issue with the malformed urls due to the fact, that a lot exceptions and problems occured.

**Comment by tobiasdiez** [comment]
Thanks to you 😄 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by systemoperator** [comment]
Build checked, it works. :)
