### ISSUE TITLE
Searching for a DOI results in an ERROR

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5892]
JabRef 5.0-beta.388--2020-01-29--eb988b6
Windows 7 6.1 amd64 
Java 13.0.2
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I searched in an empty library (in my standard library as well) for the DOI 10.1210/endrev/bnz006. This resulted in an error. In my opinion this a serious failure since a DOI should be searchable. 

<details>
  <summary>Log File</summary>
  
  ```
ERROR FallbackExceptionHandler Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
netscape.javascript.JSException: SyntaxError: Invalid regular expression: missing )
       at org.jabref.merged.module/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
       at org.jabref.merged.module/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
       at org.jabref.merged.module/com.sun.webkit.WebPage.executeScript(Unknown Source)
       at org.jabref.merged.module/javafx.scene.web.WebEngine.executeScript(Unknown Source)
       at org.jabref/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(Unknown Source)
       at org.jabref/org.jabref.gui.preview.PreviewViewer.lambda$new$0(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
       at org.jabref/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
       at org.jabref/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
       at org.jabref/org.jabref.gui.search.GlobalSearchBar.lambda$new$8(Unknown Source)
       at org.jabref/org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked(Unknown Source)
       at org.jabref/org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedB(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.markInvalid(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.lambda$new$0(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextField$TextFieldContent.insert(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.updateContent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceSelection(Unknown Source)
       at org.jabref.merged.module/javafx.scene.control.TextInputControl.paste(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.paste(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$new$20(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
       at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.Scene$KeyHandler.process(Unknown Source)
       at org.jabref.merged.module/javafx.scene.Scene.processKeyEvent(Unknown Source)
       at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
       at java.base/java.security.AccessController.doPrivileged(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.glass.ui.View.notifyKey(Unknown Source)
       at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
       at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
       at java.base/java.lang.Thread.run(Unknown Source)
ERROR FallbackExceptionHandler Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
netscape.javascript.JSException: SyntaxError: Invalid regular expression: missing )
       at org.jabref.merged.module/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
       at org.jabref.merged.module/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
       at org.jabref.merged.module/com.sun.webkit.WebPage.executeScript(Unknown Source)
       at org.jabref.merged.module/javafx.scene.web.WebEngine.executeScript(Unknown Source)
       at org.jabref/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(Unknown Source)
       at org.jabref/org.jabref.gui.preview.PreviewViewer.lambda$new$0(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
       at org.jabref.merged.module/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
       at org.jabref/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
       at org.jabref/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
       at org.jabref.merged.module/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
       at org.jabref.merged.module/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
       at org.jabref.merged.module/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
       at org.jabref.merged.module/javafx.animation.Timeline.doPlayTo(Unknown Source)
       at org.jabref.merged.module/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
       at org.jabref.merged.module/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
       at org.jabref.merged.module/javafx.animation.Animation.doTimePulse(Unknown Source)
       at org.jabref.merged.module/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
       at java.base/java.security.AccessController.doPrivileged(Unknown Source)
       at org.jabref.merged.module/javafx.animation.Animation$1.timePulse(Unknown Source)
       at org.jabref.merged.module/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
       at org.jabref.merged.module/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
       at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
       at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
       at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
       at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
       at java.base/java.lang.Thread.run(Unknown Source)
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks to @dawidm this issue should be resolved now in the latest master.
It might take some time until the new version is uploaded.

**Comment by bernhard-kleine** [comment]
I will test it tomorrow. 👍
