### ISSUE TITLE
Automatic Bug Report - 20200205221539

### ISSUE THREAD

**Issue by D3578D** [JabRef/jabref#5922]
JabRef 4.3.1
Windows 10 10.0 x86 
Java 1.8.0_172

Steps to reproduce:

1. Searching document using 'title' for 'ID-based entry generator'

Paste your log details here.
<details>
<summary>Detail information:</summary>

```
An I/O exception occurred
org.jabref.logic.importer.FetcherException: An I/O exception occurred
	at org.jabref.logic.importer.IdParserFetcher.findIdentifier(IdParserFetcher.java:93)
	at org.jabref.logic.importer.fetcher.TitleFetcher.performSearchById(TitleFetcher.java:36)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.crossref.org/works?query.title=Linear+swing+dynamics&rows=20&offset=0
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.jabref.logic.importer.IdParserFetcher.findIdentifier(IdParserFetcher.java:74)
	... 9 more

```

</details>

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by D3578D** [comment]
Hello,

Thank you for your reply. 
I checked and it is solved. 

Regards,
Deepak
