### ISSUE TITLE
class kong.unirest.JsonObjectMapper cannot access class com.google.gson.Gson

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#5947]
`JabRef 5.0-beta.419--2020-02-12--3859620`
```console
$ jabref --version
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
JabRef 5.0-beta.419--2020-02-12--3859620
Exception in Application stop method
ERROR FallbackExceptionHandler Uncaught exception occurred in Thread[main,5,main]
 java.lang.RuntimeException: Exception in Application stop method
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalAccessError: class kong.unirest.JsonObjectMapper (in module org.jabref.merged.module) cannot access class com.google.gson.Gson (in module com.google.gson) because module org.jabref.merged.module does not read module com.google.gson
	at org.jabref.merged.module/kong.unirest.JsonObjectMapper.<init>(Unknown Source)
	at org.jabref.merged.module/kong.unirest.Config.<init>(Unknown Source)
	at org.jabref.merged.module/kong.unirest.Unirest.<clinit>(Unknown Source)
	at org.jabref/org.jabref.Globals.stopBackgroundTasks(Unknown Source)
	at org.jabref/org.jabref.JabRefMain.stop(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$10(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 more
jabref --version  5,59s user 0,34s system 22% cpu 25,907 total
```

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Install JabRef
2. Try running JabRef

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by homocomputeris** [comment]
JabRef 5.0-beta.421--2020-02-14--ec93ad3 launches
