### ISSUE TITLE
Group is lost if assigned to very bottom

### ISSUE THREAD

**Issue by Ka0o0** [JabRef/jabref#5968]
JabRef version (latest master) on macOS 10.15.3, Java 13.0.1

- [x] I have tested the latest master

1. Drag and Drop a group at the very bottom.
2. Exception is shown and group is lost

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:754)
	at java.base/java.util.ArrayList.add(ArrayList.java:479)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.doAdd(ObservableListWrapper.java:101)
	at javafx.base/javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:151)
	at org.jabref/org.jabref.model.TreeNode.addChild(TreeNode.java:474)
	at org.jabref/org.jabref.model.TreeNode.moveTo(TreeNode.java:562)
	at org.jabref/org.jabref.gui.groups.GroupNodeViewModel.moveTo(GroupNodeViewModel.java:286)
	at org.jabref/org.jabref.gui.groups.GroupNodeViewModel.draggedOn(GroupNodeViewModel.java:312)
	at org.jabref/org.jabref.gui.groups.GroupTreeView.lambda$initialize$15(GroupTreeView.java:244)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:3029)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3255)
	at javafx.graphics/javafx.scene.Scene$DropTargetListener.drop(Scene.java:2969)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(GlassSceneDnDEventHandler.java:108)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:104)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(GlassViewEventHandler.java:766)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:765)
	at javafx.graphics/com.sun.glass.ui.View.handleDragDrop(View.java:713)
	at javafx.graphics/com.sun.glass.ui.View.notifyDragDrop(View.java:1042)
	at javafx.graphics/com.sun.glass.ui.mac.MacPasteboard._putItemsFromArray(Native Method)
	at javafx.graphics/com.sun.glass.ui.mac.MacPasteboard.putItemsFromArray(MacPasteboard.java:143)
	at javafx.graphics/com.sun.glass.ui.mac.MacPasteboard.putItems(MacPasteboard.java:165)
	at javafx.graphics/com.sun.glass.ui.mac.MacSystemClipboard.pushToSystem(MacSystemClipboard.java:223)
	at javafx.graphics/com.sun.glass.ui.SystemClipboard.flush(SystemClipboard.java:51)
	at javafx.graphics/com.sun.glass.ui.ClipboardAssistance.flush(ClipboardAssistance.java:59)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1286)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3049)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.process(Scene.java:3118)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3878)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2590)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

  ```
</details>

**Comment by calixtus** [comment]
Thanks for the issue. To be a bit more precise:
1.a. Grab a group at the very bottom and
1.b. Drop it at the very bottom.
Or did I miss some other misbehaving?
I'm on it.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
