### ISSUE TITLE
Timing problem when saving

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6000]
JabRef 5.0-beta.458--2020-02-23--b2ab177
Windows 10 10.0 amd64 
Java 13.0.2

- [+ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. I have delete a duplicate entry.
2. Trying to save raised the following issue:
![grafik](https://user-images.githubusercontent.com/9216487/75116656-fe3aa600-566a-11ea-9269-b9719b940d00.png)

This is most probably a timing issue. My library is 8 mb large and has 3000+ entries.

The line 
`Caused by: java.nio.file.AccessDeniedException: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib.tmp -> K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib`
is most suggestive and an old acquaintance.

<details>
  <summary>Log File</summary>
  
  ```
  org.jabref.logic.exporter.SaveException: Problems saving:
	at org.jabref/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(Unknown Source)
	at org.jabref/org.jabref.gui.exporter.SaveDatabaseAction.doSave(Unknown Source)
	at org.jabref/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.runCommand(Unknown Source)
	at org.jabref/org.jabref.gui.actions.OldDatabaseCommandWrapper.execute(Unknown Source)
	at org.jabref/org.jabref.gui.actions.JabRefAction.lambda$new$2(Unknown Source)
	at org.jabref.merged.module/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib.tmp -> K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at org.jabref/org.jabref.logic.exporter.AtomicFileOutputStream.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at org.jabref/org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(Unknown Source)
	at org.jabref/org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(Unknown Source)
	... 43 more
  ```

</details>

**Comment by Siedlerchr** [comment]
Could reproduce this partially yesterday when saving and having auto completion enabled.
I will check it again.

**Comment by stefan-kolb** [comment]
Maybe related to https://github.com/JabRef/jabref/issues/6102?

**Comment by Siedlerchr** [comment]
It's related to the autosave and normal save happening
