### ISSUE TITLE
Export - error stream closed

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#608]
Hi,
On version 3.1, I'm unable to export. I try either via cut-paste or via file menu. I try many formats (some of my own or those by default). I'm running Ubuntu 14.04, with Java 8.
I get this exception :

```
+1: AVERTISSEMENT: [ResolvePDF]
déc. 30, 2015 4:50:29 PM net.sf.jabref.exporter.ExportFormat performExport
AVERTISSEMENT: The following formatters could not be found: ResolvePDF, ResolvePDF
java.io.IOException: Stream closed
	at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at net.sf.jabref.exporter.ExportFormat.finalizeSaveSession(ExportFormat.java:365)
	at net.sf.jabref.exporter.ExportFormat.performExport(ExportFormat.java:304)
	at net.sf.jabref.exporter.ExportFormats$1ExportAction$1.run(ExportFormats.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by oscargus** [comment]
It seems like the exporter ResolvePDF is missing. When browsing the source, I can not find any references to it. I might have gone missing when the pdf-field was made obsolete (and should therefore be removed from the export formats).

**Comment by Ferry128** [comment]
Hi, 

I have the same problem but without the export format missing:

[Fatal Error] :1:1: Content is not allowed in prolog.
java.io.IOException: Stream closed
	at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at net.sf.jabref.exporter.ExportFormat.finalizeSaveSession(ExportFormat.java:365)
	at net.sf.jabref.exporter.ExportFormat.performExport(ExportFormat.java:304)
	at net.sf.jabref.exporter.ExportFormats$1ExportAction$1.run(ExportFormats.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Thread.java:745)

Any idea? 

Thanks a lot in advance!

**Comment by smarru** [comment]
I have the same issue on Java 8 on mac with version 3.1

**Comment by oscargus** [comment]
In 20 minutes or so, there will be files at http://builds.jabref.org/fixed-608/ which should fix this.

**Comment by melTr** [comment]
Thanks. Works fine for me.

**Comment by Ferry128** [comment]
Thanks  a lot! works fine!

**Comment by cdlt** [comment]
The link http://builds.jabref.org/fixed-608/ is broken and last version continues with problem.

**Comment by koppor** [comment]
please try builds.jabref.org/master and report back if that works for you

**Comment by oscargus** [comment]
If it doesn't work (I think it should work) try to mark all entries and select "Export selected entries".

**Comment by cdlt** [comment]
Thank you very much. Version 3.3dev--snapshot--2016-03-22--master--8c208a0 is working.
