### ISSUE TITLE
JabRef 5.0 no connection to LibreOffice possible

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#6353]
JabRef version: JabRef 5.0--2020-03-09--6bff936
Linux 5.4.0-26-generic amd64 
Java 13.0.2
Ubuntu 20.04
  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

-On my fresh installed Ubuntu 20.04 JabRef 5.0 (snap) fails to connect to LibreOffice (6.4 - no snap app)
-libreoffice-java-common is installed
- The following error message shows up: Connection failed

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-3
	at org.jabref.merged.module/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Stage.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Stage.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.HeavyweightDialog$1.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.HeavyweightDialog.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Dialog.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Alert.<init>(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.Alert.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.FXDialog.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.FXDialog.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.JabRefDialogService.createDialog(Unknown Source)
	at org.jabref/org.jabref.gui.JabRefDialogService.showInformationDialogAndWait(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.DetectOpenOfficeInstallation.selectInstallationPath(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.DetectOpenOfficeInstallation.autoDetectPaths(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.DetectOpenOfficeInstallation.isInstalled(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel$1.call(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel$1.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

- I also tried to use manual connection but can't browse to "usr/lib/libreoffice/program"  where soffice is located. The folder "libreoffice" just does not show up. All possible permissions were given in Software Center  
- JabRef 4.3.1 connects without any issues.

**Comment by Siedlerchr** [comment]
@LyzardKing this looks like some snap restriction. JabRef uses the uno api to connect to create a socket connection to Libre office.
Do you know if we need some extra permissions?

@teertinker could you please also test with the non snap version?

**Comment by teertinker** [comment]
Thank you for the tip! The deb version connects without any issues. Note: The ubuntu software store currently only offers snap versions.

**Comment by LyzardKing** [comment]
@Siedlerchr I believe this would not be permissible via snap.
It might be technically feasible using similar permissions to the ones used for the browser connection... (if jabref only needs access to a file to use as an endpoint for the api..)
but we should ask in the snapcraft forum, since it would need their approval.
The same goes for the integration with latex editors, or any thirdparty apps for that case.
Snaps are confined by design, so they cannot access anything from the outside of the snap.
The other possibility, since jabref uses connections for many different functions, would be to switch to a classic snap, not confined, with full access to the underlying system.

**Comment by LyzardKing** [comment]
The snap version of libreoffice might expose the api to other snaps, but that would be something to ask the libreoffice devs.

**Comment by Siedlerchr** [comment]
Hm. As Ubuntu 20.04 is now mostly recommending/installing snap apps, it would probably make sense to use "classic" mode for interactions, but this also requires an extra step when installing.
On the other hand the users can quiclkly install the deb version and have to manually update. 
Marking this as discussion for the  next devcall

**Comment by LyzardKing** [comment]
It doesn't require any extra step.. you would simply run
`snap install jabref --classic`
instead of `snap install jabref`

The point is that the "permission" to publish a classic snap needs to be asked in the forum, (like we did for the browser connection)

It was briefly mentioned back in https://github.com/JabRef/jabref/issues/3121.

**Comment by koppor** [comment]
If we understood correctly, the alternative to `--classic` is to have exceptions for a fixed set of programs. Such as libreoffice, texstudio, lyx, ...

I think `--classic` is a kind of "strange" thing to the user. So, I'd like to understand if another approach is possible.

**Comment by LyzardKing** [comment]
It's a bit complicated, since i:
1. if the application (libreoffice, texstudio, ... are snaps it'll be impossible, if the app in question does not expose a "slot" to give access to other apps to it's files.
2. if the application is not a snap, then we need to access it with a permission (like the one used for the extension). I'm testing it with libreoffice now, but I get the error "some of the jar files missing"
(on this note, what is actually needed from libreoffice?)
Also we can only hardcode the paths, so we need to be sure that in different distros the path (i.e. to the jar files in libreoffice) is consistently the same..
