### ISSUE TITLE
Uncaught exception occurred in Threard[JavaFX Application Thread,5,main]

### ISSUE THREAD

**Issue by nonglobal** [JabRef/jabref#6367]
JabRef version:
JabRef 5.0--2020-03-06--2e6f433
Linux 4.18.19-100.fc27.x86_64 amd64 
Java 13.0.2

This error fires each time I push a key in the "author" field.

Detalis:

java.lang.ClassCastException: class java.lang.String cannot be cast to class org.jabref.model.entry.Author (java.lang.String is in module java.base of loader 'bootstrap'; org.jabref.model.entry.Author is in module org.jabref of loader 'app')
	at org.jabref/org.jabref.gui.autocompleter.PersonNameStringConverter.toString(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.cell.CellUtils.getItemText(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.cell.CellUtils.updateItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.cell.TextFieldListCell.updateItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.ListCell.updateItem(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.ListCell.indexChanged(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$2$1.doLayoutPass(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.preferredSize(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$2.preferredSize(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.SceneHelper.preferredSize(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Window$12.invalidated(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Window.setShowing(Unknown Source)
	at org.jabref.merged.module/javafx.stage.Window.show(Unknown Source)
	at org.jabref.merged.module/javafx.stage.PopupWindow.showImpl(Unknown Source)
	at org.jabref.merged.module/javafx.stage.PopupWindow.show(Unknown Source)
	at org.jabref.merged.module/impl.org.controlsfx.skin.AutoCompletePopup.show(Unknown Source)
	at org.jabref.merged.module/org.controlsfx.control.textfield.AutoCompletionBinding.showPopup(Unknown Source)
	at org.jabref.merged.module/org.controlsfx.control.textfield.AutoCompletionBinding$FetchSuggestionsTask.lambda$call$0(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Gena928** [comment]
@nonglobal,
please give a bit more details about reproducing the error. So, you open Jabref, click on an article, and enter a new word in "Author" field, right?
I don't see an error on my computer. What kind of entry do you have?
<img width="412" alt="Screenshot 2020-04-29 at 23 20 21" src="https://user-images.githubusercontent.com/20572030/80643297-888af600-8a70-11ea-80f1-852ed596458a.png">

**Comment by AEgit** [comment]
JabRef 5.1--2020-04-29--7219e36
Linux 5.3.0-51-generic amd64 
Java 14.0.1

I cannot reproduce this issue.

**Comment by ilippert** [comment]
not sure, whether this is helpful - but in the log entry I get the sense of autocompletion being involved, similar to https://github.com/JabRef/jabref/issues/6344 - might that be the case?

**Comment by nonglobal** [comment]
> @nonglobal,
> please give a bit more details about reproducing the error. So, you open Jabref, click on an article, and enter a new word in "Author" field, right?

Yes. Adding a new entry in the author field and only in author field.
It's occurs with autocomplete enable or disabled.

> I don't see an error on my computer. What kind of entry do you have?

It's occurs in any kind of entry (article, book, etc.).

> <img alt="Screenshot 2020-04-29 at 23 20 21" width="412" src="https://user-images.githubusercontent.com/20572030/80643297-888af600-8a70-11ea-80f1-852ed596458a.png">

Yes

**Comment by nonglobal** [comment]
Same error in the "linux portable" version.
Possible Java instalation issue?

**Comment by Gena928** [comment]
Maybe. Can you reinstall it? 
I have Mac computer and I can't reproduce error. I.e. everything works fine and no error messages appear.

**Comment by Siedlerchr** [comment]
@nonglobal  Have you tested the latest development version? https://builds.jabref.org/master/

**Comment by nonglobal** [comment]
> @nonglobal Have you tested the latest development version? https://builds.jabref.org/master/

Yes: jabref-5.1-1.x86_64.rpm
Unfortunately, i got the same error.
Same thing with portable linux version.
Maybe an error in my Java installation?

**Comment by nonglobal** [comment]
> This issue will be closed in 7 days due to inactivity  Please provide the requested information if the problem persists.

I have provided the info asked on May 4 (see me post).

Here a resumée:

- Reinstall do not solve the problem.
- The issue is present for me in portable and rpm versions.
- I tested the development version (5.1-1) and I got the same error.

What else I can do for provide more information?

**Comment by nonglobal** [comment]
I appreciate any help.
