### ISSUE TITLE
Springer fetcher produces FetcherException

### ISSUE THREAD

**Issue by MootezSaaD** [JabRef/jabref#6395]
- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Response:
`Authentication failed`

Response Header:
```
HTTP/1.1 403 Forbidden
Server: openresty/1.7.4.1
Date: Sat, 02 May 2020 11:29:15 GMT
Content-Type: text/plain; charset=us-ascii
Transfer-Encoding: chunked
Connection: keep-alive
X-DNS-Prefetch-Control: off
```

<details>
  <summary>Log File</summary>
org.jabref.logic.importer.FetcherException: A network error occurred
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://api.springernature.com/meta/v1/json?q=API+Strategy&api_key=a98b4a55181ffcd27259bea45edad12e&p=20
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	... 11 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://api.springernature.com/meta/v1/json?q=API+Strategy&api_key=a98b4a55181ffcd27259bea45edad12e&p=20
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 12 more

</details>

**Comment by zenny** [comment]
Same at this end in voidlinux:

```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://api.springernature.com/meta/v1/json?q=<MY_SEARCH_STRING>&api_key=a98b4a55181ffcd27259bea45edad12e&p=20
```

Unhandled Exception Error log:

```
org.jabref.logic.importer.FetcherException: A network error occurred
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://api.springernature.com/meta/v1/json?q=<MY_SEARCH_STRING>&api_key=a98b4a55181ffcd27259bea45edad12e&p=20
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	... 11 more
```
