### ISSUE TITLE
fetcher isbn exception when including linebreak

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6456]
JabRef 5.1-PullRequest6455.368--2020-05-09--fff4926
Linux 5.6.8-200.fc31.x86_64 amd64 
Java 14.0.1

When I add a linebreak (enter) to an ISBN field and then click onto retrieve metadata, i get the exception

1. use isbn number with linebreak
2. retrieve metadata

Suggestion:
- before fetching isbn data, remove linebreaks
- isbn number followed by pressing enter should not generate linebreak but open the isbn (or alternatively ask whether to open or retrieve metadata).

<details>
  <summary>Log File</summary>
  
org.jabref.logic.importer.FetcherException: Could not 
	at org.jabref/org.jabref.logic.importer.fetcher.IsbnViaOttoBibFetcher.performSearchById(IsbnViaOttoBibFetcher.java:58)
	at org.jabref/org.jabref.logic.importer.fetcher.IsbnFetcher.performSearchById(IsbnFetcher.java:55)
	at org.jabref/org.jabref.gui.mergeentries.FetchAndMergeEntry.lambda$fetchAndMerge$0(FetchAndMergeEntry.java:65)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:47)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:142)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.MalformedURLException: Illegal character in URL
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.checkURL(HttpsURLConnectionImpl.java:70)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1101)
	at org.jabref.merged.module/org.jsoup.helper.HttpConnection$Response.createConnection(HttpConnection.java:892)
	at org.jabref.merged.module/org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:729)
	at org.jabref.merged.module/org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
	at org.jabref.merged.module/org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
	at org.jabref.merged.module/org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
	at org.jabref/org.jabref.logic.importer.fetcher.IsbnViaOttoBibFetcher.performSearchById(IsbnViaOttoBibFetcher.java:56)
	... 11 more
</details>

**Comment by Siedlerchr** [comment]
Thankst to @joethei this should now be fixed in the latest development version
