### ISSUE TITLE
Double bracketed author name shows wrong in author/editor column

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6465]
JabRef 5.1–2020-04-14–e86d415 on Windows 10 10.0 amd64 with Java 14.0.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Even if an author name is protected with brackets, it appears only in part in the Author/Editor column.

1. Load the following entry:
```
@WWW{Apple2020,
  author  = {{Apple Inc.}},
  date    = {2020},
  title   = {Eseguire il backup dei file con Time Machine sul Mac},
  url     = {https://support.apple.com/it-ch/guide/mac-help/mh35860/mac},
  urldate = {2020-5-09},
  langid  = {italian},
}
```
2. (optional) Use this entry in a text (Latex or markdown) to verify the text reference and citation are correct
3. In JabRef Author/Editor column, the author is shown as “Inc.” when I expected "Apple Inc."
4.  Same problem for other compound names like {Quote Investigator} that shows “Investigator” and {The LOGO Foundation} that appear as “Foundation”.

**Comment by mlep** [comment]
Different issue, but similar topic: issue #6388 .

**Comment by tobiasdiez** [comment]
Thanks to @k3KAW8Pnf7mkmdSMPHz27 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by crystalfp** [comment]
Well, no change. Same as before for `{Apple Inc.}`. I used the version 
JabRef 5.1--2020-05-27--c119ca2
Windows 10 10.0 amd64 
Java 14.0.1
Downloaded right now from builds.jabref.org/master

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@crystalfp the PR was merged 22 min ago. I don't know how long it takes to build a new development version but I'd guess it will be included in JabRef 5.1--2020-05-28.

**Comment by Siedlerchr** [comment]
@crystalfp  You were a bit too fast, the new version is still building. It should be ready in roughly 10 minutes or so: https://github.com/JabRef/jabref/runs/717321958

**Comment by crystalfp** [comment]
Unfortunately this version (2020-05-28 21:01) does not starts. No message, no error, nothing. Removed previous version and reinstalled. Nothing. Is there any debug flag to see what happens?
Thanks!

**Comment by crystalfp** [comment]
If I run the portable version it not starts. Putting command line option `-h` gives the following errors:
```

C:\Users\Mario Valle\Downloads\JabRef\runtime\bin>JabRef -h
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n java.lang.NullPointerException: null
        at org.jabref.preferences.JabRefPreferences.lambda$updateColumnSortOrder$16(Unknown Source) ~[org.jabref:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
        at org.jabref.preferences.JabRefPreferences.updateColumnSortOrder(Unknown Source) ~[org.jabref:?]
        at org.jabref.preferences.JabRefPreferences.createMainTableColumnSortOrder(Unknown Source) ~[org.jabref:?]
        at org.jabref.preferences.JabRefPreferences.loadTableSaveOrder(Unknown Source) ~[org.jabref:?]
        at org.jabref.preferences.JabRefPreferences.loadForExportFromPreferences(Unknown Source) ~[org.jabref:?]
        at org.jabref.preferences.JabRefPreferences.getCustomExportFormats(Unknown Source) ~[org.jabref:?]
        at org.jabref.preferences.JabRefPreferences.getExporterFactory(Unknown Source) ~[org.jabref:?]
        at org.jabref.JabRefMain.applyPreferences(Unknown Source) ~[org.jabref:?]
        at org.jabref.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
Could be an hint?

**Comment by Siedlerchr** [comment]
@crystalfp Try to reset your preferences, add the commandline swtich `-d all`
cc @calixtus  Related to your changes?

**Comment by calixtus** [comment]
I noticed this behaviour already before, I thought this was already reported as an issue.

**Comment by crystalfp** [comment]
Anyway, we are drifting to a different problem. I'll wait for another build to check the fix. Thanks!
FYI: `-d all` do nothing. Same error.

**Comment by calixtus** [comment]
The newest portable version should start if you start JabRef with the mentioned commandline switch. But back to the main problem: Bracket names are not kept together as they are in biber and latex.

Could be related to the issue mentioned in the post merge discussion in #6479 ?

**Comment by crystalfp** [comment]
The original problem and the last no-start one have been solved in:
JabRef 5.1--2020-05-29--ed275b6
Windows 10 10.0 amd64 
Java 14.0.1
I'm going to close this issue.
Thanks!
mario
