### ISSUE TITLE
journallist.mv mvstore exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6482]
JabRef 5.1--2020-05-14--09111be
Linux 5.6.11-200.fc31.x86_64 amd64 
Java 14.0.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I have edited the biblatex source in the entry editor and got this exception.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IllegalStateException: Reading from file nio:/tmp/journal6841416217601125907/journalList.mv failed at 1745057 (length -1), read 0, remaining 1024 [1.4.200/1]
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.DataUtils.newIllegalStateException(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.DataUtils.readFully(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.FileStore.readFully(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.Chunk.readBufferForPage(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVStore.readBufferForPage(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVStore.readPage(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVMap.readPage(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.Page$NonLeaf.getChildPage(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.Page.get(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVMap.get(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVMap.get(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.mvstore.MVMap.containsKey(Unknown Source)
	at org.jabref/org.jabref.logic.journals.JournalAbbreviationRepository.isAbbreviatedName(Unknown Source)
	at org.jabref/org.jabref.logic.integrity.AbbreviationChecker.checkValue(Unknown Source)
	at org.jabref/org.jabref.gui.fieldeditors.AbstractEditorViewModel.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.1.394/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.1.394/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.validate(Unknown Source)
	at org.jabref.merged.module@5.1.394/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref/org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked(Unknown Source)
	at org.jabref/org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedB(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.collections.ObservableMapWrapper.callObservers(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.collections.ObservableMapWrapper.put(Unknown Source)
	at org.jabref/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.SourceTab.storeSource(Unknown Source)
	at org.jabref/org.jabref.gui.entryeditor.SourceTab.lambda$setupSourceEditor$4(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Node$FocusedProperty.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene$12.invalidated(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene$KeyHandler.setFocusOwner(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene$KeyHandler.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Node.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.mousePressed(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.394/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.394/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at org.jabref.merged.module@5.1.394/org.h2.store.fs.FileNio.read(Unknown Source)
	... 90 more
  ```
</details>

**Comment by Siedlerchr** [comment]
Does this error stil occur?

**Comment by ilippert** [comment]
> Does this error stil occur?

Thanks for asking.
I am afraid I cannot say. I guess not - I am posting most exceptions I get and it probably has not occurred anymore if I did not post it again. If you give me a note what to check for, what kind of operations to conduct, then I will test the current master for it. I do not know the code well enough (no capacity to read this error code) to know what journallist or the exception code refers to.

**Comment by Siedlerchr** [comment]
Judging from the error log it seem you edited the journal field in the biblatex source tab. I tried to reproduce this, but could not. And it may be related to another fix which I did to the loading of journal abbreviaton.
Therefore I would vote to close this and you reopen it when you encounter it
