### ISSUE TITLE
New entry from plain text fails

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6517]
JabRef 5.1--2020-05-23--03e3663
Windows 10 10.0 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The new automatic parser of entries from text fails to extract anything from citations extracted from papers or sites. Here are two examples:

```
Is there life after Fortnite? An emerging trend in game design brings novelty
by Pascal Luban on 06/04/19 
<https://gamasutra.com/blogs/PascalLuban/20190604/343440/Is_there_life_after_Fortnite_An_emerging_trend_in_game_design_brings_novelty.php>

Subramony, D., Molenda, M., Betrus, A., and Thalheimer, W. (2014). The Mythical Retention Chart and the Corruption of Dale’s Cone of Experience. Educational Technology, Nov/Dec 2014, 54(6), 6-16.
```
With the old, manual one at least I can extract the relevant parts and then correct the record. Is it possible to have it back?

1. Copy one of the citations above
2. in JR "New entry from plain text"
3. Paste and push "Add to current library"
4. Nothing happens

Thanks!
mario

**Comment by crystalfp** [comment]
Also using the example from the page: https://docs.jabref.org/collect/newentryfromplaintext gives "0 entries were parsed from your query" with JabRef 5.1--2020-06-04--7cc5747 (latest available today)

To diagnose the problem I started `JabRef.bat --debug` from the portable installation. After other errors not directly related to my problem, here is the output when I ask to parse the entry from the example page:

```
%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n java.net.ConnectException: Connection refused: connect
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
        at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:?]
        at org.jabref.logic.net.URLDownload.openConnection(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.net.URLDownload.asString(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.net.URLDownload.asString(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.importer.util.GrobidService.processCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.importer.fetcher.GrobidCitationFetcher.parseUsingGrobid(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.importer.fetcher.GrobidCitationFetcher.lambda$performSearch$1(Unknown Source) ~[org.jabref:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at org.jabref.logic.importer.fetcher.GrobidCitationFetcher.performSearch(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.bibtexextractor.BibtexExtractorViewModel.lambda$startParsing$0(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) [org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) [org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) [org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n 
```
Seems like Grobid (the parser) tries to connect somewhere but the connection is refused. No sign of this need to connect in the documentation. Could it be the Grobid demo server http://cloud.science-miner.com/grobid/? From the browser I can connect to this page without problems.

Thanks for your help!
mario

**Comment by Siedlerchr** [comment]
WE have our own grobid server, but there are also currently some issues. We are trying to investigate this. See also #6587 #6369

**Comment by crystalfp** [comment]
Tried various entries from article references, but no one succeeded. Maybe I'm doing something wrong, but don't understand what.
Could be useful for you if I send you all the failed references?
For now I wait for the next official release before testing again.
Thanks!

**Comment by nitram509** [comment]
> Could be useful for you if I send you all the failed references?

Thank you for the offer, @crystalfp .
Actually, the root cause is already known, so this would add no new information.

I guess the maintainers already have this on their "radar".

**Comment by humbleambition** [comment]
Fantastic, you're working on this already then.
Any idea when this is likely to get fixed?

**Comment by dbitouze** [comment]
This issue still happens, at least on macOS and on Windows (not on GNU/Linux).
