### ISSUE TITLE
Can't connect to libreoffice

### ISSUE THREAD

**Issue by Addicted-to-coding** [JabRef/jabref#6562]
Hi,
I'm using jabref version 5.0 and LibreOffice 5.1.6.2 installed on Ubuntu 16.04. When I try to connect a LibreOffice file with jabref, I get the error
Autodetection failed
no office executable found!
The exception stacktrace was
com.sun.star.comp.helper.BootstrapException: no office executable found!
	at org.jabref/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OOBibBase.simpleBootstrap(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OOBibBase.<init>(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel.createBibBase(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

How can I fix this?

**Comment by Siedlerchr** [comment]
Hi,
do you use the deb version or the snap variant? (The snap variant does not work with libre office due to restrictions)
Have you installed the libreoffice-java-common libs? 
https://docs.jabref.org/cite/openofficeintegration#known-issues

**Comment by Addicted-to-coding** [comment]
I installed jabref_5.0-1_amd64.deb from here:https://www.fosshub.com/JabRef.html?dwl=jabref_5.0-1_amd64.deb
Yes, I have libreoffice-java-common installed

**Comment by Siedlerchr** [comment]
Did you install libre office as snap? If yes, then remove the snap version and install the non snap version
