### ISSUE TITLE
IEEE Search crash

### ISSUE THREAD

**Issue by djwoodhouse** [JabRef/jabref#6568]
JabRef 5.0--2020-03-06--2e6f433
Mac OS X 10.15.4 x86_64 
Java 13.0.2

Steps to reproduce:

1. Web search IEEEXplore for anything ...
2. Exception
org.jabref.logic.importer.FetcherException: A network error occurred
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=86wnawtvtc986d3wtnqynm8c&querytext=loeloe
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	... 11 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=86wnawtvtc986d3wtnqynm8c&querytext=loeloe
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 12 more

Paste your log details here.

**Comment by koincidencia** [comment]
I have the same issue and I think the IEEExplore api key is no longer valid. If I open [the link from the log](https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=86wnawtvtc986d3wtnqynm8c&querytext=https%3A%2F%2Fieeexplore.ieee.org%2Fdocument%2F131271) in a browser I got the following message: `<h1>Developer Inactive</h1>`

```
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2

org.jabref.logic.importer.FetcherException: A network error occurred
	at org.jabref/org.jabref.logic.importer.SearchBasedParserFetcher.performSearch(Unknown Source)
	at org.jabref/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=86wnawtvtc986d3wtnqynm8c&querytext=https%3A%2F%2Fieeexplore.ieee.org%2Fdocument%2F131271
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	... 11 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=86wnawtvtc986d3wtnqynm8c&querytext=https%3A%2F%2Fieeexplore.ieee.org%2Fdocument%2F131271
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 12 more
```

**Comment by Siedlerchr** [comment]
@koincidencia  We got a new key and it will be available in the newest developer version soon,
cc @calixtus

**Comment by limimiking** [comment]
> @koincidencia We got a new key and it will be available in the newest developer version soon,
> cc @calixtus

Encountered the same issue, looking forward to the new version

**Comment by calixtus** [comment]
The new ieee-key should now be integrated in the dev builds on builds.jabref.org. Please understand, that we cannot provide the key for builds directly from source, as IEEE has a limited number of access queries and therefore we cannot publish this key in the source like before.

So in the next master build and of course in the next main release, this should be fixed.

**Comment by calixtus** [comment]
Please remember to backup your library before testing a dev release.
