### ISSUE TITLE
unknown exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6684]
JabRef 5.1--2020-07-13--6344401
Linux 5.7.7-200.fc32.x86_64 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

sorry, no idea yet, when this exception occurs. it occurred a few times whilst adding new entries.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-9-thread-1
	at org.jabref.merged.module@5.1.791/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.control.Labeled.setText(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.791/javafx.scene.control.Tab.setText(Unknown Source)
	at org.jabref@5.1.791/org.jabref.gui.JabRefFrame.updateAllTabTitles(Unknown Source)
	at org.jabref@5.1.791/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.1.791/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.1.791/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.1.791/org.jabref.gui.dialogs.AutosaveUiManager.listen(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.1.791/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.1.791/org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
It's related to the autosave backup manager which is on the wrong thread. Nothing critical. 
I hope I find some time to work on that general restructure of thatautosave backup

**Comment by ilippert** [comment]
by now I have autosave disabled. but exceptions still take place.
