### ISSUE TITLE
regexp search throws exception when entering slash

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#6777]
JabRef 5.1--2020-08-22--dc55a76
Linux 5.4.19-050419-generic amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open bib file
2. Switch to regexp search
3. Enter something with a "/" in it, e.g. bla/bla
4. For each matching entry you get an exception (see details below) thrown. I had once about 50 results, so 50 windows with an exception trace opened.  

Maybe the regular expression could be checked and an exclamation mark icon shown as long as it is incomplete or not escaped before it's executed. Or, one could employ some automatic escaping. 

<details>
  <summary>Log File</summary>
  
 netscape.javascript.JSException: SyntaxError: Invalid regular expression: missing )
	at org.jabref.merged.module@5.1.876/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at org.jabref.merged.module@5.1.876/com.sun.webkit.WebPage.executeScript(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.preview.PreviewViewer.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref@5.1.876/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.1.876/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.876/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.876/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
</details>

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I just realised I don't know how the regexp search is supposed to work.... Is it correct that regexp should only works for fields (e.g., `citationkey = Turing\d[0-9]*`) which in turn does not get highlighted in the preview?

Right now, if I were to search only for `Turing\d[0-9]*` everything inside of a preview that matches that regexp would be highlighted while only entries containing a literal match would be shown in the search results. Have I missed something?

**Comment by Siedlerchr** [comment]
Regarding the search, have you enabled the regex mode? 
https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#regular-expressions-and-casing
(the search is actually based on an Antlr4 grammar, you find that in buildres) 

The highlight function is pretty simple, it does not work with JabRef's search grammar. It's just for highlighting search words. 
It's based on https://markjs.io/

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I believe so 😬 
Note the "no results found".

<img width="642" alt="Skärmavbild 2020-11-04 kl  16 32 47" src="https://user-images.githubusercontent.com/2598631/98170430-f995e500-1ebb-11eb-9f0d-9a923f7f1b22.png">

I have ogled Antlr4 a bit, the issue is that I don't know what should happen. Preventing the exception can either be done by escaping the slash or using `new RegExp` (which is what I tried out in #7073).

**Comment by Siedlerchr** [comment]
You are right that should show results.
try Debugging if the correct mode is correctly activated (class is GlobalSearchBar) 
Might also be an issue with multiple open libraries. That can cause quirks

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ok, in that case I will include it in the PR for this issue.

**Comment by Siedlerchr** [comment]
@k3KAW8Pnf7mkmdSMPHz27  I did a quick test and it seems like the regex search only works in combination with a field:
e.g. `author=Liu.*`
See: 
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/search/rules/SearchRules.java#L7

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr as far as I can tell that is the case. Note that `Liu.*` is a `GrammarBasedSearchRule`. I am using a break-point at https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/search/rules/SearchRules.java#L16
while debugging.

But, right now I believe
https://github.com/JabRef/jabref/blob/fcbe9c52e099a783a67b1445e2b9bb6f4c485fa0/src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java#L235
should be using
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/search/rules/SearchRules.java#L34

However, my experience of debugging Antlr consists of this issue 😀 
I'll put some more time into this and see if I can find the "correct" solution.

**Comment by Siedlerchr** [comment]
Ah yes you are right regarding the simple search. Overlooked that.
You might want to ask @tobiasdiez what he did there 4 years ago :-P 
https://github.com/JabRef/jabref/pull/1995

**Comment by tobiasdiez** [comment]
Please don't put much energy in the ANTLR code. It is obsolete and should be replaced by Lucene: https://github.com/JabRef/jabref/issues/1975

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr @tobiasdiez Ok, in that case I will try to "patch" the issue(s) rather than delving deeper into it.

**Comment by Siedlerchr** [comment]
I think you just need to add and addtional if check for regex and then call either the regex rule  or the contains. That looks like the simples way
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/search/rules/GrammarBasedSearchRule.java#L234-L235

**Comment by Siedlerchr** [comment]
@ytzemih Thanks to @k3KAW8Pnf7mkmdSMPHz27  this issue is now fixed. We also fxed another issue where regex search did not find some entries

**Comment by ytzemih** [comment]
@Siedlerchr @k3KAW8Pnf7mkmdSMPHz27 Nice to hear. Thanks for the effort. Will try it out as soon as it is in the build.

**Comment by Siedlerchr** [comment]
The new dev version should be already avaiable.

**Comment by ytzemih** [comment]
@Siedlerchr Brilliant, just downloaded it, tried it, and it seems to work properly for me. Thanks, again.
