### ISSUE TITLE
Invisible buttons for File field

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6859]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The buttons near the File field are not visible (screenshot 1). If the File entry has problems all the following fields disappear (screenshot 2).

1. Open a library containing the following entry:
```
@InCollection{Favre2004,
  Title                    = {{AVS and AVS/Express}},
  Author                   = {Jean Favre and Mario Valle},
  Booktitle                = {{The Visualization Handbook}},
  Publisher                = {Academic Press},
  Year                     = {2004},
  Editor                   = {Chuck Hansen and Chris Johnson},
  Month                    = dec,
  Pages                    = {655--672},
  File                     = {Paper:file\:///D\:\\Books\\Publications\\ch33%20favre.pdf:PDF},
  Keywords                 = {books},
  Mvpubtype                = {books},
  Langid                   = {english},
  Url                      = {http://www.elsevierdirect.com/product.jsp?isbn=9780123875822}
}
```
2. Select the entry and an exception appears (exception stack below):
```
Illegal char <:> at index 4: file:///D:/Books/Publications/ch33%20favre.pdf
```
Note this entry pertains to a library created in a very old version of JabRef.
3. Go to the General tab and notice the buttons are not visible.
4. Click on the File field and all the following fields disappear.
5. Now try to reload the entry selecting the file with the leftmost invisible button.
6. Nothing appears in the field

Missing buttons:
![image](https://user-images.githubusercontent.com/865866/92070246-cd6ec280-edab-11ea-97eb-c2cc1bce9db6.png)

After clicking on the File field:
![image](https://user-images.githubusercontent.com/865866/92070449-5128af00-edac-11ea-8be1-d31b62e3b0ca.png)

Exception text:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/Books/Publications/ch33%20favre.pdf
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.fieldeditors.LinkedFileViewModel.isGeneratedNameSameAsOriginal(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.fieldeditors.LinkedFilesEditor.createContextMenuForFile(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.util.ViewModelListCellFactory$1.updateItem(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.ListCell.updateItem(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.ListCell.indexChanged(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by crystalfp** [comment]
If I remove the file entry from the library, the buttons return visible.

**Comment by Siedlerchr** [comment]
Thanks for the report. Even if the file is invalid, the buttons should still be visible and a proper error message sould be shown

**Comment by calixtus** [comment]
Devcall: Hi @crystalfp , we recently merged a pr (#7347) which should have fixed this issue. Could you please check if this issue is still valid?

**Comment by crystalfp** [comment]
Dear @calixtus the issue seems solved, thanks! The only thing I don't understand is why file takes two lines but fill only the first one (see image below). The black border visible in the image is not visible on the live JabRef. Anyway, the main problem has been solved.

![image](https://user-images.githubusercontent.com/865866/107994557-2ab6a300-6fdd-11eb-8674-b87a1c746580.png)

**Comment by calixtus** [comment]
Thanks for checking and closing this issue.
The reason for two lines is that you can link multiple files to a BibEntry if I remember right. Although this might not be very often the case, it should be possible.
