### ISSUE TITLE
Fix shared database tests

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#6862]
Currently, in the latest master version the SharedDatabaseTests are failing with the following error

```
org.jabref.logic.shared.SynchronizationTestSimulator

  Test simulateUpdateOnNoLongerExistingEntry() FAILED

  org.opentest4j.AssertionFailedError: expected: not <null>
      at org.jabref.logic.shared.SynchronizationTestSimulator.simulateUpdateOnNoLongerExistingEntry(SynchronizationTestSimulator.java:140)

  Test simulateEntryChangeConflicts() FAILED

  org.opentest4j.AssertionFailedError: expected: not <null>
      at org.jabref.logic.shared.SynchronizationTestSimulator.simulateEntryChangeConflicts(SynchronizationTestSimulator.java:165)

```

To execute the tests locally you need to setup a shared SQL Databse, PostgresSQL 
The postgresSQL must run on localhost with the following setup:
DBname: postgres
User: postgres
Pasword: postgres

Alternatively change the values in the class `TestConnector`, method  `DBMSConnectionProperties getTestConnectionProperties()`

**Comment by Siedlerchr** [comment]
I digged a bit into this.
The problem occurs here. Somehow the SharedEntryNotPresent should have been filled.
It's only posted  in the `removeNotSharedEntries` from synchronizeLocalDatabase 
Maybe there is some timing/call order issue

```
 // client B tries to update the entry
        BibEntry bibEntryOfClientB = clientContextB.getDatabase().getEntries().get(0);
        bibEntryOfClientB.setField(StandardField.YEAR, "2009");

        // here a new SharedEntryNotPresentEvent has been thrown. In this case the user B would get an pop-up window.
        assertNotNull(eventListenerB.getSharedEntriesNotPresentEvent());
        assertEquals(List.of(bibEntryOfClientB), eventListenerB.getSharedEntriesNotPresentEvent().getBibEntries());
```

**Comment by Siedlerchr** [comment]
Okay, I think I found the underlying issue: 
1. A FieldChangedEvent is triggered due to 
`bibEntryOfClientB.setField(StandardField.YEAR, "2009"); `
2. The FieldChangeEvent calculates the delta
https://github.com/JabRef/jabref/blob/a0ca87530991900db5b34df3683aa010dffe97c8/src/main/java/org/jabref/model/entry/event/FieldChangedEvent.java#L61-L70

3. Delta is 0 because the length of the field is the same when it gets replaced.
4.  The property filteredOut is set to true 
https://github.com/JabRef/jabref/blob/a0ca87530991900db5b34df3683aa010dffe97c8/src/main/java/org/jabref/logic/util/CoarseChangeFilter.java#L43-L57
5.  No DB synchro is triggered 
https://github.com/JabRef/jabref/blob/a0ca87530991900db5b34df3683aa010dffe97c8/src/main/java/org/jabref/logic/shared/DBMSSynchronizer.java#L98-L100

**Solution**: The idea would be to check if when the lenghts is the same then check if the content differs.
@koppor  FYI
