### ISSUE TITLE
NPE when closing JabRef with new unsaved database

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#687]
Create a new database, possibly add some entries. Close JabRef with the tab active and ignore saving it.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.prefs.AbstractPreferences.put(Unknown Source)
	at net.sf.jabref.JabRefPreferences.put(JabRefPreferences.java:915)
	at net.sf.jabref.logic.preferences.LastFocusedTabPreferences.setLastFocusedTab(LastFocusedTabPreferences.java:39)
	at net.sf.jabref.gui.JabRefFrame.tearDownJabRef(JabRefFrame.java:799)
	at net.sf.jabref.gui.JabRefFrame.quit(JabRefFrame.java:899)
```

should be quite easy to fix. The main problem is what should happen? Should one just reset the last focused tab preference or leave it as is (which doesn't make sense as one might have closed that tab).

**Comment by simonharrer** [comment]
I would say reset the setting.
