### ISSUE TITLE
Problems setting checkstyle file

### ISSUE THREAD

**Issue by PremKolar** [JabRef/jabref#6870]
Hi,
I'm not sure whether this is a bug, my incompetence or a problem of idea or of the checkstyle plugin.
When I try to add the checkstyle configuration file as described in the manual, I get the following error message:

`com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'InvalidJavadocPosition' class, it is also not possible to instantiate it as .InvalidJavadocPosition, InvalidJavadocPositionCheck, .InvalidJavadocPositionCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:463)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'InvalidJavadocPosition' class, it is also not possible to instantiate it as .InvalidJavadocPosition, InvalidJavadocPositionCheck, .InvalidJavadocPositionCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:210)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:152)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:458)
	... 7 more
`

**Comment by Sylvan1985** [comment]
Hi PremKolar,
I think that due to the version of your Checkstyle.
![image](https://user-images.githubusercontent.com/52154597/99158591-9a8d5880-2691-11eb-98e4-482c0cf9f3b9.png)
For the version 8.37 I'm using, this problem doesn't appear. I hope that helps.

**Comment by PremKolar** [comment]
Thanks I'll try later

**Comment by Siedlerchr** [comment]
I close this issue, please reopen if it persists
