### ISSUE TITLE
Answering with updated authorizations to Mr. DLib. gives a uncaught exception in Thread[...]

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6896]
JabRef 5.2--2020-09-07--aa14db9
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Answering with updated authorizations to Mr. DLib. gives a uncaught exception in Thread[...]

1. Go to the related articles tab (on a thesis entry).
2. Today Mr. DLib asks to update authorizations for sharing information. Checked the remaining fields from language to the end.
3. As soon as I push the provided button (don't remember the label, but it is the only one on this page)
the following exception appears (stack trace below):

![image](https://user-images.githubusercontent.com/865866/92602727-d2051080-f2ae-11ea-9a5f-96992d7ca86a.png)

4. In the meantime the "related articles" tab appears with the suggestions as nothing happened.

```
java.lang.IllegalStateException: Called endChange before beginChange
	at org.jabref.merged.module@5.2.72/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.2.72/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.ObservableListWrapper.access$200(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.MapListenerHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.ObservableMapWrapper.callObservers(Unknown Source)
	at org.jabref.merged.module@5.2.72/com.sun.javafx.collections.ObservableMapWrapper.put(Unknown Source)
	at org.jabref@5.2.72/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.2.72/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.2.72/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.lambda$cleanup$1(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.2.72/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.cleanup(Unknown Source)
	at org.jabref@5.2.72/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at org.jabref@5.2.72/org.jabref.logic.importer.ImportCleanup.lambda$doPostCleanup$0(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by crystalfp** [comment]
Just FYI, seems solved in JabRef 5.3--2021-02-15--edcd711
Windows 10 10.0 amd64 
Java 14.0.2 
JavaFX 15.0.1+1
