### ISSUE TITLE
drag file on entry generates exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6902]
JabRef 5.2--2020-09-08--6dec174
Linux 5.8.7-200.fc32.x86_64 amd64 
Java 14.0.2

I have dragged an entry from Nautilus on an entry in the entry table and got the exception. The file got well linked to the entry.
<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException
	at org.jabref.merged.module@5.2.77/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.77/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.77/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
This should be fixed in the latest master with the new javafx version
