### ISSUE TITLE
Jabref 5.1 can't connect to libre office

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#6905]
Hello,
I have a Ubuntu 20.04 with 
-openjdk 11
- libreoffice 7 (snap) 
  -with jre support 
  - with an open writer document
- the recent jabref 5.1.

I can't connect to libreoffice. The libreoffice plugin shows the following error message.

In the past the was some trouble about snap. But the held page of JabRef does not state anything about it, so I suppose the problem is somewhere else.

I would appreciate any help.

org.jabref.gui.openoffice.NoDocumentException: No Writer documents found
	at org.jabref@5.1.60000/org.jabref.gui.openoffice.OOBibBase.selectDocument(Unknown Source)
	at org.jabref@5.1.60000/org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$2(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Siedlerchr** [comment]
Just to clarify, do you have an open writer document before connecting?
You need to open a new/existing writer document before connecting from JabRef

**Comment by teertinker** [comment]
Writer document is opened. 
May be of further interest: LibreOffice shows /snap/libreoffice/191/usr.... as path for the JRE

unoil.jar is located in the following paths:
/snap/libreoffice/191/lib/libreoffice/program/classes/unoil.jar
/usr/lib/libreoffice/program/classes/unoil.jar
/usr/share/java/unoil.jar

I did also try to connect manually to "/snap/libreoffice/191/lib/libreoffice/program/" but it didn't work either

**Comment by Siedlerchr** [comment]
Snaps are sandboxed and can't be acessed from other applications. You have to use the non snap version of LIbreOffice.
@LyzardKing  can say more about this

**Comment by LyzardKing** [comment]
The snap cannot run other applications (not included in the snap)
Also, the jabref snap would need access to the necessary files in the libreoffice directory.
The non snap jabref should be able read the snap libreoffice, but I'm not sure how it works.
@Siedlerchr What is the connection like in the libreoffice cite function?

**Comment by Siedlerchr** [comment]
The general process is as follow:
JabRef searches autoamtically the typical /or the provided path for the required uno jars. 
Then the LO-UNO Bridge is instanitated 
Finally JabRef connects to the running process (Inteprocess communcation)

For LibreOffice versions < 7 we needed a workaround because of the java module path stuff etc. I have not yet tested the general connection to LO 7. We use the SDK from 6.4 
and had to use a socket for initiating a connection. We copied and modified the boostrap method which does all the magic to use a socket instead of a pipe.
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/gui/openoffice/Bootstrap.java#L293-L317

**Comment by LyzardKing** [comment]
If we opt for using the libreoffice snap the only way to make this work would be to have libreoffice expose a content interface(https://snapcraft.io/docs/content-interface) and connect to that. Then the communication via socket should work.
If we stick with the libreoffice non snap (and non flatpak I believe) version the only solution seems to be to set the jabref snap to classic mode, so it has full access to the host system (like a deb would).
This way it would be possible to connect with other classic snaps and "normal" packages

**Comment by teertinker** [comment]
Hello I don't understand much, but just in case it is useful: I installed jabref downloading the deb file.

**Comment by LyzardKing** [comment]
Ok, so in your case the issue is that the libreoffice snap cannot be accessed from the host.
So jabref might be able to read the .jar files, but not to communicate with libreoffice.
Mostly this is an issue to raise with the libreoffice project.

**Comment by teertinker** [comment]
I suppose the issue does affect multiple users, because snap is now the common format for ubuntu. If it can't be resolved, the help page should describe the problem accordingly.

**Comment by LyzardKing** [comment]
Yes, it should. I'm testing the various combinations to describe clearly which integrations work with the different install methods.
Just to be sure, you're using the snap for libreoffice, right? Not Jabref?

**Comment by teertinker** [comment]
Yes: Jabref deb and LO snap (Version 7.0)
