### ISSUE TITLE
JabRef doesn't start, "IOException reading next record"

### ISSUE THREAD

**Issue by BartLH** [JabRef/jabref#6917]
JabRef version 5.1.60000 and 5.2.78 on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Try to open JabRef by running JabRef.exe or runtime\bin\JabRef.bat

Result: JabRef crashes before it even opens.

<details>
  <summary>Console output</summary>
  
  ```
C:\Program Files\JabRef>runtime\bin\JabRef.bat
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalList(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.applyPreferences(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
        at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.Lexer.nextToken(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.CSVParser.nextRecord(Unknown Source) ~[org.jabref.merged.module:?]
        ... 18 more
  ```
</details>

**Comment by BartLH** [comment]
No one has any idea?

For now I've installed 4.3.1 again which works, but I'd like to be able to use the latest stable(?) update.

**Comment by Siedlerchr** [comment]
This seems to a problem with reading the journal abbreviations
 Does this still happen in the latest development version? I recently fixed an issue related to hat.

**Comment by BartLH** [comment]
Thanks, I've tried the latest dev version (5.2.89) again to see if that fixed it, but the error is the same.

<details>
<summary>Console output</summary>

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalList(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.applyPreferences(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
        at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.Lexer.nextToken(Unknown Source) ~[org.jabref.merged.module:?]
        at org.apache.commons.csv.CSVParser.nextRecord(Unknown Source) ~[org.jabref.merged.module:?]
        ... 18 more
```
</details>

**Comment by BartLH** [comment]
Bump. Feedback was given over two weeks ago, but the tag is still 'waiting-for-customer-feedback'.

**Comment by Siedlerchr** [comment]
Sorry for the delay. It's related to the journal abbreviations .have you tried to reset your preferences? 
Just start JabRef from the commandline and add the switch -d all as argument

**Comment by BartLH** [comment]
Cool, that fixed it. Thanks!
However, I used a clean portable version for testing. Does that mean that the portable version somehow reads the preferences of the specific machine it's being run on?

**Comment by Siedlerchr** [comment]
@BartLH  Yep, it acesses the preferences (on Windows the registry) as well. The portable and installer version aren't really different,  the installer only installs it to the program files, creates start menu and registers its uninstaller as well
