### ISSUE TITLE
Uncaught Exception occurred in Thread

### ISSUE THREAD

**Issue by jonathan-g** [JabRef/jabref#6921]
JabRef version JabRef 5.2--2020-09-09--46e9fe2 Windows 10 10.0 amd64 Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Frequently, JabRef (both the current release and the development version) pop up dialog boxes reporting "Uncaught exception occurred in Thread[pool-7-thread-1,5,main]" with the note "Not on FX application thread; currentThread = pool-7-thread-1"

I have uninstalled JabRef and verified that the directory C:\Program Files\JabRef is gone, then rebooted and done a fresh install and the problem persists.

When I view the event log from the Help menu, the event log is empty.

<details>
  <summary>Details from Uncaught Exception dialog box</summary>
  
  ```
java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-7-thread-1
	at org.jabref.merged.module@5.2.78/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.control.Labeled.setText(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.2.78/javafx.scene.control.Tab.setText(Unknown Source)
	at org.jabref@5.2.78/org.jabref.gui.JabRefFrame.updateAllTabTitles(Unknown Source)
	at org.jabref@5.2.78/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.2.78/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.2.78/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.2.78/org.jabref.gui.dialogs.AutosaveUiManager.listen(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.2.78/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.2.78/org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

**Comment by Siedlerchr** [comment]
The problem is coming from the autosave manager.  You could try to disable autosaving in the preferences
I am working on a fix in #6694 which should also fix that.

**Comment by jonathan-g** [comment]
Thank you. I have turned off autosave. I will report back on whether this resolves the problem.

**Comment by jonathan-g** [comment]
This error has stopped. I'm closing the issue.
