### ISSUE TITLE
NPE in groups panel opening 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7114]
@Siedlerchr I still have the issue with the group panel with the version
JabRef 5.2--2020-11-21--6f35c36
Linux 4.19.0-12-amd64 amd64 
Java 15.0.1

Some details: 
With the group panel initially closed,
- if no file is opened on startup, the group panel opens and closes fine.
- if a file (like https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib) is already opened at startup, opening the group panel raises an exception:

Uncaught exception occurred in Thread[JavaFx Application Thread,5,main]
Cannot load org.jabref.gui.groups.grouptree
java.lang.IllegalStateException: Cannot load org.jabref.gui.groups.grouptree
	at org.jabref.merged.module@5.2.288/com.airhacks.afterburner.views.ViewLoader.load(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupSidePane.createContentPane(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneComponent.getContentPane(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePane.setComponents(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.updateView(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.show(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.toggle(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneComponent$ToggleCommand.execute(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.2.288/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.288/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/org.jabref/org/jabref/gui/groups/GroupTree.fxml

	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.load(Unknown Source)
	... 52 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 55 more
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TreeItem.getValue()" because "<parameter1>" is null
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.lambda$initialize$0(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.initialize(Unknown Source)
	... 65 more

_Originally posted by @mlep in https://github.com/JabRef/jabref/issues/7105#issuecomment-731626000_

**Comment by Siedlerchr** [comment]
@mlep can you send us the bib file? (developers@jabref.org)

**Comment by mlep** [comment]
Well, the bib file is in JabRef repository! ;-)
https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib

**Comment by calixtus** [comment]
already found a solution, bug was introduced #7014 
Fix incoming

**Comment by mlep** [comment]
@calixtus Ohhh, that was fast!

**Comment by calixtus** [comment]
I just encountered this problem while refactoring some code. It was pure coincidence. 😄

**Comment by Siedlerchr** [comment]
And it should be fixed now

**Comment by mlep** [comment]
Indeed, I can confirm this issue is fixed in JabRef 5.2--2020-11-21--b0af521
Linux 4.19.0-12-amd64 amd64 
Java 15.0.1

Thanks!
