### ISSUE TITLE
Exception upon copy (org.jabref.preferences.PreferencesService.getFieldWriterPreferences())

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7200]
JabRef 5.2--2020-12-14--e9be339
Linux 5.9.13-200.fc33.x86_64 amd64 
Java 15.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. select entry
2. press `CTRL+C` to copy / alternatively, use context menu to copy

The entry is not copied - cannot paste it anywhere. 
However, copying the raw bibtex code works.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException: Cannot invoke "org.jabref.preferences.PreferencesService.getFieldWriterPreferences()" because "this.preferencesService" is null
	at org.jabref@5.2.343/org.jabref.gui.ClipBoardManager.setContent(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.maintable.MainTable.copy(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.LibraryTab.copy(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.edit.EditAction.lambda$execute$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.edit.EditAction.execute(Unknown Source)
	at org.jabref@5.2.343/org.jabref.gui.maintable.MainTable.lambda$setupKeyBindings$11(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.343/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
Encountered this issue as well. Reason is that at when Globals.ClipboardManager gets initialized in Globals before the JabRefPreferences are initialized.
