### ISSUE TITLE
"About JabRef" results in exception

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#7287]
JabRef 5.3--2021-01-04--10180ed
Windows 10 10.0 amd64 
Java 14.0.2

Using `Help` -> `About JabRef` results in an exception. Note, that this does not happen the first time you click on `About JabRef`. But the second time you attempt you click on `About JabRef` (and every consecutive attempt) results in an exception. The following error message appears:

`Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]`

The exception stacktrace is:
```

java.lang.IllegalStateException: Cannot set owner once stage has been set visible
	at org.jabref.merged.module@5.3.28/javafx.stage.Stage.initOwner(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.control.HeavyweightDialog.initOwner(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.control.Dialog.initOwner(Unknown Source)
	at org.jabref@5.3.28/org.jabref.gui.JabRefDialogService.showCustomDialog(Unknown Source)
	at org.jabref@5.3.28/org.jabref.gui.help.AboutAction.execute(Unknown Source)
	at org.jabref@5.3.28/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.3.28/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.28/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.3.28/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.28/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Only by closing JabRef and re-opening it you can get rid of the error message and associated exception. But again, this is only the case for the first time you click on `About JabRef`. The second time the exception will appear again.

**Comment by Siedlerchr** [comment]
We now also have the weird behaviour that you can open some dialogs multiple times

**Comment by AEgit** [comment]
Note, that this bug must have been introduced in the last 18 days or so. I tried an earlier developer version 18 days ago (see https://github.com/JabRef/jabref/issues/5522#issuecomment-747538385), where I did not encounter this bug (at least I do not remember having seen it).

**Comment by koppor** [comment]
Should work again in the latest build (appearing in ca. 10 minutes)

**Comment by AEgit** [comment]
JabRef 5.3--2021-01-04--eca13dd
Windows 10 10.0 amd64 
Java 14.0.2

I can confirm this has been fixed in the current developer version. Well done!
