### ISSUE TITLE
Uncaught exception when searching in dark mode

### ISSUE THREAD

**Issue by KWaniova** [JabRef/jabref#7343]
JabRef version 5.2 on Windows 10, Ubuntu 20.04.1, Mac OS Catalina 10.15.7

1. Set JabRef to dark mode.
2. Create new empty library.
3. In web search input on the left side enter covid and click search button.
4. Click on Select all new entries.
5. Click on import entries button.

![JAB-200](https://user-images.githubusercontent.com/61587204/104620081-df803c00-568e-11eb-8eb8-76877de87dda.JPG)
  
![JAB-200 error no 2](https://user-images.githubusercontent.com/61587204/104620073-dd1de200-568e-11eb-9dd2-8f33f3809aeb.JPG)

**Comment by Siedlerchr** [comment]
Can you pleae expand the details of the first exception and paste the details here?

**Comment by KWaniova** [comment]
Sure

I tried it on the newest version of JabRef 5.3 and this is what happend

![exception](https://user-images.githubusercontent.com/61587204/104821609-683cda80-583d-11eb-9696-4eec48778427.jpg)

these are details of expanded exception

`java.lang.NullPointerException
	at org.jabref.merged.module@5.3.75/javafx.collections.ListChangeBuilder.findSubChange(Unknown Source)
	at org.jabref.merged.module@5.3.75/javafx.collections.ListChangeBuilder.insertUpdate(Unknown Source)
	at org.jabref.merged.module@5.3.75/javafx.collections.ListChangeBuilder.nextUpdate(Unknown Source)
	at org.jabref.merged.module@5.3.75/javafx.collections.ObservableListBase.nextUpdate(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.ObservableListWrapper.access$100(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.MapListenerHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.ObservableMapWrapper.callObservers(Unknown Source)
	at org.jabref.merged.module@5.3.75/com.sun.javafx.collections.ObservableMapWrapper.remove(Unknown Source)
	at org.jabref@5.3.75/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.3.75/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.3.75/org.jabref.logic.cleanup.ConvertToBibtexCleanup.lambda$cleanup$2(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.75/org.jabref.logic.cleanup.ConvertToBibtexCleanup.cleanup(Unknown Source)
	at org.jabref@5.3.75/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at org.jabref@5.3.75/org.jabref.logic.importer.ImportCleanup.lambda$doPostCleanup$0(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`

**Comment by calixtus** [comment]
Devcall: We are wondering, if this is really a dark mode issue, since there were no traces of this in the StackTrace. Maybe a threading issue? We are looking into it.

**Comment by Fifi-wang** [comment]
I have reproduced this bug and I think it is not related to dark mode. I'm interested in this bug.

**Comment by Siedlerchr** [comment]
Thanks to @Fifi-wang  the issue is now resolved.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
