### ISSUE TITLE
Linux JabRef does not start at all

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7367]
I am using 
jabref-5.3.85-1.x86_64, downloaded morning of 19th Jan GMT with bellsoft-java15.x86_64 on Fedora 33.

JabRef does not start.

Happy to provide details if you tell me which commands to run in the shell ;)

**Comment by ilippert** [comment]
@systemoperator sorry to bother, does the latest master run on your Linux machine?

**Comment by Siedlerchr** [comment]
Can you try to start it from the script under runtime/bin/JabRef ?

**Comment by ilippert** [comment]
I get this result

<details>
  <summary>Log File</summary>
  
  ```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: key
	at com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey(Unknown Source) ~[org.jabref.merged.module:?]
	at org.jabref.gui.Globals.startTelemetryClient(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.Globals.startBackgroundTasks(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

  ```
</details>

**Comment by Siedlerchr** [comment]
Hm, this is odd. Seems like somehow the data from our build info are not passed down... As far as I know, nothing to that has changed.  I will try something and prepare a new branch build.

**Comment by sambo57u** [comment]
I just tried this on the same configuration and it worked.  I put an alias in /etc/bashrc

alias jabref="/opt/jabref/bin/JabRef 2>/dev/null"

after this open a new window and it should work. The logger errors are always there. This is using the rpm version of Jabref
5.3.85

**Comment by systemoperator** [comment]
@ilippert I can confirm your stated issue with your mentioned master build on Ubuntu 16.04, using OpenJDK 15.

The problem is that `Globals.BUILD_INFO.azureInstrumentationKey` is empty (""), which throws an exception in `com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey()` when called in 

https://github.com/JabRef/jabref/blob/ee2e2dba313c070c491ad75f545536d870743231/src/main/java/org/jabref/gui/Globals.java#L122

because it requires that the key is non-empty and non-`null`.

Forcing a non-empty value for testing purposes starts the application properly.

**Comment by Siedlerchr** [comment]
The build info key should be set by the CI and gradle
Hmm, as far as I know nobody changed it (at least I guess).

**Comment by ilippert** [comment]
Hi @sambo57u with the proposed alias I get this result


<details>
  <summary>Log File</summary>
  
  ```
jabref 
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: key
	at com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey(Unknown Source) ~[org.jabref.merged.module:?]
	at org.jabref.gui.Globals.startTelemetryClient(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.Globals.startBackgroundTasks(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

  ```
</details>

**Comment by sambo57u** [comment]
Hmmm.....why do you say bellsoft java? jabref has its own java...perhaps some path is set that interferes with it. I only have openjdk java's from Fedora repository. You get a bunch of logger messages but jabref starts.

**Comment by ilippert** [comment]
> Hmmm.....why do you say bellsoft java? jabref has its own java...perhaps some path is set that interferes with it. I only have openjdk java's from Fedora repository. You get a bunch of logger messages but jabref starts.

Since https://github.com/JabRef/jabref/issues/6559 I have been only working with bellsoft.

**Comment by Siedlerchr** [comment]
The java version doesn't matter. JabRef ships with a custom runtime. Can you try to add the `-d all` commandline parameter when starting? Maybye your prefs are corrupt

**Comment by ilippert** [comment]
this gets me


<details>
  <summary>Log File</summary>
  
  ```
# alias jabref="/opt/jabref/bin/JabRef -d all 2>/dev/null"
# jabref 
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: key
	at com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey(Unknown Source) ~[org.jabref.merged.module:?]
	at org.jabref.gui.Globals.startTelemetryClient(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.Globals.startBackgroundTasks(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

  ```
</details>

**Comment by wujastyk** [comment]
same problem here.

**Comment by Siedlerchr** [comment]
Can you test the version from here https://builds.jabref.org/pull/7371/merge/  ?

**Comment by koppor** [comment]
It could be too late here, but I hink, the solution is simple. I do not find the setting `AzureInstrumentationKey` (read by gradle), `APPLICATION_INSIGHTS_IKEY` (read by the code), or `APPINSIGHTS_INSTRUMENTATIONKEY` (read by the code) in our build secrets (https://github.com/JabRef/jabref/settings/secrets/actions accessible for maintainers only).

The workround is to set the environment variable `APPINSIGHTS_INSTRUMENTATIONKEY` to `x` (or any other string).

**Comment by sambo57u** [comment]
This is very puzzling. Why is mine working. I am on Fedora 33 x86_64 too and have done nothing special.

**Comment by ilippert** [comment]
> Can you test the version from here https://builds.jabref.org/pull/7371/merge/ ?

The link directed me to the master. 

it still gives me the result 


<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>
#  jabref 
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: key
	at com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey(Unknown Source) ~[org.jabref.merged.module:?]
	at org.jabref.gui.Globals.startTelemetryClient(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.Globals.startBackgroundTasks(Unknown Source) ~[org.jabref:?]
	at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Siedlerchr** [comment]
Can you please try again with the latest master? Newest build contains a workaround

**Comment by ilippert** [comment]
JabRef 5.3--2021-01-21--1be95fc
Linux 5.10.7-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1

works!
thanks!

**Comment by wujastyk** [comment]
JabRef 5.3--2021-01-21--94f4c1e
Linux 5.4.0-62-generic amd64 
Java 15.0.1 
JavaFX 15.0.1+1

Also good.  Thank you!

**Comment by koppor** [comment]
Thank you all for the patience 🎉
