### ISSUE TITLE
Non valid number as font size results in an uncaught exception.

### ISSUE THREAD

**Issue by Landi29** [JabRef/jabref#7415]
Latest JabRef version build on Ubuntu 20.04.1 LTS.

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

If you enter a non valid value such as a character to the font size spinner under the appearances tab in the preference dialog and press enter, 2 exception dialogs will appear.
1. Open JabRef.
2. Click on Options
3. Click on Preferences
4. Click on Appearance.
5. In the "size" box, enter a char such as `a`.
6. Press the <kbd>Enter</kbd> key. Two uncaught exception dialogs will appear.
7. Pressing on the preferences dialog after pressing ok to the two exception dialogs, a third exception dialog will appear.

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.NumberFormatException: For input string: "a"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(IntegerStringConverter.java:49)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(IntegerStringConverter.java:35)
	at javafx.controls/javafx.scene.control.Spinner.commitValue(Spinner.java:460)
	at javafx.controls/javafx.scene.control.Spinner.lambda$new$3(Spinner.java:168)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8155)
	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8208)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:4032)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Scene.java:4054)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setFocused(Window.java:674)
	at javafx.graphics/javafx.stage.Window$1.setFocused(Window.java:149)
	at javafx.graphics/com.sun.javafx.stage.WindowHelper.setFocused(WindowHelper.java:112)
	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:64)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:126)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1351)
	at javafx.graphics/com.sun.glass.ui.Window.notifyFocus(Window.java:1330)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
	at javafx.graphics/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
	at javafx.graphics/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:635)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:465)
	at javafx.controls/javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.controls/javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
	at org.jabref@100.0.0/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(JabRefDialogService.java:192)
	at org.jabref@100.0.0/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(FallbackExceptionHandler.java:26)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:832)

  ```
</details>

**Comment by Siedlerchr** [comment]
Interesting, I thought that a Spinner was already restricted to numbers, but turns out it's not https://stackoverflow.com/a/36749659
spinner.getEditor() returns the textfield

**Comment by Landi29** [comment]
I have found a fix where you bind an event handler directly to the `TextField` of the Spinner as returned by `fontSize.getEditor()`. The event handler is called when the <kbd>Enter</kbd> key is pressed. I know however that doing event handling directly on the controls can be a bit problematic, since it is not reusable code. A pull request will follow after I add some comments.

**Comment by Siedlerchr** [comment]
I think I have found a solution based on the TextFormatter the trick is to not return null:
 ```
extFormatter<Integer> formatter = new TextFormatter<>(
                                                               new IntegerStringConverter(),
                                                               9,
                                                               c -> {
                                                                   if (Pattern.matches("\\d*", c.getText())) {
                                                                       return c;
                                                                   }
                                                                   c.setText("0");
                                                                   return c;
                                                               });
        fontSize.getEditor().setTextFormatter(formatter);
```

When you enter a char it will return 0. Returning null results in an exception as well

**Comment by Landi29** [comment]
I will try it and see if it works.

**Comment by koobs** [comment]
Could using ControlsFX (which jabref apparently uses?) Validation [1] library help here?

[1] https://controlsfx.github.io/javadoc/11.0.3/org.controlsfx.controls/org/controlsfx/validation/package-summary.html

**Comment by Siedlerchr** [comment]
@koobs  There is already a validation for that control, but that doesn't prevent the exception
