### ISSUE TITLE
Uncaught exception when pasting if date is formatted as a range like 1950/1955

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#7427]
JabRef 5.3--2021-02-05--93ad499
Linux 5.4.0-65-generic amd64 
Java 15.0.2 
JavaFX 15.0.1+1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Copy an entry containing a date range with '/', like this one:
```
@Book{vela-1930,
  author     = {H. D Velankar},
  date       = {1925/1930},
  location   = {Bombay},
  publisher  = {Royal Asiatic Society, Bombay},
  title      = {Descriptive Catalogue of the Sanskṛta and Prākṛta Manuscripts in the Library of the Bombay Branch of the Royal Asiatic Society},
  eprint     = {ark:/13960/t53g00h0n},
  eprinttype = {ark},
  keywords   = {catalogue},
  note       = {Biswas \#0115},
  volumes    = {4},
}
```
2. Try to paste into a new bibliography
3. Enjoy the following message:

![image](https://user-images.githubusercontent.com/762246/107162529-16313580-6961-11eb-85da-e33e103a07aa.png)

<details>
  <summary>Log File</summary>
  
  ```
 java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 1925
	at java.base/java.time.temporal.TemporalAccessor.get(Unknown Source)
	at org.jabref@5.3.117/org.jabref.model.entry.Date.get(Unknown Source)
	at org.jabref@5.3.117/org.jabref.model.entry.Date.getMonth(Unknown Source)
	at org.jabref@5.3.117/org.jabref.model.entry.BibEntry.genericGetFieldOrAlias(Unknown Source)
	at org.jabref@5.3.117/org.jabref.model.entry.BibEntry.getFieldOrAlias(Unknown Source)
	at org.jabref@5.3.117/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.lambda$cleanup$2(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.117/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.cleanup(Unknown Source)
	at org.jabref@5.3.117/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at org.jabref@5.3.117/org.jabref.logic.importer.ImportCleanup.lambda$doPostCleanup$0(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.jabref@5.3.117/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at org.jabref@5.3.117/org.jabref.gui.maintable.MainTable.paste(Unknown Source)
	at org.jabref@5.3.117/org.jabref.gui.LibraryTab.paste(Unknown Source)
	at org.jabref@5.3.117/org.jabref.gui.edit.EditAction.lambda$execute$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.117/org.jabref.gui.edit.EditAction.execute(Unknown Source)
	at org.jabref@5.3.117/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.3.117/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.117/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.3.117/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.117/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Landi29** [comment]
I am unable to replicate the bug when using both "new entry" and "new entry from plain text". Could you provide a more detailed description and perhaps screenshots?
On a side note, most BibTeX entries use the `year` and `month` tag which works better with most conference and journal templates, along with adding the entry to a database.

**Comment by wujastyk** [comment]
JabRef 5.3--2021-02-15--f26e25b
Linux 5.4.0-65-generic amd64 
Java 15.0.2 
JavaFX 15.0.1+1

I can no longer reproduce this, #7427, on my system.


I've been on Biblatex+biber for years and _date_ is the recommended field for calendar information; _year_ behaves slightly differently and is more limited.

Biblatex manual, p. 27:
> **Year**: The year of publication. This field is a literal field only when given explicitly in
the data (for plain BibTeX compatibility for example). It is however better to use
the date field as this is compatible with plain years too and supports many more
features.

_month_ creates so many problems for me, including error messages from Biber, that I never use it.  

Biblatex manual, p. 23:

> **month** field (literal)
The publication month. This must be an integer, not an ordinal or a string. Don’t
say month={January} but month={1}. The bibliography style converts this to
a language dependent string or ordinal where required. This field is a literal field
only when given explicitly in the data (for plain BibTeX compatibility for example).
It is however better to use the date field as this supports many more features.

**Comment by calixtus** [comment]
@wujastyk Do you consider this issue closed now?

**Comment by wujastyk** [comment]
yes.

**Comment by calixtus** [comment]
Thanks!
