### ISSUE TITLE
Telemetry makes JabRef crash on start

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#7456]
JabRef version: latest master (2021-02-16)

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

JabRef won't run anymore. It quits with this error:
```
%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: key
        at com.microsoft.applicationinsights.TelemetryConfiguration.setInstrumentationKey(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.gui.Globals.startTelemetryClient(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.Globals.startBackgroundTasks(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

1. Run JabRef (in command line to see the error message)

**Comment by calixtus** [comment]
A quick workaround is to reset all the preferences and then to deny telemetry when asked.
The command line option "-d all" should do the trick.
Depending on your OS this means e.g. "JabRef.exe -d all" or "java -jar JabRef.jar -d all".

**Comment by j0hannes** [comment]
I'm using the binary version, which apparently doesn't accept any command line arguments.
I had a quick look into the execution with _strace_ and the exception happens before any config file is touched.

**Comment by Siedlerchr** [comment]
This is odd. We already fixed this. See #7367
Not sure what you mean with binary version, but maybe this thread helps you to locate the JabRef start script https://discourse.jabref.org/t/hidpi-scaling-ignored-in-jabref-5-2/2512

**Comment by j0hannes** [comment]
I can confirm that the version from 2021-02-22, while the one from 2021-02-16 didn't. Something related to that bug must have been fixed in those 6 days.

I'm using the binaries from the portable-linux build.
