### ISSUE TITLE
arraycopy: length -1 is negative

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7466]
JabRef 5.3--2021-02-16--5546141
Linux 5.10.16-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

1. select an entry's bibtex code
2. substitute the complete entry code by another entry code

I did something (not sure what) but then jabref had lots of errors ;)

<details>
  <summary>Log File</summary>
  
  ```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.SortedList.removeFromMapping(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.SortedList.addRemove(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ReadOnlyListPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ReadOnlyListWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ListPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ListPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.scene.control.TabPane$TabPaneSelectionModel.findNearestAvailableTab(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)
	at org.jabref.merged.module@5.3.133/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)
	at org.jabref@5.3.133/org.jabref.gui.JabRefFrame.lambda$removeTab$23(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.133/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.133/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
From the error log it seems you were closing the library tab somehow during/after that

**Comment by Siedlerchr** [comment]
I tested various ways to eventually trigger this error, but cannot reproduce it.

**Comment by ilippert** [comment]
thanks for testing. Ok, let's close this then...
