### ISSUE TITLE
No-GUI mode (--nogui) should not try to use DISPLAY

### ISSUE THREAD

**Issue by bastistician** [JabRef/jabref#7510]
This has already been reported in #3754, but is apparently not fixed.

I can reproduce the failure for JabRef versions 4.0, 4.3.1, 5.0, 5.1, 5.2 and current 5.3--2021-03-09--5855bcf on Ubuntu 16.04 (openjdk version "1.8.0_282", openjfx 8u60-b27-4). It works in old JabRef 3.8.2.

1. Switch to non-graphical TTY1
2. `bin/JabRef -n --version`

 ```
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at org.jabref.merged.module@5.3.170/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.glass.ui.Application.run(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module@5.3.170/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
 ```

**Comment by Siedlerchr** [comment]
As a workaround you could use `xvfb-run --auto-servernum ` We use that for our gui tests here on the Github CI

**Comment by Siedlerchr** [comment]
With the introduction of jabkit and cli this issue is no longer relevant and can be marked as closed I think.
Pleas re open if the issue persists in the latest main version of 6.x
https://builds.jabref.org/main/
