### ISSUE TITLE
Editing "Custom preview style" triggers exception

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#7526]
JabRef version 5.2, 5.3 and 100.0.0 (commit 0dd4de7) on Linuxmint-20.1 and LinuxMint-19.3.

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Go to "Options|Preferences|Entry preview|Customised preview style|Edit"
2. Start typing new format elements into the text box, e.g.: "\begin{doi}, DOI: \doi\end{doi}" after the "...\end{page}",
3. The exception is triggered and pops up a window, disrupting the work:
![Screenshot from 2021-03-13 15-57-01](https://user-images.githubusercontent.com/10668420/111034638-4156eb00-841f-11eb-8f69-d28c453ac23f.png)

The edit still can be completed, but the box pops up sevral times, interfering with the editing process....

**Comment by Siedlerchr** [comment]
I took a quick look and it seems there is a listener on text change triggered and the new layout is set
I think it maybe makes sense to do that when the editor area is left or the user pressed save. 

```
RROR org.jabref.gui.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Backslash parsing error near 'chapter \chapter HTMLChars<BR>chapter'
	at org.jabref.logic.layout.LayoutHelper.parseField(LayoutHelper.java:261) ~[main/:?]
	at org.jabref.logic.layout.LayoutHelper.parse(LayoutHelper.java:220) ~[main/:?]
	at org.jabref.logic.layout.LayoutHelper.getLayoutFromText(LayoutHelper.java:47) ~[main/:?]
	at org.jabref.logic.layout.TextBasedPreviewLayout.setText(TextBasedPreviewLayout.java:39) ~[main/:?]
	at org.jabref.gui.preferences.preview.PreviewTabViewModel.lambda$0(PreviewTabViewModel.java:97) ~[main/:?]
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360) ~[javafx-base-16-mac.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80) ~[javafx-base-16-mac.jar:?]
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104) ~[javafx-base-16-mac.jar:?]
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111) ~[javafx-base-16-mac.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145) ~[javafx-base-16-mac.jar:?]
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50) ~[javafx-base-16-mac.jar:?]
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:71) ~[javafx-base-16-mac.jar:?]
	at org.jabref.gui.preferences.preview.PreviewTab.lambda$15(PreviewTab.java:160) ~[main/:?]
```

**Comment by sauliusg** [comment]
> I think it maybe makes sense to do that when the editor area is left 

I guess this will cause similar problems for users with "focus follows mouse/sloppy" desktop settings (like mine :), and also for "click to focus" users that start editing the text, and then decide to leave temporarily the text box to copy some text from another window for pasting.

What could be done of course is that the template compiler does run in a background and discretely marks the lines with (potential) syntax errors; function similar to IDE GUIs. But this function is not so much necessary and often very annoying; so unless JabRef is destined to become a do-everything-in-the-world IDE, I thing one can safely skip this feature...

> .... or the user pressed save.

To me (as a user) this seems the most natural way. An indication of unsaved changes and a confirmation of "Save/Discard changes" would be also handy when the editor tab is being left ...

**Comment by nlao1** [comment]
Hi, is this still open? I'd like to take it.

**Comment by Mehdi-Ayadi** [comment]
Hi,  so i followed all the steps to recreate the bug and i had no exception window that oppens so i wanted to know if this issue is persistent on all the systems or no ? cause it may be something system related ?
If yes i would like to solve it !

**Comment by calixtus** [comment]
Sorry @Mehdi-Ayadi , but @yinpeiqi already is on this issue, although you are always welcome to team up on this.
Please talk to him if you have a good idea how to solve this issue and please use the linked pull request #7539 to discuss on the idea further.

**Comment by wujastyk** [comment]
JabRef 5.3--2021-04-12--e3094ac
Linux 5.4.0-71-generic amd64 
Java 15.0.2 
JavaFX 16+8

I am seeing an exception when I merely click on a Selected preview style.  I don't have to do any more than that.  No editing or anything.


![image](https://user-images.githubusercontent.com/762246/114590675-4e494300-9c46-11eb-88d1-d50386fc091a.png)



```
java.lang.IndexOutOfBoundsException: 431 not in [0, 260)
	at org.jabref.merged.module@5.3.262/org.reactfx.util.Lists.checkIndex(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.reactfx.util.Lists.checkIndex(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.reactfx.collection.MemoizationListImpl.getIfMemoized(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.flowless.CellListManager.getCellIfPresent(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.flowless.CellPositioner.getCellIfVisible(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.flowless.VirtualFlow.getCellIfVisible(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.richtext.LineNumberFactory.deleteParagraphCheck(Unknown Source)
	at org.jabref.merged.module@5.3.262/org.fxmisc.richtext.LineNumberFactory.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.262/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.262/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.262/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.262/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.262/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by koppor** [comment]
@wujastyk May I ask whether in the jabref event log. Are there any other exceptions there? If not, may I ask whether you clicked on "Customized preview style" or at another style?

![grafik](https://user-images.githubusercontent.com/1366654/123559061-1a3be380-d79a-11eb-8624-5133d3076a17.png)

**Comment by koppor** [comment]
@wujastyk In any case, could you open a separate issue for that? We are working on a fix for the "Edit" functionality, mark that part as fixed, but do not want to lose your input.

**Comment by wujastyk** [comment]
JabRef 5.3--2021-06-22--b6697fe
Linux 5.4.0-77-generic amd64 
Java 16.0.1 
JavaFX 16+8

The error was the same; the event log was empty; no, I didn't use Customized preview style (only):

![image](https://user-images.githubusercontent.com/762246/123562230-9e767280-d76a-11eb-85a6-84fab79b3535.png)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@wujastyk I think it relates to how the `codeArea` is shown/updated. Commenting out https://github.com/JabRef/jabref/blob/9fe76174fcb41ab62dab984ff42e1790d11f44c9/src/main/java/org/jabref/gui/preferences/preview/PreviewTab.java#L155 either makes it harder to trigger or removes it.

I find it easiest to trigger switching between customized preview style quickly using the arrow keys.

If you haven't already done so, would you mind opening up an issue on it? I don't think it relates to any of the other exceptions I have seen.

**Comment by wujastyk** [comment]
will do.
