### ISSUE TITLE
Proxy authentication problem

### ISSUE THREAD

**Issue by panklucznik** [JabRef/jabref#7627]
JabRef 5.3--2021-04-12--e3094ac
Linux 5.10.0-5-amd64 amd64 
Java 15.0.2 
JavaFX 16+8

I use a university proxy to access paywalled scientific journals.
When I try to use it within JabRef, it doesn't authenticate.

Steps to reproduce:

1. Set proxy server, port, username and password
2. Try to download fulltext
3. Download Failed 

java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 407 Proxy Authentication Required"
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jabref@5.3.262/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	at org.jabref@5.3.262/org.jabref.logic.net.URLDownload.asInputStream(Unknown Source)
	at org.jabref@5.3.262/org.jabref.gui.externalfiles.FileDownloadTask.call(Unknown Source)
	at org.jabref@5.3.262/org.jabref.gui.externalfiles.FileDownloadTask.call(Unknown Source)
	at org.jabref@5.3.262/org.jabref.gui.util.BackgroundTask$3.call(Unknown Source)
	at org.jabref@5.3.262/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.3.262/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Ryyyc** [comment]
Hello, can you successfully test the Check connection in the preferences?

**Comment by panklucznik** [comment]
Hi, thanks for the reply. No, I cannot, but it doesn't produce output other than the short message that connection failed.

**Comment by Ryyyc** [comment]
I am having difficulties with the proxy test that requires certification, can I contact you for some help?

**Comment by panklucznik** [comment]
I am very sorry for the delay. Of course, how can we contact directly?

**Comment by Ryyyc** [comment]
> I am very sorry for the delay. Of course, how can we contact directly?

I am glad to get your help, contact me via my email ruanyc@mail.sustech.edu.cn.

**Comment by mlep** [comment]
Same issue with: 
JabRef 5.4--2021-09-13--fbfa35b
Linux 4.19.0-17-amd64 amd64 
Java 16.0.2 
JavaFX 17+18

In the preferences, `Check connection` works, but `Help -> Check for updates` leads to an exception window with the following stack trace:

java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.util.Version.getAllAvailableVersions(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.help.VersionWorker.getNewVersion(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.4.208/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Siedlerchr** [comment]
Related https://stackoverflow.com/a/41806109/3450689

**Comment by blacky-i** [comment]
Had the same issue. My workaround is to patch `/opt/jabref/lib/app/JabRef.cfg` file and and to section `[JavaOptions]` two lines:
```
java-options=-Djdk.http.auth.tunneling.disabledSchemes=""
java-options=-Djdk.http.auth.proxying.disabledSchemes=""
```

And proxy settings starts to work.

I think same file can be found in Windows and Mac.
