### ISSUE TITLE
DOI link: opens in preview and causes an exception

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7706]
JabRef 5.3--2021-05-05--a3f093d
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

When clicking on the DOI link displayed in the preview panel, the webpage is displayed in the preview (which is unexpected), and barely unusable (because it is very small), and then an exception is raised.

1. Open the file jabref-authors.bib (https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib)
2. Double-click on the entry Afzal et al. (for example). The entry editor opens.
3. In the preview panel, click on the DOI

Note: the exception is surely a bug. But is the display of the website in the preview panel a new feature? If so, how to get the previous behaviour back? (i.e. opening links in the regular web browser)

<details>
  <summary>Uncaught exception details</summary>
  
  ```
netscape.javascript.JSException: ReferenceError: Can't find variable: Mark
	at org.jabref.merged.module@5.3.307/com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.WebPage.executeScript(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.scene.web.WebEngine.executeScript(Unknown Source)
	at org.jabref@5.3.307/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(Unknown Source)
	at org.jabref@5.3.307/org.jabref.gui.preview.PreviewViewer.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.scene.web.WebEngine$LoadWorker.updateState(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.WebPage.fireLoadEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.WebPage.fwkFireLoadEvent(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.network.URLLoaderBase.twkDidFinishLoading(Native Method)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.network.HTTP2Loader.notifyDidFinishLoading(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.webkit.network.HTTP2Loader.lambda$callBackIfNotCanceled$10(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
Hi do you use one of the CSL styles or the custom jabref style? If the latter one, can you paste it? By default it's not displayed for me in the preview

**Comment by mlep** [comment]
Indeed, I have a customize preview style. Here it is:
````
<font face="sans-serif"><b><i>\bibtextype</i><a name="\citationkey">\begin{citationkey} (\citationkey)</a>\end{citationkey}</b><br>
\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\author}\end{author} \begin{editor} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\editor} <i>(\format[IfPlural(Eds.,Ed.)]{\editor})</i>\end{editor}
(\begin{year}\year\end{year}).
\begin{title} \format[HTMLChars]{\title}. \end{title}
\begin{chapter} \format[HTMLChars]{\chapter}\end{chapter}
\begin{journal} <em>\format[HTMLChars]{\journal}, </em>\end{journal}
\begin{booktitle} <em>\format[HTMLChars]{\booktitle}, </em>\end{booktitle}
\begin{school} <em>\format[HTMLChars]{\school}, </em>\end{school}
\begin{institution} <em>\format[HTMLChars]{\institution}, </em>\end{institution}
\begin{publisher} <em>\format[HTMLChars]{\publisher}, </em>\end{publisher}
\begin{volume}<i> \volume</i>\end{volume}: \begin{pages}\format[FormatPagesForHTML]{\pages}\end{pages}.
\begin{doi}<a href="\format[DOICheck]{\DOI}">\DOI</a>\end{doi}
</font>
````

Note: in Options -> Preferences, tab Entry preview, **a left-click on the selected style raises an exception** (see below).
Do you want me to open a specific issue?
<details>
  <summary>Details about another uncaught exception details</summary>
java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]
	at org.jabref.merged.module@5.3.307/org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.307/org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.307/org.fxmisc.richtext.LineNumberFactory.insertParagraphCheck(Unknown Source)
	at org.jabref.merged.module@5.3.307/org.fxmisc.richtext.LineNumberFactory.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.307/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
</details>

**Comment by Siedlerchr** [comment]
Seems like it's requires some listener to intercept links and then call the "normal" opening methods.
 https://stackoverflow.com/questions/15555510/javafx-stop-opening-url-in-webview-open-in-browser-instead

**Comment by mlep** [comment]
> Did it open in an external browser before?

A long time ago, indeed, it opened in an external browser.
But for a while, it was not possible to save the custom preview settings, so it was not possible to try it.

Digging in the development releases:
-  the one published on January 21, 2021 did not do anything when clicking on the URL located in the preview.
-  the one published on January 21, 2021 behaves as the current one (display of the webpage in the preview)
