### ISSUE TITLE
The "Aux file" on "Edit group" doesn't support relative sub-directories path

### ISSUE THREAD

**Issue by cfgnunes** [JabRef/jabref#7719]
JabRef version 5.2--2020-12-24--6a2a512
On Ubuntu 20.04.2 - Linux 5.8.0-50-generic amd64 

The "Aux file" on "Edit group" doesn't support relative sub-directories path.

- [X]: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Open the "Edit group" window on groups interface
2. On "Aux file" put the "latex.out/thesis.aux" (there is a "thesis.aux" on "latex.out" directory)
3. Click on "Ok" button.
4. The application raises an exception.

<details>
  <summary>Log File</summary>
  
  ```
java.nio.file.NoSuchFileException: /home/cristiano/.opt/JabRef/bin/latex.out
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.asIOException(Unknown Source)
	at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(Unknown Source)
	at java.base/sun.nio.fs.AbstractPoller.processRequests(Unknown Source)
	at java.base/sun.nio.fs.LinuxWatchService$Poller.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
  ```
</details>

Note: If I put a full path file, it works very well.

**Comment by aloofluo** [comment]
Working on this and I will try to make a pr soon.

**Comment by cfgnunes** [comment]
Thanks, @aloofluo! 💙

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@cfgnunes where is your `.bib` file? Is it in the same directory as `latex.out/`? What is the `.aux` file path relative to?
