### ISSUE TITLE
Exception when pasting an entry with a publication date-range of the form 1910/1917

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#7864]
JabRef version:

JabRef 5.3--2021-06-28--9fe7617
Linux 5.4.0-77-generic amd64 
Java 16.0.1 
JavaFX 16+8

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Created the following entry in one database:
```
@Book{bhat-1917,
  date      = {1910/1917},
  editor    = {Candrakānta Bhaṭṭācārya},
  location  = {Kalikātā},
  publisher = {Satya Press},
  title     = {\dev{suśrutasaṃhitā prathamakhaṇḍam sūtrasthānātmakam\ldots hārāṇacandracakravartikavirāja-viracita-suśrutārthasandīpanabhāṣya-sametam\ldots candrakānta bhaṭṭācāryya-pramukhaiḥ saṃśodhitam} = [The Suśrutasaṃhitā with the Commentary Suśrutārthasandīpanabhāṣya by Hārāṇacandra Cakravarti]},
  note      = {Edition "t" in \cite[IB, 312]{meul-hist}},
  volumes   = {3},
}

```

2. Copied it (right click, copy)
3. Moved to the other database window
4. Right click, paste ... Exception!

![image](https://user-images.githubusercontent.com/762246/124050708-4fce1000-d9d8-11eb-97be-6e739fea4f58.png)

<details>
  <summary>Log File</summary>
  
  ```
  java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 1910
	at java.base/java.time.temporal.TemporalAccessor.get(Unknown Source)
	at org.jabref@5.3.420/org.jabref.model.entry.Date.get(Unknown Source)
	at org.jabref@5.3.420/org.jabref.model.entry.Date.getMonth(Unknown Source)
	at org.jabref@5.3.420/org.jabref.model.entry.BibEntry.genericGetFieldOrAlias(Unknown Source)
	at org.jabref@5.3.420/org.jabref.model.entry.BibEntry.getFieldOrAlias(Unknown Source)
	at org.jabref@5.3.420/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.lambda$cleanup$2(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.420/org.jabref.logic.cleanup.ConvertToBiblatexCleanup.cleanup(Unknown Source)
	at org.jabref@5.3.420/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.3.420/org.jabref.logic.importer.ImportCleanup.doPostCleanup(Unknown Source)
	at org.jabref@5.3.420/org.jabref.gui.maintable.MainTable.paste(Unknown Source)
	at org.jabref@5.3.420/org.jabref.gui.LibraryTab.paste(Unknown Source)
	at org.jabref@5.3.420/org.jabref.gui.edit.EditAction.lambda$execute$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.420/org.jabref.gui.edit.EditAction.execute(Unknown Source)
	at org.jabref@5.3.420/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.3.420/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.420/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
What is the intended meaning of the date? In this case, JabRef tries to interpret it as `Month/Year`.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Oops, I misread.

**Comment by wujastyk** [comment]
It's Biblatex syntax for a range of dates or the two dates of a two-volume MVbook.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@wujastyk, yup, I just saw :P
[The biblatex package 2.3.7 (page 38)](https://ctan.math.illinois.edu/macros/latex/contrib/biblatex/doc/biblatex.pdf) has some more information, and 

https://github.com/JabRef/jabref/blob/be41c40566f202e6c8e9426f623664c6f13b6910/src/main/java/org/jabref/model/entry/Date.java#L22-L34

is likely part of the issue

**Comment by Siedlerchr** [comment]
Refs #2753

**Comment by ThiloteE** [comment]
Might be related to #8902
