### ISSUE TITLE
"Related Articles Tab" always returning "no recommendations for this entry"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#7874]
[Mr. Dlib](https://mr-dlib.org/)'s API is currently down. This powers our "[Related Articles Tab](https://docs.jabref.org/advanced/entryeditor#related-articles-tab)". Thus, this tab always returns "no recommendations for this entry"

![grafik](https://user-images.githubusercontent.com/1366654/124397042-a3f52f00-dd0d-11eb-918c-374fd4c1fc32.png)

For the next release, this needs to be working again.

`Caused by: java.net.ConnectException: Connection timed out: no further information`

<details>
<code>
21:19:33.733 [pool-3-thread-2] WARN  org.jabref.logic.net.URLDownload - Fix SSL exceptions by accepting ALL certificates
21:19:54.779 [JavaFX Application Thread] ERROR org.jabref.gui.entryeditor.RelatedArticlesTab - Error while fetching from Mr. DLib
org.jabref.logic.importer.FetcherException: Problem downloading
	at org.jabref.logic.importer.fetcher.MrDLibFetcher.makeServerRequest(MrDLibFetcher.java:110) ~[classes/:?]
	at org.jabref.logic.importer.fetcher.MrDLibFetcher.performSearch(MrDLibFetcher.java:59) ~[classes/:?]
	at org.jabref.gui.entryeditor.RelatedArticlesTab.lambda$getRelatedArticlesPane$0(RelatedArticlesTab.java:71) ~[classes/:?]
	at org.jabref.gui.entryeditor.RelatedArticlesTab$$Lambda$1859/0x00000000c36c6ff0.call(Unknown Source) ~[?:?]
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:59) ~[classes/:?]
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:160) ~[classes/:?]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425) ~[javafx-graphics-16-win.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:660) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.Socket.connect(Socket.java:648) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1261) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:351) ~[classes/:?]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:237) ~[classes/:?]
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:250) ~[classes/:?]
	at org.jabref.logic.importer.fetcher.MrDLibFetcher.makeServerRequest(MrDLibFetcher.java:103) ~[classes/:?]
	... 12 more
</code>
</details>

CC: @Joeran

**Comment by Siedlerchr** [comment]
See also https://discourse.jabref.org/t/related-article-tab-not-working/2756/3

**Comment by koppor** [comment]
Workaround by https://github.com/JabRef/jabref/issues/7995.

**Comment by Siedlerchr** [comment]
Mr DLIb is back online.
