### ISSUE TITLE
Dark Theme : Search -> Import entries dialog text not readable 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7927]
Latest JabRef version from main.

1. Have Dark Theme enabled 
1. Search for an entry in the web search
2. Import entries window opens
3.  See the color of the abstract text is black 

<img width="974" alt="Bildschirmfoto 2021-07-19 um 21 27 49" src="https://user-images.githubusercontent.com/320228/126221029-b0a0cb75-e002-4f23-977e-db2a29f12975.png">

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Good starting points are,

1. https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Base.css, the default theme, where most of our .css are stored.
2. https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Dark.css, which is where changes most likely should be made.

**Comment by calvinmorett** [comment]
@k3KAW8Pnf7mkmdSMPHz27 is there process I can do to so that I can make a browser-inspectable mock up of this entry section? Specifically, looking to bring it into the browser so I can use the inspect tools, to see what variables are targeted/attached here from the dark.css.

**Comment by Siedlerchr** [comment]
@calvinmorett  Have a look at the sceniv view tool https://github.com/JonathanGiles/scenic-view 
You bascially start JabRef, then scenic view and then you can inspect the gui

**Comment by calvinmorett** [comment]
@Siedlerchr Stuck on the dialog "Scanning for JavaFX application" in scenic view, JabRef never registers. Troubleshooting, any suggestions is certainly appreciated, thanks.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
You might have to check if there is a workaround for Java 16

> Scenic View will detect JavaFX applications running on Java 9, 10 or 11.

There is also https://github.com/JonathanGiles/scenic-view/issues/56

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr do you have any experience with loading `.css` into the [scene-builder](https://gluonhq.com/products/scene-builder/)? (I.e., do you know if it is possible/a good idea)

**Comment by Siedlerchr** [comment]
I got it to work when I start jabref from eclipse, guess because the release version is stripped out of some debug modules or whatever 
<img width="1225" alt="grafik" src="https://user-images.githubusercontent.com/320228/126525212-375bab21-0890-460d-9cb3-0911b63a9db8.png">

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Yup. I have cloned both Scenic View and JabRef and are building them from the Gradle projects in IntelliJ, which also seem to work. Might be overkill.

@calvinmorett how do you run JabRef? (or have you gotten it working through some other means?)

<img width="1280" alt="Skärmavbild 2021-07-21 kl  16 33 55" src="https://user-images.githubusercontent.com/2598631/126556665-5431b2cb-3aa6-484b-b67b-a28f6c872e9f.png">

**Comment by calvinmorett** [comment]
Still troubleshooting,

@k3KAW8Pnf7mkmdSMPHz27 `@calvinmorett how do you run JabRef? (or have you gotten it working through some other means?)`

I just run the application, JabRef.exe. Could this be the reason why scenic-view isn't picking up on it?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
It doesn't pick it up when I run `JabRef.app`, I guess .exe is the same

**Comment by calvinmorett** [comment]
Installed eclipse, will try that next.

**Comment by Siedlerchr** [comment]
./gradlew run should also work. See the devoloper docs how to setup your development environment

**Comment by calvinmorett** [comment]
It's registering 2 java applications, but no JavaFX applications when running scenicview.bat after starting JabRef.exe

```
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 2
Error while obtaining properties for JVM:sun.tools.attach.AttachProviderImpl@186067bb: 12076 org.jabref/org.jabref.gui.JabRefLauncher
java.io.IOException: Access is denied
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.openProcess(Native Method)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(Unknown Source)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(Unknown Source)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(Unknown Source)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.getRunningJavaFXApplications(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.connect(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdateStrategy.getActiveApps(Unknown Source)
        at org.scenicview.scenicview/org.scenicview.model.update.RemoteVMsUpdateStrategy.work(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.helper.WorkerThread.run(Unknown Source)
0 JavaFX applications found
```

**Comment by Siedlerchr** [comment]
@calvinmorett  https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace
I recommend Intellij as the Eclipse formatter has some problems.

You start scenic view from the folder bin\scenivew.bat it already ships with a jdk. 
You probably need to modify the line to:

`pushd %DIR% & %JAVA_EXEC%  -m org.scenicview.scenicview/org.scenicview.ScenicView --add-opens java.base/java.instrument=ALL-UNNAMED %* & popd
`

**Comment by calvinmorett** [comment]
Okay, I haven't installed Intellij yet, but did make the .bat file change that you suggested. That change did seem to register JabRef as a JavaFX application in the log, but still kept showing scanning in the UI in SV.

![image](https://user-images.githubusercontent.com/11654917/126685088-7778da2f-61a1-45ea-8375-73a2941d288d.png)

```
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 2
Obtaining properties for Java application with PID:2780
1 JavaFX applications found
Loading agent from: C:\Users\ideas\Documents\sv\scenicview\lib\scenicview.jar
Loading agent for:sun.tools.attach.AttachProviderImpl@3b8611da: 2780 ID:2780 on port:7559 took:107ms using agent defined in C:\Users\ideas\Documents\sv\scenicview\lib\scenicview.jar
com.sun.tools.attach.AgentLoadException: Failed to load agent library: java.lang.module.FindException: Module java.instrument not found
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.access$200(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl$3.run(Unknown Source)
com.sun.tools.attach.AgentLoadException: Failed to load agent library: java.lang.module.FindException: Module java.instrument not found
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.access$200(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl$3.run(Unknown Source)
com.sun.tools.attach.AgentLoadException: Failed to load agent library: java.lang.module.FindException: Module java.instrument not found
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(Unknown Source)
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.loadAgent(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl.access$200(Unknown Source)
        at org.scenicview.scenicview/org.fxconnector.remote.RemoteConnectorImpl$3.run(Unknown Source)
....
```

**Comment by Siedlerchr** [comment]
Try running JabRef with `./gradlew run ` in the source folder where you cloned the project source code repo.
You need to have jdk16 installed (as noted in the docs)

**Comment by calvinmorett** [comment]
Did `./gradlew run`
it finished executing 
```
18:37:12.370 [pool-4-thread-1] WARN  org.jabref.logic.net.URLDownload - Fix SSL exceptions by accepting ALL ce18:37:41.659 [JavaFX Application Thread] INFO  org.jabref.gui.util.Theme - Enabling live reloading of css file C:\Users\ideas\git\jabref\build\resources\main\org\jabref\gui\Base.css
18:38:04.869 [JavaFX Application Thread] INFO  org.jabref.gui.util.Theme - Enabling live reloading of css file C:\Users\ideas\git\jabref\build\resources\main\org\jabref\gui\Base.css
18:38:14.447 [JavaFX Application Thread] INFO  org.jabref.gui.util.Theme - Enabling live reloading of css file C:\Users\ideas\git\jabref\build\resources\main\org\jabref\gui\Base.css
18:38:14.448 [JavaFX Application Thread] INFO  org.jabref.gui.util.Theme - Enabling live reloading of css file C:\Users\ideas\git\jabref\build\resources\main\org\jabref\gui\Dark.css
18:38:17.033 [JavaFX Application Thread] INFO  org.jabref.gui.JabRefDialogService - Preferences recorded.
<============-> 92% EXECUTING [5m `19s]
``
`
I then tried running scenic view and got 0 applications.
```
Platform running
Launching ScenicView v11.0.2
Startup done
Creating server
Server done
Number of running Java applications found: 0
0 JavaFX applications found
Loading agent from: C:\Users\ideas\Documents\sv\scenicview\lib\scenicview.jar
```

**Comment by calvinmorett** [comment]
While not the fastest approach, I'll just add a new CSS style sheet to pull into JabRef, and go individually through each variable, to identify ambiguously named variables, and to see what variable is being assigned.

![image](https://user-images.githubusercontent.com/11654917/126759789-7e3e7038-bc54-4436-b053-76dfde1a291c.png)

I've found the variable causing the cause of why dark mode search items are difficult to read.  `-fx-light-text-color:` the problems it causes is that it's being used for both non-selected/non-active items in the search results, _while_ also being used for selected items. 

![image](https://user-images.githubusercontent.com/11654917/126759423-db1e5bdf-3d0d-4470-b0a4-21ecabe2c192.png)

As you can see, the orange is the text as the search result item titles, for both selected and non-selected items, as detailed above. 

A solution -- where the text remains the same color in both instances -- could be, to set the background of selected and non-selected items, close in color value, where it still maintains a suitable contrast. 

**@Siedlerchr Please assign me this issue.**

**Comment by Siedlerchr** [comment]
I guess we need to have a different color for active/inactive

**Comment by calvinmorett** [comment]
@Siedlerchr Are you going to set specific classes for the queries results or should we target the current with pseudo classes?

Either way, would it be possible for you to provide the classes?

**Comment by Siedlerchr** [comment]
Maybe @calixtus  has an idea

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Isn't it set by one of the “base” colors? (see the `base.css` file)

I am not sure what you have tried/not but it is likely easier to explore the CSS in that file as it is more complete. (unless you have already tried that)

**Comment by calvinmorett** [comment]
@k3KAW8Pnf7mkmdSMPHz27 current approach was to add a custom stylesheet. The way that worked was I was able to edit most things and see the change in real time to then add comments to what was being affected by the CSS classes I was sort of editing.

I haven't considered until now pulling in all the base.css styles into the custom stylesheet, thanks for the excellent suggestion though it will not help me targeting this specific element without going through each element it contains.

Even after doing just that, I haven't found the CSS style that controls result summary text.

![image](https://user-images.githubusercontent.com/11654917/126918814-f6dee848-08b1-4ebd-87c9-c1a721038218.png)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@calvinmorett not sure if you are still looking at this issue but perhaps these two links are relevant,

1. https://stackoverflow.com/questions/47562036/javafx-textflow-set-default-text-color , in this case, perhaps `TextFlowLimited > Text` is a usable selector (based on Scenic-View and the above link). It can at least set the text to a static color using `-fx-fill`.
2. Based on https://stackoverflow.com/questions/60488426/change-font-color-in-javafx-via-css-file , could it be that the background color doesn't exist/isn't properly propagated? I'd guess that `ladder` (from the JFX CSS) should deal with the different background colors correctly?

Otherwise, perhaps the `:entry-selected` pseudo-class can be "re-used"?

**Comment by victordmp** [comment]
Hi, we are a group of students studying Computer Science at Universidade Tecnologica Federal do Paraná (UTFPR) and we wanted to check if this issue is available for us to work on in our free software discipline task. And if it's available, we'd like to get some valuable input based on previous contributions to this edition.

**Comment by calixtus** [comment]
I believe it's free to work on. Last edit on this this issue is almost a year old.

**Comment by ThiloteE** [comment]
Hello @victordmp :-) Thanks for your interest and your groups intention to work on JabRef.

As a general advice: Check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by sorattorafa** [comment]
@Siedlerchr Please, can u assign this issue to @victordmp ?
