### ISSUE TITLE
Creating Groups fails since JabRef 5.4

### ISSUE THREAD

**Issue by btut** [JabRef/jabref#7930]
JabRef 5.4--2021-07-19--5624b85 on Linux 5.8.0-59-generic amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Click Add group

Adding groups fails with an exception.

<details>
  <summary>16:25:41.532 [JavaFX Application Thread] ERROR org.jabref.gui.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1862) ~[javafx-fxml-16-linux.jar:?]
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1729) ~[javafx-fxml-16-linux.jar:?]
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[javafx-base-16-linux.jar:?]
        at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-16-linux.jar:?]
        at javafx.scene.Node.fireEvent(Node.java:8889) ~[javafx-graphics-16-linux.jar:?]
        at javafx.scene.control.Button.fire(Button.java:203) ~[javafx-controls-16-linux.jar:?]
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208) ~[javafx-controls-16-linux.jar:?]
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274) ~[javafx-controls-16-linux.jar:?]
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[javafx-base-16-linux.jar:?]
        at javafx.event.Event.fireEvent(Event.java:198) ~[javafx-base-16-linux.jar:?]
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3856) ~[javafx-graphics-16-linux.jar:?]
        at javafx.scene.Scene.processMouseEvent(Scene.java:1851) ~[javafx-graphics-16-linux.jar:?]
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299) ~[javafx-graphics-16-linux.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.glass.ui.View.handleMouseEvent(View.java:556) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.glass.ui.View.notifyMouse(View.java:942) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-16-linux.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) ~[javafx-graphics-16-linux.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[javafx-base-16-linux.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[javafx-fxml-16-linux.jar:?]
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1859) ~[javafx-fxml-16-linux.jar:?]
        ... 54 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.EnumSet.contains(Object)" because the return value of "javafx.beans.property.ObjectProperty.getValue()" is null
        at org.jabref.gui.groups.GroupDialogViewModel.lambda$setupValidation$5(GroupDialogViewModel.java:202) ~[JabRef-100.0.0.jar:?]
        at de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$2(FunctionBasedValidator.java:95) ~[mvvmfx-validation-1.9.0-SNAPSHOT.jar:?]
        at de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.validate(FunctionBasedValidator.java:102) ~[mvvmfx-validation-1.9.0-SNAPSHOT.jar:?]
        at de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.<init>(FunctionBasedValidator.java:97) ~[mvvmfx-validation-1.9.0-SNAPSHOT.jar:?]
        at org.jabref.gui.groups.GroupDialogViewModel.setupValidation(GroupDialogViewModel.java:217) ~[JabRef-100.0.0.jar:?]
        at org.jabref.gui.groups.GroupDialogViewModel.<init>(GroupDialogViewModel.java:121) ~[JabRef-100.0.0.jar:?]
        at org.jabref.gui.groups.GroupDialogView.<init>(GroupDialogView.java:74) ~[JabRef-100.0.0.jar:?]
        at org.jabref.gui.groups.GroupTreeViewModel.lambda$addNewSubgroup$7(GroupTreeViewModel.java:153) ~[JabRef-100.0.0.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at org.jabref.gui.groups.GroupTreeViewModel.addNewSubgroup(GroupTreeViewModel.java:152) ~[JabRef-100.0.0.jar:?]
        at org.jabref.gui.groups.GroupTreeViewModel.addNewGroupToRoot(GroupTreeViewModel.java:114) ~[JabRef-100.0.0.jar:?]
        at org.jabref.gui.groups.GroupTreeView.addNewGroup(GroupTreeView.java:401) ~[JabRef-100.0.0.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[javafx-base-16-linux.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[javafx-base-16-linux.jar:?]
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[javafx-fxml-16-linux.jar:?]
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1859) ~[javafx-fxml-16-linux.jar:?]
        ... 54 more
</summary>
  
</details>

**Comment by btut** [comment]
Duplicate of #7912
