### ISSUE TITLE
No start possible: Unsupported JavaFX configuration and amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by xoquon** [JabRef/jabref#7969]
JabRef version 5.4.49 (Snap 1211 (edge)) or 5.3.450 (Snap 1180) on 

- Xubuntu 20.04 with current LTS kernel 5.11.0-25-generic on 
- AMD Ryzen 7 PRO 4750U with Radeon Graphics, 
- 32 GB 3200 Mhz RAM, 
- X.Org 1.20.11 with amdgpu,ati driver.

- [X] I have tested the latest development version from http://builds.jabref.org/main and the problem persists

JabRef was working fine with Kernel 5.8 until upgrade. 

1. Install current JabRef snap with ```sudo snap install jabref ``` or ```sudo snap install jabref  --edge```
2. Run JabRef via Whisker Menu -> No GUI appears, No error message, nothing
3. Run ```jabref``` command in terminal and receive error message.

Error message with --edge version:

```
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/jabref/1211
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Aug. 07, 2021 1:59:21 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #39
  Current Serial #40
  ```
Error message with stable version:

 ```
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/jabref/1180
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Aug. 07, 2021 2:04:17 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #39
  Current Serial #40
 ```
Equal snap /amdgpu problems: https://forum.snapcraft.io/t/problem-with-libdrm-and-amdgpu-pro/9421/21.

libdrm2 and libdrm-amdgpu1 are installed on the system.

Regarding the si_initi_perfcounters: https://forum.manjaro.org/t/si-init-perfcounters-max-sh-per-se-2-not-supported/66656

> After some research i can just basically say that max_sh_per_se = 2 is is not supported by your gpu. So it will not run with this chip. I guess the amdgpu driver runs with max_sh_per_se = 1. No idea what this variable stand for. 

If more information is needed, please let me know.

**Comment by Siedlerchr** [comment]
Seems also to affect Firefox  https://bugzilla.mozilla.org/show_bug.cgi?id=1710326
@LyzardKing in the bug report they see one should only add this, but I don't know exactly how

```
layout:
  /usr/shar/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm
```

**Comment by LyzardKing** [comment]
I can add that to the snap, and then once it is uploaded to the edge channel @xoquon can test it

**Comment by xoquon** [comment]
That would be great. When you have applied the patch, I kindly ask you to reply here so that I can test it immediately!

**Comment by LyzardKing** [comment]
@Siedlerchr I do not have access to the jabref repo any more. Thus I cannot upload the branch with the fix.
I built the snap locally and it works for me, but I do not have an amd gpu

**Comment by LyzardKing** [comment]
I opened a quick PR

**Comment by xoquon** [comment]
Great! The AMD problem was solved with the fix.

Version: jabref (edge) 5.4.184 from Oliver Kopp (koppor)

```
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/jabref/1261
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.versionSanityCheck(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.performInitialization(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getProvider(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getILoggerFactory(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.jabref@5.4.184/org.jabref.gui.JabRefMain.<clinit>(Unknown Source)
	at org.jabref@5.4.184/org.jabref.gui.JabRefLauncher.main(Unknown Source)
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Sept. 11, 2021 3:19:31 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #39
  Current Serial #40

```

The important parts are:

```
Sept. 11, 2021 3:19:31 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #39
  Current Serial #40
```

New in logs:

```
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/jabref/1261
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.versionSanityCheck(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.performInitialization(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getProvider(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getILoggerFactory(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.jabref@5.4.184/org.jabref.gui.JabRefMain.<clinit>(Unknown Source)
	at org.jabref@5.4.184/org.jabref.gui.JabRefLauncher.main(Unknown Source)
```

Same system as above. Cleaned my `snap` and `.config` folder before testing the new snap.

I check the X Error: BadAlloc and somebody came up with a [mesa/video problem](https://stackoverflow.com/questions/15577540/x-error-of-failed-request-badalloc-insufficient-resources-for-operation) or a [wayland related thing](https://bugs.freedesktop.org/show_bug.cgi?id=104351). Currently my system is running X11. (`echo $XDG_SESSION_TYPE`)

Maybe there is a relation to this [issue](https://discourse.jabref.org/t/buttons-in-gui-invisible/2653) (even if its concerns Windows?)

Finally I found this [treasure at Stackoverflow](https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna).

> Technically JavaFX only supports being loaded as named modules. As of version 16 a warning is now emitted if JavaFX ends up in the unnamed module. In other words, JavaFX only supports being loaded from the module-path and does not support being loaded from the class-path. You need to make sure JavaFX is resolved as modules, which can be done in at least one of three ways [...].

Java Version of my machine is:

```
$ java -version
openjdk version "13.0.7" 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

Probably worth pursuing the last idea? In any case, thank you very much for your help!

**Comment by Siedlerchr** [comment]
The warnings can be ignored, we are merging them together with several other libraries (that are not yet modularized) into this merged module that's why it says it's in the wrong module.
And you can also ignore the sfl4j error message. That's not relevant.

Your installed java version is also irrelevant, as JabRef ships with its own.
Just out of curiosity, can you try the portable or the deb version? https://builds.jabref.org/main/ 
I wonder if also throws the badalloc error or a different one. I suspect it has something to do with your graphic card/display driver.

**Comment by xoquon** [comment]
Ah right - I had forgotten for a brief moment that Snaps bring their own environment (which is already a huge advantage for debugging). Thanks for the reminder!

Installing the jabref_5.4-1_amd64.deb file using `apt install` worked great and jabref is now working again (GUI launches).

I just tested my graphics using Unigine_Heaven-4.0 and Unigine_Valley-1.0, glxgears as well as gmark2 and all run fine with OpenGL.

**Comment by Siedlerchr** [comment]
Glad to hear that it's working now! Snaps are usually more restricted in accessing system stuff, so this might cause some side effects.
The deb version also comes with all necessary java libraries and its own custom java jdk environment.

**Comment by LyzardKing** [comment]
There is also the flatpak build, that should work.

**Comment by hhlp** [comment]
Doens't works in flathub too:

5.4                  stable     x86_64       flathub user        org.jabref.jabref/x86_64/stable

``` 
flatpak run org.jabref.jabref/x86_64/stable
Jan 09, 2022 11:58:28 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  147 ()
  Minor opcode of failed request:  7
  Serial number of failed request:  38
  Current serial number in output stream:  39
user: hhlp on 〘FedoraBox〙…/🏠 
```

Regards.,
