### ISSUE TITLE
exception upon importing entries via ISBN

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7971]
JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.7-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

This exception happens repeatedly whilst I am importing entries via the ISBN search.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IndexOutOfBoundsException: [ fromIndex: 4, toIndex: 5, size: 1 ]
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeListener$Change.getAddedSubList(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.callObservers(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.SelectedCellsMap.setAll(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateSelection(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.FilteredList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.MappedBackedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref@5.3.21/org.jabref.gui.util.UiThreadList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.FXCollections$UnmodifiableObservableListImpl.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.FXCollections$SynchronizedObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ObservableListWrapper.access$200(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ObservableMapWrapper.callObservers(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.collections.ObservableMapWrapper.put(Unknown Source)
	at org.jabref@5.3.21/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.3.21/org.jabref.model.entry.BibEntry.setField(Unknown Source)
	at org.jabref@5.3.21/org.jabref.gui.UpdateTimestampListener.listen(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.3.21/org.jabref.model.database.BibDatabase.relayEntryChangeEvent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber$1.run(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.util.concurrent.DirectExecutor.execute(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Subscriber.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.google.common.eventbus.EventBus.post(Unknown Source)
	at org.jabref@5.3.21/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.3.21/org.jabref.model.entry.BibEntry.clearField(Unknown Source)
	at org.jabref@5.3.21/org.jabref.gui.entryeditor.SourceTab.storeSource(Unknown Source)
	at org.jabref@5.3.21/org.jabref.gui.entryeditor.SourceTab.lambda$setupSourceEditor$5(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Node$FocusedProperty.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$12.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$KeyHandler.setFocusOwner(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$KeyHandler.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Node.requestFocus(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.behavior.TabPaneBehavior.lambda$new$10(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
The error could be related to some threading error in combination with Timestamp/Modification Date.
I'm trying to reproduce this but cannot in the latest dev version (5.4..)
Do you have any save formatters enabeld?

**Comment by ilippert** [comment]
Hi, "save formatters", as in "linked file name conventions"? Or what to search for in the Preferences?

**Comment by Siedlerchr** [comment]
Hi, the Save actions in the LIbrary properties at the bottom

**Comment by ilippert** [comment]
Thanks, no save formatters enabled.

**Comment by ThiloteE** [comment]
Does this still happen in newest development version?

Could you provide an example ISBN?

**Comment by ilippert** [comment]
Hi, I have not experienced this issue for a long time. Therefore, and thanks for the reminder, I am closing this issue.
