### ISSUE TITLE
Exception when editing an online file

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#8008]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.4--2021-08-19--05a0ce9 Windows 10 10.0 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select any entry with an online attached file
2. Select the online attached file
3. Right-click and hit Edit
4. Hit Apply

### Appendix

<details>
  <summary>Exception</summary>
  
  ```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://arxiv.org/pdf/2003.09501v1
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at org.jabref@5.4.69/org.jabref.gui.linkedfile.LinkedFilesEditDialogViewModel.getNewLinkedFile(Unknown Source)
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for the report! Should now be fixed in the latest dev version (currently building, ready in roughly half an hour)
