### ISSUE TITLE
Crashes on launch due to missing library libawt_xawt.so

### ISSUE THREAD

**Issue by fpdotmonkey** [JabRef/jabref#8060]
### JabRef version

3.8.2

### Operating system

GNU / Linux

### Details on version and operating system

Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Note that the above check "I have tested the latest development version and the problem persists" is misleading because this issue is related to installation via `apt`, not the function of JabRef itself, so this issue cannot be tested by downloading a development build.

1. `sudo apt install jabref`
2. Attempt to open JabRef with

```
$ jabref 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1312)
	at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
	at net.sf.jabref.JabRefMain.main(JabRefMain.java:40)
```

### Workaround

1. `sudo apt install jabref openjdk-11-jdk`
2. JabRef successfully opens

**Comment by Siedlerchr** [comment]
Sorry to inform you, but 3.8.2 is outdated. We are all working on JabRef in our free time and therefore are unable to maintain any old versions. You can get the newer versions from our Download.

If you are interested in helping to bring 5.x to the Debian repository, feel free to checkout https://github.com/koppor/jabref/blob/about/jabref-in-debian.md
