### ISSUE TITLE
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main] when trying the new tool Start new systematic bibliographic review

### ISSUE THREAD

**Issue by sdamour** [JabRef/jabref#8086]
### JabRef version

5.3 (latest release)

### Operating system

mac OS

### Details on version and operating system

BigSur version 11.5.2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Tools --> Start new systematic literature review
2. Fill in the info requested (Titles, authors, query, database, etc.) and then click Start Survey

Then, exception details error box pop: Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]

### **java.lang.IllegalStateException: Error during creation of repository structure.**
	at org.jabref@5.4.208/org.jabref.logic.crawler.StudyRepository.createBibFile(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.crawler.StudyRepository.createFetcherResultFile(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.crawler.StudyRepository.lambda$setUpRepositoryStructure$0(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.crawler.StudyRepository.setUpRepositoryStructure(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.crawler.StudyRepository.<init>(Unknown Source)
	at org.jabref@5.4.208/org.jabref.logic.crawler.Crawler.<init>(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.slr.ExistingStudySearchAction.crawl(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.slr.StartNewStudyAction.execute(Unknown Source)
	at org.jabref@5.4.208/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.4.208/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.4.208/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.4.208/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.4.208/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(Unknown Source)
### **Caused by: java.nio.file.NoSuchFileException: /Users/sabrinadamour1/Documents/testsjab/-1393435121 - inferior longitudinal fascic OR ILF/Medline/PubMed.bib**
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.createFile(Unknown Source)
	... 32 more

**Comment by Siedlerchr** [comment]
Please try the latest development version https://builds.jabref.org/main/ 
I cannot reproduce this

**Comment by sdamour** [comment]
@Siedlerchr Sorry for the delay, I already tried the latest development version and it changed nothing
