### ISSUE TITLE
cannot open a file with invalid group search expressions

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8087]
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.4--2021-09-17--3d7521c
Linux 5.13.16-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 17+18

1. ... I open JabRef; it starts up with two of my key libraries opened. Good.
2. ... I try to open a specific third library. That generates the exception

Visible effect: opening the third library generates a new tab; but no table is visible. Sometimes the exception is reoccuring in a loop; other times it only shows 2 times, then I can click it away. In the latter case, when I switch to the other libraries, their table  columns are minimised, so I cannot see anything. But I can resize the column widths.

I test it with another third library. No problem.

Ok, so that means I have a library that generates that exception in interaction with JabRef. Happy to share the file confidentially.

### Appendix

...
<details>
<summary>Log File</summary>
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.searchResults" is null
	at org.jabref@5.4.211/org.jabref.model.search.rules.GrammarBasedSearchRule.getFulltextResults(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.rules.GrammarBasedSearchRule.applyRule(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.GroupSearchQuery.isMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.groups.SearchGroup.contains(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.groups.AbstractGroup.isMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.matchers.OrMatcher.lambda$isMatch$0(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.util.ListUtil.anyMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.matchers.OrMatcher.isMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.matchers.OrMatcher.lambda$isMatch$0(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.util.ListUtil.anyMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.search.matchers.OrMatcher.isMatch(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.groups.GroupTreeNode.getMatchingGroups(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.groups.GroupTreeNode.getMatchingGroups(Unknown Source)
	at org.jabref@5.4.211/org.jabref.model.groups.GroupTreeNode.getMatchingGroups(Unknown Source)
	at org.jabref@5.4.211/org.jabref.gui.maintable.BibEntryTableViewModel.lambda$createMatchedGroupsBinding$5(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.jabref@5.4.211/org.jabref.gui.maintable.BibEntryTableViewModel.lambda$createMatchedGroupsBinding$6(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.EasyBind$4.computeValue(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.beans.binding.ObjectBinding.get(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.beans.binding.ObjectExpression.getValue(Unknown Source)
	at org.jabref@5.4.211/org.jabref.gui.util.uithreadaware.UiThreadBinding.getValue(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.TableRowSkinBase.<init>(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.TableRowSkin.<init>(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.TableRow.createDefaultSkin(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.Control.doProcessCSS(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.Control$1.doProcessCSS(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Node.processCSS(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Node.applyCss(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Parent.layout(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.4.211/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.4.211/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(Unknown Source)
	at org.jabref@5.4.211/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.211/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
</details>

**Comment by Siedlerchr** [comment]
Thanks for the exception log, there seems to be something wrong with the search for the groups. You can send the file privately to vorstand@jabref.org

**Comment by Siedlerchr** [comment]
I could reproduce the exception when opening the file. I'll look into it

**Comment by Siedlerchr** [comment]
So I found the error and added a fix so that the library can be opened again.
However, your SearchGroups use a RegularExpression pattern. Regular expressions cannot start with a quantifier (the * is a quantifier) Yo just simply need to remove the star at the beginning.
`project=*data|number|quant*` 
`project=*Digital*` is also a problem.

**Comment by ilippert** [comment]
>  However, your SearchGroups use a RegularExpression pattern. Regular expressions cannot start with a quantifier (the * is a quantifier) Yo just simply need to remove the star at the beginning.

a related feature request then would be to conduct a check of RegularExpressions when these are generated/defined.
