### ISSUE TITLE
Error when using (global) search

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8151]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

no clue how to reproduce. I have come across them multiple times, but not often.

It usually is when i am editing an entry and then try to search for another entry.

JabRef 5.4--2021-10-15--93b8025
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.0.1+1

### Appendix

...
<Log>
<summary>Log File</summary>
```
java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.4.294/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref@5.4.294/org.jabref.gui.LibraryTab.lambda$createMainTable$15(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.4.294/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref@5.4.294/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.4.294/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.294/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at org.jabref.merged.module@5.4.294/javafx.collections.transformation.SortedList.get(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.4.294/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.4.294/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(Unknown Source)
	... 79 more

```
</details>

**Comment by Siedlerchr** [comment]
I think @koppor  had a similar issue

**Comment by ThiloteE** [comment]
Sorry, no. Maybe i should remove the global here. My bad.
I just used the searchbar to search for an author of an entry by typing the author-name there. nothing fancy. Did NOT use author=xxxx
- Only one library was opened.
- 'search across libraries in a new window' was not used.
- 'keep search string across libraries' was not used.
- Don't remember if 'full text search' was enabled.
- Don't remember if 'regular expression' was enabled

**Comment by ThiloteE** [comment]
I encountered it again today.

I cannot reproduce doing the following steps! It just pops up randomly.

I think my last action before i remember what happened was editing the urldate or i was attaching the pdf file via F7 or maybe my last action was to push it to my latexfile. Not sure. Don't remember. Maybe something else, but those are the three most likely ones.

What i DO remember for sure: I was looking at the **entry preview** of this article:

```
@Article{Thompson20200330MCR,
  author       = {Thompson, {Mark R.}},
  date         = {2020-03-30},
  journaltitle = {Global Asia},
  title        = {Middle-Class Remorse: Re-embracing Liberal Democracy in the Philippines and Thailand},
  language     = {English},
  number       = {1},
  pages        = {60--64},
  url          = {https://scholars.cityu.edu.hk/en/publications/publication(484a64e7-5da0-4ea6-affc-0d3e9ffdc7d7).html},
  urldate      = {2021-11-13},
  volume       = {15},
  abstract     = {Democracy in both Thailand and the Philippines has been crippled by support given to anti-democratic forces by intellectuals who foolishly endorsed leaders who have done serious damage to the prospects for democratic governance in both countries. The middle classes that supported those views are now seized by remorse, and it remains to be seen whether a course correction in both countries is on the horizon, writes Mark R. Thompson.},
  file         = {:Thompson (2020-03-30) middle-class-remorse-re-embracing-liberal-democracy-in-the-philippines-and-thailand.pdf:PDF},
  publisher    = {East Asia Foundation},
}
```

Then i was trying to search for another author called Kurlantzik. I entered `kurlan` into the search bar in the following way: 
![image](https://user-images.githubusercontent.com/73715071/141661267-93cfa4b6-d027-4ca2-8528-27c2420fe707.png)
The search found the following two entries in my database:

```
@Article{Kurlantzick201609DBa,
  author       = {Joshua Kurlantzick},
  date         = {2016-09},
  journaltitle = {Current History},
  title        = {Democratic Backsliding and the Reach of Isis in Southeast Asia},
  doi          = {10.1525/curh.2016.115.782.226},
  number       = {782},
  pages        = {226--232},
  volume       = {115},
  file         = {:Kurlantzick (2016-09) Democratic Backsliding and the Reach of ISIS in Southeast Asia.pdf:PDF},
  publisher    = {University of California Press},
```
and

```
@Book{Kurlantzick20130319DiR,
  author    = {Kurlantzick, Joshua},
  date      = {2013-03-19},
  title     = {Democracy in Retreat},
  isbn      = {9780300188967},
  pagetotal = {288},
  publisher = {Yale University Press},
  url       = {https://books.google.de/books?id=rFzmr8Uar70C&lr},
  urldate   = {2021-11-13},
  ean       = {9780300188967},
  year      = {2013},
}
```

Error messages emerged.
Unfortunately i forgot to copy the error message, but i very much suspect it is the same as from last time :/ Sorry

**Comment by ThiloteE** [comment]
Closing, because the error was never reliably reproducible and the codebase has changed substantially in the areas of indexing, sorting the maintable and searching. Hopefully the issue has been fixed. Refs https://github.com/JabRef/jabref/pull/14128
