### ISSUE TITLE
collection is empty exception - upon starting JabRef

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8230]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-11-08--583bf6f Fedora Linux 5.14.16-301.fc35.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Open JabRef, the error immediately shows up. 

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: Collection is empty
	at java.base/java.util.EnumSet.copyOf(Unknown Source)
	at org.jabref@5.4.484/org.jabref.preferences.SearchPreferences.getSearchFlags(Unknown Source)
	at org.jabref@5.4.484/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.4.484/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.484/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.4.484/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.484/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.4.484/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.484/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.484/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.484/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
@calixtus  This is related to your preferences refactoring

**Comment by ilippert** [comment]
JabRef 5.4--2021-11-11--80ab4ca
Linux 5.14.16-301.fc35.x86_64 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

same again - or other bug? Now appears directly when opening JabRef, without any other interaction:

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: Collection is empty
	at java.base/java.util.EnumSet.copyOf(Unknown Source)
	at org.jabref@5.4.486/org.jabref.preferences.SearchPreferences.getSearchFlags(Unknown Source)
	at org.jabref@5.4.486/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.4.486/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.486/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.4.486/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.486/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.4.486/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.486/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.486/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.486/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by ilippert** [comment]
oh, ignore, it's the same bug ;) @calixtus, any chance you are already noting this? (I ask for practical work reasons & timeline planning)

**Comment by calixtus** [comment]
Hi Ingmar, yes thanks for the bug report, I noticed it. It's just I'm totally buried with work right now for the next two weeks. I'll get into this asap.
Is this blocking you working with jabref or can you continue even with this annoying error message?

**Comment by ilippert** [comment]
> Hi Ingmar, yes thanks for the bug report, I noticed it. It's just I'm totally buried with work right now for the next two weeks. I'll get into this asap. Is this blocking you working with jabref or can you continue even with this annoying error message?

Thanks, Carl, I can work with it. https://github.com/JabRef/jabref/issues/8234 is so much worse.

**Comment by calixtus** [comment]
He Ingmar, also tried this one. Although i can somehow locate the problem by reading your errorlog, i cannot reproduce the issue. Could you maybe try to reset your preferences?
Does the issue appear, when there are sidepanes open or not?

**Comment by ilippert** [comment]
thx for fixing!
