### ISSUE TITLE
 Jabref Portable does not start on Windows 10

### ISSUE THREAD

**Issue by rs028** [JabRef/jabref#8275]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download Jabref Portable Windows
2. Unzip the archive file and click on `JabRef.exe`

Nothing happens. No error messages are displayed.
I can see briefly `JabRef.exe` in the Task Manager, but then it disappears. 

If I launch `JabRef.exe` from `cmd.exe` it outputs a blank line and returns to prompt.

I have tested this with JabRef 5.1, 5.2, 5.3, 5.4. Any suggestions please?

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Do you or did you have another (older) version of Jabref installed on the machine? In that case, maybe the configuration-file needs to be reset?

**Comment by rs028** [comment]
Yes I had a 4.* but I uninstalled it before trying to use the 5.* Portable (the portable version is more convenient for me to use because I have limitations on what I can install)

**Comment by Siedlerchr** [comment]
Hi, can you try to launch it from Jabref/lib/runtime/bin/JabRef.bat ?

**Comment by rs028** [comment]
Hi , I have a `Jabref/runtime/bin/JabRef.bat` (without `lib/`) and this is what I get:

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Nov 24, 2021 7:45:33 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
%d [%thread] %-5level %logger - %msg%n java.nio.file.NoSuchFileException: \home\username\JabRef\journals-abbreviations.csv
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.applyPreferences(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.nio.file.InvalidPathException: Illegal char <:> at index 41: /home/username/JabRef/linux/bin/C:\home\username\library.bib
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
        at java.nio.file.Path.of(Unknown Source) ~[?:?]
        at org.jabref.preferences.JabRefPreferences.lambda$getFileHistory$13(Unknown Source) ~[org.jabref:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at org.jabref.preferences.JabRefPreferences.getFileHistory(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.menus.FileHistoryMenu.<init>(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefFrame.<init>(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefGUI.<init>(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Siedlerchr** [comment]
There seems to be something wrong with your preferences, e.g. linux and windows path mixed
Try to call `Jabref/runtime/bin/JabRef.bat` with the "-d all" argument for resetting the preferences. 

Or modify:
`pushd %DIR% & %JAVA_EXEC% %CDS_JVM_OPTS%  -p "%~dp0/../app" -m org.jabref/org.jabref.gui.JabRefLauncher  %* & popd`
to 
`
pushd %DIR% & %JAVA_EXEC% %CDS_JVM_OPTS%  -p "%~dp0/../app" -m org.jabref/org.jabref.gui.JabRefLauncher -d all %* & popd
`

If you modify the bat file you have to remove the `-d all` afterwards. (I currently don't have access to a windows computer, so   I cannot test it)

**Comment by rs028** [comment]
That would make sense because I was trying to come up with a system where I can use the same library/settings on a Windows and a Linux machine. I will test it tomorrow.

**Comment by rs028** [comment]
I executed `Jabref/runtime/bin/JabRef.bat -d all` and it is running, and now it runs even with `JabRef.exe`.

I am still getting the following (warning? error?) messages, but they don't seem to stop it from working.

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Nov 26, 2021 10:35:07 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
```

**Comment by Siedlerchr** [comment]
@rs028  You can ignore the status logger messages and the other warning. But glad that JabRef is working now for you!
