### ISSUE TITLE
Jabref 5.3 import xmp annotated pdf Unhandled exception occurred

### ISSUE THREAD

**Issue by radiospatial** [JabRef/jabref#8310]
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Whenever I dropped a large (35MB) PDF with XMP data onto the library window the file is imported and linked without any metadata, only the file name is shown as the title. I am sure the file has Metadata, It was written by an earlier version of Jabref. I verified this by using exiftool which shows the bibtex information in the file.

When I use the file import into current library and select the large file in question, I got an error message, saying Jabref could not find a suitable import filter;  See Appendix for details.

For smaller files of 1 MB and below I got more information when dropped but still not the file metadata,  the small files also do not create the exception whenever I use the file import dialog, the information gathered by this method is the same as when dropped. the information seems to be from the heuristic search carried out on the first page of the document.

In the past with Jabref 2.8 on Linux I have always been able to drop multiple files on the library window and watch Jabref Import all xmp data accurately. The ability to handle XMP data like this, both reading and Writing, was one of the endearing features of Jabref that kept me tied to It, nothing else came close.

### Appendix

org.jabref.logic.importer.ImportException: Could not find a suitable import format.
	at org.jabref@5.3.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.3.60000/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(Unknown Source)
	at org.jabref@5.3.60000/org.jabref.gui.importer.ImportAction.doImport(Unknown Source)
	at org.jabref@5.3.60000/org.jabref.gui.importer.ImportAction.lambda$automatedImport$1(Unknown Source)
	at org.jabref@5.3.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.3.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.3.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ThiloteE** [comment]
This thread sheds some light on the way how Jabref imports metadata currently: https://discourse.jabref.org/t/extract-information-from-pdf-import/2899

"If you want to force an XMP import, you can go to file → import → either to current or new library and select XMP-annotated PDF (last in the drop-down list) in the bottom right corner." - @btut

**Comment by radiospatial** [comment]
Thanks for the early reply, I had done what you said I forgot to mention it in the report, I did select the proper filter (Annotated PDF)  in the dialog. I also tried the development version which is at v 5.4, your bug report system had suggested that, it is the same result.

**Comment by Siedlerchr** [comment]
@radiospatial Can you share the PDF file somehow? If not public then you can send it to developers@jabref.org

**Comment by radiospatial** [comment]
Ok I will do that right away.

**Comment by radiospatial** [comment]
Will send you a Pcloud link to download at the email address you provided.

**Comment by Siedlerchr** [comment]
Thanks for the files, I already found some bugs in the code and I am currently working on a fix.

**Comment by radiospatial** [comment]
Great, thanks for letting me know!
