### ISSUE TITLE
JabRef does not open after csv file was edited by hand

### ISSUE THREAD

**Issue by swiss-cottage** [JabRef/jabref#8376]
### JabRef version

5.4 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. edit csv file of journal abbreviations by hand
2. JabRef won't start anymore
3. Reinstalled in hope of fixing this; to no avail
4. Ran the command C:\Program Files\JabRef\runtime\bin>JabRef.bat that I found on another thread: the output is below.

### Appendix

...
<details>

<summary>Log File</summary>

Jan 02, 2022 4:50:38 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-01-02 16:50:38 [JavaFX Application Thread] org.jabref.logic.net.URLDownload.bypassSSLVerification()
WARN: Fix SSL exceptions by accepting ALL certificates
2022-01-02 16:50:38 [JavaFX Application Thread] org.jabref.gui.JabRefMain.start()
ERROR: Unexpected exception: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 18) invalid char between encapsulated token and delimiter
at org.jabref.merged.module@5.4.60000/org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(Unknown Source)
at org.jabref.merged.module@5.4.60000/org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(Unknown Source)
at org.jabref@5.4.60000/org.jabref.logic.journals.AbbreviationParser.readJournalList(Unknown Source)
at org.jabref@5.4.60000/org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source)
at org.jabref@5.4.60000/org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source)
at org.jabref@5.4.60000/org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(Unknown Source)
at org.jabref@5.4.60000/org.jabref.logic.journals.JournalAbbreviationLoader.loadRepository(Unknown Source)
at org.jabref@5.4.60000/org.jabref.gui.JabRefMain.applyPreferences(Unknown Source)
at org.jabref@5.4.60000/org.jabref.gui.JabRefMain.start(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
at org.jabref.merged.module@5.4.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at org.jabref.merged.module@5.4.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: (line 18) invalid char between encapsulated token and delimiter
at org.jabref.merged.module@5.4.60000/org.apache.commons.csv.Lexer.parseEncapsulatedToken(Unknown Source)
at org.jabref.merged.module@5.4.60000/org.apache.commons.csv.Lexer.nextToken(Unknown Source)
at org.jabref.merged.module@5.4.60000/org.apache.commons.csv.CSVParser.nextRecord(Unknown Source)
... 18 more

</details>

**Comment by swiss-cottage** [comment]
I have now renamed the offending csv file and JabRef starts again. Cannot understand how it knew where to look after it was uninstalled but it must have a settings file somewhere that was not deleted during the uninstall.

**Comment by Siedlerchr** [comment]
The error message indicates that there was a Syntax mistake in the file. What file did you edit exactly? 
Maybe you missed some Semicolon? 
Jabref stores it preferences in the registry.

**Comment by swiss-cottage** [comment]
I am sure I have made some syntax error with either " " or \\' for French accents. The editing of the journal abbrv file directly in JabRef is somewhat difficult; if one forgets to press ENTER, the entry is lost. But the functionality of having the abbrv list is great. I have a small regret that the built-in abbrv are not consistent, e.g., The Annals of Applied Probability are abbreviated without full stops.

**Comment by Siedlerchr** [comment]
@swiss-cottage  The built-in journal abbreviations are assembled/combined from the ones in this repository: https://github.com/JabRef/abbrv.jabref.org
You are welcome to add/correct the entries

**Comment by swiss-cottage** [comment]
I have found the issue: the file "journal_abbreviations_webofscience.csv" has no dots and I am guessing it overwrites some of the dotted entries. Certainly, in the files "journal_abbreviations_ams" and "journal_abbreviations_mathematics.csv" the dots are present and correct. This is not something that I can fix but perhaps it is not difficult to exclude the undotted file?

**Comment by Siedlerchr** [comment]
Thanks for the investigation. I guess this refs the issue here https://github.com/JabRef/abbrv.jabref.org/issues/79#issuecomment-921966936
