### ISSUE TITLE
PubMed not working with JabRef

### ISSUE THREAD

**Issue by agcraig** [JabRef/jabref#8384]
### JabRef version

5.4 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...Repeated search after restarting programme and computer
2. ...
3. ...

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```org.jabref.logic.importer.FetcherException: Unable to get PubMed IDs
	at org.jabref@5.4.60000/org.jabref.logic.importer.fetcher.MedlineFetcher.getPubMedIdsFromQuery(Unknown Source)
	at org.jabref@5.4.60000/org.jabref.logic.importer.fetcher.MedlineFetcher.performSearch(Unknown Source)
	at org.jabref@5.4.60000/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.4.60000/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(Unknown Source)
	at org.jabref@5.4.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.4.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.4.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&sort=relevance&retmax=50&term=mohanty+2021+Noncerebral
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	... 13 more


</details>

**Comment by Siedlerchr** [comment]
Hi, this seems to have been a temporary issue from Medline/Pubmed. For me it's workin again
