### ISSUE TITLE
Systematic Literature Review Cannot create "Medline/PubMed" file on Linux

### ISSUE THREAD

**Issue by mhnazeri** [JabRef/jabref#8455]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 35 with Gnome 41.3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start a new systematic literature review
2. Choose "Medline/PubMed" as a database
3. Start the survey

The app will throw an error about the creation of repository structure. Systematic literature review creates (and looks for) files based on the query plus database name (if I understand correctly). It appears that on Linux file names cannot contain `/` whereas in `Medline/PubMed` there is a `/` and it wants to create a file with the database name which is not possible. The issue also persists in the development version 5.6.8-1.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalStateException: Error during creation of repository structure.
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.createBibFile(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.createFetcherResultFile(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.lambda$setUpRepositoryStructure$0(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.setUpRepositoryStructure(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.StudyRepository.<init>(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.logic.crawler.Crawler.<init>(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.slr.ExistingStudySearchAction.crawl(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.slr.StartNewStudyAction.execute(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.5.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.5.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: /home/user/bibliography/Survey/1611996361 - cancer/Medline/PubMed.bib
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.createFile(Unknown Source)
	... 53 more

```

</details>

**Comment by addak** [comment]
Hey
I think maybe this could solve it
```
 private void createBibFile(Path file) {
        if (Files.notExists(file)) {
            try {
                // Create non-existent directories (the fetcherName Medline/Pubmed causes an issue as Linux interprets Medline as another directory to Publine.bib 
                Files.createDirectories(file.getParent());  <-- I added this line
                Files.createFile(file);
            } catch (IOException e) {
                throw new IllegalStateException("Error during creation of repository structure.", e);
            }
        }
    }
```
Not sure if this is intended, but the fetcher name ought to be changed if the name itself is "Medline/Pubmed.bib"

**Comment by Siedlerchr** [comment]
@addak  Thanks for looking into it. For the name of the folder, I guess a simple fix would be to use JabRef's FileNameCleaner  to ensure that the filanme is valid. It replaces illegal characters
