### ISSUE TITLE
Menu "Open terminal here" causes an uncaught exception

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8466]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-01-25--2c92eb0 Linux 4.19.0-18-amd64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a file
2. Select the menu View -> Open terminal here

No terminal opens, and a window opens, showing that an exception is raised:
```
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]]
Cannot invoke "java.util.function.Supplier.get()" because "this.databaseContext" is null
```

### Appendix

...
<details>

<summary>Log File</summary>Fix SSL exceptions by accepting ALL certificates
Not updating theme because it hasn't changed
Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Index path for /home/USER/Documents/Biblio/jabref-authors.bib is /home/USER/.local/share/JabRef/0.5a
Could not find geiger2016evolution.pdf
Could not find Geiger2016ProcessEngineBenchmarking.pdf
Could not find Nikol2016.pdf
Could not find Geiger2015BPMNConformanceIn.pdf
Could not find Harrer2015ImprovingStaticAnalysis.pdf
Could not find Harrer2014AutomatedandIsolated.pdf
Could not find Harrer2014BPELConformancein.pdf
Could not find Roeck2014PerformanceBenchmarkingBPEL.pdf
Could not find Harrer2014ProcessEngineSelection.pdf
Could not find Preissinger2014StaticAnalysisRules.pdf
Could not find Roeck2014TestingBPELEngine.pdf
Could not find Harrer2014TowardsRobustnessEvaluation.pdf
Could not find Kolb2014TowardsApplicationPortability.pdf
Could not find Preissinger2014BPELStaticAnalysisProposal.pdf
Could not find Harrer2014TowardsUniformBPEL.pdf
Could not find Geiger2013BPMN20Process.pdf
Could not find Geiger2013BPMN20Serialization.pdf
Could not find Geiger2013DetectingInteroperabilityand.pdf
Could not find Lenhard2013DetectingPortabilityIssues.pdf
Could not find Lenhard2013MeasuringInstallabilityService.pdf
Could not find Lenhard2013MeasuringPortabilityof.pdf
Could not find Harrer2013OpenSourceversus.pdf
Could not find Harrer2012BetsyBPELEngine.pdf
Could not find Harrer2012BPELconformancein.pdf
Could not find Kolb2012BridgingHeterogeneityOrchestrations.pdf
Could not find Geiger2011ProposalCheckingConformance.pdf
Could not find Lenhard2011EditDistanceBased.pdf
Could not find Schoenberger2011HasWSIs.pdf
Could not find Geiger2011TowardsAutomatedConformance.pdf
Could not find Benker2009.pdf
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.databaseContext" is null
	at org.jabref@5.6.15/org.jabref.gui.OpenConsoleAction.execute(Unknown Source)
	at org.jabref@5.6.15/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.6.15/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.6.15/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.6.15/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.15/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

</details>

**Comment by RyanEubank** [comment]
Hello @Siedlerchr, I can confirm this issue persists on Windows 10 when using the latest portable version:

JabRef 5.6--2022-01-30--8ca6b7f
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.2-ea+3

and is reproduced using the steps above in the original post.

I would like to look into this issue myself if possible; I have never contributed to an open source project before but I am quite familiar with Java and see this listed as a good first issue. I am currently reading documentation and familiarizing myself with JabRef's codebase, do you have any other suggestions to get me started?

**Comment by ThiloteE** [comment]
Thank you! I will let Christoph answer your questions, but i just want to add something that might help in solving this:

- `ctrl + shift + L` still works.
- Also, right clicking on a library file and opening a terminal from the corresponding submenu also works.

The only command that fails seems to be `view > open terminal here`

**Comment by Siedlerchr** [comment]
@RyanEubank  Welcome to JabRef!  From the stack strace it seems the issue arose somewhere here.
 https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/actions/JabRefAction.java 

For getting started, just follow the contribution guide: https://devdocs.jabref.org/contributing#contribute-code

**Comment by RyanEubank** [comment]
Thanks, I believe I found and fixed the issue; just a simple one line change. However, I've noticed the master branch fails a few tests when running gradlew check, unrelated to any changes here. Is this an issue before submitting any pull requests?

**Comment by Siedlerchr** [comment]
@RyanEubank no worries, if the Unit test pass on CI/ GitHub action it's fine.

**Comment by mlep** [comment]
I can confirm the issue is now fixed
Thanks @RyanEubank!
