### ISSUE TITLE
Problem when searching DOI

### ISSUE THREAD

**Issue by goodluck1982** [JabRef/jabref#8507]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04 with Plasma 5.18.8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I paste a doi to the search box, the following dialog boxes  usually pop.
But after I crossed out all the dialog boxes and pasted the doi again, no more dialog box poped.

![图片](https://user-images.githubusercontent.com/48718961/154793257-7f9d823a-7672-4e2d-87c5-a8ef2ed81b01.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Can you pleas copy the whole error text /stack trace here? Thar helps us to locate the root cause

**Comment by goodluck1982** [comment]
> Can you pleas copy the whole error text /stack trace here? Thar helps us to locate the root cause

```
java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.LibraryTab.lambda$createMainTable$15(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.5.60000/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at org.jabref.merged.module@5.5.60000/javafx.collections.transformation.SortedList.get(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.5.60000/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(Unknown Source)
	... 79 more
```
