### ISSUE TITLE
Can't generate new subsidiary bib file from aux file

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8513]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-02-15--b33ebfb Linux 5.13.0-28-generic amd64  Java 17.0.2  JavaFX 17.0.2-ea+3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I'm using BibLaTeX.

1. Tools / New subsidiary ...
2. When I "parse" the aux file I get this

![image](https://user-images.githubusercontent.com/762246/154857766-89b33d71-dea8-402d-8f57-a8655430629f.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Fix SSL exceptions by accepting ALL certificates
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Index path for /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib is /home/dom/.local/share/JabRef/0.5a
invalid url
java.net.MalformedURLException: no protocol: :/home/dom/GoogleDrive@Ualberta/DataDrive02/ebooks/Buddhism/www.ahandfulofleaves.org/documents/How Buddhism Began_Gombrich.pdf:PDF
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.44/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.addToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.LibraryTab.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefFrame.addTab(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefFrame.addParserResult(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

invalid url
java.net.MalformedURLException: no protocol: :https\://www.jstor.org/stable/24008036:URL
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.44/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.addToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.LibraryTab.<init>(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefFrame.addTab(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefFrame.addParserResult(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.44/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[...]
java.io.IOException: Unknown dir object c=')' cInt=41 peek=')' peekInt=41 at offset 9892175 (start offset: 9892175)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.parseDirObject(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.parseCOSDictionaryValue(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.parseCOSDictionaryNameValuePair(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.parseCOSDictionary(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.parseDirObject(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parseFileObject(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parseObjectDynamically(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parseObjectDynamically(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parseTrailerValuesDynamically(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.PDFParser.initialParse(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.PDFParser.parse(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.DocumentReader.readPdfContents(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.DocumentReader.readLinkedPdf(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.PdfIndexer.writeToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.PdfIndexer.addToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.lambda$addToIndex$4(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.call(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.call(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.44/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[...]
Could not read pdf file /home/dom/Dropbox/Library/Colleagues Papers/Franco, Eli/2996  JIP A new era in Buddhist studies.pdf!
java.io.IOException: Error: End-of-File, expected line
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.BaseParser.readLine(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parseHeader(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdfparser.PDFParser.parse(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref.merged.module@5.6.44/org.apache.pdfbox.pdmodel.PDDocument.load(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.DocumentReader.readPdfContents(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.DocumentReader.readLinkedPdf(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.PdfIndexer.writeToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.PdfIndexer.addToIndex(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.lambda$addToIndex$4(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.call(Unknown Source)
	at org.jabref@5.6.44/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.call(Unknown Source)
	at org.jabref@5.6.44/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.44/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[...]
Could not find /home/dom/GoogleDriveUofA/DataDrive02/ebooks/Indology/Bisschop and Cecil_Primary Sources and Asian Pasts_2020.pdf
Copied version to clipboard
```

</details>

**Comment by Siedlerchr** [comment]
The error reason is the same as in #8510. 
You are lucky I just fixed this in a PR, can you test this version? https://builds.jabref.org/pull/8514/merge/

**Comment by wujastyk** [comment]
JabRef 5.6-PullRequest8514.51--2022-02-20--e7b38d4
Linux 5.13.0-30-generic amd64 
Java 17.0.2 
JavaFX 17.0.2-ea+3

Unfortunately, same error.

**Comment by Siedlerchr** [comment]
Ah I think I need to modify the url detection algorithm again, because of the www

**Comment by Insomniac66** [comment]
I ran into the same issue (logfile aside) after setting up a newer TeXLive environment. After a little investigation, it turned out that the citations in the aux file now look like this
```
\abx@aux@cite{0}{TestCitation}
```
instead of like this
```
\abx@aux@cite{TestCitation}
```
I am guessing this causes the regex `CITE_PATTERN` in the [DefaultAuxParser](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/auxparser/DefaultAuxParser.java#L35) to return those `0}{blah` results rather than the ones we want.

This could maybe be fixed by just changing the regex to greedily match that first argument if it's there and discard it, like this:
```regex
\\(citation|abx@aux@cite)(\{\d+\})?\{(.+)\}
```
This would also require the group index to be changed elsewhere in the file. I haven't tried this, but if you would like I could try it out and submit a patch if it works.
