### ISSUE TITLE
bad install from .deb

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8525]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

5.6.53-1 on linux mint

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. The deb appears to install but doesn't give a working installation.  Screen scrape below.

### Appendix

...
<details>

<summary>Log File</summary>

```
$ ./JabRef 
Feb 23, 2022 10:53:16 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-02-23 10:53:16 [JavaFX Application Thread] org.jabref.logic.net.URLDownload.bypassSSLVerification()
WARN: Fix SSL exceptions by accepting ALL certificates
Exception in Application start method
2022-02-23 10:53:16 [main] org.jabref.gui.FallbackExceptionHandler.uncaughtException()
ERROR: Uncaught exception occurred in Thread[main,5,main]: java.lang.RuntimeException: Exception in Application start method
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.TelemetryConfiguration.getActive(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.Globals.startTelemetryClient(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.Globals.startBackgroundTasks(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

```

</details>

**Comment by Siedlerchr** [comment]
Oops that was me :( Didn't know the telemetry stuff still uses that)
