### ISSUE TITLE
cannot start jabref - .jabref.gui.FallbackExceptionHandler.uncaughtException

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8528]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

fedora 35, master from 2022-02-22

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

download rpm master - run on linux
I cannot start JabRef

### Appendix

...
<details>

<summary>Log File</summary>

```
Feb 24, 2022 8:32:37 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-02-24 08:32:37 [JavaFX Application Thread] org.jabref.logic.net.URLDownload.bypassSSLVerification()
WARN: Fix SSL exceptions by accepting ALL certificates
Exception in Application start method
2022-02-24 08:32:37 [main] org.jabref.gui.FallbackExceptionHandler.uncaughtException()
ERROR: Uncaught exception occurred in Thread[main,5,main]: java.lang.RuntimeException: Exception in Application start method
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.microsoft.applicationinsights.TelemetryConfiguration.getActive(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.Globals.startTelemetryClient(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.Globals.startBackgroundTasks(Unknown Source)
	at org.jabref@5.6.53/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.53/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

```

</details>

**Comment by Siedlerchr** [comment]
yes, hast just been fixed was related to the telemetry
