### ISSUE TITLE
JabRef inserts incorrect keys 

### ISSUE THREAD

**Issue by ImpracticalDogg** [JabRef/jabref#8541]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

8.1 with Classic Shell

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open new Writer document (no references)
2. Open JabRef
3. Connect from J to W
4. Insert a few citations
5. Press the Update Bibliography button on the left panel
6. JabRef reports "Citation key xxxx not found in your current library"
7. Look at the JabRef entries.  Key is shown in the table.
8. Writer document has JR_cite_1_ in in front of the key shown in JabRef

### Appendix

Writer file:
![image](https://user-images.githubusercontent.com/25794174/156799115-39ac75a8-b18c-40f2-9976-76df95f417a2.png)

JabRef screen with reference key:
![image](https://user-images.githubusercontent.com/25794174/156799517-f83b1a4f-9933-4910-b59e-5b893ebb4461.png)

```
Paste an excerpt of your log file here
```

</details>

Fix SSL exceptions by accepting ALL certificates
Not updating theme because it hasn't changed
Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Index path for E:\Documents\Data-Research\ResearchDocuments\BIB\TEST-01-FullDatabase.bib is C:\Users\Brendon\AppData\Local\org.jabref\JabRef\0.5a
invalid url
java.net.MalformedURLException: unknown protocol: pdf
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at org.jabref@5.6.62/org.jabref.logic.importer.util.FileFieldParser.parse(Unknown Source)
	at org.jabref@5.6.62/org.jabref.model.entry.BibEntry.getFiles(Unknown Source)
	at org.jabref@5.6.62/org.jabref.logic.pdf.search.indexing.IndexingTaskManager.addToIndex(Unknown Source)
	at org.jabref@5.6.62/org.jabref.gui.LibraryTab$IndexUpdateListener.<init>(Unknown Source)
	at org.jabref@5.6.62/org.jabref.gui.LibraryTab.<init>(Unknown Source)
	at org.jabref@5.6.62/org.jabref.gui.JabRefFrame.addTab(Unknown Source)
	at org.jabref@5.6.62/org.jabref.gui.JabRefFrame.addParserResult(Unknown Source)
	at org.jabref@5.6.62/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.62/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)

**Comment by Siedlerchr** [comment]
Can you please try the latest development version? We merged some changes related to OO and I now longer can reproduce the errors

**Comment by ImpracticalDogg** [comment]
I no longer have these errors.

Thanks
Brendon

**Comment by ThiloteE** [comment]
For the record: Fixed by https://github.com/JabRef/jabref/pull/7795
