### ISSUE TITLE
Event log: Could not access app-directory at %USERPROFILE%\AppData\Local\org.jabref\JabRef

### ISSUE THREAD

**Issue by pratt33k** [JabRef/jabref#8600]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Just downloaded and installed Jabref version 5.5 on my **D: drive** of my Windows 10 21H1 laptop instead of the C drive (where windows is installed)
2. Opened Event Log
3. Saw the error as shown in the appendix log file (screenshot)

### Appendix

<details>

<summary>Log File</summary>

```
Fix SSL exceptions by accepting ALL certificates
Migrating old custom entry types.
Could not access app-directory at C:\Users\prate\AppData\Local\org.jabref\JabRef
java.nio.file.NoSuchFileException: C:\Users\prate\AppData\Local\org.jabref\JabRef
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
	at java.base/java.nio.file.Files.newDirectoryStream(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.JabRefMain.clearOldSearchIndices(Unknown Source)
	at org.jabref@5.5.60000/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.5.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}

```

</details>

**Screenshot:**

![image](https://user-images.githubusercontent.com/53478966/159628599-f1fd0571-ab83-40c9-a7d1-e5524893f92d.png)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
