### ISSUE TITLE
FullText Search Results exception in entry editor results document viewer 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#8628]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...Have some pdfs linked to entries and fulltext search enabled
2. ...search for a string e.g. test
3. .. Open entry editor with search results tab for found entries.
```

DEBUG: Inject into org.jabref.gui.documentviewer.DocumentViewerView
Mar 30, 2022 11:30:43 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@18 of loader 'app')' while converting value for '-fx-background-color' from rule '*#mainPane' in stylesheet file:/Users/christophs/workspace/jabref/build/resources/main/org/jabref/gui/documentviewer/documentviewer.css
[ERROR] COSObject - Can't dereference COSObject{5, 0} <java.io.IOException: org.apache.pdfbox.io.RandomAccessReadBufferedFile already closed>java.io.IOException: org.apache.pdfbox.io.RandomAccessReadBufferedFile already closed
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.io.RandomAccessReadBufferedFile.checkClosed(RandomAccessReadBufferedFile.java:245)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.io.RandomAccessReadBufferedFile.getPosition(RandomAccessReadBufferedFile.java:99)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdfparser.COSParser.dereferenceCOSObject(COSParser.java:584)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.cos.COSObject.getObject(COSObject.java:115)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.cos.COSArray.getObject(COSArray.java:208)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdmodel.PDPage.getContentsForRandomAccess(PDPage.java:198)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdfparser.PDFStreamParser.<init>(PDFStreamParser.java:60)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:485)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:142)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:264)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:338)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:259)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImageWithDPI(PDFRenderer.java:245)
	at org.jabref/org.jabref.gui.documentviewer.PdfDocumentPageViewModel.render(PdfDocumentPageViewModel.java:53)
	at org.jabref/org.jabref.gui.documentviewer.DocumentViewerControl$DocumentViewerPage.renderPage(DocumentViewerControl.java:214)
	at org.jabref/org.jabref.gui.documentviewer.DocumentViewerControl$DocumentViewerPage.lambda$0(DocumentViewerControl.java:160)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:59)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:162)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[ERROR] COSObject - Can't dereference COSObject{38, 0} <java.io.IOException: org.apache.pdfbox.io.RandomAccessReadBufferedFile already closed>java.io.IOException: org.apache.pdfbox.io.RandomAccessReadBufferedFile already closed
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.io.RandomAccessReadBufferedFile.checkClosed(RandomAccessReadBufferedFile.java:245)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.io.RandomAccessReadBufferedFile.getPosition(RandomAccessReadBufferedFile.java:99)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdfparser.COSParser.dereferenceCOSObject(COSParser.java:584)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.cos.COSObject.getObject(COSObject.java:115)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.cos.COSArray.getObject(COSArray.java:208)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdmodel.PDPage.getContentsForRandomAccess(PDPage.java:198)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.pdfparser.PDFStreamParser.<init>(PDFStreamParser.java:60)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:485)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:142)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:264)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:338)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:259)
	at pdfbox@3.0.0-RC1/org.apache.pdfbox.rendering.PDFRenderer.renderImageWithDPI(PDFRenderer.java:245)
	at org.jabref/org.jabref.gui.documentviewer.PdfDocumentPageViewModel.render(PdfDocumentPageViewModel.java:53)
	at org.jabref/org.jabref.gui.documentviewer.DocumentViewerControl$DocumentViewerPage.renderPage(DocumentViewerControl.java:214)
	at org.jabref/org.jabref.gui.documentviewer.DocumentViewerControl$DocumentViewerPage.lambda$0(DocumentViewerControl.java:160)
	at org.jabref/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:59)
	at org.jabref/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:162)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Will be fixed by #8362
