### ISSUE TITLE
Standalone on linux can't start: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS

### ISSUE THREAD

**Issue by jakkarth** [JabRef/jabref#8648]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 20.1 MATE

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download JabRef-5.6-portable_linux.tar.gz
2. tar xvf JabRef-5.6-portable_linux.tar.gz
3. cd JabRef/bin
4. ./JabRef

Expected result: application launches.

Actual result: Uncaught exception stack trace, application does not launch.

Output:

Apr 06, 2022 1:57:27 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
Exception in Application start method
2022-04-06 13:57:28 [main] org.jabref.gui.FallbackExceptionHandler.uncaughtException()
ERROR: Uncaught exception occurred in Thread[main,5,main]: java.lang.RuntimeException: Exception in Application start method
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at java.prefs/java.util.prefs.XmlSupport.loadPrefsDoc(Unknown Source)
	at java.prefs/java.util.prefs.XmlSupport.importMap(Unknown Source)
	at java.prefs/java.util.prefs.FileSystemPreferences$6.run(Unknown Source)
	at java.prefs/java.util.prefs.FileSystemPreferences$6.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.prefs/java.util.prefs.FileSystemPreferences.loadCache(Unknown Source)
	at java.prefs/java.util.prefs.FileSystemPreferences.initCacheIfNecessary(Unknown Source)
	at java.prefs/java.util.prefs.FileSystemPreferences.getSpi(Unknown Source)
	at java.prefs/java.util.prefs.AbstractPreferences.get(Unknown Source)
	at org.jabref@5.6.144/org.jabref.preferences.JabRefPreferences.get(Unknown Source)
	at org.jabref@5.6.144/org.jabref.preferences.JabRefPreferences.updateLanguage(Unknown Source)
	at org.jabref@5.6.144/org.jabref.preferences.JabRefPreferences.getLanguage(Unknown Source)
	at org.jabref@5.6.144/org.jabref.preferences.JabRefPreferences.<init>(Unknown Source)
	at org.jabref@5.6.144/org.jabref.preferences.JabRefPreferences.getInstance(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 more
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by mlep** [comment]
FYI, I do not have this issue on my computer under Linux.

JabRef 5.6--2022-04-04--dbf921e
Linux 4.19.0-20-amd64 amd64 
Java 17.0.2 
JavaFX 18+12

**Comment by jakkarth** [comment]
If kernel version is important: Linux rin 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

I have openjdk 11.0.14.1 on this system, but I did not expect that to matter if I'm installing a standalone binary, assuming it would include whatever runtime and libraries it needed within the binary itself. I don't know how to check the host's version of JavaFX. Are there minimum versions of these components expected on the host system, even with the standalone version?

**Comment by ThiloteE** [comment]
Looks like it.

I think the documentation is outdated, though. I think somewhere is still JDK mentioned. We should update it.
- Newest development version of Jabref uses JDK 17.0.2 and JavaFX 18 +12
- Jabref 5.5 uses JDK 16.0.2 and JavaFX 17.0.1+1

**Comment by jakkarth** [comment]
Again, when you say "uses", do you mean "bundles this within the standalone binary" or "depends on this being available on the host system"? Do I need to install/upgrade these libraries on my system?

**Comment by ThiloteE** [comment]
I don't know. This is the information that is available to users when opening Jabref and clicking on `Help > About Jabref`.
There was a similar issue recently on github. If I remember correctly, updating JDK helped that person. It may or may not help in your case.

**Comment by ThiloteE** [comment]
Also check out this thread: https://discourse.jabref.org/t/jabref-5-1-linux-portable/2293

> Locate JabRef.bat (Windows) or JabRef (Linux, Mac OS). In the portable versions, this is JabRef-5.0-portable_windows\JabRef\runtime\bin\JabRef.bat and JabRef-5.0-portable_linux\JabRef\lib\runtime\bin\JabRef.
> 
> Do not use JabRef\JabRef.exe or bin/JabRef

**Comment by Siedlerchr** [comment]
JabRef ships with it's own custom bundled jdk + openjfx version, so yeah it seems you  have to use the different launcher path as stated in the link

**Comment by jakkarth** [comment]
Running bin/JabRef exhibits the problem. Running lib/runtime/bin/JabRef in a terminal results in the same problem. However, double-clicking it from a gui file manager and selecting "run in terminal" launches the application correctly. This defies all my expectations and is not the way I launch basically any other application on my system. I have no idea why this works, but it does. I may continue this investigation and mention my results if I find any, but at least I can document here what the problem was and my current workaround, and we can close the issue.

Thanks for the pointers to the right direction! And for some nice software :)

**Comment by jakkarth** [comment]
Update. Under some circumstances, my shell was initializing a CLASSPATH environment variable based on a project from long ago. With that set to its long original value, neither the application nor the browser extension would open properly. Double-clicking the executable in my gui file manager was launching a shell with an empty environment, which is why it was successful. Removing the environment variable and restarting my shells and browsers has resulted in both the application and the extension working.

This was definitely user error, not a bug. And other than _maybe_ adding a note to check one's CLASSPATH if the application doesn't start, I don't even think there's any documentation changes necessary to avoid it. Updating the installation instructions would still be appreciated, but would not directly affect this particular problem.

Thank you all for the help and sorry for the noise. I hope this bug report will help someone in the future who is as forgetful as I am.

**Comment by mlep** [comment]
Thank you for the follow-up!
