### ISSUE TITLE
Jabref corrupts PDF file when writing XMP metadata to linked PDF

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8655]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.6--2022-04-04--dbf921e Windows 10 10.0 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Have a linked pdf file
   (my pdf file was 838 kb)
2. Have bibliographic data
3. Write XMP metadata to pdf via `Tools > write XMP metadata to PDF files (F6)`

What happens:

- Trying to open this pdf file with a pdf reader (e.g. foxit reader / pdf xchange) shows the pdf has no pages anymore.
- The size of the pdf shrinks to ~ 4kb

**Comment by ThiloteE** [comment]
Here the destroyed file: [test samefile (2021).pdf](https://github.com/JabRef/jabref/files/8451491/test.samefile.2021.pdf)

**Comment by ThiloteE** [comment]
I also encountered an error message just now when doing some other test trying to write XMP metadata to linked pdf.

But that was related to groups and this entrytable/groups index bug. Maybe not related to this issue here. I removed a keyword, hence the entry was removed from a group. Then I tried to write the XMP metadata.

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: 1-based index not found: 1
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$Segment.get(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache.get(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache.getOrLoad(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$LocalLoadingCache.get(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.FileAnnotationCache.getFromCache(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTabViewModel.lambda$reloadAnnotations$1(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.6.144/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.JabRefDialogService.showErrorDialogAndWait(Unknown Source)
	at org.jabref@5.6.144/org.jabref.gui.FallbackExceptionHandler.lambda$uncaughtException$0(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.144/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: 1-based index not found: 1
	at org.jabref.merged.module@5.6.144/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref.merged.module@5.6.144/org.apache.pdfbox.pdmodel.PDPageTree.get(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.PdfAnnotationImporter.importAnnotations(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.EntryAnnotationImporter.lambda$importAnnotationsFromFiles$2(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.EntryAnnotationImporter.importAnnotationsFromFiles(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.FileAnnotationCache$1.load(Unknown Source)
	at org.jabref@5.6.144/org.jabref.logic.pdf.FileAnnotationCache$1.load(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$Segment.loadSync(Unknown Source)
	at org.jabref.merged.module@5.6.144/com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(Unknown Source)
	... 42 more
```

**Comment by ThiloteE** [comment]
Something committed in between 2022-01-30 (issue 8477) and 2022-02-24 (issue 8526) broke it. I can't compile these commits with git using

```
git checkout <commithash>
./gradlew run
```

There are different error messages.

**Comment by ThiloteE** [comment]
https://github.com/JabRef/jabref/commit/d98a603d47835b6564f03fa550d5a84d7c2c6f3e looks like it was touching XMP and PDF

**Comment by Siedlerchr** [comment]
Hm. When you switch to an older hash, you need to run ./gradlew clean before.

**Comment by Siedlerchr** [comment]
But I could reproduce your issue.

**Comment by ThiloteE** [comment]
2022-02-21 still works. Something in between these 3 days.

**Comment by Siedlerchr** [comment]
I get a warning:
> [WARN] PDDocument - You are overwriting an existing file, this will produce a corrupted file if you're also reading from it

https://pdfbox.apache.org/3.0/migration.html
> The input file must not be used as output for saving operations. It will corrupt the file and throw an exception as parts of the file are read the first time when saving it.

Hmm. @btut  Any ideas?

**Comment by ThiloteE** [comment]
https://issues.apache.org/jira/browse/PDFBOX-4028?orderby=affectedVersion+ASC%2C+priority+DESC%2C+updated+DESC

> We solved this problem by workaround -> performing save incremental into the temporary file and then replace the original by this temporary file.
