### ISSUE TITLE
Saving bug after import - braces don't match

### ISSUE THREAD

**Issue by falschgeldkind** [JabRef/jabref#8730]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Jabref Version: latest (main) dev build (today) but this bug exists in previous versions as well.

Saving throws an exception after importing PDF Files.
Probably has to do with OCR reading some special characters like { } \n etc.
Trying to save them then leads to a Situation where Jabref can't decide where the entry ends or something like that

To reproduce:
1. Import some PDF
2. click on save
3. get an exception

Exception in the appendix

### Appendix

...
<details>

```
org.jabref.logic.exporter.SaveException: Problems saving: java.io.IOException: Error in field 'AUTHOR of entry SINGLEFINandBUFFETINGALLEVIATION0656': Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveDatabaseAction.save(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.exporter.SaveAction.execute(Unknown Source)
	at org.jabref@5.7.4/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.7.4/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.4/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.7.4/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error in field 'AUTHOR of entry SINGLEFINandBUFFETINGALLEVIATION0656': Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.writeField(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.BibEntryWriter.write(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(Unknown Source)
	... 42 more
Caused by: org.jabref.logic.bibtex.InvalidFieldValueException: Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.checkBraces(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.formatAndResolveStrings(Unknown Source)
	at org.jabref@5.7.4/org.jabref.logic.bibtex.FieldWriter.write(Unknown Source)
	... 48 more

```

</details>

**Comment by ThiloteE** [comment]
Would it be possible if you could provide the pdf that you imported? (As long as there is no copy-right) you also can send the file to jabref maintainers in a private e-mail (web@jabref.org).

**Comment by Siedlerchr** [comment]
Well, the error mesage says the problem is a brace: org.jabref.logic.exporter.SaveException: Problems saving: java.io.IOException: Error in field 'AUTHOR of entry SINGLEFINandBUFFETINGALLEVIATION0656': Braces don't match. Field value: FOR SINGLE{FIN and BUFFETING ALLEVIATION

**Comment by falschgeldkind** [comment]
@ThiloteE Sorry due to copyright issues I cannot share the PDF file

But @Siedlerchr is correct. 

Maybe you could just check the new entries after the OCR step for any braces and discard them? Maybe even leave that field empty (because it probably is fucked up OCR and the value does not make any sense anyway)

**Comment by ThiloteE** [comment]
Maybe you could share the metadata that gets imported into JabRef before saving then. There should not be any copyright on that, right?

I assume there is a brace too many in one of the fields, therefore JabRef detects this and gives the error. If you have many entries and routinely stumble upon odd number of braces in your PDFs, then you should check your workflow and the programs you use to create them. Instead of trying to repair wrong syntax, please make sure to also prevent wrong syntax being created in the first place.

`{` and `}` are JabRef special characters and denote the beginning and end of a field. Imagine JabRef automatically removing an odd number of braces: text that comes after or before the brace that was removed will still be there, but not within braces, therefore will be out of place.

I just did a short test what JabRef will do, when there are no braces. The below is an example for it, but keep in mind that this is WRONG syntax and should be heavily avoided:

```
@Book{aii,
  title  = {Africa in International Politics},
  groups = test,
}
```

after clicking on another entry in the main table, will somehow turn to:

```
@Book{aii,
  title  = {Africa in International Politics},
  groups = {#test#},
}
```

So I guess having a mechanism that automatically removes odd number of braces upon saving would be ok, because there is a fall-back mechanism in place that tries to recreate fields?

Removing the odd number of braces would need to be done at a certain point in time, at which it is clear that the user is not working on the bibliographic entries anymore. Removing braces instantly, when users  would want to ADD braces and have not finished adding the right amount of braces would be a detriment.

Btw.: JabRef's integrity check does not find   `{#test#},`, which should probably be the case.

**Comment by falschgeldkind** [comment]
I do not create any PDFs i'm just importing unlinked files (that already exist). 

I think the OCR sometimes confuses normal braces with curly braces

Yes the Problem is that there sometimes are (curly) braces within the fields. Wouldn't it be enough to just delete all braces WITHIN fields or swap them out for normal braces?

**Comment by ThiloteE** [comment]
I still don't know what OCR means.

**Comment by falschgeldkind** [comment]
Optical character recognition. Isn't that what the PDF import does to get the Author etc. if its not contained in the PDF metadata?

**Comment by ThiloteE** [comment]
We don't know what is imported to JabRef and what it parses and what method it uses to import because you have failed to provide this data to us. Sorry :/ Troubleshooting this is not easy.

JabRef by default checks for data in the following order, when Grobid is enabled (but you also can disable Grobid):

    1. Look for bibtex entry on first page of pdf
    2. Look for embedded bib file
    3. Grobid
    4. XMP metadata
    5. Attempt to find metadata on first page (not in bibtex format).

Source: https://discourse.jabref.org/t/extract-information-from-pdf-import/2899/6

If you say it parses optically, this then points to a Grobid issue: https://github.com/kermitt2/grobid/issues

**Comment by ThiloteE** [comment]
You can check metadata attached to the pdf via [exiftool ](https://www.exiftool.org/). 

The following command will allow you to extract all available metadata from PDFs:

`exiftool -ee3 -U -G3:1 -api requestall=3 -api largefilesupport FILE`

[Source](https://www.exiftool.org/faq.html)

**Comment by falschgeldkind** [comment]
the next time this problem turns up I'll make a screenshot or something like that and investigate with exiftool

**Comment by falschgeldkind** [comment]
Allright. Got another one:
There seems to be no metadata in this pdf:
```
exiftool -ee3 -U -G3:1 -api requestall=3 -api largefilesupport $DOCPATH/Druckschriften/DGLR/JT99_102.PDF
bley@DellOptiPlex-7010:~$ 

```
![Bildschirmfoto von 2022-04-29 13-40-21](https://user-images.githubusercontent.com/74116031/165937914-b5fdee58-d3e9-4f1f-9c06-8a6b29d86d59.png)

**Comment by ThiloteE** [comment]
Also, please show the bibtex source tab. sometimes what is shown in other tabs diverges from what is shown in bibtex source.

**Comment by falschgeldkind** [comment]
I use linux. So no exe :D

how do I get the bibtex source tab?

**Comment by ThiloteE** [comment]
Ah right. My bad.

The `{} biblatex source` tab is one of the tabs of the entry editor in JabRef.
![image](https://user-images.githubusercontent.com/73715071/165943272-34d0f8d4-e521-4a9e-99d2-a5a8c99cbd6d.png)

**Comment by falschgeldkind** [comment]
another one with a similar error:
`bley@DellOptiPlex-7010:/home/pfisun8n/allgem0/08_Literatur/Dokumente/Druckschriften/EUCASS$ exiftool -ee3 -U -G3:1 -api requestall=3 -api largefilesupport a169.pdf
bley@DellOptiPlex-7010:/home/pfisun8n/allgem0/08_Literatur/Dokumente/Druckschriften/EUCASS$ 
`

the source tab says this:
`Error in field 'AUTHOR of entry ГпуезИаНоп1310': Braces don't match. Field value: Ап ГпуезИ^аНоп and оГ Бупапнс and о( Огйегей and 81гис1иге ш Ехсйей and Зе1 изш РГУ and - Ъазес and рЬазе-  and ауега§1П§ {есЬшцие.

Correct the entry, and reopen editor to display/edit source.`

**Comment by falschgeldkind** [comment]
Thank you.

I do not have the bibliographic data unfortunately
