### ISSUE TITLE
JabRef unable to open its own BibTeX file

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8757]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-05-03--46a4edf Linux 4.19.0-20-amd64 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open a BibTeX file using the menu `File > Open Library`

==> A Exception window is displayed, with "Connection error. Not on FX application thread; currentThread = pool-2-thread-3. A local copy will be opened".

After clicking on OK, a "wheel" appears in the window. And remains for a very long time.

Notes: 
- Putting the cursor on the tab shows "biblatex mode" (?!?)
- On JabRef launch, pre-opened files are displayed correctly (and without raising an exception)
- Same bug using a drag-and-drop
- Bug not found in JabRef 5.7--2022-05-02--4718930
Linux 4.19.0-20-amd64 amd64 
Java 17.0.2 
JavaFX 18+12

### Appendix

...
<details>

<summary>Log File</summary>

java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-3
	at org.jabref.merged.module@5.7.24/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.7.24/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.7.24/javafx.stage.Window.setShowing(Unknown Source)
	at org.jabref.merged.module@5.7.24/javafx.stage.Window.show(Unknown Source)
	at org.jabref.merged.module@5.7.24/javafx.stage.PopupWindow.showImpl(Unknown Source)
	at org.jabref.merged.module@5.7.24/javafx.stage.PopupWindow.show(Unknown Source)
	at org.jabref.merged.module@5.7.24/org.controlsfx.control.Notifications$NotificationPopupHandler.show(Unknown Source)
	at org.jabref.merged.module@5.7.24/org.controlsfx.control.Notifications$NotificationPopupHandler.show(Unknown Source)
	at org.jabref.merged.module@5.7.24/org.controlsfx.control.Notifications.show(Unknown Source)
	at org.jabref@5.7.24/org.jabref.gui.JabRefDialogService.notify(Unknown Source)
	at org.jabref@5.7.24/org.jabref.gui.importer.actions.OpenDatabaseAction.loadDatabase(Unknown Source)
	at org.jabref@5.7.24/org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openTheFile$0(Unknown Source)
	at org.jabref@5.7.24/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.7.24/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.7.24/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

</details>

**Comment by mlep** [comment]
I can confirm this issue is solved in JabRef 5.7--2022-05-04--b2e4ecc
Linux 4.19.0-20-amd64 amd64 
Java 17.0.2 
JavaFX 18+12

Thank you @Siedlerchr
