### ISSUE TITLE
Error while parsing changed file

### ISSUE THREAD

**Issue by MHFrey** [JabRef/jabref#8895]
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

WIndows 10 Pro 21H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open library
2. Save library
3. Check Log
4. Close and try to reopen library
5. Error opening file '(filename unknown)'. Input lentgh = 1

### Appendix

...
<details>

<summary>Log File</summary>

```
Error when Saving============================================
Trust store path: C:\Users\frey\AppData\Local\org.jabref\ssl\truststore.jks
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Index path for C:\Users\frey\Documents\My_Documents\Papers\JabRef\MHF.bib is C:\Users\frey\AppData\Local\org.jabref\JabRef\lucene91
Saving library...
Library saved
Error while parsing changed file.
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.read(Unknown Source)
	at java.base/java.io.FilterReader.read(Unknown Source)
	at java.base/java.io.PushbackReader.read(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.read(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.consumeUncritically(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.parse(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.OpenDatabase.loadDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.collab.ChangeScanner.scanForChanges(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.6.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Error when Reopening=================================================
Trust store path: C:\Users\frey\AppData\Local\org.jabref\ssl\truststore.jks
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Error opening file 'C:\Users\frey\Documents\My_Documents\Papers\JabRef\MHF.bib'
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.read(Unknown Source)
	at java.base/java.io.FilterReader.read(Unknown Source)
	at java.base/java.io.PushbackReader.read(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.read(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.consumeUncritically(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexParser.parse(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.logic.importer.OpenDatabase.loadDatabase(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.JabRefGUI.openLastEditedDatabases(Unknown Source)
	at org.jabref@5.6.60000/org.jabref.gui.JabRefGUI.openDatabases(Unknown Source)
	at org.jabref.merged.module@5.6.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.6.60000/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.6.60000/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.6.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.6.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the report. The error message looks similar to #8870
There seems to be something wrong with detecting the char set. 

Can you open the bib file in an application like Notepad++ and check the encoding? JabRef always tries to Write and Read in UTF-8.
And second, would it be possible for you to make the bib file available to us? (You can send it privately to web@jabref.org

**Comment by Siedlerchr** [comment]
Thanks a lot for the files. I could reproduce this on my machine as well

**Comment by ThiloteE** [comment]
Cause could maybe be: https://github.com/koppor/jabref/issues/75#issuecomment-1154495754
