### ISSUE TITLE
NPE when renaming a file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#890]
JabRef v3.3dev 2016-02-28--master--a0444ab

I've searched for an entry as I lost it somehow:

![grabbed_20160228-211449](https://cloud.githubusercontent.com/assets/1366654/13381609/50c37cb2-de60-11e5-93c4-c88b6db5ac9f.png)

Now, I'm dropping the PDF onto the preview. Nothing happens, but an NPE is raised and output at "Exceptions":

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.sf.jabref.logic.search.MatchesHighlighter.highlightWordsWithHTML(MatchesHighlighter.java:26)
	at net.sf.jabref.logic.layout.LayoutEntry.doLayout(LayoutEntry.java:234)
	at net.sf.jabref.logic.layout.Layout.doLayout(Layout.java:123)
	at net.sf.jabref.logic.layout.Layout.doLayout(Layout.java:110)
	at net.sf.jabref.util.Util.getLinkedFileName(Util.java:212)
	at net.sf.jabref.external.DroppedFileHandler.showLinkMoveCopyRenameDialog(DroppedFileHandler.java:363)
	at net.sf.jabref.external.DroppedFileHandler.handleDroppedfile(DroppedFileHandler.java:143)
	at net.sf.jabref.gui.fieldeditors.FileListEditorTransferHandler$1.run(FileListEditorTransferHandler.java:133)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

My filename format pattern is `\bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}`.

**Comment by oscargus** [comment]
In the two argument Layout constructor: can you change null to Optional.empty()?
