### ISSUE TITLE
Exception when saving a new name formatter

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9120]
*[Originally posted in the discussion forum](https://discourse.jabref.org/t/uncaught-exception-when-saving-a-new-name-formatter/3523/2)* 

### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. From the menu bar, `Options > Preferences`
2. Select `Name formatter`
3. Add a new name formatter
4. Save
5. An exception is thrown! And the name is not saved.

### Appendix
<details>

<summary>Log File</summary>

```
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.collections.ObservableListWrapper.doAdd(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at java.base/java.util.AbstractList.add(Unknown Source)
	at java.base/java.util.AbstractCollection.addAll(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.collections.ModifiableObservableListBase.addAll(Unknown Source)
	at org.jabref@5.8.11/org.jabref.logic.layout.format.NameFormatterPreferences.setNameFormatterKey(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.preferences.nameformatter.NameFormatterTabViewModel.storeSettings(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.preferences.AbstractPreferenceTabView.storeSettings(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.preferences.PreferencesDialogViewModel.storeAllSettings(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.preferences.PreferencesDialogView.savePreferencesAndCloseDialog(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.preferences.PreferencesDialogView.lambda$new$0(Unknown Source)
	at org.jabref@5.8.11/org.jabref.gui.util.ControlHelper.lambda$setAction$0(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.8.11/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.8.11/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
I guess the  FXCollections.observableList(nameFormatterValue); must be changed to observableArrayList
