### ISSUE TITLE
Connecting to shared database with Kerberos fails since v5.6

### ISSUE THREAD

**Issue by m-mauersberger** [JabRef/jabref#9171]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Leap 15.3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Set up a PostgreSQL server with Kerberos authentication.
2. Set up a shared database on the server with Kerberos.
3. Set up configuration file `java.security` in `JabRef_path/lib/runtime/conf/security` (see below).
4. Try to connect to the database via Kerberos ticket.

When connecting to the database there is a GSS authentication error. The Kerberos authentication still worked with JabRef 5.5. Since JabRef 5.6 there are the errors which are described in the Appendix.

Do you have any idea what changed since v5.5 so that the authentication fails now?

I would be glad if you could help with this issue.

### Appendix

<details>

<summary>Excerpt of java.security (around line 240)</summary>

```
#
# Default login configuration file
#
#login.config.url.1=file:${user.home}/.java.login.config
login.config.url.1=file:/path/to/pgjdbc.conf
```

</details>

<details>

<summary>pgjdbc.conf</summary>

```
pgjdbc {
  com.sun.security.auth.module.Krb5LoginModule required
  doNotPrompt=true
  useTicketCache=true
  renewTGT=true
  debug=false;
};
```

</details>

<details>

<summary>Exception stack trace</summary>

```
org.postgresql.util.PSQLException: GSS Authentication failed
	at org.jabref.merged.module@5.7.60000/org.postgresql.gss.GssAction.run(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.gss.GssAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.gss.MakeGSS.authenticate(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.v3.ConnectionFactoryImpl.lambda$doAuthentication$3(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.v3.AuthenticationPluginManager.withPassword(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.core.ConnectionFactory.openConnection(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.jdbc.PgConnection.<init>(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.Driver.makeConnection(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.postgresql.Driver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.logic.shared.DBMSConnection.<init>(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.SharedDatabaseUIManager.openNewSharedDatabaseTab(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.SharedDatabaseLoginDialogViewModel.openSharedDatabase(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.SharedDatabaseLoginDialogViewModel.openDatabase(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.SharedDatabaseLoginDialogView.openDatabase(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.SharedDatabaseLoginDialogView.lambda$new$0(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.util.ControlHelper.lambda$setAction$0(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.shared.ConnectToSharedDatabaseCommand.execute(Unknown Source)
	at org.jabref@5.7.60000/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.60000/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.7.60000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: GSSException: No valid credentials provided (Mechanism level: Fail to create credential. (63) - No service creds)
	at java.security.jgss/sun.security.jgss.krb5.Krb5Context.initSecContext(Unknown Source)
	at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
	at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
	... 124 more
Caused by: KrbException: Fail to create credential. (63) - No service creds
	at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.serviceCredsSingle(Unknown Source)
	at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.serviceCreds(Unknown Source)
	at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.acquireServiceCreds(Unknown Source)
	at java.security.jgss/sun.security.krb5.Credentials.acquireServiceCreds(Unknown Source)
	... 127 more
```

</details>

<details>

<summary>Console error v5.6</summary>

```
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.658 CEST|null:-1|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.659 CEST|null:-1|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.665 CEST|null:-1|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.666 CEST|null:-1|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|41|JavaFX Application Thread|2022-09-23 12:29:00.709 CEST|null:-1|Closing output stream
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.709 CEST|null:-1|duplex close of SSLSocket
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:29:00.709 CEST|null:-1|close the SSL connection (passive)
javax.net.ssl|ALL|41|JavaFX Application Thread|2022-09-23 12:29:00.710 CEST|null:-1|Closing input stream
2022-09-23 12:29:00 [JavaFX Application Thread] org.jabref.logic.shared.DBMSConnection.<init>()
ERROR: Could not connect to database: GSS Authentication failed - Error code: 0
```

</details>

<details>

<summary>Console error v5.7</summary>

```
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.744 CEST|null:-1|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.838 CEST|null:-1|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.839 CEST|null:-1|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.854 CEST|null:-1|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.857 CEST|null:-1|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|41|JavaFX Application Thread|2022-09-23 12:40:06.958 CEST|null:-1|Closing output stream
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.958 CEST|null:-1|duplex close of SSLSocket
javax.net.ssl|DEBUG|41|JavaFX Application Thread|2022-09-23 12:40:06.959 CEST|null:-1|close the SSL connection (passive)
javax.net.ssl|ALL|41|JavaFX Application Thread|2022-09-23 12:40:06.959 CEST|null:-1|Closing input stream
2022-09-23 12:40:06 [JavaFX Application Thread] org.jabref.logic.shared.DBMSConnection.<init>()
ERROR: Could not connect to database: GSS Authentication failed - Error code: 0
```

</details>

**Comment by Siedlerchr** [comment]
Hi, it seems this was an issue in the psql driver versin https://github.com/pgjdbc/pgjdbc/issues/2469
Can you try the latest dev version? It uses the latest version 42.5.0 of the driver

**Comment by HoussemNasri** [comment]
Could this be caused by https://github.com/JabRef/jabref/pull/8583?
In that PR, I changed the default truststore location to `/org.jabref/jabref/ssl`. I'm not familiar with security configuration in Java, but I noticed there is a `cacerts` file in `JabRef_path/lib/runtime/conf/security`. Maybe the configuration is being applied on the wrong truststore?

**Comment by HoussemNasri** [comment]
@m-mauersberger We made a [build](https://builds.jabref.org/pull/9184/merge/) with the custom SSL feature disabled. Could you please take a look and see if the problem persists? Also, make sure to back up your library or use a test library before trying it out since it's still under development and not stable yet.

**Comment by HoussemNasri** [comment]
@m-mauersberger We have made changes to the build since you last tried it to prevent the crash at startup. Can you test it again?

**Comment by m-mauersberger** [comment]
I can confirm, that the problem has been solved by updating the PostgreSQL server and JabRef v5.7. Thank you very much for your efforts!
