### ISSUE TITLE
Download single file leads to not on fx thread error

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9256]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add a link in the General  file editor tab
2. Right click -> Download
3. Exception:
```

java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-1-thread-5
	at org.jabref.merged.module@5.8.162/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.scene.control.skin.LabeledSkinBase.lambda$new$5(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref@5.8.162/org.jabref.model.entry.LinkedFile.setFileType(Unknown Source)
	at org.jabref@5.8.162/org.jabref.gui.fieldeditors.LinkedFileViewModel.lambda$prepareDownloadTask$7(Unknown Source)
	at org.jabref@5.8.162/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.8.162/org.jabref.gui.util.BackgroundTask$3.call(Unknown Source)
	at org.jabref@5.8.162/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.8.162/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Seems to be fixed now. Was proba
