### ISSUE TITLE
Issue resolving DOI

### ISSUE THREAD

**Issue by JoWi2** [JabRef/jabref#9359]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

endeavourOS / Arch derivate  /// JabRef 5.7--ArchLinux--1 Linux 6.0.7-arch1-1 amd64  Java 19.0.1  JavaFX 18.0.1+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I tried to add the following paper (https://doi.org/10.1073/pnas.2203150119) into my jabref-collection via "new entry" and then entering the doi, so that jabref would get the respective data online and fill in the blanks. This has worked in the past without any issue.
As this did not work, I tried generating a new article, entering the DOI in the respective field and then click on "get bibliographic data from DOI" - with the same result.

The resulting message is as below:

Unhandled exception occured   [ X ]

No DOI data exists
org.jabref.logic.importer.FetcherException: No DOI data exists
	at org.jabref@5.7/org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:84)
	at org.jabref@5.7/org.jabref.gui.mergeentries.FetchAndMergeEntry.lambda$fetchAndMerge$0(FetchAndMergeEntry.java:66)
	at org.jabref@5.7/org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:60)
	at org.jabref@5.7/org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:161)
	at javafx.graphics@18.0.1/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://api.crossref.org/v1/works/10.1073%2Fpnas.2203150119/transform
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2044)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2039)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2038)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1605)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.jabref@5.7/org.jabref.logic.net.URLDownload.asString(URLDownload.java:239)
	at org.jabref@5.7/org.jabref.logic.net.URLDownload.asString(URLDownload.java:252)
	at org.jabref@5.7/org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:81)
	... 10 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://api.crossref.org/v1/works/10.1073%2Fpnas.2203150119/transform
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at org.jabref@5.7/org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:352)
	... 13 more

_______________________

The message "no DOI data exists" is incorrect, as I entered the DOI on doi.org, which was resolved flawlessly

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Hi,

I encounter the same and get as well the HTTP Status Code 500. Seems like an issue on the CrossRef side. I also tested manually.

**Comment by ianhbell** [comment]
I am having similar problems. On Mac, with 5.7 (my colleague on windows has a similar problem), for a valid DOI of 10.1007/s10973-022-11850-2
on 

JabRef 5.7--2022-08-05--73c111c
Mac OS X 12.6.1 x86_64 
Java 18.0.1 
JavaFX 18.0.1+2

I get:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/11966765/207499652-82ca9984-46db-42d1-948a-88c421420e49.png">

I do not have this problem on another windows machine. All machines have internet access.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by ianhbell** [comment]
I think this ended up being a VPN redirection problem with my institution's management of the VPN.
