### ISSUE TITLE
FileAccessDeniedException during save

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9363]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When saving a file, it often happens that I get `org.jabref.logic.exporter.SaveException: Problems saving: java.nio.file.AccessDeniedException: C:\TEMP\test-541.bib.tmp -> C:\TEMP\test-541.bib`

```
org.jabref.logic.exporter.SaveException: Problems saving: java.nio.file.AccessDeniedException: C:\TEMP\test-541.bib.tmp -> C:\TEMP\test-541.bib
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:257)
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:213)
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:187)
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveDatabaseAction.save(SaveDatabaseAction.java:74)
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveAction.execute(SaveAction.java:41)
	at org.jabref@100.0.0/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:64)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@19/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@19/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@19/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(ControlAcceleratorSupport.java:190)
	at javafx.graphics@19/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:383)
	at javafx.graphics@19/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:163)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@19/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@19/javafx.scene.Scene$KeyHandler.process(Scene.java:4113)
	at javafx.graphics@19/javafx.scene.Scene.processKeyEvent(Scene.java:2159)
	at javafx.graphics@19/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2627)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics@19/com.sun.glass.ui.View.handleKeyEvent(View.java:542)
	at javafx.graphics@19/com.sun.glass.ui.View.notifyKey(View.java:966)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.AccessDeniedException: C:\TEMP\test-541.bib.tmp -> C:\TEMP\test-541.bib
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.jabref@100.0.0/org.jabref.logic.exporter.AtomicFileOutputStream.close(AtomicFileOutputStream.java:225)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:254)
	at org.jabref@100.0.0/org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:254)
	... 41 more
```

**Comment by Cs137** [comment]
I can confirm a similar behaviour on a linux system (JabRef 5.7--ArchLinux--1) using the CLI:

I call jabref via CLI like this:
```
jabref -n -a some.aux,references.bib references_all.bib
```

it produces amongst others the following output:
```
Saving: references.bib
cp: cannot stat 'references.bib': No such file or directory
Created a backup file: references.bib.bak
```

Interesting is that it created the file `references.bib.tmp` so it seems to stuck at exactly the same task like described in the initial issue. 

If I use the GUI it works and there is no issue at all with creating `references.bib` via 'Tools' | 'New sublib...' and providing `some.aux`.

**Comment by Siedlerchr** [comment]
@Cs137  can you test the latest development version? We reworked the saving and backup creation. Does it still occur?

**Comment by HoussemNasri** [comment]
@koppor Any updates on this? Can you still reproduce it?

**Comment by koppor** [comment]
Did not encounter this issue since months. Thus, I closed.
