### ISSUE TITLE
Error in 5.8 on bibtex library with doubled braces in booktitle (@InCollection)

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#9475]
### JabRef version

5.8 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.8--2022-12-18--b7fae4b Windows 11 10.0 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Load the following library as BibTeX:

```
@InCollection{Favre2004,
  author    = {Jean Favre and Mario Valle},
  booktitle = {{The Visualization Handbook}},
  publisher = {Academic Press},
  title     = {{AVS and AVS/Express}},
  year      = {2004},
  editor    = {Chuck Hansen and Chris Johnson},
  month     = dec,
  pages     = {655--672},
  file      = {:D\:/LibraryBooks/Publications/LibroHansen/hansen.pdf:PDF},
  keywords  = {books},
  langid    = {english},
  mvpubtype = {books},
  url       = {http://www.elsevierdirect.com/product.jsp?isbn=9780123875822},
}

@Comment{jabref-meta: databaseType:bibtex;}
```
2. Run Quality > Check Integrity
3. The following PopUp appears:

```
java.util.regex.PatternSyntaxException: Illegal repetition near index 1
{The[\.\s]*Visualization[\.\s]*Handbook}[\.\s]*
 ^
	at java.base/java.util.regex.Pattern.error(Unknown Source)
	at java.base/java.util.regex.Pattern.closure(Unknown Source)
	at java.base/java.util.regex.Pattern.sequence(Unknown Source)
	at java.base/java.util.regex.Pattern.expr(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at java.base/java.util.regex.Pattern.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.lambda$findDottedAbbrFromDotless$2(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.findDottedAbbrFromDotless(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.isAbbreviatedName(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.integrity.AbbreviationChecker.checkValue(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.integrity.FieldChecker.check(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.integrity.IntegrityCheck.checkEntry(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.integrity.IntegrityCheckAction$1.call(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
5. With the previous versions of JabRef no error were reported.
6. If I remove the additional brace, the error appears on another `@InCollection` entry like the following with braces around the `booktitle`

```
@InCollection{Lyakhov2010a,
  author    = {Andriy O. Lyakhov and Artem R. Oganov and Mario Valle},
  booktitle = {{Modern Methods of Crystal Structure Prediction}},
  publisher = {Wiley-VCH},
  title     = {{Crystal Structure Prediction Using Evolutionary Approach}},
  year      = {2010},
  editor    = {Artem R. Oganov},
  month     = nov,
  keywords  = {books},
  langid    = {english},
  mvpubtype = {books},
  url       = {http://www.wiley-vch.de/publish/en/books/bySubjectPH00/ISBN3-527-40939-4/short/?sID=ou0r6rp7eaadonst3lfkjtktd1},
}
```
7. Seems the error appears only on `@InCollection` entries with double braces around `booktitle`

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by HoussemNasri** [comment]
I can confirm. Apparently the bug was introduced in https://github.com/JabRef/jabref/pull/9453

**Comment by Siedlerchr** [comment]
@K5qu4r3d  Can you take a look at this?

**Comment by spethso** [comment]
It also happens on MacOS Ventura with JabRef 5.8 for inProceedings entries with double braces for the title.

**Comment by Siedlerchr** [comment]
Yes, apparently the journal abbreivation check is called from the IntegrityChecker which checks all kind of book related fields and it sems like the regex does not escape the curly braces.

**Comment by Siedlerchr** [comment]
The issue is now fixed in the latest dev version. We will release a version 5.9 this week which will contain these fixesxs as well
