### ISSUE TITLE
Selecting an entry InProceedings causes an uncaught exception

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9503]
### JabRef version

5.8 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 6.0--2022-12-25--ed78e89 Linux 5.10.0-20-amd64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a library, such as  https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib
2. Do a left click on an entry of type InProceedings (maybe a few of them)
==> an uncaught exception is raised:
```

java.util.regex.PatternSyntaxException: Illegal repetition near index 12
2015[\.\s]*{IEEE}[\.\s]*International[\.\s]*Conference[\.\s]*on[\.\s]*Digital[\.\s]*Signal[\.\s]*Processing,[\.\s]*{DSP}[\.\s]*2015,[\.\s]*Singapore,[\.\s]*July[\.\s]*21-24,[\.\s]*2015[\.\s]*
            ^
	at java.base/java.util.regex.Pattern.error(Unknown Source)
	at java.base/java.util.regex.Pattern.closure(Unknown Source)
	at java.base/java.util.regex.Pattern.sequence(Unknown Source)
	at java.base/java.util.regex.Pattern.expr(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at java.base/java.util.regex.Pattern.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.logic.journals.JournalAbbreviationRepository.lambda$findDottedAbbrFromDotless$2(Unknown Source)
[...]
```

### Appendix

...
<details>

<summary>Log File</summary>

Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Ouverture en cours: '/home/user/Documents/Biblio/jabref-authors.bib'
Index path for /home/user/Documents/Biblio/jabref-authors.bib is /home/user/.local/share/JabRef/lucene94
Could not find geiger2016evolution.pdf
Could not find Geiger2016ProcessEngineBenchmarking.pdf
Could not find Nikol2016.pdf
Could not find Geiger2015BPMNConformanceIn.pdf
Could not find Harrer2015ImprovingStaticAnalysis.pdf
Could not find Harrer2014AutomatedandIsolated.pdf
Could not find Harrer2014BPELConformancein.pdf
Could not find Roeck2014PerformanceBenchmarkingBPEL.pdf
Could not find Harrer2014ProcessEngineSelection.pdf
Could not find Preissinger2014StaticAnalysisRules.pdf
Could not find Roeck2014TestingBPELEngine.pdf
Could not find Harrer2014TowardsRobustnessEvaluation.pdf
Could not find Kolb2014TowardsApplicationPortability.pdf
Could not find Preissinger2014BPELStaticAnalysisProposal.pdf
Could not find Harrer2014TowardsUniformBPEL.pdf
Could not find Geiger2013BPMN20Process.pdf
Could not find Geiger2013BPMN20Serialization.pdf
Could not find Geiger2013DetectingInteroperabilityand.pdf
Could not find Lenhard2013DetectingPortabilityIssues.pdf
Could not find Lenhard2013MeasuringInstallabilityService.pdf
Could not find Lenhard2013MeasuringPortabilityof.pdf
Could not find Harrer2013OpenSourceversus.pdf
Could not find Harrer2012BetsyBPELEngine.pdf
Could not find Harrer2012BPELconformancein.pdf
Could not find Kolb2012BridgingHeterogeneityOrchestrations.pdf
Could not find Geiger2011ProposalCheckingConformance.pdf
Could not find Lenhard2011EditDistanceBased.pdf
Could not find Schoenberger2011HasWSIs.pdf
Could not find Geiger2011TowardsAutomatedConformance.pdf
Could not find Benker2009.pdf
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.util.regex.PatternSyntaxException: Illegal repetition near index 12
2015[\.\s]*{IEEE}[\.\s]*International[\.\s]*Conference[\.\s]*on[\.\s]*Digital[\.\s]*Signal[\.\s]*Processing,[\.\s]*{DSP}[\.\s]*2015,[\.\s]*Singapore,[\.\s]*July[\.\s]*21-24,[\.\s]*2015[\.\s]*
            ^
	at java.base/java.util.regex.Pattern.error(Unknown Source)
	at java.base/java.util.regex.Pattern.closure(Unknown Source)
	at java.base/java.util.regex.Pattern.sequence(Unknown Source)
	at java.base/java.util.regex.Pattern.expr(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at java.base/java.util.regex.Pattern.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.logic.journals.JournalAbbreviationRepository.lambda$findDottedAbbrFromDotless$2(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.logic.journals.JournalAbbreviationRepository.findDottedAbbrFromDotless(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.logic.journals.JournalAbbreviationRepository.isAbbreviatedName(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.logic.integrity.AbbreviationChecker.checkValue(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.fieldeditors.AbstractEditorViewModel.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@6.0.3185/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@6.0.3185/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.validate(Unknown Source)
	at org.jabref.merged.module@6.0.3185/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.util.BindingsHelper.bindBidirectional(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.util.BindingsHelper.bindBidirectional(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.fieldeditors.AbstractEditorViewModel.bindToEntry(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.fieldeditors.SimpleEditor.bindToEntry(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.entryeditor.EntryEditor.setEntry(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@6.0.3185/org.jabref.gui.LibraryTab.lambda$createMainTable$10(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearAndSelect(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.control.TableView$TableViewSelectionModel.clearAndSelect(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@6.0.3185/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@6.0.3185/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source

</details>

**Comment by HoussemNasri** [comment]
Seems to be the same issue as https://github.com/JabRef/jabref/issues/9475
