### ISSUE TITLE
BackupManager exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9623]
### JabRef version

Other (please describe below)

### Operating system

Other (please describe below)

### Details on version and operating system

cannot access, Fedora 37; one of the latest development versions

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

a start Jabref, and I immediately get the message below; cannot see any otherwise normally loaded library.
Not sure what to do about this. clicking "ok" does not achieve results.

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is org.jabref.logic.autosaveandbackup.BackupManager@6a069dc6 registered?
	at org.jabref.merged.module@5.10.124/com.google.common.eventbus.SubscriberRegistry.unregister(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.google.common.eventbus.EventBus.unregister(Unknown Source)
	at org.jabref@5.10.124/org.jabref.logic.util.CoarseChangeFilter.unregisterListener(Unknown Source)
	at org.jabref@5.10.124/org.jabref.logic.autosaveandbackup.BackupManager.shutdown(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.jabref@5.10.124/org.jabref.logic.autosaveandbackup.BackupManager.shutdown(Unknown Source)
	at org.jabref@5.10.124/org.jabref.gui.JabRefFrame.quit(Unknown Source)
	at org.jabref@5.10.124/org.jabref.gui.JabRefGUI.lambda$openWindow$1(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.stage.WindowPeerListener.closing(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.glass.ui.Window.handleWindowEvent(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.glass.ui.Window.notifyClose(Unknown Source)
	at org.jabref.merged.module@5.10.124/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.10.124/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
</details>

**Comment by Siedlerchr** [comment]
Hm this looks, from the stack trace it says it's exiting JabRef and therefore shutting down..
