### ISSUE TITLE
Citation bibliography failed in Libreoffice

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#9670]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

windows 7

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Hello,
1. Cite to Libreoffice
2. Refresh to get bibliography
3. Error.

Was tried in both windows 7 and 10 with Jabref 5.9. 
Both Jabref and LO are **portable** versions. 

Please note I connect to LO, citations appears correctly. However, bibliography never appears.
I tried with the same bib and jstyle files on a Ubuntu computer and it works correctly. 
Thanks

### Appendix

versions installed : 
JabRef 5.9--2023-01-08--76253f1a7
Windows 7 6.1 amd64 
Java 19.0.1 
JavaFX 19+11

dev versions tested : 
JabRef 5.10--2023-03-13--8958e8b
Windows 7 6.1 amd64 
Java 19.0.2 
JavaFX 19+11

...
<details>

<summary>Log File</summary>

```
Could not update bibliography
com.sun.star.lang.IllegalArgumentException: 
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.Job.execute(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JobQueue.enter(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JobQueue.enter(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(Unknown Source)
	at org.libreoffice.uno/com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy25.setPropertyValue(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.model.openoffice.ootext.OOTextIntoOO.removeDirectFormatting(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.openoffice.frontend.UpdateBibliography.populateBibTextSection(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.openoffice.frontend.UpdateBibliography.rebuildBibTextSection(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.openoffice.action.Update.updateDocument(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.openoffice.action.Update.synchronizeDocument(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.openoffice.OOBibBase.guiActionUpdateDocument(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$9(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


```

</details>

**Comment by HoussemNasri** [comment]
Thank you for bringing our attention to this issue.

 I have tried to reproduce the issue on my Windows 10 machine but all of my attempts failed. Looking at the exception, I can tell that it was started by `removeDirectFormatting`. This method is responsible for clearing the formatting applied to the bibliography entries to ensure that it conforms to the chosen jstyles after synchronization.

To narrow the scope of the search, I need you to answer a few questions. Have you tried OpenOffice instead? What jstyle did you use, standard one or custom-made? Did you manage to synchronize the bibliography without the exception being thrown even once? If yes, what do you think happened?

**Comment by Siedlerchr** [comment]
Another thing which might be an issue: Have you a character style named "Standard"? 
https://elearn.ellak.gr/mod/page/view.php?id=2789

**Comment by melTr** [comment]
Hi. 
Thanks to help me. It's on my work's computer and I will try again ASAP. However, I can answer some questions already :
I tried both a standard and a custom style. This custom style is however working on my Ubuntu computer.
I have never been able to see the bibliography without getting the error.
The writer document is completely empty.

**Comment by Siedlerchr** [comment]
Yes that seems good, in JabRef's Libre Office connection menu there is an option to update the bibliography automatically or manually 
<img width="381" alt="grafik" src="https://user-images.githubusercontent.com/320228/226421511-687c9232-6e20-421f-bf36-00ca5469eb47.png">

**Comment by melTr** [comment]
Hi,
I try with and without automatically sync and both didn't work.

**Comment by Siedlerchr** [comment]
I tried with latest libreoffice version on mac, I see you are using LO in French, I will test this later as well if it's the language which causes problems here

**Comment by melTr** [comment]
Hi,
Found it... I updated LibreOffice to 7.5 (last portable version) and suddenly works. Still didn't work for ApacheOffiche last version, but I don't really care...
Thanks and sorry for derangement.
