### ISSUE TITLE
Unable to search doi directly in web search

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [JabRef/jabref#9674]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Turn on web search panel, select INSPIRE for example
2. search a doi, i.e. `10.1007/JHEP02(2023)082` without using quotes
3. the search failed with an unhandled exception. 
4. The exception goes away if surround the doi with quotes

### Appendix

...
<details>
I think the problem is that the search box is unable to handle the slash "/". Either escaping "/" or adding quotes would solve it. But a more general solution is preferred. 

<summary>Log File</summary>

```
org.jabref.logic.importer.FetcherException: An error occurred when parsing the query
	at org.jabref@5.10.236/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.10.236/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$3(Unknown Source)
	at org.jabref@5.10.236/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.10.236/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.10.236/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Yes this is a known issue. For identifiers like DOI you can directly paste them directly on the main table or use this dialog 
<img width="478" alt="grafik" src="https://user-images.githubusercontent.com/320228/225718506-ac965b2c-f908-425e-8a39-bab2f97e82c9.png">

Or the general new entry dialog

**Comment by HoussemNasri** [comment]
This is because the search query needs to adhere to [Lucene query syntax](https://github.com/mahnunchik/lucene-query-parser/blob/master/lucene-query.grammar).

**Comment by Turgon-Aran-Gondolin** [comment]
> Yes this is a known issue. For identifiers like DOI you can directly paste them directly on the main table or use this dialog <img alt="grafik" width="478" src="https://user-images.githubusercontent.com/320228/225718506-ac965b2c-f908-425e-8a39-bab2f97e82c9.png">
> 
> Or the general new entry dialog

Thanks for your reply. I would prefer using a particular database, so that's why I was using the web search. There're workarounds, of course. Worst-case scenario, I need to spend an extra 5 seconds to escape the slash. It would be nice if jabref can support this generically though, but if it's too complicated to implement, I can live with workarounds.

**Comment by ThiloteE** [comment]
Is this issue something that theoretically can be fixed if somebody would just start doing it or is it legit impossible and we should put label "status: won't fix"?

**Comment by koppor** [comment]
Screenshot of the issue:

![image](https://user-images.githubusercontent.com/1366654/234114585-80a0f960-32ca-4082-bede-cf19631458ae.png)

As first "fix": If the thing is a DOI, ignore the selected search engine and do the DOI search.

**Comment by koppor** [comment]
Code similar to the one with the id fetcher. Needs to be adaptged.

**Comment by koppor** [comment]
This is a part of issue https://github.com/JabRef/jabref/issues/7575. 

Proposal:

1. Fix DOI entering (as wished here)
2. Fix entering any ID (as wished at https://github.com/JabRef/jabref/issues/7575) - and possible in the quick fetcher (https://github.com/JabRef/jabref/issues/9674#issuecomment-1472521776)

**Comment by aqurilla** [comment]
I would like to take up this issue

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/13)
