### ISSUE TITLE
Opening of File or Url by clicking on icon don't work in last snapshot

### ISSUE THREAD

**Issue by burrbull** [JabRef/jabref#972]
* JabRef version (available in the About box): JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7
* Operating system and version: Ubuntu 15.10
* Steps to reproduce:
  1. Add File path or Url to entry.
  2. Try to open by clicking on icon in main table.
 
Status: Unable to open link.
In JabRef-3.3dev--snapshot--2016-03-14--master--63d5555 it works fine.

**Comment by matthiasgeiger** [comment]
Thanks for your report! 
We have made some restructuring in the OS handling - apparently not everything works as it supposed to be... 

Can you please post the content of the error console?

Thanks!

**Comment by burrbull** [comment]
12:54:39.325 [JabRef CachedThreadPool] ERROR net.sf.jabref.gui.desktop.JabRefDesktop - Error opening file 'http://ea.donntu.org/handle/123456789/13966'
java.io.IOException: Cannot run program "": error=2, Нет такого файла или каталога
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Runtime.java:620) ~[?:1.8.0_74]
	at java.lang.Runtime.exec(Runtime.java:485) ~[?:1.8.0_74]
	at net.sf.jabref.gui.desktop.os.Linux.openFile(Linux.java:19) ~[JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFilePlatformIndependent(JabRefDesktop.java:158) ~[JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openBrowser(JabRefDesktop.java:256) ~[JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7.jar:?]
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalViewer(JabRefDesktop.java:93) [JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7.jar:?]
	at net.sf.jabref.gui.maintable.MainTableSelectionListener$1.run(MainTableSelectionListener.java:327) [JabRef-3.3dev--snapshot--2016-03-15--master--ee1c5d7.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.io.IOException: error=2, Нет такого файла или каталога
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_74]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[?:1.8.0_74]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_74]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_74]
	... 10 more

**Comment by matthiasgeiger** [comment]
Thanks!

**Comment by stefan-kolb** [comment]
Please try the newest build at http://builds.jabref.org/master/.

**Comment by burrbull** [comment]
Still not works!

Now other exception:

Exception in thread "JabRef CachedThreadPool" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFilePlatformIndependent(JabRefDesktop.java:161)
	at net.sf.jabref.gui.desktop.JabRefDesktop.openExternalFileAnyFormat(JabRefDesktop.java:147)
	at net.sf.jabref.external.ExternalFileMenuItem.openLink(ExternalFileMenuItem.java:104)
	at net.sf.jabref.gui.maintable.MainTableSelectionListener.lambda$mouseClicked$3(MainTableSelectionListener.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stefan-kolb** [comment]
Ouch, sorry I had a typo in the code, please try again in a few minutes :smile:

**Comment by burrbull** [comment]
Same exception.
