### ISSUE TITLE
undo keyboard shortcut Ctrl-Z disfonction 

### ISSUE THREAD

**Issue by jh-midi** [JabRef/jabref#9737]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

almalinux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...open library
2. insert entry
3. use keyboard shortcut Contol-Z
4. .=> exception
5. ...
I have the same result on windows and os-x

JabRef 5.10--2023-04-05--643319b
Linux 5.14.0-162.22.2.el9_1.x86_64 amd64 
Java 19.0.2 
JavaFX 20+19

### Appendix

<details>
<summary>Detail information:</summary>

```
Uncaught exception occurred in Thread[#37,JavaFX Application Thread,5,main]
java.lang.IllegalStateException: Only cut/copy/paste supported but got UNDO
	at org.jabref@5.10.418/org.jabref.gui.edit.EditAction.lambda$execute$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.10.418/org.jabref.gui.edit.EditAction.execute(Unknown Source)
	at org.jabref@5.10.418/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.10.418/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.10.418/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module@5.10.418/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.10.418/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Log copied to clipboard.
```

</details>

**Comment by Siedlerchr** [comment]
thanks for reporting, I encountered this recently as well

**Comment by brunaoo** [comment]
Hello!
I would like to work on this issue

**Comment by koppor** [comment]
You will have to touch nearly the complete code base and introduce the command pattern there. Will take > 100 hours to complete. Much thinking involved: How does proper undo/redo management look like? How is the state of the art in Java in 2023? In Swing/AWT times, it was easy with the "UndoManager", which we also use. However, JabRef did not strictly implement it in all places, because we thought, in JavaFX we need to do it differently.

You are also welcome to try to fix the concrete issue (not solving the underlying issue), but better some step forward than nothing.

**Comment by jh-midi** [comment]
Only the Control-Z shortcut disfunction, the menu Edit>Undo work well. 
It is a bug introduced in 5.10, the error message in the window fired by Control-Z  is irelevant.

**Comment by brunaoo** [comment]
I believe I can start addressing the concrete problem by working on the org.jabref.gui.maintable.MainTable class. What do you think?

**Comment by Siedlerchr** [comment]
@brunaoo  You have to look into the EditAction. Probably remove or check the default case https://github.com/JabRef/jabref/blob/e7f55d9da9193d7610aae732765b0369b1d7c419/src/main/java/org/jabref/gui/edit/EditAction.java#L21

**Comment by brunaoo** [comment]
> @brunaoo You have to look into the EditAction. Probably remove or check the default case
> 
> https://github.com/JabRef/jabref/blob/e7f55d9da9193d7610aae732765b0369b1d7c419/src/main/java/org/jabref/gui/edit/EditAction.java#L21

ok!

**Comment by Siedlerchr** [comment]
```
java.lang.IllegalStateException: Only cut/copy/paste supported but got REDO
	at org.jabref@100.0.0/org.jabref.gui.edit.EditAction.lambda$execute$0(EditAction.java:78)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.jabref@100.0.0/org.jabref.gui.edit.EditAction.execute(EditAction.java:49)
	at org.jabref@100.0.0/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:64)
	at javafx.base@20/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@20/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@20/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@20/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(ControlAcceleratorSupport.java:184)
	at javafx.graphics@20/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:383)
	at javafx.graphics@20/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:163)
	at javafx.base@20/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@20/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@20/javafx.scene.Scene.processKeyEvent(Scene.java:2190)
	at javafx.graphics@20/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2711)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics@20/com.sun.glass.ui.View.handleKeyEvent(View.java:542)
	at javafx.graphics@20/com.sun.glass.ui.View.notifyKey(View.java:966)

```
