### ISSUE TITLE
Quick import should work if DOI is included

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9821]
1. Open "Import new entry from Id"\
    ![image](https://user-images.githubusercontent.com/1366654/235362373-88dcfd13-9b78-4fe4-ae6a-044fe8f67937.png)
2. Paste `https://www.scitepress.org/Link.aspx?doi=10.5220/0010404301780189`
3. Click on the arrow on the right to trigger the fetch.

Expected result: Entry found

Actual result: No entry found

One can find the entry when searching for `10.5220/0010404301780189`

There needs to be implemented a heuristic at the `CompositeIdFetcher`. Before passing the DOI to the DOI parser, a) existence of `?doi=` needs to be checked, b) if yes, that part removed. Then passed to `DOI.parse`

[/src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java#L23](https://github.com/JabRef/jabref/blob/3009e8105a779f6c6570b10c42e71ebd671099cc/src/main/java/org/jabref/logic/importer/CompositeIdFetcher.java#L23)
```java
        Optional<DOI> doi = DOI.parse(identifier);
```

Test-enabling: Heuristics as own method. This method needs to be tested. Method can be "package private".

With that being implemented, https://github.com/JabRef/jabref/issues/7575 can also be fixed (howto at https://github.com/JabRef/jabref/issues/7575#issuecomment-1529055712).

**Comment by sean-leichtle** [comment]
> Can you try? And add test cases?

Sure, though I may have some questions, especially about testing.

**Comment by koppor** [comment]
General hints on UI testing are that a) the ViewModel can be tested, b) if UI tests are really needed (I don't think in these tests), then hints can be read in the changes at https://github.com/JabRef/jabref/pull/9794.

In the concrete case, a test addition to `org.jabref.logic.importer.fetcher.CompositeIdFetcherTest` seems to be enough.

Side note: I also updated the other issue for code and test hints: https://github.com/JabRef/jabref/issues/7575#issuecomment-1534166164

**Comment by sean-leichtle** [comment]
@koppor 
Just a point of clarification - your original description of the problem indicates that input  ```https://www.scitepress.org/Link.aspx?doi=10.5220/0010404301780189``` results in "no entry found" (= a toaster report). With the same input, I receive "Input error. Could not find a suitable format." (= pop-up titled "Exception Details"). Did you actually mean you get an input error as I do or do you really get a "no entry found"? If it makes a difference, I'm on macOS Monterey 12.6.x.

**Comment by koppor** [comment]
@sean-leichtle Thank you for working to refine the issue description. I used today's version from the `main` branch and recorded following video: https://www.loom.com/share/61c33deca44b4ec3951f69e7ddc1f846

I see at minute 00:07 "No entry found".

Do you use some different button?

**Comment by koppor** [comment]
My event log also does not show any exception: 

![image](https://user-images.githubusercontent.com/1366654/236636391-54b97024-079d-4047-acb7-5e9281eae625.png)

Sid enote: The log could be refined in adding some details on the search.

**Comment by sean-leichtle** [comment]
@koppor 
Unfortunately not. I get the error I described just as soon as I paste ```https://www.scitepress.org/Link.aspx?doi=10.5220/0010404301780189```into the field, that is *without* pressing the arrow button.
<img width="357" alt="Bildschirmfoto 2023-05-06 um 17 42 10" src="https://user-images.githubusercontent.com/98459426/236636557-64e2189d-4668-4b48-8569-91a1734c94f8.png">

**Comment by sean-leichtle** [comment]
@koppor 
I'm on macOS Monterey 12.6.x if that makes a difference.

**Comment by koppor** [comment]
I am on Windows. Interesting cc @Siedlerchr.

However, IntelliJ should also work on macOS. There, one can set breakpoints and step through the code and see where code changes are needed. I think, we already discussed, that the change should go into `CompositeIdFetcher`?

**Comment by sean-leichtle** [comment]
A bit more context: inserting a doi-number, such as ```10.5220/0010404301780189```, results in a successful import, though, again, without pressing the arrow button.

**Comment by koppor** [comment]
> A bit more context: inserting a doi-number, such as ```10.5220/0010404301780189```, results in a successful import, though, again, without pressing the arrow button.

How can you trigger Quick Import without pressing the button for Quick Import. That button is the arrow button - do you refer to some other button? 

Maybe it would be good if you share a video. Loom was recommended me by Microsoft.

As said, working on a fix can happen in parallel.

**Comment by sean-leichtle** [comment]
Sorry for the delay. Here is a video of the behavior I described:

https://user-images.githubusercontent.com/98459426/236639048-ea02f163-4560-445c-a6f5-3c9699a04a8a.mp4

**Comment by sean-leichtle** [comment]
Ok, if I enter ```https://www.scitepress.org/Link.aspx?doi=10.5220/0010404301780189``` manually, ie. *not* copy-paste, then I get a "no entry found" toaster report.

**Comment by koppor** [comment]
Can you paste the exception here?

**Comment by sean-leichtle** [comment]
org.jabref.logic.importer.ImportException: Could not find a suitable import format.
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:247)
	at org.jabref@100.0.0/org.jabref.logic.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:267)
	at org.jabref@100.0.0/org.jabref.gui.externalfiles.ImportHandler.tryImportFormats(ImportHandler.java:306)
	at org.jabref@100.0.0/org.jabref.gui.externalfiles.ImportHandler.handleStringData(ImportHandler.java:301)
	at org.jabref@100.0.0/org.jabref.gui.maintable.MainTable.handleNonBibTeXStringData(MainTable.java:344)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.jabref@100.0.0/org.jabref.gui.maintable.MainTable.paste(MainTable.java:330)
	at org.jabref@100.0.0/org.jabref.gui.LibraryTab.paste(LibraryTab.java:783)
	at org.jabref@100.0.0/org.jabref.gui.edit.EditAction.lambda$execute$0(EditAction.java:76)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.jabref@100.0.0/org.jabref.gui.edit.EditAction.execute(EditAction.java:49)
	at org.jabref@100.0.0/org.jabref.gui.actions.JabRefAction.lambda$new$3(JabRefAction.java:40)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:423)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.action.Action.handle(Action.java:64)
	at javafx.base@20/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@20/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@20/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@20/com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:150)
	at javafx.base@20/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@20/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@20/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)

**Comment by koppor** [comment]
You pasted into the main table? Nice. You can work on that this works for those kinds of strings too

**Comment by sean-leichtle** [comment]
I'm sorry, I don't mean to be slow on the uptake, but could you clarify?

**Comment by Siedlerchr** [comment]
@sean-leichtle  @koppor  This is the buggy behavior of javafx under mac that copy paste is triggered twice when you paste in the text field and the maintable also still gets focus

**Comment by sean-leichtle** [comment]
@koppor I've lodged a pull request, though I declared the method public (and not, as you requested, package private) for testing purposes. Is there a way to declare the method as package private and still test? I also want to add that my testing experience is preliminary, so I'd appreciate feedback on this point.

**Comment by Siedlerchr** [comment]
package private is just a  method without any modifier. The test class has to be in the same package then you can use it

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/10)
