### ISSUE TITLE
Development branch: Linux portable version does not start

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9908]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Was working a few days ago. Does not work today.

1. download https://builds.jabref.org/main/JabRef-5.10-portable_linux.tar.gz
2. gunzip it
3. launch Jabref (e.g. `~/test/JabRef/bin/JabRef`)

JabRef does not start.
Console message:
````
Exception in thread "main" java.lang.UnsupportedOperationException: Configuration cannot be changed after applying to tinylog
	at org.tinylog.api@2.6.2/org.tinylog.configuration.Configuration.set(Unknown Source)
	at org.jabref@5.10.891/org.jabref.cli.Launcher.lambda$addLogToDisk$0(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.10.891/org.jabref.cli.Launcher.addLogToDisk(Unknown Source)
	at org.jabref@5.10.891/org.jabref.cli.Launcher.main(Unknown Source)

````

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
I thought, I fixed that at https://github.com/JabRef/jabref/pull/9887/commits/c200fefb4cdbf3de94d8e2f09ea4f623712950d2 - Pull request is that one: https://github.com/JabRef/jabref/pull/9887

JabRef installer version for Windows starts without issues. Thus, Linux seems to log something at the start. We need to check the startup on Linux.

**Comment by wujastyk** [comment]
+1

**Comment by Siedlerchr** [comment]
Thanks all for your prompt reaction! That is really valuable. 
The error happened during yesterday's coding session ;)   We just merged the fix. A new version should be ready in roughly 30 minutes  [0247913](https://github.com/JabRef/jabref/commit/0247913a6a5d9cb637bf03903695dcdf8dc8e3d6)

**Comment by mlep** [comment]
JabRef is starting now. Thank you!

I noticed the following exceptions (they occurred already with JabRef 5.10--2023-05-11--c6ff4c1)
```
May 16, 2023 11:18:05 PM com.sun.javafx.application.PlatformImpl startup
AVERTISSEMENT: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2023-05-16 23:18:05 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2023-05-16 23:18:05 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2023-05-16 23:18:06 [JavaFX Application Thread] org.jabref.logic.layout.Layout.<init>()
WARN: Nested field/group entries are not implemented!
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.Layout.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.LayoutHelper.getLayoutFromText(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.TextBasedPreviewLayout.setText(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.TextBasedPreviewLayout.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.preferences.JabRefPreferences.lambda$getPreviewLayouts$118(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.10.901/org.jabref.preferences.JabRefPreferences.getPreviewLayouts(Unknown Source)
	at org.jabref@5.10.901/org.jabref.preferences.JabRefPreferences.getPreviewPreferences(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.createMenu(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.initLayout(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.init(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefGUI.openWindow(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefGUI.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.MainApplication.start(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-16 23:18:06 [JavaFX Application Thread] org.jabref.logic.layout.Layout.<init>()
WARN: Nested field/group entries are not implemented!
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.Layout.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.LayoutHelper.getLayoutFromText(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.TextBasedPreviewLayout.setText(Unknown Source)
	at org.jabref@5.10.901/org.jabref.logic.layout.TextBasedPreviewLayout.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.preferences.JabRefPreferences.getPreviewPreferences(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.createMenu(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.initLayout(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefFrame.init(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefGUI.openWindow(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.JabRefGUI.<init>(Unknown Source)
	at org.jabref@5.10.901/org.jabref.gui.MainApplication.start(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.10.901/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-16 23:18:06 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
````
