### ISSUE TITLE
ISBN fetching fails

### ISSUE THREAD

**Issue by Uwe100github** [JabRef/jabref#9979]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windowa 10 21H1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Hallo, seit ein paar Wochen funktioniert das Erstellen eines Eintrags über die ISBN nicht mehr. Ich nutze JabRef 5.9–2023-01-08–76253f1a7 unter Windows 10. Beim Versuch, den Datensatz zu erzeugen, hängt sich das Programm auf. Der Prozess wird leider nicht im Ereignisprotokoll eingetragen.

Following ISBN will fail:

`9783746633756`

### Appendix

org.jabref.logic.importer.FetcherException: An internal parser error occurred
	at org.jabref@5.9.6000/org.jabref.logic.importer.IdBasedParserFetcher.performSearchById(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fetcher.isbntobibtex.IsbnFetcher.performSearchById(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fetcher.isbntobibtex.IsbnFetcher.performSearch(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.mergeentries.FetchAndMergeEntry.lambda$fetchAndMerge$3(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.9.6000/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jabref.logic.importer.ParseException: javax.net.ssl.SSLException: Tag mismatch
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.BibtexParser.parseEntries(Unknown Source)
	... 13 more
Caused by: javax.net.ssl.SSLException: Tag mismatch
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.implRead(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source)
	at java.base/sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.implRead(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.net.ProgressInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.implRead(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.implRead(Unknown Source)
	at java.base/java.io.BufferedReader.read(Unknown Source)
	at java.base/java.io.FilterReader.read(Unknown Source)
	at java.base/java.io.PushbackReader.read(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.BibtexParser.read(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.BibtexParser.skipWhitespace(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.BibtexParser.parseDatabaseID(Unknown Source)
	at org.jabref@5.9.6000/org.jabref.logic.importer.fileformat.BibtexParser.parse(Unknown Source)
	... 14 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch
	at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(Unknown Source)
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	... 47 more

<summary>Log File</summary>

```
Paste an excerpt of your log file here
![image](https://github.com/JabRef/jabref/assets/135751199/68027143-869d-4257-aef8-98417ce06444)


</details>

**Comment by ThiloteE** [comment]
Hallo Uwe, hast du es schon mit der neuesten [Entwicklungsversion von JabRef](https://builds.jabref.org/main/) versucht?
Danke für die Fehlermeldung, die ist bestimmt hilfreich bei der Fehlersuche.

Wäre es dir möglich eine ISBN die zu der Fehlermeldung führt zu nennen?

**Comment by Uwe100github** [comment]
Bei der Version 5.10 habe ich das gleiche Problem

**Comment by Uwe100github** [comment]
sorry nicht completed, bin neu hier ...

**Comment by Uwe100github** [comment]
Der Fehler betrifft jedwede ISBN, ich habe auch die probiert, die früher funktionierten z.B. 9783746633756

**Comment by Siedlerchr** [comment]
@Uwe100github  Danke für das Errorlog. Benutzt du oder bist du vielleicht hinter einem Proxy-Server? Das sieht nach irgendeiner Netzwerk Geschichte aus

**Comment by koppor** [comment]
https://www.ebook.de/de/ hat den ISBN-Endpunkt <https://www.ebook.de/de/tools/isbn2bibtex> abgeschaltet. Früher kamen darüber die Daten inkl. einer URL, wo man das Buch über ebook.de kaufen konnte.

@hugendubeldigital / @jpapenhagen wisst ihr evtl. mehr? Könnt ihr helfen? Gerne auch private Mail an mich (Sichtbar über GitHub profil)

**Comment by koppor** [comment]
Current discussion:

- There is https://lead.to/amazon/com/?op=bt
- https://www.xarg.org/tools/isbn-to-bibtex/
- https://zbib.org/

**Comment by koppor** [comment]
Discussion on the technical fix is going on at https://github.com/JabRef/jabref/issues/10125

This issue is about user-facing discussion. The other one is about developer-facing discussion. This means, no devleoper discussion here.
